//! Decision-provenance types and a minimal PROV-O/Turtle exporter.
//!
//! This module is intentionally small and dependency-free. It defines a
//! thin semantic coating over `mvm`'s existing chain-signed audit
//! substrate: audit events are mapped to W3C PROV-O activities, agents,
//! and entities, then serialized as Turtle.
//!
//! The serializer is hand-written rather than generated by an RDF crate
//! to keep the trusted compute base and dependency footprint small. The
//! output is valid Turtle for the subset of PROV-O that `mvm` uses.

use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::fmt::Write as _;

use crate::policy::audit::{AuditEntry, LocalAuditEvent};

/// Default PROV-O namespace URI.
pub const NS_PROV: &str = "http://www.w3.org/ns/prov#";
/// Default RDF schema namespace URI.
pub const NS_RDFS: &str = "http://www.w3.org/2001/02/rdf-schema#";
/// XML schema namespace URI (used for typed literals).
pub const NS_XSD: &str = "http://www.w3.org/2001/XMLSchema#";

/// A provenance triple in abbreviated Turtle form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Triple {
    /// `subject a object`
    Type { subject: String, object: String },
    /// `subject predicate object` where object is an IRI/local name.
    Iri {
        subject: String,
        predicate: String,
        object: String,
    },
    /// `subject predicate "literal"`
    Literal {
        subject: String,
        predicate: String,
        value: String,
    },
    /// `subject predicate "literal"^^xsd:dateTime`
    DateTime {
        subject: String,
        predicate: String,
        value: String,
    },
}

/// A bag of provenance triples that can be serialized to Turtle.
#[derive(Debug, Clone, Default)]
pub struct ProvenanceGraph {
    triples: Vec<Triple>,
}

impl ProvenanceGraph {
    /// Create an empty graph.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a triple declaring the type of a subject.
    pub fn add_type(&mut self, subject: impl Into<String>, object: impl Into<String>) {
        self.triples.push(Triple::Type {
            subject: subject.into(),
            object: object.into(),
        });
    }

    /// Add a triple linking a subject to an IRI/local object.
    pub fn add_iri(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        object: impl Into<String>,
    ) {
        self.triples.push(Triple::Iri {
            subject: subject.into(),
            predicate: predicate.into(),
            object: object.into(),
        });
    }

    /// Add a triple with a string literal object.
    pub fn add_literal(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        value: impl Into<String>,
    ) {
        self.triples.push(Triple::Literal {
            subject: subject.into(),
            predicate: predicate.into(),
            value: value.into(),
        });
    }

    /// Merge another graph into this one.
    pub fn extend(&mut self, other: Self) {
        self.triples.extend(other.triples);
    }

    /// Add a triple with an `xsd:dateTime` literal object.
    pub fn add_datetime(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        value: impl Into<String>,
    ) {
        self.triples.push(Triple::DateTime {
            subject: subject.into(),
            predicate: predicate.into(),
            value: value.into(),
        });
    }

    /// Serialize the graph to Turtle, including standard namespace prefixes.
    pub fn to_turtle(&self) -> String {
        let mut out = String::new();
        writeln!(
            out,
            "@prefix prov: <{NS_PROV}> .\n@prefix rdfs: <{NS_RDFS}> .\n@prefix xsd: <{NS_XSD}> ."
        )
        .expect("write to string cannot fail");
        if self.triples.is_empty() {
            return out;
        }
        out.push('\n');

        // Group triples by subject so Turtle can use semicolon shorthand.
        let mut by_subject: alloc::collections::BTreeMap<&str, Vec<&Triple>> =
            alloc::collections::BTreeMap::new();
        for triple in &self.triples {
            by_subject.entry(triple.subject()).or_default().push(triple);
        }

        for (subject, triples) in by_subject {
            let subject_local = turtle_local_name(subject);
            for (idx, triple) in triples.iter().enumerate() {
                if idx == 0 {
                    write!(out, "{subject_local}").expect("write to string cannot fail");
                }
                let separator = if idx == triples.len() - 1 { " ." } else { " ;" };
                match triple {
                    Triple::Type { object, .. } => {
                        write!(out, " a {object}{separator}").expect("write to string cannot fail");
                    }
                    Triple::Iri {
                        predicate, object, ..
                    } => {
                        write!(out, " {predicate} {object}{separator}")
                            .expect("write to string cannot fail");
                    }
                    Triple::Literal {
                        predicate, value, ..
                    } => {
                        let escaped = turtle_escape_string(value);
                        write!(out, " {predicate} \"{escaped}\"{separator}")
                            .expect("write to string cannot fail");
                    }
                    Triple::DateTime {
                        predicate, value, ..
                    } => {
                        let escaped = turtle_escape_string(value);
                        write!(out, " {predicate} \"{escaped}\"^^xsd:dateTime{separator}")
                            .expect("write to string cannot fail");
                    }
                }
            }
            out.push('\n');
        }
        out
    }
}

impl Triple {
    fn subject(&self) -> &str {
        match self {
            Triple::Type { subject, .. }
            | Triple::Iri { subject, .. }
            | Triple::Literal { subject, .. }
            | Triple::DateTime { subject, .. } => subject.as_str(),
        }
    }
}

/// Convert an `AuditEntry` into PROV-O triples.
///
/// Each entry produces:
/// - an `prov:Activity` for the action,
/// - a `prov:Agent` for the tenant,
/// - an optional `prov:Entity` for the instance,
/// - association/usage links tying them together.
pub fn audit_entry_to_provenance(entry: &AuditEntry, sequence: u64) -> ProvenanceGraph {
    let mut graph = ProvenanceGraph::new();

    let activity_id = format!("mvm:audit_activity_{sequence}");
    let agent_id = format!("mvm:tenant_{}", turtle_safe_local(&entry.tenant_id));
    let action_label = format!("{:?}", entry.action);

    graph.add_type(&activity_id, "prov:Activity");
    graph.add_literal(&activity_id, "rdfs:label", action_label);
    graph.add_datetime(&activity_id, "prov:startedAtTime", &entry.timestamp);

    graph.add_type(&agent_id, "prov:Agent");
    graph.add_literal(&agent_id, "rdfs:label", &entry.tenant_id);
    graph.add_iri(&activity_id, "prov:wasAssociatedWith", &agent_id);

    if let Some(instance_id) = &entry.instance_id {
        let entity_id = format!("mvm:instance_{}", turtle_safe_local(instance_id));
        graph.add_type(&entity_id, "prov:Entity");
        graph.add_literal(&entity_id, "rdfs:label", instance_id);
        graph.add_iri(&activity_id, "prov:used", &entity_id);
    }

    if let Some(detail) = &entry.detail {
        graph.add_literal(&activity_id, "rdfs:comment", detail);
    }

    graph
}

/// Convert a `LocalAuditEvent` into PROV-O triples.
pub fn local_audit_event_to_provenance(event: &LocalAuditEvent, sequence: u64) -> ProvenanceGraph {
    let mut graph = ProvenanceGraph::new();

    let activity_id = format!("mvm:local_activity_{sequence}");
    let agent_id = "mvm:host_operator".to_string();
    let kind_label = format!("{:?}", event.kind);

    graph.add_type(&activity_id, "prov:Activity");
    graph.add_literal(&activity_id, "rdfs:label", kind_label);
    graph.add_datetime(&activity_id, "prov:startedAtTime", &event.timestamp);

    graph.add_type(&agent_id, "prov:Agent");
    graph.add_literal(&agent_id, "rdfs:label", "mvmctl host operator");
    graph.add_iri(&activity_id, "prov:wasAssociatedWith", &agent_id);

    if let Some(vm_name) = &event.vm_name {
        let entity_id = format!("mvm:vm_{}", turtle_safe_local(vm_name));
        graph.add_type(&entity_id, "prov:Entity");
        graph.add_literal(&entity_id, "rdfs:label", vm_name);
        graph.add_iri(&activity_id, "prov:used", &entity_id);
    }

    if let Some(detail) = &event.detail {
        graph.add_literal(&activity_id, "rdfs:comment", detail);
    }

    graph
}

/// Make a string safe to use as the local part of a prefixed Turtle name.
///
/// Replaces characters that are not valid in `PN_LOCAL` with `_`, and
/// prefixes a leading digit with `_`.
pub fn turtle_safe_local(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for (idx, ch) in s.chars().enumerate() {
        if idx == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' || ch == '.' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// Produce a prefixed Turtle local name from an already-safe identifier.
///
/// Accepts identifiers in two forms:
/// - `prefix:local` → returned as-is (assumed safe)
/// - anything else → wrapped as `:local`
pub fn turtle_local_name(s: &str) -> String {
    if s.contains(':') {
        s.to_string()
    } else {
        format!(":{}", turtle_safe_local(s))
    }
}

/// Escape a string for use as a Turtle double-quoted literal.
fn turtle_escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::audit::{AuditAction, LocalAuditKind};

    #[test]
    fn test_empty_graph_emits_prefixes() {
        let graph = ProvenanceGraph::new();
        let turtle = graph.to_turtle();
        assert!(turtle.contains("@prefix prov:"));
        assert!(turtle.contains("@prefix rdfs:"));
        assert!(turtle.contains("@prefix xsd:"));
        assert!(!turtle.contains("prov:Activity"));
    }

    #[test]
    fn test_audit_entry_to_provenance() {
        let entry = AuditEntry {
            timestamp: "2025-01-01T00:00:00Z".to_string(),
            tenant_id: "acme".to_string(),
            pool_id: Some("workers".to_string()),
            instance_id: Some("i-abc123".to_string()),
            action: AuditAction::InstanceStarted,
            detail: Some("pid=12345".to_string()),
            threats: vec![],
            gate_decision: None,
            frame_sequence: None,
        };

        let graph = audit_entry_to_provenance(&entry, 1);
        let turtle = graph.to_turtle();
        assert!(turtle.contains("mvm:audit_activity_1 a prov:Activity"));
        assert!(turtle.contains("prov:startedAtTime \"2025-01-01T00:00:00Z\"^^xsd:dateTime"));
        assert!(turtle.contains("mvm:tenant_acme a prov:Agent"));
        assert!(turtle.contains("prov:wasAssociatedWith mvm:tenant_acme"));
        assert!(turtle.contains("mvm:instance_i-abc123 a prov:Entity"));
        assert!(turtle.contains("prov:used mvm:instance_i-abc123"));
        assert!(turtle.contains('"'));
    }

    #[test]
    fn test_local_audit_event_to_provenance() {
        let event = LocalAuditEvent {
            timestamp: "2025-01-01T00:00:00Z".to_string(),
            kind: LocalAuditKind::VmStart,
            vm_name: Some("my-vm".to_string()),
            detail: Some("template=alpine".to_string()),
        };

        let graph = local_audit_event_to_provenance(&event, 7);
        let turtle = graph.to_turtle();

        assert!(turtle.contains("mvm:local_activity_7 a prov:Activity"));
        assert!(turtle.contains("mvm:host_operator a prov:Agent"));
        assert!(turtle.contains("mvm:vm_my-vm a prov:Entity"));
        assert!(turtle.contains("template=alpine"));
    }

    #[test]
    fn test_turtle_safe_local_escapes_leading_digit() {
        assert_eq!(turtle_safe_local("123foo"), "_123foo");
        assert_eq!(turtle_safe_local("foo bar"), "foo_bar");
        assert_eq!(turtle_safe_local(""), "_");
    }

    #[test]
    fn test_turtle_escape_string() {
        assert_eq!(turtle_escape_string("a\"b"), "a\\\"b");
        assert_eq!(turtle_escape_string("a\\b"), "a\\\\b");
        assert_eq!(turtle_escape_string("a\nb"), "a\\nb");
    }
}
