//! Decision-provenance types and a minimal PROV-O/Turtle exporter.
//!
//! This module is intentionally small and dependency-free. It defines a
//! thin semantic coating over `mvm`'s existing chain-signed audit
//! substrate: audit events are mapped to W3C PROV-O activities, agents,
//! and entities, then serialized as Turtle.
//!
//! The serializer is hand-written rather than generated by an RDF crate
//! to keep the trusted compute base and dependency footprint small. The
//! output is valid Turtle for the subset of PROV-O that `mvm` uses.

use alloc::collections::BTreeMap;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::fmt::{self, Write as _};

use crate::ir::ir_hash;
use crate::policy::audit::{AuditEntry, LocalAuditEvent};
use serde::{Deserialize, Serialize};

/// Default PROV-O namespace URI.
pub const NS_PROV: &str = "http://www.w3.org/ns/prov#";
/// Default RDF schema namespace URI.
pub const NS_RDFS: &str = "http://www.w3.org/2001/02/rdf-schema#";
/// XML schema namespace URI (used for typed literals).
pub const NS_XSD: &str = "http://www.w3.org/2001/XMLSchema#";

/// A provenance triple in abbreviated Turtle form.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Triple {
    /// `subject a object`
    Type { subject: String, object: String },
    /// `subject predicate object` where object is an IRI/local name.
    Iri {
        subject: String,
        predicate: String,
        object: String,
    },
    /// `subject predicate "literal"`
    Literal {
        subject: String,
        predicate: String,
        value: String,
    },
    /// `subject predicate "literal"^^xsd:dateTime`
    DateTime {
        subject: String,
        predicate: String,
        value: String,
    },
}

/// A bag of provenance triples that can be serialized to Turtle.
#[derive(Debug, Clone, Default)]
pub struct ProvenanceGraph {
    triples: Vec<Triple>,
}

impl ProvenanceGraph {
    /// Create an empty graph.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add a triple declaring the type of a subject.
    pub fn add_type(&mut self, subject: impl Into<String>, object: impl Into<String>) {
        self.triples.push(Triple::Type {
            subject: subject.into(),
            object: object.into(),
        });
    }

    /// Add a triple linking a subject to an IRI/local object.
    pub fn add_iri(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        object: impl Into<String>,
    ) {
        self.triples.push(Triple::Iri {
            subject: subject.into(),
            predicate: predicate.into(),
            object: object.into(),
        });
    }

    /// Add a triple with a string literal object.
    pub fn add_literal(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        value: impl Into<String>,
    ) {
        self.triples.push(Triple::Literal {
            subject: subject.into(),
            predicate: predicate.into(),
            value: value.into(),
        });
    }

    /// Merge another graph into this one.
    pub fn extend(&mut self, other: Self) {
        self.triples.extend(other.triples);
    }

    /// Add a triple with an `xsd:dateTime` literal object.
    pub fn add_datetime(
        &mut self,
        subject: impl Into<String>,
        predicate: impl Into<String>,
        value: impl Into<String>,
    ) {
        self.triples.push(Triple::DateTime {
            subject: subject.into(),
            predicate: predicate.into(),
            value: value.into(),
        });
    }

    /// Serialize the graph to Turtle, including standard namespace prefixes.
    pub fn to_turtle(&self) -> String {
        let mut out = String::new();
        writeln!(
            out,
            "@prefix prov: <{NS_PROV}> .\n@prefix rdfs: <{NS_RDFS}> .\n@prefix xsd: <{NS_XSD}> ."
        )
        .expect("write to string cannot fail");
        if self.triples.is_empty() {
            return out;
        }
        out.push('\n');

        // Group triples by subject so Turtle can use semicolon shorthand.
        let mut by_subject: alloc::collections::BTreeMap<&str, Vec<&Triple>> =
            alloc::collections::BTreeMap::new();
        for triple in &self.triples {
            by_subject.entry(triple.subject()).or_default().push(triple);
        }

        for (subject, triples) in by_subject {
            let subject_local = turtle_local_name(subject);
            for (idx, triple) in triples.iter().enumerate() {
                if idx == 0 {
                    write!(out, "{subject_local}").expect("write to string cannot fail");
                }
                let separator = if idx == triples.len() - 1 { " ." } else { " ;" };
                match triple {
                    Triple::Type { object, .. } => {
                        write!(out, " a {object}{separator}").expect("write to string cannot fail");
                    }
                    Triple::Iri {
                        predicate, object, ..
                    } => {
                        write!(out, " {predicate} {object}{separator}")
                            .expect("write to string cannot fail");
                    }
                    Triple::Literal {
                        predicate, value, ..
                    } => {
                        let escaped = turtle_escape_string(value);
                        write!(out, " {predicate} \"{escaped}\"{separator}")
                            .expect("write to string cannot fail");
                    }
                    Triple::DateTime {
                        predicate, value, ..
                    } => {
                        let escaped = turtle_escape_string(value);
                        write!(out, " {predicate} \"{escaped}\"^^xsd:dateTime{separator}")
                            .expect("write to string cannot fail");
                    }
                }
            }
            out.push('\n');
        }
        out
    }
}

impl Triple {
    fn subject(&self) -> &str {
        match self {
            Triple::Type { subject, .. }
            | Triple::Iri { subject, .. }
            | Triple::Literal { subject, .. }
            | Triple::DateTime { subject, .. } => subject.as_str(),
        }
    }
}

/// Convert an `AuditEntry` into PROV-O triples.
///
/// Each entry produces:
/// - an `prov:Activity` for the action,
/// - a `prov:Agent` for the tenant,
/// - an optional `prov:Entity` for the instance,
/// - association/usage links tying them together.
pub fn audit_entry_to_provenance(entry: &AuditEntry, sequence: u64) -> ProvenanceGraph {
    let mut graph = ProvenanceGraph::new();

    let activity_id = format!("mvm:audit_activity_{sequence}");
    let tenant_agent_id = format!("mvm:tenant_{}", turtle_safe_local(&entry.tenant_id));
    let action_label = format!("{:?}", entry.action);

    graph.add_type(&activity_id, "prov:Activity");
    graph.add_literal(&activity_id, "rdfs:label", action_label);
    graph.add_datetime(&activity_id, "prov:startedAtTime", &entry.timestamp);

    // Tenant is always an agent in the activity.
    graph.add_type(&tenant_agent_id, "prov:Agent");
    graph.add_literal(&tenant_agent_id, "rdfs:label", &entry.tenant_id);
    graph.add_iri(&activity_id, "prov:wasAssociatedWith", &tenant_agent_id);

    // When an authorizer principal is recorded, model it as the specific
    // actor that authorized the action.
    if let Some(authorizer) = &entry.authorizer_principal {
        let authorizer_id = format!("mvm:authorizer_{}", turtle_safe_local(authorizer));
        graph.add_type(&authorizer_id, "prov:Agent");
        graph.add_literal(&authorizer_id, "rdfs:label", authorizer);
        graph.add_iri(&activity_id, "prov:wasAssociatedWith", &authorizer_id);
    }

    if let Some(instance_id) = &entry.instance_id {
        let entity_id = format!("mvm:instance_{}", turtle_safe_local(instance_id));
        graph.add_type(&entity_id, "prov:Entity");
        graph.add_literal(&entity_id, "rdfs:label", instance_id);
        graph.add_iri(&activity_id, "prov:used", &entity_id);
    }

    if let Some(detail) = &entry.detail {
        graph.add_literal(&activity_id, "rdfs:comment", detail);
    }

    if let Some(reason) = &entry.authorization_reason {
        graph.add_literal(&activity_id, "rdfs:comment", reason);
    }

    if let Some(ticket_ref) = &entry.authorization_ticket_ref {
        graph.add_literal(&activity_id, "rdfs:seeAlso", ticket_ref);
    }

    graph
}

/// Convert a `LocalAuditEvent` into PROV-O triples.
pub fn local_audit_event_to_provenance(event: &LocalAuditEvent, sequence: u64) -> ProvenanceGraph {
    let mut graph = ProvenanceGraph::new();

    let activity_id = format!("mvm:local_activity_{sequence}");
    let agent_id = "mvm:host_operator".to_string();
    let kind_label = format!("{:?}", event.kind);

    graph.add_type(&activity_id, "prov:Activity");
    graph.add_literal(&activity_id, "rdfs:label", kind_label);
    graph.add_datetime(&activity_id, "prov:startedAtTime", &event.timestamp);

    graph.add_type(&agent_id, "prov:Agent");
    graph.add_literal(&agent_id, "rdfs:label", "mvmctl host operator");
    graph.add_iri(&activity_id, "prov:wasAssociatedWith", &agent_id);

    if let Some(vm_name) = &event.vm_name {
        let entity_id = format!("mvm:vm_{}", turtle_safe_local(vm_name));
        graph.add_type(&entity_id, "prov:Entity");
        graph.add_literal(&entity_id, "rdfs:label", vm_name);
        graph.add_iri(&activity_id, "prov:used", &entity_id);
    }

    if let Some(detail) = &event.detail {
        graph.add_literal(&activity_id, "rdfs:comment", detail);
    }

    graph
}

/// Make a string safe to use as the local part of a prefixed Turtle name.
///
/// Replaces characters that are not valid in `PN_LOCAL` with `_`, and
/// prefixes a leading digit with `_`.
pub fn turtle_safe_local(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for (idx, ch) in s.chars().enumerate() {
        if idx == 0 && ch.is_ascii_digit() {
            out.push('_');
        }
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '-' || ch == '.' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// Produce a prefixed Turtle local name from an already-safe identifier.
///
/// Accepts identifiers in two forms:
/// - `prefix:local` → returned as-is (assumed safe)
/// - anything else → wrapped as `:local`
pub fn turtle_local_name(s: &str) -> String {
    if s.contains(':') {
        s.to_string()
    } else {
        format!(":{}", turtle_safe_local(s))
    }
}

/// Escape a string for use as a Turtle double-quoted literal.
fn turtle_escape_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Content-addressed identifier for a decision record.
///
/// The id is the SHA-256 of the canonical decision body excluding the
/// `decision_id` field, rendered as a 64-character lowercase hex string.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(transparent)]
pub struct DecisionId(pub String);

/// Role an authorizing key asserted when making a decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub enum DecisionActorRole {
    /// Drives release promotions.
    Promoter,
    /// Reports or updates host inventory.
    Inventory,
    /// Catch-all for orchestrator actions.
    Orchestrator,
}

/// Principal that authorized the decision.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct ActorRef {
    /// Human, on-call rotation, or automated-system identity.
    pub principal: String,
    /// Signing key identifier.
    pub key_id: String,
    /// Role the key asserted, if known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub key_role: Option<DecisionActorRole>,
}

/// What triggered the decision.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct DecisionScenario {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_addr: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub capability_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub approval_id: Option<String>,
}

/// Category of decision recorded.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub enum DecisionCategory {
    /// Workload admission decision.
    Admission,
    /// Workload launch decision.
    Launch,
    /// Network egress decision.
    Egress,
    /// Checkpoint create/restore/fork decision.
    Checkpoint,
    /// Human or automated approval decision.
    Approval,
    /// Policy resolution decision.
    Policy,
    /// Control-plane orchestrator decision.
    Control,
}

/// Outcome of a decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub enum DecisionOutcome {
    Approved,
    Denied,
    Deferred,
}

/// Relationship between a decision and a prior decision.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub enum CausalRelation {
    Caused,
    Influenced,
    PrecedentFor,
    Invalidated,
}

/// Link to a prior decision.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct CausalLink {
    pub relation: CausalRelation,
    pub decision_id: DecisionId,
}

/// Free-form compliance metadata.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct DecisionMetadata {
    /// Optional ticket / incident / change-request reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ticket_ref: Option<String>,
    /// Optional policy reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub policy_ref: Option<String>,
    /// Regulation scopes (e.g. EU-AI-Act, NIS2).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub regulation_scope: Vec<String>,
}

/// Cryptographic binding to the existing audit substrate.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct AttestationBinding {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workload_addr: Option<String>,
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub artifact_digests: BTreeMap<String, String>,
    /// Hash of the chain-signed audit entry that carries this decision.
    pub audit_entry_hash: String,
    /// Public key that signed the audit entry.
    pub signer_pubkey: String,
}

/// A content-addressed decision record.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
pub struct DecisionRecord {
    pub decision_id: DecisionId,
    pub version: u32,
    pub category: DecisionCategory,
    pub actor: ActorRef,
    pub scenario: DecisionScenario,
    pub reasoning: String,
    pub outcome: DecisionOutcome,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub timestamp: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub causal_links: Vec<CausalLink>,
    pub metadata: DecisionMetadata,
    pub attestation: AttestationBinding,
}

/// Serializable subset of `DecisionRecord` used to compute its content address.
///
/// The attestation binding is excluded from the id body so that the same
/// semantic decision keeps the same address even when it is carried by
/// different audit entries. The attestation is still part of the stored
/// record and is verified independently.
#[derive(Serialize)]
struct DecisionRecordBody<'a> {
    version: &'a u32,
    category: &'a DecisionCategory,
    actor: &'a ActorRef,
    scenario: &'a DecisionScenario,
    reasoning: &'a str,
    outcome: &'a DecisionOutcome,
    confidence: &'a Option<f64>,
    timestamp: &'a str,
    causal_links: &'a [CausalLink],
    metadata: &'a DecisionMetadata,
}

impl DecisionRecord {
    /// Recompute the content-address of this record.
    ///
    /// The hash is taken over the canonical JSON of the decision body
    /// (everything except `decision_id` and `attestation`) so the id
    /// identifies the semantic decision, not the chain entry that carries it.
    pub fn compute_id(&self) -> DecisionId {
        let body = DecisionRecordBody {
            version: &self.version,
            category: &self.category,
            actor: &self.actor,
            scenario: &self.scenario,
            reasoning: &self.reasoning,
            outcome: &self.outcome,
            confidence: &self.confidence,
            timestamp: &self.timestamp,
            causal_links: &self.causal_links,
            metadata: &self.metadata,
        };
        DecisionId(ir_hash(&body).expect("canonical JSON serialization cannot fail"))
    }

    /// Verify that the stored `decision_id` matches the record body.
    pub fn verify_id(&self) -> bool {
        self.decision_id == self.compute_id()
    }
}

/// Error returned when a `DecisionRecordBuilder` cannot produce a record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecisionRecordError {
    MissingField(&'static str),
}

impl fmt::Display for DecisionRecordError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::MissingField(field) => {
                write!(f, "missing required decision-record field: {field}")
            }
        }
    }
}

/// Builder for [`DecisionRecord`].
///
/// The builder separates construction from content-address computation:
/// `build()` validates required fields, computes the `DecisionId`, and
/// returns an immutable record.
#[derive(Debug, Clone, Default)]
pub struct DecisionRecordBuilder {
    version: u32,
    category: Option<DecisionCategory>,
    actor: Option<ActorRef>,
    scenario: DecisionScenario,
    reasoning: Option<String>,
    outcome: Option<DecisionOutcome>,
    confidence: Option<f64>,
    timestamp: Option<String>,
    causal_links: Vec<CausalLink>,
    metadata: DecisionMetadata,
    attestation: Option<AttestationBinding>,
}

impl DecisionRecordBuilder {
    /// Start a builder for a decision of the given category and outcome.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the schema version.
    pub fn version(mut self, version: u32) -> Self {
        self.version = version;
        self
    }

    /// Set the decision category.
    pub fn category(mut self, category: DecisionCategory) -> Self {
        self.category = Some(category);
        self
    }

    /// Set the authorizing actor.
    pub fn actor(mut self, actor: ActorRef) -> Self {
        self.actor = Some(actor);
        self
    }

    /// Set the scenario that triggered the decision.
    pub fn scenario(mut self, scenario: DecisionScenario) -> Self {
        self.scenario = scenario;
        self
    }

    /// Set the human-readable reasoning.
    pub fn reasoning(mut self, reasoning: impl Into<String>) -> Self {
        self.reasoning = Some(reasoning.into());
        self
    }

    /// Set the decision outcome.
    pub fn outcome(mut self, outcome: DecisionOutcome) -> Self {
        self.outcome = Some(outcome);
        self
    }

    /// Set an optional confidence score.
    pub fn confidence(mut self, confidence: f64) -> Self {
        self.confidence = Some(confidence);
        self
    }

    /// Set the RFC 3339 timestamp.
    pub fn timestamp(mut self, timestamp: impl Into<String>) -> Self {
        self.timestamp = Some(timestamp.into());
        self
    }

    /// Add a causal link to a prior decision.
    pub fn causal_link(mut self, link: CausalLink) -> Self {
        self.causal_links.push(link);
        self
    }

    /// Set compliance metadata.
    pub fn metadata(mut self, metadata: DecisionMetadata) -> Self {
        self.metadata = metadata;
        self
    }

    /// Set the cryptographic attestation binding.
    pub fn attestation(mut self, attestation: AttestationBinding) -> Self {
        self.attestation = Some(attestation);
        self
    }

    /// Build and content-address the decision record.
    pub fn build(self) -> Result<DecisionRecord, DecisionRecordError> {
        let category = self
            .category
            .ok_or(DecisionRecordError::MissingField("category"))?;
        let actor = self
            .actor
            .ok_or(DecisionRecordError::MissingField("actor"))?;
        let reasoning = self
            .reasoning
            .ok_or(DecisionRecordError::MissingField("reasoning"))?;
        let outcome = self
            .outcome
            .ok_or(DecisionRecordError::MissingField("outcome"))?;
        let timestamp = self
            .timestamp
            .ok_or(DecisionRecordError::MissingField("timestamp"))?;
        let attestation = self
            .attestation
            .ok_or(DecisionRecordError::MissingField("attestation"))?;

        let record = DecisionRecord {
            decision_id: DecisionId(String::new()),
            version: self.version,
            category,
            actor,
            scenario: self.scenario,
            reasoning,
            outcome,
            confidence: self.confidence,
            timestamp,
            causal_links: self.causal_links,
            metadata: self.metadata,
            attestation,
        };

        Ok(DecisionRecord {
            decision_id: record.compute_id(),
            ..record
        })
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::policy::audit::{AuditAction, LocalAuditKind};

    #[test]
    fn test_empty_graph_emits_prefixes() {
        let graph = ProvenanceGraph::new();
        let turtle = graph.to_turtle();
        assert!(turtle.contains("@prefix prov:"));
        assert!(turtle.contains("@prefix rdfs:"));
        assert!(turtle.contains("@prefix xsd:"));
        assert!(!turtle.contains("prov:Activity"));
    }

    #[test]
    fn test_audit_entry_to_provenance() {
        let entry = AuditEntry {
            timestamp: "2025-01-01T00:00:00Z".to_string(),
            tenant_id: "acme".to_string(),
            pool_id: Some("workers".to_string()),
            instance_id: Some("i-abc123".to_string()),
            action: AuditAction::InstanceStarted,
            detail: Some("pid=12345".to_string()),
            threats: vec![],
            gate_decision: None,
            frame_sequence: None,
            authorizer_principal: None,
            authorization_reason: None,
            authorization_ticket_ref: None,
        };

        let graph = audit_entry_to_provenance(&entry, 1);
        let turtle = graph.to_turtle();
        assert!(turtle.contains("mvm:audit_activity_1 a prov:Activity"));
        assert!(turtle.contains("prov:startedAtTime \"2025-01-01T00:00:00Z\"^^xsd:dateTime"));
        assert!(turtle.contains("mvm:tenant_acme a prov:Agent"));
        assert!(turtle.contains("prov:wasAssociatedWith mvm:tenant_acme"));
        assert!(turtle.contains("mvm:instance_i-abc123 a prov:Entity"));
        assert!(turtle.contains("prov:used mvm:instance_i-abc123"));
        assert!(turtle.contains('"'));
    }

    #[test]
    fn test_local_audit_event_to_provenance() {
        let event = LocalAuditEvent {
            timestamp: "2025-01-01T00:00:00Z".to_string(),
            kind: LocalAuditKind::VmStart,
            vm_name: Some("my-vm".to_string()),
            detail: Some("template=alpine".to_string()),
        };

        let graph = local_audit_event_to_provenance(&event, 7);
        let turtle = graph.to_turtle();

        assert!(turtle.contains("mvm:local_activity_7 a prov:Activity"));
        assert!(turtle.contains("mvm:host_operator a prov:Agent"));
        assert!(turtle.contains("mvm:vm_my-vm a prov:Entity"));
        assert!(turtle.contains("template=alpine"));
    }

    #[test]
    fn test_turtle_safe_local_escapes_leading_digit() {
        assert_eq!(turtle_safe_local("123foo"), "_123foo");
        assert_eq!(turtle_safe_local("foo bar"), "foo_bar");
        assert_eq!(turtle_safe_local(""), "_");
    }

    #[test]
    fn test_turtle_escape_string() {
        assert_eq!(turtle_escape_string("a\"b"), "a\\\"b");
        assert_eq!(turtle_escape_string("a\\b"), "a\\\\b");
        assert_eq!(turtle_escape_string("a\nb"), "a\\nb");
    }

    fn sample_decision_record() -> DecisionRecord {
        DecisionRecordBuilder::new()
            .version(1)
            .category(DecisionCategory::Admission)
            .actor(ActorRef {
                principal: "host:builder".to_string(),
                key_id: "host-signer-1".to_string(),
                key_role: Some(DecisionActorRole::Orchestrator),
            })
            .scenario(DecisionScenario {
                plan_id: Some("sha256:abc".to_string()),
                ..DecisionScenario::default()
            })
            .reasoning("plan satisfies grant ceiling")
            .outcome(DecisionOutcome::Approved)
            .timestamp("2026-08-13T00:00:00Z".to_string())
            .metadata(DecisionMetadata {
                ticket_ref: Some("CHG-123".to_string()),
                ..DecisionMetadata::default()
            })
            .attestation(AttestationBinding {
                plan_id: Some("sha256:abc".to_string()),
                audit_entry_hash: "sha256:entryhash".to_string(),
                signer_pubkey: "ed25519:pubkey".to_string(),
                ..AttestationBinding::default()
            })
            .build()
            .expect("valid decision record")
    }

    #[test]
    fn decision_record_builder_computes_id() {
        let record = sample_decision_record();
        assert!(!record.decision_id.0.is_empty());
        assert_eq!(record.decision_id.0.len(), 64);
        assert!(record.verify_id());
    }

    #[test]
    fn decision_id_is_stable_across_clones() {
        let record = sample_decision_record();
        let cloned = record.clone();
        assert_eq!(record.decision_id, cloned.decision_id);
        assert_eq!(record.compute_id(), cloned.compute_id());
    }

    #[test]
    fn decision_id_changes_when_body_changes() {
        let mut record = sample_decision_record();
        let id1 = record.decision_id.clone();
        record.reasoning = "different rationale".to_string();
        record.decision_id = record.compute_id();
        assert_ne!(record.decision_id, id1);
    }

    #[test]
    fn decision_record_serde_roundtrip() {
        let record = sample_decision_record();
        let json = serde_json::to_string(&record).unwrap();
        let parsed: DecisionRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(record, parsed);
        assert!(parsed.verify_id());
    }

    #[test]
    fn decision_record_builder_requires_required_fields() {
        let err = DecisionRecordBuilder::new()
            .reasoning("only reasoning set")
            .build()
            .expect_err("missing fields");
        assert!(matches!(err, DecisionRecordError::MissingField(_)));
    }

    #[test]
    fn decision_record_causal_links_roundtrip() {
        let parent = sample_decision_record();
        let mut child = sample_decision_record();
        child.causal_links.push(CausalLink {
            decision_id: parent.decision_id.clone(),
            relation: CausalRelation::PrecedentFor,
        });
        child.decision_id = child.compute_id();
        assert_ne!(child.decision_id, parent.decision_id);

        let json = serde_json::to_string(&child).unwrap();
        let parsed: DecisionRecord = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.causal_links.len(), 1);
        assert_eq!(parsed.causal_links[0].decision_id, parent.decision_id);
        assert!(parsed.verify_id());
    }
}
