# generated by datamodel-codegen:
#   filename:  workload-ir-v0.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Union


class Kind(Enum):
    registry = 'registry'


@dataclass
class AddonRef1:
    kind: Kind
    url: str
    version: str


class Kind1(Enum):
    local = 'local'


@dataclass
class AddonRef2:
    kind: Kind1
    path: str


AddonRef = Union[AddonRef1, AddonRef2]


class AddonTier(Enum):
    separate = 'separate'
    in_vm = 'in_vm'


class Kind2(Enum):
    warm_process = 'warm_process'


class Kind3(Enum):
    python = 'python'


class Kind4(Enum):
    node = 'node'


class Kind5(Enum):
    none = 'none'


@dataclass
class Dependencies3:
    kind: Kind5


class Kind6(Enum):
    command = 'command'


class Kind7(Enum):
    function = 'function'


class Kind8(Enum):
    literal = 'literal'


@dataclass
class EnvValue1:
    kind: Kind8
    value: str


class Kind9(Enum):
    secret_ref = 'secret_ref'


class Format1(Enum):
    json = 'json'


class Format2(Enum):
    msgpack = 'msgpack'


Format = Union[Format1, Format2]


class Kind10(Enum):
    shell = 'shell'


@dataclass
class HookCmd1:
    kind: Kind10
    line: str


class Kind11(Enum):
    argv = 'argv'


@dataclass
class HookCmd2:
    argv: List[str]
    kind: Kind11


HookCmd = Union[HookCmd1, HookCmd2]


@dataclass
class Hooks:
    after_start: Optional[List[HookCmd]] = None
    before_build: Optional[List[HookCmd]] = None
    before_start: Optional[List[HookCmd]] = None
    before_stop: Optional[List[HookCmd]] = None


@dataclass
class HostPort:
    host: str
    port: int


class Kind12(Enum):
    nix_packages = 'nix_packages'


@dataclass
class Image1:
    kind: Kind12
    packages: List[str]


class Kind13(Enum):
    oci_base = 'oci_base'


@dataclass
class Image2:
    digest: str
    kind: Kind13
    reference: str


Image = Union[Image1, Image2]


class InProcessMode1(Enum):
    serial = 'serial'


class InProcessMode2(Enum):
    concurrent = 'concurrent'


InProcessMode = Union[InProcessMode1, InProcessMode2]


@dataclass
class JsonSchemaShape:
    pass


class MountMode(Enum):
    ro = 'ro'
    rw = 'rw'


class Kind14(Enum):
    volume = 'volume'


@dataclass
class MountSource1:
    kind: Kind14
    name: str


class Kind15(Enum):
    host_path = 'host_path'


@dataclass
class MountSource2:
    kind: Kind15
    path: str


class Kind16(Enum):
    tmpfs = 'tmpfs'


@dataclass
class MountSource3:
    kind: Kind16
    size_mb: int


MountSource = Union[MountSource1, MountSource2, MountSource3]


class Kind17(Enum):
    none = 'none'


@dataclass
class NetworkDns1:
    kind: Kind17


class Kind18(Enum):
    system = 'system'


@dataclass
class NetworkDns2:
    kind: Kind18


class Kind19(Enum):
    resolver = 'resolver'


@dataclass
class NetworkDns3:
    host: str
    kind: Kind19
    port: int


NetworkDns = Union[NetworkDns1, NetworkDns2, NetworkDns3]


@dataclass
class NetworkEgress:
    allowlist: List[HostPort]


class NetworkMode(Enum):
    none = 'none'
    bridge = 'bridge'
    host = 'host'


class NodeTool1(Enum):
    pnpm = 'pnpm'


class NodeTool2(Enum):
    npm = 'npm'


class NodeTool3(Enum):
    yarn = 'yarn'


NodeTool = Union[NodeTool1, NodeTool2, NodeTool3]


class PortProto(Enum):
    tcp = 'tcp'
    udp = 'udp'


class PythonTool1(Enum):
    uv = 'uv'


class PythonTool2(Enum):
    pip_tools = 'pip_tools'


PythonTool = Union[PythonTool1, PythonTool2]


@dataclass
class Resources:
    cpu_cores: int
    memory_mb: int
    rootfs_size_mb: int


class Kind20(Enum):
    env = 'env'


@dataclass
class SecretMount1:
    kind: Kind20
    var: str


class Kind21(Enum):
    file = 'file'


@dataclass
class SecretMount2:
    kind: Kind21
    path: str


SecretMount = Union[SecretMount1, SecretMount2]


@dataclass
class SecretRef:
    mount: SecretMount
    name: str


class Kind22(Enum):
    local_path = 'local_path'


@dataclass
class Source1:
    kind: Kind22
    path: str
    exclude: Optional[List[str]] = field(default_factory=lambda: [])
    include: Optional[List[str]] = field(default_factory=lambda: ['**'])


class Kind23(Enum):
    nix_derivation = 'nix_derivation'


@dataclass
class Source2:
    expr: str
    kind: Kind23


class Kind24(Enum):
    oci_image = 'oci_image'


@dataclass
class Source3:
    digest: str
    kind: Kind24
    reference: str


Source = Union[Source1, Source2, Source3]


class ThreatTier1(Enum):
    untrusted = 'untrusted'


class ThreatTier2(Enum):
    trusted = 'trusted'


ThreatTier = Union[ThreatTier1, ThreatTier2]


@dataclass
class Volume:
    name: str
    persist: bool
    size_mb: int


@dataclass
class AddonUse:
    name: str
    ref: AddonRef
    sha256: str
    tier: AddonTier
    alias: Optional[str] = None
    hooks: Optional[Hooks] = None
    params: Optional[Dict[str, Any]] = None


@dataclass
class Concurrency1:
    in_process: InProcessMode
    kind: Kind2
    max_calls_per_worker: int
    max_rss_mb: int
    pool_size: int
    max_queue_depth: Optional[int] = None


Concurrency = Concurrency1


@dataclass
class Dependencies1:
    kind: Kind3
    lockfile: str
    tool: PythonTool


@dataclass
class Dependencies2:
    kind: Kind4
    lockfile: str
    tool: NodeTool


Dependencies = Union[Dependencies1, Dependencies2, Dependencies3]


@dataclass
class EnvValue2:
    kind: Kind9
    ref: SecretRef


EnvValue = Union[EnvValue1, EnvValue2]


@dataclass
class Mount:
    mode: MountMode
    source: MountSource
    target: str


@dataclass
class PortForward:
    guest: int
    host: int
    proto: PortProto


@dataclass
class Entrypoint1:
    command: List[str]
    kind: Kind6
    env: Optional[Dict[str, EnvValue]] = field(default_factory=lambda: {})
    working_dir: Optional[str] = '/app'


@dataclass
class Entrypoint2:
    format: Format
    function: str
    kind: Kind7
    language: str
    module: str
    args_schema: Optional[JsonSchemaShape] = None
    concurrency: Optional[Concurrency] = None
    env: Optional[Dict[str, EnvValue]] = field(default_factory=lambda: {})
    extra_imports: Optional[List[str]] = None
    primary: Optional[bool] = False
    return_schema: Optional[JsonSchemaShape] = None
    working_dir: Optional[str] = '/app'


Entrypoint = Union[Entrypoint1, Entrypoint2]


@dataclass
class Network:
    mode: NetworkMode
    dns: Optional[NetworkDns] = None
    egress: Optional[NetworkEgress] = None
    peers: Optional[List[str]] = None
    ports: Optional[List[PortForward]] = field(default_factory=lambda: [])


@dataclass
class App:
    entrypoints: List[Entrypoint]
    image: Image
    name: str
    resources: Resources
    source: Source
    addons: Optional[List[AddonUse]] = None
    dependencies: Optional[Dependencies] = None
    env: Optional[Dict[str, EnvValue]] = field(default_factory=lambda: {})
    hooks: Optional[Hooks] = None
    mounts: Optional[List[Mount]] = field(default_factory=lambda: [])
    network: Optional[Network] = None
    threat_tier: Optional[ThreatTier] = None


@dataclass
class Workload:
    apps: List[App]
    id: str
    schema_version: str
    extensions: Optional[Dict[str, Any]] = field(default_factory=lambda: {})
    volumes: Optional[List[Volume]] = field(default_factory=lambda: [])
