/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Per-entry status in a batch response.
 */
export type EmitBatchEntryStatus =
  | {
      chain_head: string;
      kind: "ok";
    }
  | {
      code: EmitErrorCode;
      kind: "err";
      message: string;
    }
  | {
      kind: "skipped";
    };
/**
 * Per-entry error code for batch responses.
 */
export type EmitErrorCode = "record_too_large" | "invalid_entry" | "audit_signer_error";
/**
 * Reverse-DNS-like service identifier with a mandatory version segment.
 *
 * Examples: `host.secrets.v1`, `host.time.v1`, `host.cost.v1`, `broker.v1`.
 *
 * Strings are validated at construction so the gate code can rely on the shape (in particular, the version segment is the rate-limiting parser for the binding gate).
 */
export type ServiceId = string;
/**
 * The guest-bound envelope. Tagged variant; `Ok` carries the typed response payload, `Err` carries a typed error code + message.
 */
export type ServiceResponse =
  | {
      correlation_id: string;
      kind: "ok";
      payload: unknown;
    }
  | {
      code: ServiceErrorCode;
      correlation_id: string;
      kind: "err";
      message: string;
    };
/**
 * Typed broker error codes. Audit log entries carry the code as a stable snake_case string. New variants are additive; renames are wire-breaking.
 */
export type ServiceErrorCode =
  | "not_bound"
  | "not_implemented"
  | "bad_request"
  | "rate_limit_exceeded"
  | "lifetime_quota_exhausted"
  | "queue_full"
  | "response_too_large"
  | "timeout"
  | "unavailable"
  | "not_ready"
  | "composition_depth"
  | "composition_width"
  | "service_call_abuse"
  | "session_revoked"
  | "internal_error";

/**
 * Schema root: every broker wire type under one document so the shared `$defs` (`ServiceErrorCode`, `CorrelationId`, `EmitBatchEntryStatus`, …) are emitted once and the generated clients reference one definition set.
 */
export interface BrokerServices {
  cost_report: CostReport;
  emit_batch_request: EmitBatchRequest;
  emit_batch_response: EmitBatchResponse;
  emit_request: EmitRequest;
  emit_response: EmitResponse;
  service_call: ServiceCall;
  service_response: ServiceResponse;
  time_now_response: TimeNowResponse;
}
/**
 * Response for both `host.cost.v1` verbs: the accumulated spend for the queried scope.
 */
export interface CostReport {
  /**
   * Accumulated spend for the queried scope, in micro-USD (1e-6 USD).
   */
  spent_micros_usd: number;
}
/**
 * Payload for `host.audit.v1::emit_batch`.
 */
export interface EmitBatchRequest {
  /**
   * Entries to append, in order. Length capped at [`BROKER_AUDIT_BATCH_MAX`]; total bytes capped at [`BROKER_AUDIT_BATCH_BYTES`].
   */
  entries: EmitRequest[];
}
/**
 * Payload for `host.audit.v1::emit`.
 */
export interface EmitRequest {
  /**
   * Typed workload-supplied fields. The broker treats them as opaque JSON; they're carried verbatim into the chain entry's `fields` after the per-record byte-cap check.
   */
  fields: {
    [k: string]: unknown;
  };
  /**
   * Wall-clock timestamp in RFC 3339 form. The broker handler records its own timestamp in addition for clock-jump detection.
   */
  ts: string;
}
/**
 * Response for `host.audit.v1::emit_batch`.
 */
export interface EmitBatchResponse {
  /**
   * Final chain head after the last successful append. Equal to the pre-batch chain head if every entry was rejected.
   */
  chain_head: string;
  /**
   * Per-entry status, one per input entry, in input order.
   */
  statuses: EmitBatchEntryStatus[];
}
/**
 * Response for `host.audit.v1::emit`.
 */
export interface EmitResponse {
  /**
   * SHA-256-or-equivalent hash of the JCS-canonical chain entry bytes, signed by `mvm-audit-signer`'s chain key. This is the new chain head after the append.
   */
  chain_head: string;
}
/**
 * The host-bound envelope every broker call rides on.
 *
 * The envelope itself is strictly typed (`deny_unknown_fields`); the `payload` is `serde_json::Value` because per-handler payloads vary. The handler's `parse_payload` step is the *real* schema gate for payload contents.
 */
export interface ServiceCall {
  correlation_id: string;
  payload: unknown;
  service: ServiceId;
  verb: string;
}
/**
 * Response for `host.time.v1::now`: the host wall-clock, milliseconds since the Unix epoch (UTC).
 */
export interface TimeNowResponse {
  /**
   * Milliseconds since the Unix epoch, host-authoritative.
   */
  wall_ms: number;
}
