//! The baked-entrypoint call action — `machine run --entrypoint`.
//!
//! Distinct from `mvmctl machine exec` (dev-only, arbitrary shell). This is
//! the production-safe call surface: it dispatches the `RunEntrypoint` vsock
//! verb, which the guest agent serves only by spawning the program named in
//! `/etc/mvm/entrypoint`.
//!
//! The boot, admission, dispatch and teardown are `mvm_client::entrypoint`'s,
//! the same functions the host library calls, so a call made here and one
//! made from a language SDK are admitted and audited identically. What stays
//! here is what only a terminal command has: reading this process's stdin,
//! writing the workload's output to this process's fds as it arrives, the
//! operator notices on stderr, and the process exit status.

use std::io::{Read, Write};
use std::path::PathBuf;

use anyhow::{Context, Result};
use mvm_client::entrypoint::dispatch::{
    CallObserver, CallOutcome, CallStdin, CallTerminal, RecordedDivergence, error_label,
    one_shot_payload,
};
use mvm_client::entrypoint::stdin_stream::StreamedInputReport;
use mvm_client::entrypoint::{
    CallLifecycle, EntrypointAdmission, EntrypointVm, SessionVmName, WorkloadSource,
};
pub(crate) use mvm_client::entrypoint::{DispatchStdin, EntrypointDispatch};
use mvm_hostd::stream::ShownChunk;

use super::denial_review::{ReviewOffer, ReviewSource};
use crate::ui;

/// One baked-entrypoint call, decoupled from clap so the `machine run`
/// lifecycle dispatcher can drive it directly. `machine run --entrypoint`
/// builds this from `MachineRunArgs` (source → `source`, `-d`/`--name` →
/// `keep_alive`, `--attach` → `attach`); there is no separate `invoke` verb.
pub(in crate::commands) struct EntrypointCall {
    /// Template name / pre-built manifest slot to boot, resolved the same way
    /// as `machine exec --manifest`. With `attach`, this is the running VM's
    /// name instead.
    pub source: String,
    /// What reaches the baked entrypoint's stdin, and when.
    pub stdin: EntrypointStdin,
    /// Wall-clock timeout for the call, in seconds.
    pub timeout: u64,
    /// vCPU count for the booted VM.
    pub cpus: u32,
    /// Memory for the booted VM (MiB).
    pub memory_mib: u32,
    /// Workload IR (`workload.json`) declaring `.secrets`. When set, the
    /// ephemeral VM is admitted so the host spawns the substitution endpoint;
    /// the guest only ever holds the opaque `mvm-secret-<hex>` placeholder.
    pub from_workload_ir: Option<PathBuf>,
    /// Raw `--secret NAME[:HOST,...]` values, bound on top of whatever the
    /// workload IR declares. Resolved before boot, like the IR's own.
    pub secret_flags: Vec<String>,
    /// The `[secrets]` the run's project manifest declares, merged with
    /// `secret_flags` under the same narrowing rules.
    pub manifest_secrets: Vec<mvm_client::admission::run_secrets::RunSecretSpec>,
    /// Explicit ProdSafe agent-verb override to mint into the admitted grant
    /// for the transient entrypoint boot. Empty => use the computed default.
    pub agent_verb_override: Vec<String>,
    /// Opaque commitment to bind into the transient entrypoint plan.
    pub caller_commitment: Option<mvm_core::plan::CallerCommitment>,
    /// Restore the session VM from its post-boot snapshot before the call.
    /// Accepted but not acted on in this build.
    pub reset: bool,
    /// Keep the substrate VM alive after the call (warm session). The machine
    /// name and session id are printed on stderr. Mapped from `machine run`'s
    /// persistence axis.
    pub keep_alive: bool,
    /// Persistent machine identity resolved from `--name`, or generated by the
    /// shared persistent-machine naming policy. Transient calls leave this
    /// empty and receive a collision-resistant internal name.
    pub machine_name: Option<String>,
    /// Mark the kept-alive session `mode=dev` so subsequent `session exec` /
    /// `run-code` are allowed. No effect without `keep_alive`.
    pub keep_alive_dev: bool,
    /// Attach this call to an existing warm session id. Accepted but not
    /// acted on in this build; a non-empty value warns and falls back to the
    /// transient path.
    pub session: Option<String>,
    /// Dispatch into a specific function within a multi-function app. Accepted
    /// so SDK argv survives; routing lands with per-function dispatch.
    pub r#fn: Option<String>,
    /// Dispatch into an **already-running** machine (booted by
    /// `machine run --name <NAME>`) instead of booting a transient VM. `source`
    /// is the running VM's name. Its substitution endpoint + boot-minted
    /// placeholders are reused; the VM is left running (no teardown).
    pub attach: bool,
    /// Whether this terminal invocation may print host denial notices.
    pub show_denials: bool,
    /// Keep denial feedback structured and never open a review prompt.
    pub json_denials: bool,
    /// Where the boot's policy came from, for reviewing its refusals once the
    /// call ends. An `attach` dispatches into a machine another invocation
    /// admitted, and ignores it.
    pub review_source: ReviewSource,
    /// Resolved egress policy for the transient entrypoint boot (from `--net` /
    /// `--allow-host`). Threaded onto the admitted plan and shared vsock
    /// endpoint so a baked entrypoint enforces egress identically to the
    /// transient argv path. Defaults to `deny_all`.
    pub network_policy: mvm_core::network_policy::NetworkPolicy,
    /// Explicit hypervisor/backend selector passed through from `--hypervisor`.
    /// When `None` the platform-default auto-selection is used.
    pub hypervisor: Option<String>,
}

/// How a call's stdin is supplied.
///
/// The two are not variations on a theme; they are different contracts with
/// the guest. A one-shot payload is complete before the call starts, so the
/// guest writes it and closes the pipe — a workload reading to EOF sees one.
/// A streamed stdin has no such moment, so the guest keeps the pipe open and
/// EOF becomes something the host must send, which is why it needs a signed
/// grant, a lease, and a scan, and a one-shot payload needs none of them.
pub(in crate::commands) enum EntrypointStdin {
    /// Every byte, known before the call. Empty ⇒ the default no-argument
    /// payload (`[[], {}]`), because the wrapper's wire contract needs a JSON
    /// `[args, kwargs]` body and an empty one is a decode error in the guest.
    OneShot(Vec<u8>),
    /// mvmctl's own stdin, carried into the workload while it runs, with the
    /// caller's EOF closing the workload's stdin.
    ///
    /// Requested explicitly (`--stdin -` on the entrypoint action), never
    /// inferred: it is what puts the input grant on the signed plan, and a
    /// plan that carries the grant is one the sealed-production shell refusal
    /// applies to. Inferring it from a piped stdin would move every existing
    /// piped call onto that path without anybody asking.
    Streaming,
}

impl EntrypointStdin {
    /// Whether this call asks for a host→guest stdin stream — the one thing
    /// that puts `host.stream.v1` on the plan.
    fn is_streaming(&self) -> bool {
        matches!(self, Self::Streaming)
    }

    /// The payload the `RunEntrypoint` frame carries.
    ///
    /// A streaming call carries none: its bytes arrive as frames afterwards,
    /// and substituting the no-argument body here would put `[[], {}]` in
    /// front of whatever the caller actually piped.
    fn prologue(self) -> Vec<u8> {
        match self {
            Self::OneShot(bytes) => one_shot_payload(bytes),
            Self::Streaming => Vec::new(),
        }
    }

    /// The library's shape for this stdin: a streamed one reads this process's
    /// own stdin.
    fn into_call_stdin(self) -> CallStdin {
        match self {
            Self::OneShot(bytes) => CallStdin::OneShot(one_shot_payload(bytes)),
            Self::Streaming => CallStdin::Streaming(Box::new(std::io::stdin())),
        }
    }
}

pub(in crate::commands) fn run_entrypoint(call: EntrypointCall) -> Result<()> {
    if call.attach {
        let exit_code = dispatch_attached(call)?;
        if exit_code != 0 {
            mvm_observability::exit(exit_code);
        }
        return Ok(());
    }
    run_booted_entrypoint(call)
}

/// Dispatch into an already-running workload by name (booted by `machine run
/// --name <NAME>`), reusing its substitution endpoint and boot-minted
/// placeholders, and return the entrypoint's exit status. No transient boot,
/// no teardown — the VM is the user's to reap.
pub(in crate::commands) fn dispatch_attached(call: EntrypointCall) -> Result<i32> {
    if call.stdin.is_streaming() {
        // The grant lives on the plan the *boot* was admitted under, and
        // that admission happened in whatever process ran `machine run
        // --name`. This one holds no admitted plan for the VM, so there is
        // nothing here that could authorize a write — and a message saying
        // so beats a refusal from three layers down.
        anyhow::bail!(
            "streamed stdin needs the run that boots the workload: the input grant \
             rides on the plan admitted at boot, and `--attach` dispatches into a \
             machine another invocation admitted — drop `--attach`, or pipe a \
             complete payload with `--stdin <PATH>`"
        );
    }
    ui::info(&format!(
        "entrypoint: dispatching into running workload '{}'",
        call.source
    ));
    let mut denials = CallDenials::new(
        call.show_denials,
        call.json_denials,
        ReviewSource::admitted_elsewhere(),
    );
    denials.arm(&call.source);
    let outcome = dispatch(EntrypointDispatch {
        vm_name: &call.source,
        stdin: DispatchStdin::OneShot(call.stdin.prologue()),
        timeout_secs: call.timeout,
        session_id: None,
    });
    denials.finish();
    outcome
}

fn run_booted_entrypoint(call: EntrypointCall) -> Result<()> {
    warn_accepted_but_inert(&call);

    // The entrypoint action targets a manifest slot, resolved through the same
    // helper as `machine exec --manifest`.
    let slot = mvm_client::entrypoint::resolve_slot(WorkloadSource::Manifest(&call.source))?;
    let lifecycle_label = if call.keep_alive {
        "warm session"
    } else {
        "transient VM"
    };
    ui::info(&format!(
        "entrypoint: booting {lifecycle_label} for template '{slot}'"
    ));
    let secrets = mvm_client::admission::run_secrets::resolve_launch_secrets(
        call.from_workload_ir.as_deref(),
        &call.secret_flags,
        &call.manifest_secrets,
        "local",
    )?;
    let backend_name = mvm_client::entrypoint::backend_name_for(call.hypervisor.as_deref())?;
    let admission = EntrypointAdmission::builder(backend_name)
        .cpus(call.cpus)
        .mem_mib(u64::from(call.memory_mib))
        .secrets(secrets)
        .agent_verb_override(call.agent_verb_override)
        .caller_commitment(call.caller_commitment)
        .dev(call.keep_alive_dev)
        .network_policy(call.network_policy)
        .build()?;
    let lifecycle = if call.keep_alive {
        CallLifecycle::KeepAlive {
            mode: if call.keep_alive_dev {
                mvm_core::session::SessionMode::Dev
            } else {
                mvm_core::session::SessionMode::Prod
            },
        }
    } else {
        CallLifecycle::Transient
    };
    let vm_name = call
        .machine_name
        .as_deref()
        .map_or(SessionVmName::Prefixed("invoke"), SessionVmName::Exact);

    let mut out = CallOutput::inherited();
    out.denials = CallDenials::new(call.show_denials, call.json_denials, call.review_source);
    let outcome = crate::commands::env::builder_vm::with_pair_artifact_source(|pair| {
        mvm_client::entrypoint::run_entrypoint_call(
            mvm_client::entrypoint::EntrypointCall {
                vm: EntrypointVm {
                    slot: &slot,
                    vm_name,
                    cpus: call.cpus,
                    memory_mib: call.memory_mib,
                    admission,
                },
                stdin: call.stdin.into_call_stdin(),
                timeout_secs: call.timeout,
                lifecycle,
            },
            pair,
            &mut out,
        )
    });
    out.finish_denials();
    let outcome = outcome?;
    flush_inherited();
    let exit_code = outcome.exit_code();
    if exit_code != 0 {
        mvm_observability::exit(exit_code);
    }
    Ok(())
}

/// Say which accepted flags this build does not act on, rather than ignoring
/// them silently.
fn warn_accepted_but_inert(call: &EntrypointCall) {
    if call.reset {
        ui::warn(
            "--reset is accepted but not acted on in this build; treating as default behaviour",
        );
    }
    if let Some(id) = &call.session {
        ui::warn(&format!(
            "--session {id} is accepted but not acted on in this build; falling back to a \
             transient VM for this call"
        ));
    }
    if let Some(name) = &call.r#fn {
        ui::warn(&format!(
            "--fn {name} is accepted but not acted on in this build; the workload's primary \
             entrypoint will be dispatched"
        ));
    }
}

fn kept_alive_notice(vm_name: &str, session_id: Option<&str>) -> String {
    match session_id {
        Some(id) => format!("Machine kept alive: {vm_name}\nSession kept alive: {id}"),
        None => format!("Machine kept alive: {vm_name}"),
    }
}

/// Read the stdin payload for the call.
///
/// - `None`: the no-argument call payload `[[], {}]` — the wrapper's wire
///   contract requires a JSON `[args, kwargs]` body, and an empty one is a
///   decode error in the guest, so a bare invoke means "call with no args".
/// - `Some("-")`: read everything from mvmctl's own stdin.
/// - `Some(path)`: read the file at `path`.
pub(in crate::commands) fn read_stdin_payload(spec: Option<&str>) -> Result<Vec<u8>> {
    match spec {
        None => Ok(mvm_client::entrypoint::NO_ARGUMENT_PAYLOAD.to_vec()),
        Some("-") => {
            let mut buf = Vec::new();
            std::io::stdin()
                .read_to_end(&mut buf)
                .context("Reading stdin from mvmctl's own stdin")?;
            Ok(buf)
        }
        Some(path) => std::fs::read(path).with_context(|| format!("Reading stdin from {path}")),
    }
}

/// Host-side cap on a buffered stdin payload. Mirrors the guest runner's v1
/// inbound cap; over-cap fails closed rather than silently truncating.
const MAX_STDIN_BYTES: usize = 1024 * 1024;

#[derive(Debug)]
pub(in crate::commands) enum AutoStdinError {
    TooLarge { cap: usize },
    Io(std::io::Error),
}

impl std::fmt::Display for AutoStdinError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::TooLarge { cap } => {
                write!(f, "stdin payload exceeds the {cap}-byte limit")
            }
            Self::Io(e) => write!(f, "reading stdin: {e}"),
        }
    }
}
impl std::error::Error for AutoStdinError {}

/// What the caller's stdin is, for the purpose of the implicit payload read.
///
/// Three states rather than a `bool`, because "not a terminal" was doing two
/// jobs and only one of them is "a payload is waiting".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::commands) enum AutoStdin {
    /// A terminal. Interactive input for the person at the keyboard, never a
    /// workload payload.
    Terminal,
    /// Not a terminal, and nothing readable right now — stdin was inherited
    /// rather than redirected at us.
    Idle,
    /// Not a terminal and readable now: the caller handed us something.
    Ready,
}

/// Classify the real stdin fd without consuming a byte of it.
///
/// A terminal is decided first: a TTY with type-ahead buffered is *readable*,
/// and reading it would steal the person's keystrokes.
///
/// Otherwise `poll` with a zero timeout answers "is there something here", which
/// is the question the implicit read actually needs. A regular file and
/// `/dev/null` always poll readable, so redirection still works; a pipe that was
/// merely inherited does not, so it is left alone. `POLLHUP` counts as readable
/// because a closed pipe yields EOF immediately rather than blocking.
fn classify_stdin() -> AutoStdin {
    use std::io::IsTerminal as _;
    if std::io::stdin().is_terminal() {
        return AutoStdin::Terminal;
    }
    if fd_is_readable_now(libc::STDIN_FILENO) {
        AutoStdin::Ready
    } else {
        AutoStdin::Idle
    }
}

/// Whether `fd` would yield something — bytes, EOF, or an error — without
/// waiting. Split from [`classify_stdin`] so it can be exercised against a real
/// pipe rather than whatever the test harness happens to have on fd 0.
fn fd_is_readable_now(fd: std::os::fd::RawFd) -> bool {
    let mut pfd = libc::pollfd {
        fd,
        events: libc::POLLIN,
        revents: 0,
    };
    // SAFETY: `pfd` is a single initialized `pollfd` living for the whole call,
    // and the count matches. A zero timeout cannot block. `poll` writes only
    // `revents`.
    let ready = unsafe { libc::poll(&mut pfd, 1, 0) };
    ready > 0 && pfd.revents != 0
}

/// Read one buffered stdin payload, capped.
///
/// Only [`AutoStdin::Ready`] is read. The other two yield empty without
/// touching the fd, which is what keeps this from blocking: an inherited pipe
/// that nobody ever writes to or closes used to park the whole launch here in
/// `read_to_end` — before any VM was created, with no output and no timeout.
///
/// One residual: a producer that writes, then holds the pipe open without
/// closing it, polls readable and then blocks in `read_to_end` waiting for the
/// end it was promised. That is the contract this mode has — one whole buffered
/// payload — and truncating at whatever happened to arrive first would be worse
/// than waiting. Callers who want a stream rather than a payload have
/// `--stdin -`, which is a different contract with the guest.
fn read_auto_stdin_from<R: std::io::Read>(
    mut reader: R,
    stdin: AutoStdin,
    cap: usize,
) -> Result<Vec<u8>, AutoStdinError> {
    if stdin != AutoStdin::Ready {
        return Ok(Vec::new());
    }
    // Read cap+1 so an exactly-cap payload passes and the first over-cap byte trips.
    let mut buf = Vec::new();
    reader
        .by_ref()
        .take(cap as u64 + 1)
        .read_to_end(&mut buf)
        .map_err(AutoStdinError::Io)?;
    if buf.len() > cap {
        return Err(AutoStdinError::TooLarge { cap });
    }
    Ok(buf)
}

/// Public entry: acquire the caller's stdin payload from the real stdin fd.
pub(in crate::commands) fn read_auto_stdin() -> anyhow::Result<Vec<u8>> {
    read_auto_stdin_from(std::io::stdin().lock(), classify_stdin(), MAX_STDIN_BYTES)
        .map_err(|e| anyhow::anyhow!(e))
}

/// Dispatch one `RunEntrypoint` call into a running VM, writing its output to
/// this process's fds, and return the exit status to report.
///
/// # Errors
/// The agent unreachable, the stdin route refused, or the stream broken.
pub(crate) fn dispatch(call: EntrypointDispatch<'_>) -> Result<i32> {
    let mut out = CallOutput::inherited();
    let outcome = mvm_client::entrypoint::dispatch(call, &mut out)?;
    flush_inherited();
    Ok(outcome.exit_code())
}

/// Dispatch one call into a running session, writing its output to this
/// process's fds, and return the exit status to report.
///
/// # Errors
/// The dispatch failed; the session is left as it was.
pub(in crate::commands) fn dispatch_into_session(
    id: &mvm_core::session::SessionId,
    record: &mvm_core::session::SessionRecord,
    payload: Vec<u8>,
    timeout_secs: u64,
) -> Result<i32> {
    let mut out = CallOutput::inherited();
    let outcome =
        mvm_client::entrypoint::call_session(id, record, payload, timeout_secs, &mut out)?;
    flush_inherited();
    Ok(outcome.exit_code())
}

/// Deliver one prompt to a machine's resident agent, writing the answer to
/// this process's fds exactly as an entrypoint call's output is written.
///
/// # Errors
/// The prompt was refused, could not be recorded or audited, or its delivery
/// failed.
pub(in crate::commands) fn prompt_machine(
    prompt: &mvm_client::agent_prompt::AgentPrompt,
    checkpointer: Option<&dyn mvm_client::agent_prompt::StepCheckpointer>,
) -> Result<mvm_client::agent_prompt::PromptOutcome> {
    let mut out = CallOutput::inherited();
    let outcome = mvm_client::agent_prompt::send_prompt(prompt, &mut out, checkpointer);
    flush_inherited();
    outcome
}

/// Re-deliver a replay plan's recorded prompts onto the fork `vm_name`,
/// writing each answer to this process's fds.
///
/// # Errors
/// The fork does not grant prompts, or a delivery or its audit entry failed.
pub(in crate::commands) fn replay_prompts(
    vm_name: &str,
    plan: &mvm_runtime::agent_session::replay::ReplayPlan,
    inputs: &mvm_runtime::agent_session::replay_input::ReplayInputStore,
    timeout_secs: u64,
) -> Result<mvm_client::agent_prompt::replay::ReplayedPrompts> {
    let mut out = CallOutput::inherited();
    let replayed = mvm_client::agent_prompt::replay::replay_onto(
        vm_name,
        plan,
        inputs,
        timeout_secs,
        &mut out,
    );
    flush_inherited();
    replayed
}

/// Flush this process's stdout and stderr before a possible exit.
fn flush_inherited() {
    let _ = std::io::stdout().flush();
    let _ = std::io::stderr().flush();
}

/// Where a streamed entrypoint event's bytes land. Behind a struct so a test
/// asserts on what the handler wrote and when, rather than on the process's
/// real fds.
struct EventSinks<'a> {
    out: Box<dyn Write + 'a>,
    err: Box<dyn Write + 'a>,
}

impl EventSinks<'static> {
    fn inherited() -> Self {
        Self {
            out: Box::new(std::io::stdout()),
            err: Box::new(std::io::stderr()),
        }
    }
}

impl CallObserver for EventSinks<'_> {
    /// Put one chunk on the fd its channel belongs to.
    ///
    /// Routed by the channel the guest sent the frame on. The recorded copy
    /// may have been retagged `Trace` — a chunk the seam would not vouch for is
    /// recorded as a marker — but that is a property of the record, not of the
    /// bytes the caller asked for.
    ///
    /// **Flushed per chunk, deliberately.** Rust's stdout is block-buffered
    /// whenever it is not a terminal, so without this the agent could stream
    /// perfectly and `mvmctl … | tee` would still show nothing until exit.
    fn output(&mut self, chunk: &ShownChunk) {
        use mvm_contract::stream::StreamKind;
        let sink = match chunk.kind {
            StreamKind::Stdout => &mut self.out,
            StreamKind::Stderr | StreamKind::Trace => &mut self.err,
            // Entrypoint capture never creates frame chunks. If a future shared
            // caller supplies one, do not print compressed image bytes to a
            // terminal; the dedicated display viewer is the only frame renderer.
            StreamKind::Frame => return,
        };
        let _ = sink.write_all(&chunk.body);
        let _ = sink.flush();
    }

    /// Surface an fd-3 control record to the operator with a clearly-labelled
    /// prefix the workload's own stderr cannot spoof (these come from mvmctl,
    /// not the wrapper).
    fn control(&mut self, header: &str, payload_len: usize) {
        if payload_len == 0 {
            let _ = writeln!(self.err, "[mvmctl-control] {header}");
        } else {
            let _ = writeln!(
                self.err,
                "[mvmctl-control] {header} (+{payload_len} payload bytes)"
            );
        }
        let _ = self.err.flush();
    }

    fn streamed_input(&mut self, vm_name: &str, report: &StreamedInputReport) {
        if let Some(line) = streamed_stdin_notice(vm_name, report) {
            notice(self, &line);
        }
    }
}

/// One call's output: the caller's two fds, and a running tally of how the
/// recorded copy diverged from what they were handed.
struct CallOutput<'a> {
    sinks: EventSinks<'a>,
    divergence: RecordedDivergence,
    /// Answers the endpoint's `ask` decisions while the call runs. A machine
    /// kept alive past the call has no one to ask, and its asks deny.
    approvals: Option<mvm_client::approval_broker::ApprovalServer>,
    denials: CallDenials,
}

/// A call's egress refusals: watched from the moment its machine is named,
/// summarized when it ends, and offered for review against the manifest its
/// boot was admitted under.
#[derive(Default)]
struct CallDenials {
    /// Where the boot's policy came from; `None` when refusals are not shown.
    source: Option<ReviewSource>,
    watch: Option<super::egress_denials::DenialWatch>,
    review: Option<ReviewOffer>,
    json: bool,
}

impl CallDenials {
    fn new(show: bool, json: bool, source: ReviewSource) -> Self {
        Self {
            source: (show || json).then_some(source),
            json,
            ..Self::default()
        }
    }

    /// Start watching `vm_name`, if refusals are shown.
    fn arm(&mut self, vm_name: &str) {
        self.review = self.review_for(vm_name);
        if self.review.is_some() {
            self.watch = super::egress_denials::watch_machine(
                vm_name,
                if self.json {
                    super::egress_denials::Live::Quiet
                } else {
                    super::egress_denials::Live::Notices
                },
            );
        }
    }

    /// How `vm_name`'s refusals are offered for review, if they are shown.
    fn review_for(&self, vm_name: &str) -> Option<ReviewOffer> {
        self.source
            .clone()
            .map(|source| ReviewOffer::new(vm_name, source))
    }

    /// Stop watching, print the summary, and offer the review.
    fn finish(&mut self) {
        if let Some(review) = self.review.take() {
            if self.json {
                let tally = self
                    .watch
                    .take()
                    .map(|watch| watch.finish())
                    .unwrap_or_default();
                if let Err(error) = super::denial_review::emit_json_denial_summary(&tally, &review)
                {
                    eprintln!("could not report denied egress: {error:#}");
                }
            } else {
                super::egress_denials::finish_and_summarize(self.watch.take(), &review);
            }
        }
    }
}

impl CallOutput<'static> {
    fn inherited() -> Self {
        Self {
            sinks: EventSinks::inherited(),
            divergence: RecordedDivergence::default(),
            approvals: None,
            denials: CallDenials::default(),
        }
    }
}

impl CallOutput<'_> {
    fn finish_denials(&mut self) {
        self.denials.finish();
    }

    /// Tell the caller, on stderr, how what an operator can read back differs
    /// from what this call printed.
    ///
    /// Silent when the two agree, which is the ordinary case — a notice that
    /// fires on every call stops being read. Prefixed so a script can detect
    /// it without parsing prose, and on stderr so it never lands in the bytes
    /// an SDK is parsing.
    fn report(&mut self, vm_name: &str, recorded: bool) {
        if !recorded {
            notice(
                &mut self.sinks,
                &format!(
                    "this call's output was not recorded: no output capture for microVM \
                     {vm_name:?} in this process, so `mvmctl machine logs {vm_name}` will not show it"
                ),
            );
            return;
        }
        if let Some(line) = describe_divergence(&self.divergence, vm_name) {
            notice(&mut self.sinks, &line);
        }
    }
}

impl CallObserver for CallOutput<'_> {
    fn vm_named(&mut self, vm_name: &str) {
        self.denials.arm(vm_name);
    }

    fn output(&mut self, chunk: &ShownChunk) {
        self.sinks.output(chunk);
    }

    fn control(&mut self, header: &str, payload_len: usize) {
        self.sinks.control(header, payload_len);
    }

    fn streamed_input(&mut self, vm_name: &str, report: &StreamedInputReport) {
        self.sinks.streamed_input(vm_name, report);
    }

    /// A terminal being streamed to the workload is the workload's, not
    /// ours, so an ask is then answered by the configured non-interactive
    /// choice.
    fn dispatching(&mut self, vm_name: &str, streams_stdin: bool) {
        let terminal_streamed =
            streams_stdin && std::io::IsTerminal::is_terminal(&std::io::stdin());
        self.approvals = crate::approval::serve_for(vm_name, terminal_streamed);
    }

    fn dispatched(&mut self) {
        self.approvals = None;
    }

    /// After the output, before the exit: the caller has just been handed the
    /// workload's own bytes, and this is where it learns whether the copy an
    /// operator can read back is the same one.
    fn call_finished(&mut self, vm_name: &str, outcome: &CallOutcome) {
        if let Some(capture) = &outcome.capture {
            self.divergence = capture.divergence.clone();
            self.report(vm_name, capture.recorded);
        }
        if let CallTerminal::Failed { kind, message } = &outcome.terminal {
            ui::warn(&format!("invoke: {}: {message}", error_label(*kind)));
        }
    }

    /// Stderr keeps stdout clean for the function's actual output bytes. The
    /// machine is named even when no session record could be written: the VM
    /// is still alive and its identity is how the user manages it.
    fn kept_alive(&mut self, vm_name: &str, session_id: Option<&mvm_core::session::SessionId>) {
        let _ = writeln!(
            self.sinks.err,
            "{}",
            kept_alive_notice(
                vm_name,
                session_id.map(mvm_core::session::SessionId::as_str)
            )
        );
        let _ = self.sinks.err.flush();
    }
}

#[cfg(test)]
mod denial_observation_tests {
    use super::*;
    use mvm_core::util::test_env::TestEnv;

    #[test]
    fn entrypoint_name_arms_a_watch_only_for_human_output() {
        let mut quiet = CallOutput::inherited();
        quiet.vm_named("entrypoint-quiet");
        assert!(quiet.denials.watch.is_none());
        assert!(quiet.denials.review.is_none());

        let mut env = TestEnv::new();
        let home = tempfile::tempdir().expect("isolated home");
        env.isolate_mvm_home(home.path());
        let mut human = CallOutput::inherited();
        human.denials = CallDenials::new(true, false, ReviewSource::admitted_elsewhere());
        human.vm_named("entrypoint-human");
        assert!(human.denials.watch.is_some());
        human.finish_denials();
        assert!(human.denials.watch.is_none());
    }

    /// The refusals a booted call summarizes are offered against the manifest
    /// that boot was admitted under, by the name its machine was given.
    #[test]
    fn a_booted_call_offers_its_refusals_against_its_admitted_manifest() {
        let manifest = ReviewSource::Manifest("/project/mvm.toml".into());
        let mut env = TestEnv::new();
        let home = tempfile::tempdir().expect("isolated home");
        env.isolate_mvm_home(home.path());
        let mut out = CallOutput::inherited();
        out.denials = CallDenials::new(true, false, manifest.clone());
        out.vm_named("invoke-7");
        assert_eq!(
            out.denials.review,
            Some(ReviewOffer::new("invoke-7", manifest))
        );
    }

    /// `--json` shows no refusals, so it neither watches nor offers a review.
    #[test]
    fn a_machine_readable_call_watches_quietly_and_points_at_later_review() {
        let source = ReviewSource::Manifest("/p/mvm.toml".into());
        let mut env = TestEnv::new();
        let home = tempfile::tempdir().expect("isolated home");
        env.isolate_mvm_home(home.path());
        let mut denials = CallDenials::new(false, true, source.clone());
        denials.arm("invoke-8");
        assert_eq!(denials.review, Some(ReviewOffer::new("invoke-8", source)));
        assert!(denials.watch.is_some());
        assert!(denials.json);
    }

    /// An attach dispatches into a machine another invocation admitted, so
    /// its refusals are pointed at `mvmctl explain` rather than at a manifest
    /// this process cannot know.
    #[test]
    fn an_attached_call_offers_its_refusals_as_admitted_elsewhere() {
        let denials = CallDenials::new(true, false, ReviewSource::admitted_elsewhere());
        assert_eq!(
            denials.review_for("already-running"),
            Some(ReviewOffer::new(
                "already-running",
                ReviewSource::admitted_elsewhere()
            ))
        );
    }
}

/// Prefix on the operator notices this command writes. Fixed and greppable:
/// the divergence line is the caller's only signal that the recorded copy is
/// not what it printed, and a script has to be able to detect it.
const NOTICE_PREFIX: &str = "[mvmctl-stream]";

fn notice(sinks: &mut EventSinks<'_>, line: &str) {
    // `eprintln!` panics when the write fails, and `mvmctl … 2>&-` is an
    // ordinary thing for a script to do — a diagnostic must not kill the
    // command it is diagnosing.
    let _ = writeln!(sinks.err, "{NOTICE_PREFIX} {line}");
    let _ = sinks.err.flush();
}

/// One line naming how the recorded copy diverged, or `None` when the two
/// copies agree.
fn describe_divergence(divergence: &RecordedDivergence, vm_name: &str) -> Option<String> {
    if divergence.is_clean() {
        return None;
    }
    let mut parts = Vec::new();
    if divergence.dropped_chunks > 0 {
        parts.push(format!(
            "{} chunk(s) went unrecorded because the capture ended mid-call",
            divergence.dropped_chunks
        ));
    }
    if divergence.masked_chunks > 0 {
        parts.push(format!(
            "{} chunk(s) masked by: {}",
            divergence.masked_chunks,
            divergence
                .rules_fired
                .iter()
                .copied()
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    if divergence.withheld_chunks > 0 {
        parts.push(format!(
            "{} chunk(s) withheld because the redaction seam could not check them",
            divergence.withheld_chunks
        ));
    }
    Some(format!(
        "recorded output differs from what this call printed — {}; \
         the bytes above are the workload's own, `mvmctl machine logs {vm_name}` shows the \
         redacted copy",
        parts.join("; ")
    ))
}

/// What to tell the caller when the stdin it streamed did not all land.
///
/// `None` on the ordinary outcome — the caller's stdin ended, the workload's
/// stdin was closed — because a notice that fires every time stops being read.
fn streamed_stdin_notice(vm_name: &str, report: &StreamedInputReport) -> Option<String> {
    if let Some(reason) = &report.stopped_because {
        return Some(format!(
            "streamed stdin to {vm_name:?} stopped early after {} byte(s) in {} frame(s): \
             {reason}",
            report.bytes, report.frames
        ));
    }
    (!report.reached_eof).then(|| {
        format!(
            "the call ended before your stdin did: {} byte(s) in {} frame(s) reached \
             {vm_name:?}, and anything after that was not sent",
            report.bytes, report.frames
        )
    })
}

/// Tell the caller, on stderr, when the stdin it streamed did not all land.
#[cfg(test)]
fn report_streamed_stdin(vm_name: &str, out: &mut CallOutput<'_>, report: StreamedInputReport) {
    out.sinks.streamed_input(vm_name, &report);
}

/// Write one streamed entrypoint event, as it arrives, through the capture and
/// onto the caller's fds — the handler the dispatch runs per frame.
#[cfg(test)]
fn write_entrypoint_event(
    event: &mvm_agentd::vsock::EntrypointEvent,
    capture: &mut mvm_hostd::stream::EntrypointSink,
    out: &mut CallOutput<'_>,
) {
    let CallOutput {
        sinks, divergence, ..
    } = out;
    mvm_client::entrypoint::route_event(event, capture, divergence, sinks);
}

#[cfg(test)]
fn workload_egress_env(vm_name: &str) -> Vec<(String, String)> {
    mvm_client::entrypoint::dispatch::workload_egress_env(vm_name)
}

#[cfg(test)]
fn vsock_egress_env(vm_name: &str) -> Vec<(String, String)> {
    if !mvm_core::config::vm_vsock_egress_marker_path(vm_name).is_file() {
        return Vec::new();
    }
    mvm_core::guest_netd::proxy_env_vars(mvm_core::guest_netd::DEFAULT_EGRESS_PROXY_LISTEN)
}

/// Point the workload's TLS stack at the guest-side egress CA bundle when one
/// is provisioned. An OCI entrypoint runs under `env_clear()` + the request
/// env, so — unlike a flake `/init` child that inherits the shell exports —
/// these must ride the agent request env. Mirrors the mkGuest egress-ca
/// exports (`SSL_CERT_FILE`/`CURL_CA_BUNDLE`/`REQUESTS_CA_BUNDLE` →
/// combined bundle, `NODE_EXTRA_CA_CERTS` → the egress cert alone). No CA
/// provisioned ⇒ env unchanged.
#[cfg(test)]
fn with_egress_ca_env(
    env: Vec<(String, String)>,
    egress_ca_present: bool,
) -> Vec<(String, String)> {
    if !egress_ca_present {
        return env;
    }
    let mut ca = vec![
        (
            "SSL_CERT_FILE".to_string(),
            "/run/mvm/ca-bundle.crt".to_string(),
        ),
        (
            "CURL_CA_BUNDLE".to_string(),
            "/run/mvm/ca-bundle.crt".to_string(),
        ),
        (
            "REQUESTS_CA_BUNDLE".to_string(),
            "/run/mvm/ca-bundle.crt".to_string(),
        ),
        (
            "NODE_EXTRA_CA_CERTS".to_string(),
            "/run/mvm/egress-ca.crt".to_string(),
        ),
    ];
    ca.extend(env);
    ca
}

/// Pure half of the substitution env: given the endpoint's minted placeholder
/// vars, prepend the standard proxy environment so the workload routes
/// secret-bearing egress through the guest's one loopback proxy. Empty
/// placeholders ⇒ empty env (a plain workload is left untouched).
#[cfg(test)]
fn build_substitution_env(placeholders: Vec<(String, String)>) -> Vec<(String, String)> {
    if placeholders.is_empty() {
        return Vec::new();
    }
    let mut env =
        mvm_core::guest_netd::proxy_env_vars(mvm_core::guest_netd::DEFAULT_EGRESS_PROXY_LISTEN);
    env.extend(placeholders);
    env
}

#[cfg(test)]
mod streaming_tests {
    use super::{CallOutput, EventSinks, RecordedDivergence, write_entrypoint_event};
    use mvm_agentd::vsock::EntrypointEvent;
    use mvm_hostd::stream::EntrypointSink;

    /// Sinks over borrowed buffers, so a test reads back exactly what the
    /// handler wrote.
    fn buffers<'a>(out: &'a mut Vec<u8>, err: &'a mut Vec<u8>) -> CallOutput<'a> {
        CallOutput {
            sinks: EventSinks {
                out: Box::new(out),
                err: Box::new(err),
            },
            divergence: RecordedDivergence::default(),
            approvals: None,
            denials: Default::default(),
        }
    }

    /// The capture a call gets when no plane in this process holds the VM —
    /// the `--attach`-into-another-process's-machine case, and the default for
    /// the tests here that are about the rendering rather than the recording.
    fn uncaptured() -> EntrypointSink {
        EntrypointSink::unrecorded()
    }

    #[test]
    fn each_entrypoint_channel_goes_to_its_own_fd() {
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut capture = uncaptured();
            let mut sinks = buffers(&mut out, &mut err);
            write_entrypoint_event(
                &EntrypointEvent::Stdout {
                    chunk: b"to-stdout".to_vec(),
                },
                &mut capture,
                &mut sinks,
            );
            write_entrypoint_event(
                &EntrypointEvent::Stderr {
                    chunk: b"to-stderr".to_vec(),
                },
                &mut capture,
                &mut sinks,
            );
        }
        assert_eq!(out, b"to-stdout");
        assert_eq!(err, b"to-stderr");
    }

    #[test]
    fn a_control_record_is_labelled_and_kept_off_stdout() {
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut capture = uncaptured();
            let mut sinks = buffers(&mut out, &mut err);
            write_entrypoint_event(
                &EntrypointEvent::Control {
                    header_json: r#"{"event":"ready"}"#.to_string(),
                    payload: vec![1, 2, 3],
                },
                &mut capture,
                &mut sinks,
            );
        }
        assert!(out.is_empty(), "a control record is not workload stdout");
        let rendered = String::from_utf8(err).expect("utf8");
        assert!(rendered.starts_with("[mvmctl-control] "), "{rendered}");
        assert!(rendered.contains("(+3 payload bytes)"), "{rendered}");
    }

    #[test]
    fn an_uncaptured_call_hands_the_workloads_bytes_straight_through() {
        // Nothing is recording this VM here, so there is no second copy to
        // protect and nobody to protect it from — the caller ran the function.
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut capture = uncaptured();
            let mut sinks = buffers(&mut out, &mut err);
            write_entrypoint_event(
                &EntrypointEvent::Stdout {
                    chunk: br#"{"card":"4111111111111111"}"#.to_vec(),
                },
                &mut capture,
                &mut sinks,
            );
        }
        assert_eq!(out, br#"{"card":"4111111111111111"}"#);
    }

    /// A sink that records *when* it was pushed, not just what it holds.
    ///
    /// Buffered bytes prove output was produced; the flush is what proves it
    /// left the process. Rust's stdout is block-buffered off a terminal, so a
    /// handler that writes without flushing produces a `| tee` that shows
    /// nothing until exit — indistinguishable, to the operator, from the
    /// buffer-to-exit agent this whole path replaced.
    #[derive(Default)]
    struct RecordingSink {
        ops: Vec<Op>,
    }

    #[derive(Debug, PartialEq, Eq)]
    enum Op {
        Wrote(Vec<u8>),
        Flushed,
    }

    impl std::io::Write for &mut RecordingSink {
        fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
            self.ops.push(Op::Wrote(buf.to_vec()));
            Ok(buf.len())
        }

        fn flush(&mut self) -> std::io::Result<()> {
            self.ops.push(Op::Flushed);
            Ok(())
        }
    }

    /// Every chunk is pushed out of the process before the next one is taken,
    /// so a running workload's output is visible while it runs rather than at
    /// exit.
    ///
    /// This is the hop `mvmctl` owns. The other two legs are proven where they
    /// live: the guest pump emitting before the child exits, and
    /// `send_run_entrypoint` invoking this handler once per non-terminal event
    /// rather than collecting them, both in `mvm-agentd`.
    #[test]
    fn output_reaches_the_operator_before_the_child_exits() {
        let mut out = RecordingSink::default();
        let mut err = RecordingSink::default();
        {
            let mut capture = uncaptured();
            let mut sinks = CallOutput {
                sinks: EventSinks {
                    out: Box::new(&mut out),
                    err: Box::new(&mut err),
                },
                divergence: RecordedDivergence::default(),
                approvals: None,
                denials: Default::default(),
            };
            for chunk in [&b"first"[..], &b"second"[..]] {
                write_entrypoint_event(
                    &EntrypointEvent::Stdout {
                        chunk: chunk.to_vec(),
                    },
                    &mut capture,
                    &mut sinks,
                );
            }
        }
        assert_eq!(
            out.ops,
            vec![
                Op::Wrote(b"first".to_vec()),
                Op::Flushed,
                Op::Wrote(b"second".to_vec()),
                Op::Flushed,
            ],
            "each chunk must leave the process before the next is handled"
        );
    }

    /// The handler is for streaming chunks only: a terminal event is returned
    /// by `send_run_entrypoint` and rendered by the exit-code path, so nothing
    /// this writes is deferred until one arrives.
    #[test]
    fn a_terminal_event_writes_nothing_through_the_streaming_handler() {
        let mut out = RecordingSink::default();
        let mut err = RecordingSink::default();
        {
            let mut sinks = CallOutput {
                sinks: EventSinks {
                    out: Box::new(&mut out),
                    err: Box::new(&mut err),
                },
                divergence: RecordedDivergence::default(),
                approvals: None,
                denials: Default::default(),
            };
            let mut capture = uncaptured();
            write_entrypoint_event(&EntrypointEvent::Exit { code: 0 }, &mut capture, &mut sinks);
        }
        assert!(out.ops.is_empty(), "{:?}", out.ops);
        assert!(err.ops.is_empty(), "{:?}", err.ops);
    }

    #[test]
    fn an_uncaptured_call_says_so_rather_than_leaving_the_operator_to_find_out() {
        // The residual from a `--attach` into a machine some other process
        // booted: the call runs, but `mvmctl machine logs` will not show it.
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut sinks = buffers(&mut out, &mut err);
            sinks.report("detached-vm", false);
        }
        let rendered = String::from_utf8(err).expect("utf8");
        assert!(rendered.starts_with("[mvmctl-stream] "), "{rendered}");
        assert!(rendered.contains("was not recorded"), "{rendered}");
        assert!(rendered.contains("detached-vm"), "{rendered}");
        assert!(out.is_empty(), "a diagnostic never lands on stdout");
    }

    #[test]
    fn a_call_whose_copies_agree_says_nothing() {
        // A notice that fires on every call stops being read. Noted directly
        // against `RecordedCopy::Identical` rather than through `uncaptured()`
        // — that helper's sink answers every frame `NotRecorded`, which is
        // itself something `report` must now surface (see the mid-call-release
        // regression test in `captured_tests`), so it can no longer stand in
        // for "nothing diverged".
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut sinks = buffers(&mut out, &mut err);
            sinks
                .divergence
                .note(&mvm_hostd::stream::RecordedCopy::Identical);
            sinks.report("quiet-vm", true);
        }
        assert!(out.is_empty(), "{}", String::from_utf8_lossy(&out));
        assert!(err.is_empty(), "{}", String::from_utf8_lossy(&err));
    }
}

#[cfg(test)]
mod captured_tests {
    //! What a call leaves behind, read back the way `mvmctl machine logs` reads it.
    //!
    //! Driven against a real plane over a real encrypted transcript: the
    //! entrypoint source's whole reason to exist is that a reader can ask for
    //! one channel and get it, and only an end-to-end read proves the tags
    //! survive the broker, the transcript, and the manifest.

    use super::{CallOutput, EventSinks, RecordedDivergence, write_entrypoint_event};
    use mvm_agentd::vsock::EntrypointEvent;
    use mvm_contract::stream::StreamKind;
    use mvm_core::policy::RedactionPolicy;
    use mvm_core::stream_client::{
        KindFilter, OutputRequest, StreamAvailability, StreamOpts, open_vm_output,
    };
    use mvm_core::util::test_env::TestEnv;
    use mvm_hostd::stream::StreamPlane;
    use mvm_runtime::workload_runner::ConsoleCapture;

    /// A plane holding one VM whose console never appears, so every record in
    /// the capture came from the entrypoint frames this test wrote.
    struct Captured {
        plane: StreamPlane,
        vm: &'static str,
        out: Vec<u8>,
        err: Vec<u8>,
        _env: TestEnv,
        _home: tempfile::TempDir,
    }

    impl Captured {
        /// Attach a plane for `vm`, then run `events` through the same handler
        /// `dispatch` gives `send_run_entrypoint`, closing with the same
        /// end-of-call report `dispatch` writes.
        fn of(vm: &'static str, events: &[EntrypointEvent]) -> Self {
            let mut env = TestEnv::new();
            let home = tempfile::tempdir().expect("tempdir");
            env.isolate_mvm_home(home.path());

            let state = mvm_core::config::vm_state_dir(vm);
            std::fs::create_dir_all(&state).expect("state dir");
            let plane = StreamPlane::new();
            let redaction = RedactionPolicy::default();
            plane
                .attach(&ConsoleCapture {
                    vm_name: vm,
                    console_log: &state.join("console.log"),
                    display_socket: None,
                    redaction: &redaction,
                    retention: mvm_core::plan::StreamRetention::Persist,
                })
                .expect("attach a plane");

            let (mut out, mut err) = (Vec::new(), Vec::new());
            {
                let mut capture = plane.entrypoint_sink(vm);
                let recorded = capture.is_recorded();
                let mut sinks = CallOutput {
                    sinks: EventSinks {
                        out: Box::new(&mut out),
                        err: Box::new(&mut err),
                    },
                    divergence: RecordedDivergence::default(),
                    approvals: None,
                    denials: Default::default(),
                };
                for event in events {
                    write_entrypoint_event(event, &mut capture, &mut sinks);
                }
                sinks.report(vm, recorded);
            }
            Self {
                plane,
                vm,
                out,
                err,
                _env: env,
                _home: home,
            }
        }

        /// Seal the capture and replay it, keeping only `kinds`.
        fn recorded(&self, kinds: KindFilter) -> Vec<(StreamKind, Vec<u8>)> {
            self.plane.release(self.vm);
            let request = OutputRequest {
                opts: StreamOpts::builder().kinds(kinds).build(),
                ..OutputRequest::default()
            };
            let mut stream =
                open_vm_output(self.vm, request).expect("the sealed capture must open");
            assert_eq!(stream.availability(), StreamAvailability::HistoryOnly);
            let mut out = Vec::new();
            while let Some(record) = stream.next_output().expect("read the sealed capture") {
                out.push((record.kind, record.payload));
            }
            out
        }
    }

    fn stdout(bytes: &[u8]) -> EntrypointEvent {
        EntrypointEvent::Stdout {
            chunk: bytes.to_vec(),
        }
    }

    fn stderr(bytes: &[u8]) -> EntrypointEvent {
        EntrypointEvent::Stderr {
            chunk: bytes.to_vec(),
        }
    }

    #[test]
    fn a_call_that_writes_to_stderr_is_readable_on_the_stderr_channel() {
        // The gap this closes: with a plane up and only the console feeding
        // it, every record was labelled stdout, so `--stream stderr` matched
        // nothing a workload had ever written.
        let captured = Captured::of("invoke-stderr-vm", &[stdout(b"o"), stderr(b"e")]);

        assert_eq!(
            captured.recorded(KindFilter::only(StreamKind::Stderr)),
            vec![(StreamKind::Stderr, b"e".to_vec())],
            "a stderr read must return the stderr frame and nothing else"
        );
    }

    #[test]
    fn the_two_channels_stay_separable_all_the_way_into_the_transcript() {
        let captured = Captured::of("invoke-split-vm", &[stdout(b"o"), stderr(b"e")]);

        assert_eq!(captured.out, b"o", "stdout went to the caller's stdout");
        assert_eq!(captured.err, b"e", "stderr went to the caller's stderr");
        assert_eq!(
            captured.recorded(KindFilter::all()),
            vec![
                (StreamKind::Stdout, b"o".to_vec()),
                (StreamKind::Stderr, b"e".to_vec()),
            ],
            "the capture keeps the channel the guest sent each frame on"
        );
    }

    #[test]
    fn a_frame_is_recorded_once_and_shown_once() {
        // The failure mode of a tee: the frame reaches the capture *and* the
        // caller's fd by two paths, and one of them runs twice.
        let captured = Captured::of(
            "invoke-once-vm",
            &[stdout(b"first "), stdout(b"second"), stderr(b"only")],
        );

        assert_eq!(captured.out, b"first second");
        assert_eq!(captured.err, b"only");
        assert_eq!(
            captured.recorded(KindFilter::all()),
            vec![
                (StreamKind::Stdout, b"first ".to_vec()),
                (StreamKind::Stdout, b"second".to_vec()),
                (StreamKind::Stderr, b"only".to_vec()),
            ],
            "three frames must leave three records, not six"
        );
    }

    /// A JSON body carrying a Luhn-valid number — the shape an SDK parses off
    /// `MachineResult.stdout`, and the shape the curated ruleset matches.
    const JSON_RETURN: &[u8] = br#"{"email":"a@b.com","id":4111111111111111}"#;

    #[test]
    fn a_return_value_reaches_the_caller_whole_while_the_transcript_holds_the_masked_copy() {
        // The correction: whoever ran this call has code execution inside the
        // workload that produced these bytes, so masking their own return
        // value protects nothing — and `{"id":XXX}` is not JSON, so it breaks
        // every SDK that parses the result. The copy that leaves the host is
        // still masked.
        let captured = Captured::of("invoke-json-vm", &[stdout(JSON_RETURN)]);
        let shown = captured.out.clone();

        assert_eq!(
            shown, JSON_RETURN,
            "the caller's own return value must round-trip byte for byte"
        );
        serde_json::from_slice::<serde_json::Value>(&shown)
            .expect("what the caller was handed must still parse as JSON");

        let recorded = captured.recorded(KindFilter::all());
        let (kind, body) = recorded.first().expect("one record").clone();
        assert_eq!(kind, StreamKind::Stdout);
        assert!(
            !body.windows(16).any(|w| w == b"4111111111111111"),
            "the recorded copy must still be masked: {}",
            String::from_utf8_lossy(&body)
        );
        assert_ne!(body, shown);
    }

    #[test]
    fn the_caller_is_told_the_recorded_copy_diverged_and_which_rules_fired() {
        // Divergence the caller cannot detect is the worst of both: their
        // bytes are whole, and they have no way to know an operator reading
        // the same call back sees something else.
        let captured = Captured::of("invoke-divergence-vm", &[stdout(JSON_RETURN)]);

        let rendered = String::from_utf8(captured.err.clone()).expect("utf8");
        assert!(
            rendered.starts_with("[mvmctl-stream] "),
            "a script has to be able to detect this without parsing prose: {rendered}"
        );
        assert!(rendered.contains("recorded output differs"), "{rendered}");
        assert!(rendered.contains("credit_card"), "{rendered}");
        assert!(rendered.contains("email"), "{rendered}");
        assert!(rendered.contains("1 chunk(s) masked"), "{rendered}");
        assert!(
            !rendered.contains("4111111111111111"),
            "naming the rule must not mean quoting the value: {rendered}"
        );
    }

    #[test]
    fn an_fd3_control_record_is_captured_on_the_trace_channel() {
        let captured = Captured::of(
            "invoke-trace-vm",
            &[EntrypointEvent::Control {
                header_json: r#"{"event":"ready"}"#.to_string(),
                payload: vec![1, 2, 3],
            }],
        );

        assert!(captured.out.is_empty());
        assert_eq!(
            captured.recorded(KindFilter::only(StreamKind::Trace)),
            vec![(StreamKind::Trace, br#"{"event":"ready"}"#.to_vec())],
            "the structured record belongs on the trace channel, not stdout"
        );
    }

    #[test]
    fn a_release_mid_call_is_reported_not_swallowed() {
        // `recorded` is sampled once, before the first frame. A teardown that
        // lands between two frames of the same dispatch — `release` sealing
        // the transcript out from under a call still streaming — must not
        // leave the report describing a clean call just because that one
        // early sample was still true.
        let mut env = TestEnv::new();
        let home = tempfile::tempdir().expect("tempdir");
        env.isolate_mvm_home(home.path());
        let _env = env;
        let vm = "invoke-mid-release-vm";
        let state = mvm_core::config::vm_state_dir(vm);
        std::fs::create_dir_all(&state).expect("state dir");
        let plane = StreamPlane::new();
        let redaction = RedactionPolicy::default();
        plane
            .attach(&ConsoleCapture {
                vm_name: vm,
                console_log: &state.join("console.log"),
                display_socket: None,
                redaction: &redaction,
                retention: mvm_core::plan::StreamRetention::Persist,
            })
            .expect("attach a plane");

        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut capture = plane.entrypoint_sink(vm);
            let recorded = capture.is_recorded();
            assert!(recorded, "the plane just attached this VM");
            let mut sinks = CallOutput {
                sinks: EventSinks {
                    out: Box::new(&mut out),
                    err: Box::new(&mut err),
                },
                divergence: RecordedDivergence::default(),
                approvals: None,
                denials: Default::default(),
            };
            write_entrypoint_event(&stdout(b"before"), &mut capture, &mut sinks);
            plane.release(vm); // a teardown racing this call
            write_entrypoint_event(&stdout(b"after"), &mut capture, &mut sinks);
            sinks.report(vm, recorded);
        }

        assert_eq!(
            out, b"beforeafter",
            "the caller still gets its own bytes in full, release or not"
        );
        let rendered = String::from_utf8(err).expect("utf8");
        assert!(
            rendered.contains("went unrecorded"),
            "a chunk dropped by a mid-call release must not be silent: {rendered}"
        );
    }
}

#[cfg(test)]
mod auto_stdin_tests {
    use super::{AutoStdin, AutoStdinError, read_auto_stdin_from};
    use std::io::Cursor;

    #[test]
    fn tty_stdin_yields_empty_payload() {
        // A terminal on stdin is interactive, not input: never block reading it.
        let got = read_auto_stdin_from(Cursor::new(b"ignored" as &[u8]), AutoStdin::Terminal, 1024)
            .unwrap();
        assert!(got.is_empty());
    }

    #[test]
    fn piped_stdin_under_cap_is_read_whole() {
        let got =
            read_auto_stdin_from(Cursor::new(b"STDIN-RT-42" as &[u8]), AutoStdin::Ready, 1024)
                .unwrap();
        assert_eq!(got, b"STDIN-RT-42");
    }

    #[test]
    fn piped_stdin_over_cap_fails_closed() {
        let payload = vec![b'x'; 2048];
        let err =
            read_auto_stdin_from(Cursor::new(&payload[..]), AutoStdin::Ready, 1024).unwrap_err();
        assert!(matches!(err, AutoStdinError::TooLarge { cap: 1024 }));
    }

    #[test]
    fn piped_stdin_exactly_at_cap_passes() {
        let payload = vec![b'x'; 1024];
        let got = read_auto_stdin_from(Cursor::new(&payload[..]), AutoStdin::Ready, 1024).unwrap();
        assert_eq!(got.len(), 1024);
    }

    /// An inherited pipe must not be touched at all. Asserted with a reader that
    /// panics if anyone reads it, because "returned empty" and "never read" are
    /// different facts and only the second one cannot hang.
    #[test]
    fn idle_stdin_is_never_read() {
        struct Explode;
        impl std::io::Read for Explode {
            fn read(&mut self, _: &mut [u8]) -> std::io::Result<usize> {
                panic!("idle stdin must not be read — this is the blocking read that hung a launch")
            }
        }
        let got = read_auto_stdin_from(Explode, AutoStdin::Idle, 1024).unwrap();
        assert!(got.is_empty());
    }

    /// How long the readiness test waits for EOF to surface: far past the
    /// delay seen on a loaded macOS host, far short of the 30-second holder a
    /// leaked write end would have.
    const EOF_DEADLINE: std::time::Duration = std::time::Duration::from_secs(5);

    /// Whether `fd` polls readable before `deadline`, blocking in `poll` rather
    /// than spinning.
    fn fd_becomes_readable_within(fd: std::os::fd::RawFd, deadline: std::time::Duration) -> bool {
        let timeout = libc::c_int::try_from(deadline.as_millis()).unwrap_or(libc::c_int::MAX);
        let mut pfd = libc::pollfd {
            fd,
            events: libc::POLLIN,
            revents: 0,
        };
        // SAFETY: `pfd` is a single initialized `pollfd` living for the whole
        // call, and the count matches. `poll` writes only `revents`.
        let ready = unsafe { libc::poll(&mut pfd, 1, timeout) };
        ready > 0 && pfd.revents != 0
    }

    /// The probe itself, against real pipes. The first case is the bug: a pipe
    /// with a live writer that has sent nothing is what `ssh host 'mvmctl ...'`,
    /// CI runners and any script hand us, and reading it parks the launch
    /// forever before a VM is ever created.
    #[test]
    fn the_readiness_probe_distinguishes_an_idle_pipe_from_a_written_one() {
        use std::io::Write as _;
        use std::os::fd::{AsRawFd as _, FromRawFd as _};

        let mut fds = [0 as libc::c_int; 2];
        // SAFETY: `fds` is a two-element array, which is what `pipe` writes.
        assert_eq!(unsafe { libc::pipe(fds.as_mut_ptr()) }, 0, "pipe()");
        // `pipe` hands back descriptors *without* close-on-exec, unlike every
        // fd Rust's std opens. This suite spawns subprocesses continuously, and
        // any child forked while these are open inherits them — including the
        // write end. A surviving writer means the final assertion below never
        // sees EOF, which is a load-sensitive failure that looks like a bug in
        // the probe rather than a leaked descriptor.
        //
        // Set it before touching the pipe, so the window a concurrent spawn
        // could land in is these two adjacent syscalls rather than the whole
        // test body. macOS has no `pipe2`, so the window cannot be closed
        // outright; leaking a descriptor into every process the suite starts is
        // the part actually worth fixing.
        for fd in fds {
            // SAFETY: `fd` is a live descriptor from the successful `pipe` above.
            assert_ne!(
                unsafe { libc::fcntl(fd, libc::F_SETFD, libc::FD_CLOEXEC) },
                -1,
                "set FD_CLOEXEC"
            );
        }
        // SAFETY: both fds come from a successful `pipe` and are owned here.
        let (read_end, mut write_end) = unsafe {
            (
                std::fs::File::from_raw_fd(fds[0]),
                std::fs::File::from_raw_fd(fds[1]),
            )
        };
        let fd = read_end.as_raw_fd();

        assert!(
            !super::fd_is_readable_now(fd),
            "a pipe whose writer has sent nothing must not read as ready"
        );

        write_end.write_all(b"payload").unwrap();
        assert!(
            super::fd_is_readable_now(fd),
            "a pipe carrying data must read as ready"
        );

        // A closed writer is EOF — reading it returns empty rather than
        // blocking, so it counts as ready.
        //
        // Spawning a child here is the point, not incidental setup. This
        // assertion was flaky before `FD_CLOEXEC` was set above: it failed
        // roughly once in twelve full-suite runs, and only under load, because
        // some *other* test's subprocess happened to be forked while this pipe
        // was open and inherited the write end — leaving a writer alive, so no
        // EOF, so no readiness. Holding a child open deliberately turns that
        // race into a fact: without close-on-exec this fails every time.
        // The child must be past `exec` before the write end is dropped.
        // Close-on-exec applies *at* exec; between fork and exec the child holds
        // a copy of every parent descriptor, so polling in that window sees a
        // live writer no matter what `FD_CLOEXEC` says. Waiting for a byte the
        // child could only emit after exec removes the race rather than
        // out-running it — the first version of this test spawned and polled
        // immediately, and duly failed under a loaded full-suite run while
        // passing alone.
        //
        // `exec` makes the shell *become* the long-lived holder, so killing the
        // child kills the process that would keep an inherited write end open.
        // Without it `sleep` is a grandchild that outlives `kill`, still holding
        // the piped stdout and the test's stderr.
        let mut child = std::process::Command::new("sh")
            .arg("-c")
            .arg("echo exec-done; exec sleep 30")
            .stdout(std::process::Stdio::piped())
            .spawn()
            .expect("spawn a child to hold any inherited descriptor open");
        {
            use std::io::BufRead as _;
            let stdout = child.stdout.as_mut().expect("child stdout is piped");
            let mut line = String::new();
            std::io::BufReader::new(stdout)
                .read_line(&mut line)
                .expect("read the child's post-exec marker");
            assert_eq!(line.trim(), "exec-done", "child must reach exec");
        }

        let mut drain = [0u8; 7];
        std::io::Read::read_exact(&mut { &read_end }, &mut drain).unwrap();
        drop(write_end);
        // EOF is awaited, not sampled. On macOS, once a child has been spawned
        // while the pipe was open, EOF can surface up to a few hundred
        // milliseconds after the last write end is closed — with no process
        // holding that end, and even when the child has already been reaped.
        // A zero-timeout poll read that as a live writer. A leaked writer is
        // held by a child that lives for 30 seconds, so a bounded wait still
        // fails every time on the leak this test exists to catch.
        //
        // Read the answer before cleaning up, so a failure still reaps the child.
        let ready_at_eof = fd_becomes_readable_within(fd, EOF_DEADLINE);
        let _ = child.kill();
        let _ = child.wait();

        assert!(
            ready_at_eof,
            "a closed writer is EOF and must read as ready — a live child still \
             holding the inherited write end means the pipe was not close-on-exec"
        );
    }
}

#[cfg(test)]
mod tests {
    use mvm_core::util::test_env::TestEnv;

    use super::*;

    #[test]
    fn kept_alive_notice_identifies_both_machine_and_session() {
        let notice = kept_alive_notice("named-agent", Some("session-123"));

        assert!(
            notice.contains("Machine kept alive: named-agent"),
            "{notice}"
        );
        assert!(
            notice.contains("Session kept alive: session-123"),
            "{notice}"
        );
    }

    #[test]
    fn kept_alive_notice_still_identifies_the_machine_without_a_session_record() {
        assert_eq!(
            kept_alive_notice("named-agent", None),
            "Machine kept alive: named-agent"
        );
    }

    #[test]
    fn test_read_stdin_none_is_the_no_arg_call() {
        // The wrapper wire contract requires `[args, kwargs]`; a bare invoke
        // sends the explicit no-argument call rather than an empty body.
        let bytes = read_stdin_payload(None).unwrap();
        assert_eq!(bytes, b"[[], {}]");
    }

    #[test]
    fn test_read_stdin_file_returns_contents() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), b"hello-stdin").unwrap();
        let bytes = read_stdin_payload(Some(tmp.path().to_str().unwrap())).unwrap();
        assert_eq!(bytes, b"hello-stdin");
    }

    #[test]
    fn test_read_stdin_missing_file_errors() {
        let err = read_stdin_payload(Some("/this/does/not/exist")).unwrap_err();
        assert!(err.to_string().contains("Reading stdin from"));
    }

    #[test]
    fn build_substitution_env_empty_when_no_placeholders() {
        assert!(super::build_substitution_env(Vec::new()).is_empty());
    }

    /// A secret-bearing workload is handed the same proxy environment as a
    /// plain one: the guest's single loopback listener, which tunnels TLS from
    /// the first byte. That is what makes substitution independent of which
    /// proxy variable a workload's toolchain happens to read.
    #[test]
    fn build_substitution_env_points_every_proxy_var_at_the_tunnelling_endpoint() {
        let env = super::build_substitution_env(vec![(
            "OPENAI_API_KEY".to_string(),
            "mvm-secret-abc123".to_string(),
        )]);
        let expected =
            mvm_core::guest_netd::proxy_env_vars(mvm_core::guest_netd::DEFAULT_EGRESS_PROXY_LISTEN);
        for (key, value) in &expected {
            assert!(
                env.iter().any(|(k, v)| k == key && v == value),
                "missing {key}={value} in {env:?}"
            );
        }
        // An `https://` destination must be reached by tunnelling, never by
        // handing an absolute-URI request to a proxy that would forward the
        // head in cleartext.
        assert_eq!(
            env.iter()
                .find(|(k, _)| k == "ALL_PROXY")
                .map(|(_, v)| v.as_str()),
            Some("socks5h://127.0.0.1:1080")
        );
        // Nothing points the workload at a second, non-tunnelling listener.
        assert!(
            env.iter()
                .all(|(k, v)| !k.ends_with("_PROXY") && !k.ends_with("_proxy")
                    || v.contains("127.0.0.1:1080")
                    || k.eq_ignore_ascii_case("no_proxy")),
            "a proxy var names an endpoint other than the loopback egress proxy: {env:?}"
        );
        // The opaque placeholder var survives (never the value).
        assert!(
            env.iter()
                .any(|(k, v)| k == "OPENAI_API_KEY" && v == "mvm-secret-abc123")
        );
    }

    /// A workload with no secrets and one carrying them are pointed at the same
    /// endpoint. There is no second listener to land on, so a plain workload's
    /// admitted destination is reached through the proxy that also carries the
    /// credentialed flows — and the two tiers cannot disagree about where
    /// egress goes.
    #[test]
    fn a_plain_workload_and_a_secret_bearing_one_get_the_same_proxy_endpoint() {
        let mut env_guard = TestEnv::new();
        let dir = tempfile::tempdir().expect("tempdir");
        env_guard.set("MVM_HOME", dir.path());
        let marker = mvm_core::config::vm_vsock_egress_marker_path("plain-vm");
        std::fs::create_dir_all(marker.parent().expect("marker parent"))
            .expect("mkdir marker parent");
        std::fs::write(&marker, b"1").expect("write marker");

        let proxy_vars = |env: &[(String, String)]| -> Vec<(String, String)> {
            env.iter()
                .filter(|(k, _)| k.to_ascii_lowercase().ends_with("_proxy"))
                .cloned()
                .collect()
        };
        let plain = proxy_vars(&super::vsock_egress_env("plain-vm"));
        let secret_bearing = proxy_vars(&super::build_substitution_env(vec![(
            "OPENAI_API_KEY".to_string(),
            "mvm-secret-abc123".to_string(),
        )]));

        assert!(!plain.is_empty(), "the plain workload must get a proxy");
        assert_eq!(
            plain, secret_bearing,
            "a bound secret must not move the workload to a different listener"
        );
    }

    #[test]
    fn vsock_egress_env_empty_without_marker() {
        let mut env = TestEnv::new();
        let dir = tempfile::tempdir().expect("tempdir");
        env.set("MVM_HOME", dir.path());
        assert!(super::vsock_egress_env("plain-vm").is_empty());
    }

    #[test]
    fn vsock_egress_env_emits_http_proxy_vars_when_marker_present() {
        let mut env = TestEnv::new();
        let dir = tempfile::tempdir().expect("tempdir");
        env.set("MVM_HOME", dir.path());
        let marker = mvm_core::config::vm_vsock_egress_marker_path("plain-vm");
        std::fs::create_dir_all(marker.parent().expect("marker parent"))
            .expect("mkdir marker parent");
        std::fs::write(&marker, b"1").expect("write marker");

        let env = super::vsock_egress_env("plain-vm");
        assert!(
            env.iter()
                .any(|(k, v)| k == "ALL_PROXY" && v == "socks5h://127.0.0.1:1080")
        );
        assert!(
            env.iter()
                .any(|(k, v)| k == "HTTP_PROXY" && v == "http://127.0.0.1:1080")
        );
        assert!(
            env.iter()
                .any(|(k, v)| k == "NO_PROXY" && v.contains("127.0.0.1"))
        );
    }

    #[test]
    fn workload_egress_env_prefers_substitution_env_over_plain_vsock_env() {
        let mut env_guard = TestEnv::new();
        let dir = tempfile::tempdir().expect("tempdir");
        env_guard.set("MVM_HOME", dir.path());

        let marker = mvm_core::config::vm_vsock_egress_marker_path("pref-vm");
        std::fs::create_dir_all(marker.parent().expect("marker parent"))
            .expect("mkdir marker parent");
        std::fs::write(&marker, b"1").expect("write marker");
        let subst = mvm_core::config::vm_substitution_env_path("pref-vm");
        std::fs::create_dir_all(subst.parent().expect("subst parent")).expect("mkdir subst parent");
        std::fs::write(
            &subst,
            serde_json::to_vec(&vec![("OPENAI_API_KEY", "mvm-secret-1")]).expect("json"),
        )
        .expect("write substitution env");

        let env = super::workload_egress_env("pref-vm");
        assert!(env.iter().any(|(k, _)| k == "HTTP_PROXY"));
        // Both paths name the same proxy, so the discriminator is the minted
        // placeholder: only the substitution env carries one.
        assert!(
            env.iter()
                .any(|(k, v)| k == "OPENAI_API_KEY" && v == "mvm-secret-1"),
            "the substitution env's placeholders must win over the plain vsock env: {env:?}"
        );
    }

    #[test]
    fn with_egress_ca_env_noop_when_absent() {
        let base = vec![("HTTP_PROXY".to_string(), "http://x".to_string())];
        assert_eq!(super::with_egress_ca_env(base.clone(), false), base);
    }

    #[test]
    fn with_egress_ca_env_prepends_ca_vars_before_existing() {
        let env = super::with_egress_ca_env(
            vec![("OPENAI_API_KEY".to_string(), "mvm-secret".to_string())],
            true,
        );
        // The TLS-trust vars point the workload at the guest-side bundle the
        // /init decode wrote (the OCI entrypoint's env_clear means a shell
        // export would not reach it).
        assert_eq!(
            env.iter()
                .find(|(k, _)| k == "SSL_CERT_FILE")
                .map(|(_, v)| v.as_str()),
            Some("/run/mvm/ca-bundle.crt")
        );
        assert!(
            env.iter()
                .any(|(k, v)| k == "CURL_CA_BUNDLE" && v == "/run/mvm/ca-bundle.crt")
        );
        assert!(
            env.iter()
                .any(|(k, v)| k == "REQUESTS_CA_BUNDLE" && v == "/run/mvm/ca-bundle.crt")
        );
        assert!(
            env.iter()
                .any(|(k, v)| k == "NODE_EXTRA_CA_CERTS" && v == "/run/mvm/egress-ca.crt")
        );
        // Existing substitution vars are preserved after the CA prefix.
        assert!(
            env.iter()
                .any(|(k, v)| k == "OPENAI_API_KEY" && v == "mvm-secret")
        );
        let ca_at = env.iter().position(|(k, _)| k == "SSL_CERT_FILE").unwrap();
        let key_at = env.iter().position(|(k, _)| k == "OPENAI_API_KEY").unwrap();
        assert!(ca_at < key_at, "CA vars must precede the placeholder vars");
    }
}

/// The two ways a call that asked to stream its stdin is turned down, and what
/// the caller is told when the bytes it typed did not all land.
#[cfg(test)]
mod streamed_stdin_tests {
    use super::*;
    use mvm_client::entrypoint::stdin_stream::StreamedInputReport;

    fn streaming_attach_call() -> EntrypointCall {
        EntrypointCall {
            source: "already-running".to_string(),
            stdin: EntrypointStdin::Streaming,
            timeout: 30,
            cpus: 1,
            memory_mib: 256,
            from_workload_ir: None,
            secret_flags: Vec::new(),
            manifest_secrets: Vec::new(),
            agent_verb_override: Vec::new(),
            caller_commitment: None,
            machine_name: None,
            reset: false,
            keep_alive: false,
            keep_alive_dev: false,
            session: None,
            r#fn: None,
            attach: true,
            show_denials: true,
            json_denials: false,
            review_source: ReviewSource::admitted_elsewhere(),
            network_policy: mvm_core::network_policy::NetworkPolicy::deny_all(),
            hypervisor: None,
        }
    }

    #[test]
    fn attaching_to_a_machine_someone_else_admitted_refuses_a_streamed_stdin() {
        // The grant rides on the plan the *boot* was admitted under, and this
        // process holds no such plan. Without the refusal the write is turned
        // down three layers down, where the message cannot say why.
        let error = run_entrypoint(streaming_attach_call())
            .expect_err("no plan here can authorize a write into that machine");
        let rendered = format!("{error:#}");
        assert!(rendered.contains("--attach"), "{rendered}");
        assert!(rendered.contains("input grant"), "{rendered}");
    }

    fn rendered_report(report: StreamedInputReport) -> (String, String) {
        let (mut out, mut err) = (Vec::new(), Vec::new());
        {
            let mut sinks = CallOutput {
                sinks: EventSinks {
                    out: Box::new(&mut out),
                    err: Box::new(&mut err),
                },
                divergence: RecordedDivergence::default(),
                approvals: None,
                denials: CallDenials::default(),
            };
            report_streamed_stdin("call-vm", &mut sinks, report);
        }
        (
            String::from_utf8(out).expect("utf8"),
            String::from_utf8(err).expect("utf8"),
        )
    }

    #[test]
    fn a_writer_that_stopped_early_says_so_with_the_reason() {
        let (out, err) = rendered_report(StreamedInputReport {
            frames: 3,
            bytes: 42,
            reached_eof: false,
            stopped_because: Some("the workload did not take streamed input".to_string()),
        });
        assert!(err.starts_with("[mvmctl-stream] "), "{err}");
        assert!(err.contains("stopped early"), "{err}");
        assert!(err.contains("42 byte(s) in 3 frame(s)"), "{err}");
        assert!(
            err.contains("the workload did not take streamed input"),
            "{err}"
        );
        assert!(out.is_empty(), "a diagnostic never lands on stdout");
    }

    #[test]
    fn a_call_that_ended_before_the_callers_stdin_did_says_so() {
        // The truncation is invisible otherwise: the workload simply saw less
        // than the caller sent.
        let (out, err) = rendered_report(StreamedInputReport {
            frames: 2,
            bytes: 9,
            reached_eof: false,
            stopped_because: None,
        });
        assert!(err.starts_with("[mvmctl-stream] "), "{err}");
        assert!(err.contains("ended before your stdin did"), "{err}");
        assert!(err.contains("9 byte(s) in 2 frame(s)"), "{err}");
        assert!(err.contains("call-vm"), "{err}");
        assert!(out.is_empty(), "a diagnostic never lands on stdout");
    }

    #[test]
    fn a_stream_that_ran_to_the_end_says_nothing() {
        // A notice that fires every time stops being read.
        let (out, err) = rendered_report(StreamedInputReport {
            frames: 5,
            bytes: 100,
            reached_eof: true,
            stopped_because: None,
        });
        assert!(err.is_empty(), "{err}");
        assert!(out.is_empty(), "{out}");
    }
}
