//! VM lifecycle commands — start, stop, list, attach, exec.

pub(super) use mvm_client::admission::agent_verbs;
pub(super) mod artifact;
pub(super) mod audit_chain;
pub(in crate::commands) mod checkpoint;
pub(crate) mod console;
pub(super) mod cp;
pub(super) mod diff;
pub(super) mod display;
pub(super) mod down;
use mvm_client::admission::entrypoint_resolve;
pub(super) mod exec;
pub(in crate::commands) mod explain;
pub(super) mod forward;
pub(super) mod fs;
pub(super) mod group;
mod host_services;
pub(super) mod host_signer;
pub(crate) mod invoke;
pub(crate) mod launch_sample;
pub(super) mod logs;
pub(super) mod managed_secrets;
mod outputs;
pub(super) mod pause;
pub(crate) mod phase_timing;
pub(super) mod plan_persist;
pub(in crate::commands) mod prepare;
pub(super) mod proc;
pub(super) mod readiness;
pub(super) mod redaction_flags;
pub(super) mod rekernel;
pub(super) mod run_plan;
pub(in crate::commands) mod run_routes;
mod run_secrets;
mod run_validation;
pub(super) mod runtime_pack;
pub(super) mod sandbox;
pub(super) mod sdk_no_vm;
pub(super) mod session;
pub(super) mod set_ttl;
pub(super) mod snapshot;
mod stdin_stream;
pub(super) mod tenant_resolution;
pub(crate) mod up;
pub(in crate::commands) mod verb_audit;
pub(super) mod volume;
pub(crate) mod wait;

pub(super) use super::{Cli, shared};
pub(crate) use agent_verbs::image_is_sealed;
