//! Linux nftables firewall rules.
//!
//! Generates a default-deny ruleset for a per-VM TAP interface
//! and applies it via `nft -f -`. The ruleset blocks all egress
//! from the TAP except for the supervisor's proxy endpoint
//! (typically a TUN device the L4/L7 proxies own); the proxy's
//! own allow-list does the per-flow gating.
//!
//! ## Threat model
//!
//! - **Goal:** even if the L4/L7 proxies' allow-list is
//!   misconfigured, the firewall's default-deny keeps stray
//!   packets confined to the policy-permitted path.
//! - **Not in scope:** ingress to the VM (the host doesn't expose
//!   services to the VM by default; the supervisor's vsock control
//!   path is the only host↔guest channel).
//!
//! ## Rule shape
//!
//! ```text
//! table inet mvm_<vm_id> {
//!   chain forward {
//!     type filter hook forward priority 0; policy drop;
//!     iifname "<tap>" oifname "<proxy>" accept
//!     oifname "<tap>" iifname "<proxy>" ct state established,related accept
//!     iifname "<tap>" drop  # final fail-closed (redundant w/ policy drop)
//!   }
//! }
//! ```
//!
//! The `inet` family covers both IPv4 and IPv6 in one table.
//! Each per-VM table is named `mvm_<vm_id>` (slug-validated) so
//! the supervisor can `nft delete table inet mvm_<vm_id>` on
//! teardown without touching unrelated tables.

use std::io::Write;
use std::process::{Command, Stdio};

use thiserror::Error;

use crate::supervisor::firewall::{FirewallEnforcer, FirewallError, FirewallSpec};

/// Errors `apply` can return.
#[derive(Debug, Error)]
pub enum NftError {
    #[error("invalid table identifier {value:?}: only [A-Za-z0-9_-] permitted")]
    InvalidTableId { value: String },
    #[error("invalid interface name {value:?}: only [A-Za-z0-9_-] permitted")]
    InvalidInterface { value: String },
    #[error("spawning nft failed: {0}")]
    Spawn(std::io::Error),
    #[error("writing rules to nft stdin failed: {0}")]
    Stdin(std::io::Error),
    #[error("nft exited with non-zero status: {status}\nstderr:\n{stderr}")]
    NonZero {
        status: std::process::ExitStatus,
        stderr: String,
    },
    #[error("nft binary not found in $PATH — install nftables")]
    NotInstalled,
}

/// Injectable nft backend. Production shells out via [`CommandNftApplier`];
/// tests capture the generated script without requiring root or nftables.
pub trait NftApplier {
    fn apply_rules(&self, rules: &str) -> Result<(), NftError>;
}

#[derive(Debug, Default, Clone, Copy)]
pub struct CommandNftApplier;

impl NftApplier for CommandNftApplier {
    fn apply_rules(&self, rules: &str) -> Result<(), NftError> {
        apply(rules)
    }
}

/// Linux implementation of the host firewall enforcer. It installs
/// the same default-deny rules generated by this module and keeps all
/// command execution behind an injectable applier.
#[derive(Debug, Clone)]
pub struct LinuxNftFirewall<A = CommandNftApplier> {
    applier: A,
}

impl Default for LinuxNftFirewall<CommandNftApplier> {
    fn default() -> Self {
        Self {
            applier: CommandNftApplier,
        }
    }
}

impl<A> LinuxNftFirewall<A> {
    pub fn new(applier: A) -> Self {
        Self { applier }
    }
}

impl<A: NftApplier> LinuxNftFirewall<A> {
    pub fn install_default_deny_nft(&self, spec: &FirewallSpec) -> Result<(), NftError> {
        let rules = build_default_deny_rules(&spec.vm_id, &spec.tap_iface, &spec.proxy_iface)?;
        self.applier.apply_rules(&rules)
    }

    pub fn teardown_nft(&self, vm_id: &str) -> Result<(), NftError> {
        let rules = build_teardown_rules(vm_id)?;
        self.applier.apply_rules(&rules)
    }
}

impl<A: NftApplier + Send + Sync> FirewallEnforcer for LinuxNftFirewall<A> {
    fn install_default_deny(&self, spec: &FirewallSpec) -> Result<(), FirewallError> {
        self.install_default_deny_nft(spec)
            .map_err(|e| FirewallError::Backend(e.to_string()))
    }

    fn teardown(&self, vm_id: &str) -> Result<(), FirewallError> {
        self.teardown_nft(vm_id)
            .map_err(|e| FirewallError::Backend(e.to_string()))
    }
}

/// Build the default-deny ruleset for a per-VM TAP. Returns the
/// `nft` script that `apply` feeds via stdin.
///
/// `vm_id` is included in the table name (`mvm_<vm_id>`) so the
/// supervisor can scope tear-downs. `tap_iface` is the per-VM
/// virtual NIC name (e.g., `mvmtap0`). `proxy_iface` is the
/// supervisor's egress endpoint — typically the TUN the L4/L7
/// proxies open.
///
/// All three identifiers are slug-validated against
/// `[A-Za-z0-9_-]+`; anything else fails at script-build time so
/// shell-injection attempts via the policy bundle can't slip
/// through.
pub fn build_default_deny_rules(
    vm_id: &str,
    tap_iface: &str,
    proxy_iface: &str,
) -> Result<String, NftError> {
    validate_slug("vm_id", vm_id).map_err(|_| NftError::InvalidTableId {
        value: vm_id.to_string(),
    })?;
    validate_slug("tap_iface", tap_iface).map_err(|_| NftError::InvalidInterface {
        value: tap_iface.to_string(),
    })?;
    validate_slug("proxy_iface", proxy_iface).map_err(|_| NftError::InvalidInterface {
        value: proxy_iface.to_string(),
    })?;
    Ok(format!(
        "table inet mvm_{vm_id} {{\n\
         \tchain forward {{\n\
         \t\ttype filter hook forward priority 0; policy drop;\n\
         \t\tiifname \"{tap_iface}\" oifname \"{proxy_iface}\" accept\n\
         \t\toifname \"{tap_iface}\" iifname \"{proxy_iface}\" ct state established,related accept\n\
         \t\tiifname \"{tap_iface}\" drop\n\
         \t}}\n\
         }}\n"
    ))
}

/// Build the teardown ruleset — removes the per-VM table.
/// Idempotent on the nft side: `nft delete table` errors if the
/// table doesn't exist, so callers wrap with `nft list table`
/// existence check or tolerate the error.
pub fn build_teardown_rules(vm_id: &str) -> Result<String, NftError> {
    validate_slug("vm_id", vm_id).map_err(|_| NftError::InvalidTableId {
        value: vm_id.to_string(),
    })?;
    Ok(format!("delete table inet mvm_{vm_id}\n"))
}

/// Pipe the ruleset to `nft -f -`. Errors with `NotInstalled` if
/// `nft` isn't on `$PATH`, `NonZero` with stderr when nft refuses
/// the script, `Spawn` / `Stdin` for I/O failures.
///
/// Live test: gated behind `MVM_LIVE_NFTABLES=1` because applying
/// rules requires root + an existing TAP. CI Linux runners
/// without privileges can still exercise `build_default_deny_rules`
/// directly.
pub fn apply(rules: &str) -> Result<(), NftError> {
    let mut child = Command::new("nft")
        .arg("-f")
        .arg("-")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| {
            if e.kind() == std::io::ErrorKind::NotFound {
                NftError::NotInstalled
            } else {
                NftError::Spawn(e)
            }
        })?;
    {
        let stdin = child
            .stdin
            .as_mut()
            .ok_or_else(|| NftError::Spawn(std::io::Error::other("nft stdin unavailable")))?;
        stdin.write_all(rules.as_bytes()).map_err(NftError::Stdin)?;
    }
    let output = child.wait_with_output().map_err(NftError::Spawn)?;
    if !output.status.success() {
        return Err(NftError::NonZero {
            status: output.status,
            stderr: String::from_utf8_lossy(&output.stderr).into_owned(),
        });
    }
    Ok(())
}

fn validate_slug(field: &'static str, value: &str) -> Result<(), &'static str> {
    if value.is_empty() {
        return Err(field);
    }
    if !value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return Err(field);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Clone, Default)]
    struct RecordingApplier {
        calls: Arc<Mutex<Vec<String>>>,
    }

    impl RecordingApplier {
        fn calls(&self) -> Vec<String> {
            self.calls.lock().expect("calls lock poisoned").clone()
        }
    }

    impl NftApplier for RecordingApplier {
        fn apply_rules(&self, rules: &str) -> Result<(), NftError> {
            self.calls
                .lock()
                .expect("calls lock poisoned")
                .push(rules.to_string());
            Ok(())
        }
    }

    #[derive(Debug, Clone, Copy)]
    struct FailingApplier;

    impl NftApplier for FailingApplier {
        fn apply_rules(&self, _rules: &str) -> Result<(), NftError> {
            Err(NftError::NotInstalled)
        }
    }

    // ──────────────────────────────────────────────────────────────
    // Enforcement adapter — hermetic apply boundary
    // ──────────────────────────────────────────────────────────────

    #[test]
    fn linux_firewall_installs_generated_default_deny_rules() {
        let applier = RecordingApplier::default();
        let firewall = LinuxNftFirewall::new(applier.clone());
        let spec = FirewallSpec::new("vm1", "mvmtap0", "mvmtun0");

        firewall
            .install_default_deny_nft(&spec)
            .expect("install rules");

        let calls = applier.calls();
        assert_eq!(calls.len(), 1);
        assert!(calls[0].contains("table inet mvm_vm1"));
        assert!(calls[0].contains("policy drop"));
        assert!(calls[0].contains("iifname \"mvmtap0\" oifname \"mvmtun0\" accept"));
    }

    #[test]
    fn linux_firewall_teardown_deletes_only_vm_table() {
        let applier = RecordingApplier::default();
        let firewall = LinuxNftFirewall::new(applier.clone());

        firewall.teardown_nft("vm1").expect("teardown rules");

        let calls = applier.calls();
        assert_eq!(calls, vec!["delete table inet mvm_vm1\n".to_string()]);
    }

    #[test]
    fn linux_firewall_rejects_unsafe_identifiers_before_apply() {
        let applier = RecordingApplier::default();
        let firewall = LinuxNftFirewall::new(applier.clone());
        let spec = FirewallSpec::new("vm1; rm", "mvmtap0", "mvmtun0");

        assert!(matches!(
            firewall.install_default_deny_nft(&spec),
            Err(NftError::InvalidTableId { .. })
        ));
        assert!(applier.calls().is_empty());
    }

    #[test]
    fn firewall_enforcer_maps_backend_errors_without_allowing_boot() {
        let firewall = LinuxNftFirewall::new(FailingApplier);
        let spec = FirewallSpec::new("vm1", "mvmtap0", "mvmtun0");

        let err = FirewallEnforcer::install_default_deny(&firewall, &spec).unwrap_err();
        match err {
            FirewallError::Backend(msg) => assert!(msg.contains("nft binary not found")),
            other => panic!("expected backend error, got {other:?}"),
        }
    }

    // ──────────────────────────────────────────────────────────────
    // Rule-string formatter — hermetic, runs on every host
    // ──────────────────────────────────────────────────────────────

    #[test]
    fn default_deny_rules_format_carries_all_three_identifiers() {
        let rules = build_default_deny_rules("vm1", "mvmtap0", "mvmtun0").unwrap();
        assert!(
            rules.contains("table inet mvm_vm1"),
            "rules missing table name: {rules}"
        );
        assert!(
            rules.contains("iifname \"mvmtap0\""),
            "rules missing tap iif: {rules}"
        );
        assert!(
            rules.contains("oifname \"mvmtun0\""),
            "rules missing proxy oif: {rules}"
        );
    }

    #[test]
    fn default_deny_rules_set_chain_policy_drop() {
        // The "policy drop" line is the load-bearing default-deny
        // — every test on this module should pin its presence so
        // a refactor can't silently flip it to "policy accept".
        let rules = build_default_deny_rules("vm1", "mvmtap0", "mvmtun0").unwrap();
        assert!(
            rules.contains("policy drop"),
            "default-deny missing from rules: {rules}"
        );
    }

    #[test]
    fn default_deny_rules_allow_tap_to_proxy_and_return_established() {
        let rules = build_default_deny_rules("vm1", "mvmtap0", "mvmtun0").unwrap();
        // Forward path: tap → proxy.
        assert!(rules.contains("iifname \"mvmtap0\" oifname \"mvmtun0\" accept"));
        // Return path: proxy → tap, only established/related.
        assert!(rules.contains("ct state established,related accept"));
    }

    #[test]
    fn default_deny_rules_drop_unmatched_tap_traffic_explicitly() {
        // The trailing `iifname "<tap>" drop` is redundant with
        // `policy drop` but explicit — kept so an operator reading
        // the rules doesn't have to remember chain default
        // semantics. Pinning catches a "simplification" PR that
        // removes it.
        let rules = build_default_deny_rules("vm1", "mvmtap0", "mvmtun0").unwrap();
        assert!(rules.contains("iifname \"mvmtap0\" drop"));
    }

    #[test]
    fn default_deny_rules_reject_unsafe_vm_id() {
        // Shell-injection style identifiers must be refused at
        // build time — `nft -f -` reads stdin verbatim, so a
        // crafted vm_id like `vm1; system("rm -rf /")` would
        // execute were it interpolated.
        let err = build_default_deny_rules("vm1; rm -rf /", "mvmtap0", "mvmtun0").unwrap_err();
        assert!(matches!(err, NftError::InvalidTableId { .. }));
    }

    #[test]
    fn default_deny_rules_reject_unsafe_interface() {
        assert!(matches!(
            build_default_deny_rules("vm1", "tap; rm", "mvmtun0"),
            Err(NftError::InvalidInterface { .. })
        ));
        assert!(matches!(
            build_default_deny_rules("vm1", "mvmtap0", "tun.."),
            Err(NftError::InvalidInterface { .. })
        ));
    }

    #[test]
    fn default_deny_rules_reject_empty_identifiers() {
        assert!(build_default_deny_rules("", "tap0", "tun0").is_err());
        assert!(build_default_deny_rules("vm1", "", "tun0").is_err());
        assert!(build_default_deny_rules("vm1", "tap0", "").is_err());
    }

    #[test]
    fn teardown_rules_scope_to_the_vm_table() {
        let rules = build_teardown_rules("vm1").unwrap();
        assert!(rules.contains("delete table inet mvm_vm1"));
        // Doesn't touch unrelated tables.
        assert!(!rules.contains("mvm_vm2"));
    }

    #[test]
    fn teardown_rules_reject_unsafe_id() {
        let err = build_teardown_rules("vm; rm").unwrap_err();
        assert!(matches!(err, NftError::InvalidTableId { .. }));
    }

    // ──────────────────────────────────────────────────────────────
    // apply() — error paths exercised hermetically; live nft
    // success path needs root + an existing tap and is gated by
    // MVM_LIVE_NFTABLES=1 (no such test included here — operators
    // run the full smoke via `tests/smoke_network.rs::nftables_*`
    // which lands in a follow-up).
    // ──────────────────────────────────────────────────────────────

    #[test]
    fn apply_fails_with_not_installed_when_nft_absent() {
        // If `nft` is not on $PATH this returns NotInstalled cleanly.
        // We can't force `nft` to be absent across CI environments,
        // so the test just runs apply() with an obviously-bad
        // ruleset and accepts either NotInstalled (no nft) or
        // NonZero (nft present, refuses bad input). Both are
        // valid hermetic outcomes.
        let r = apply("not actually valid nft input ;;;\n");
        match r {
            Err(NftError::NotInstalled) | Err(NftError::NonZero { .. }) => {}
            Err(other) => panic!("unexpected error type: {other}"),
            Ok(()) => panic!("expected apply() to fail on garbage input"),
        }
    }
}
