# Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/env.rs.
# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
"""SDK environment-variable names, owned by the Rust registry."""

#: Overrides the path to the `mvmctl` binary the SDKs shell out to.
MVM_CLI_BIN_ENV = "MVM_CLI_BIN"

#: Selects the SDK's execution mode (for example `live` or `record`).
MVM_SDK_MODE_ENV = "MVM_SDK_MODE"

#: Carries an explicitly selected security profile from `mvmctl run`
#: into the live SDK's nested `mvmctl machine run` invocation.
MVM_SDK_RUN_PROFILE_ENV = "MVM_SDK_RUN_PROFILE"

#: When set, the SDK writes its wire-shape recording JSON to this
#: path on exit, so a caller need not parse stdout.
MVM_SDK_OUT_PATH_ENV = "MVM_SDK_OUT_PATH"

#: Overrides the per-call timeout, in seconds, applied to a `mvmctl
#: machine` subprocess. Both language wrappers read it and give up at
#: the deadline rather than waiting forever.
MVM_MACHINE_TIMEOUT_ENV = "MVM_MACHINE_TIMEOUT_SEC"

#: Overrides the cap, in bytes, on captured output from a `mvmctl
#: machine` subprocess. Both language wrappers read it and report an
#: overflow as an overflow.
MVM_MACHINE_MAX_OUTPUT_ENV = "MVM_MACHINE_MAX_OUTPUT_BYTES"

__all__ = [
    "MVM_CLI_BIN_ENV",
    "MVM_SDK_MODE_ENV",
    "MVM_SDK_RUN_PROFILE_ENV",
    "MVM_SDK_OUT_PATH_ENV",
    "MVM_MACHINE_TIMEOUT_ENV",
    "MVM_MACHINE_MAX_OUTPUT_ENV",
]
