# Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/env.rs.
# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
"""SDK environment-variable names, owned by the Rust registry."""

#: Selects the SDK's execution mode (for example `live` or `record`).
MVM_SDK_MODE_ENV = "MVM_SDK_MODE"

#: Carries an explicitly selected security profile from `mvmctl run`
#: into the machine a live-mode `Sandbox` boots through the host
#: library.
MVM_SDK_RUN_PROFILE_ENV = "MVM_SDK_RUN_PROFILE"

#: When set, the SDK writes its wire-shape recording JSON to this
#: path on exit, so a caller need not parse stdout.
MVM_SDK_OUT_PATH_ENV = "MVM_SDK_OUT_PATH"

#: Names the `libmvm_hostlib` file the SDKs load in-process.
#: Consulted before any other location; `mvmctl run --mode live` sets
#: it to the library installed beside itself, so a script it runs
#: drives the same build.
MVM_HOSTLIB_PATH_ENV = "MVM_HOSTLIB_PATH"

__all__ = [
    "MVM_SDK_MODE_ENV",
    "MVM_SDK_RUN_PROFILE_ENV",
    "MVM_SDK_OUT_PATH_ENV",
    "MVM_HOSTLIB_PATH_ENV",
]
