#!/bin/sh
filtered=""
for arg in "$@"; do
    case "$arg" in
        --target=aarch64-unknown-linux-gnu) ;;
        *) filtered="$filtered $arg" ;;
    esac
done
exec zig c++ -target aarch64-linux-gnu $filtered
