/* eslint-disable */
/**
 * Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/env.rs.
 * DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
 */

/** Overrides the path to the `mvmctl` binary the SDKs shell out to. */
export const MVM_CLI_BIN_ENV = "MVM_CLI_BIN";

/** Selects the SDK's execution mode (for example `live` or `record`). */
export const MVM_SDK_MODE_ENV = "MVM_SDK_MODE";

/**
 * When set, the SDK writes its wire-shape recording JSON to this
 * path on exit, so a caller need not parse stdout.
 */
export const MVM_SDK_OUT_PATH_ENV = "MVM_SDK_OUT_PATH";
