# Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/error_taxonomy.rs.
# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
"""SDK error taxonomy, owned by the Rust registry."""


class HostServiceError(Exception):
    """Base of every typed host-services failure."""


class BadRequestError(HostServiceError):
    """The host rejected the record shape or size (audit cap)."""


class RateLimitedError(HostServiceError):
    """The per-workload audit emit rate limit is exhausted."""


class UnavailableError(HostServiceError):
    """The host could not answer (handler down, broker not ready)."""


class NotBoundError(HostServiceError):
    """The workload's `ExecutionPlan.services` did not bind the
    service.
    """


class VerbNotImplementedError(HostServiceError):
    """The verb is not implemented in this build."""


class ServiceError(HostServiceError):
    """Any other typed broker error code."""


class TransportError(HostServiceError):
    """Connect, framing, or (de)serialization failure on the vsock
    path.
    """


class InvalidInputError(HostServiceError):
    """The request was malformed: unknown method or a body the verb
    rejects.
    """


#: The success status; any other value is a failure.
STATUS_OK = 0

#: Broker status code -> error type. Mirrors the `MVM_HSVC_*`
#: constants; `MVM_HSVC_OK` is absent because it is not a failure.
STATUS_ERRORS = {
    1: BadRequestError,
    2: RateLimitedError,
    3: UnavailableError,
    4: NotBoundError,
    5: VerbNotImplementedError,
    6: ServiceError,
    7: TransportError,
    8: InvalidInputError,
}

__all__ = [
    "HostServiceError",
    "BadRequestError",
    "RateLimitedError",
    "UnavailableError",
    "NotBoundError",
    "VerbNotImplementedError",
    "ServiceError",
    "TransportError",
    "InvalidInputError",
    "STATUS_OK",
    "STATUS_ERRORS",
]
