# Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/error_taxonomy.rs.
# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
"""SDK error taxonomy, owned by the Rust registry."""


class HostServiceError(Exception):
    """Base of every typed host-services failure."""


class BadRequestError(HostServiceError):
    """The host rejected the record shape or size (audit cap)."""


class RateLimitedError(HostServiceError):
    """The per-workload audit emit rate limit is exhausted."""


class UnavailableError(HostServiceError):
    """The host could not answer (handler down, broker not ready)."""


class NotBoundError(HostServiceError):
    """The workload's `ExecutionPlan.services` did not bind the
    service.
    """


class VerbNotImplementedError(HostServiceError):
    """The verb is not implemented in this build."""


class ServiceError(HostServiceError):
    """Any other typed broker error code."""


class TransportError(HostServiceError):
    """Connect, framing, or (de)serialization failure on the vsock
    path.
    """


class InvalidInputError(HostServiceError):
    """The request was malformed: unknown method or a body the verb
    rejects.
    """


class RemoteError(Exception):
    """User code inside the VM raised; a structured envelope was
    parsed.
    """

    def __init__(self, *, kind: str, error_id: str, message: str):
        super().__init__(f"{kind}: {message} (error_id={error_id})")
        self.kind = kind
        self.error_id = error_id
        self.message = message


class MvmTransportError(RuntimeError):
    """Could not reach the substrate, or got an unparseable response."""


class MsgpackUnavailable(RuntimeError):
    """The workload declared msgpack but the SDK has no msgpack
    support.
    """


class PayloadTooLarge(MvmTransportError):
    """The encoded request exceeded the payload cap, refused before
    anything was sent.
    """


class NoVmIntrospectionError(MvmTransportError):
    """No-VM dispatch was requested without a local function to
    introspect. Python-only in practice: the mode itself has no
    TypeScript form.
    """


class SecretInArgError(RuntimeError):
    """A secret-shaped value was passed as a call argument under strict
    mode.
    """


class SecretInArgWarning(UserWarning):
    """Heuristic flagged a secret-shaped value passed as a call
    argument.
    """


class EmittingContextError(RuntimeError):
    """A transport call fired while `mvm emit` was running the script
    to lower its declarations, where no live microVM exists.
    """


class HostLibraryError(Exception):
    """Base of every error the host library reports."""


class MachineNotFoundError(HostLibraryError):
    """The machine named does not exist."""


class MachineSpecError(HostLibraryError):
    """The request described a machine that cannot be built."""


class MachineBackendError(HostLibraryError):
    """The backend failed while carrying the request out."""


class MachineUnauthorizedError(HostLibraryError):
    """The caller is not allowed to do this."""


class MachineConflictError(HostLibraryError):
    """The request conflicts with the machine's current state."""


class MachineRejectedError(HostLibraryError):
    """A policy refused the request."""


class MachineUnavailableError(HostLibraryError):
    """The backend cannot answer right now; the request may be retried."""


class HostLibraryInputError(HostLibraryError):
    """The method is unknown or its request did not parse."""


class HostLibraryAbiError(HostLibraryError):
    """The library and this binding disagree about the ABI version."""


class HostLibraryEmbedderError(HostLibraryError):
    """The library could not set itself up in this process."""


class HostLibraryInternalError(HostLibraryError):
    """A fault inside the host library itself."""


#: The success status; any other value is a failure.
STATUS_OK = 0

#: Broker status code -> error type. Mirrors the `MVM_HSVC_*`
#: constants; `MVM_HSVC_OK` is absent because it is not a failure.
STATUS_ERRORS = {
    1: BadRequestError,
    2: RateLimitedError,
    3: UnavailableError,
    4: NotBoundError,
    5: VerbNotImplementedError,
    6: ServiceError,
    7: TransportError,
    8: InvalidInputError,
}

#: Host-library error code -> error type. Keyed by the `code` an
#: error body carries, from `mvm_core::error_codes`.
CODE_ERRORS = {
    "NOT_FOUND": MachineNotFoundError,
    "INVALID_SPEC": MachineSpecError,
    "BACKEND_ERROR": MachineBackendError,
    "UNAUTHORIZED": MachineUnauthorizedError,
    "CONFLICT": MachineConflictError,
    "REJECTED": MachineRejectedError,
    "UNAVAILABLE": MachineUnavailableError,
    "INVALID_INPUT": HostLibraryInputError,
    "ABI_NOT_NEGOTIATED": HostLibraryAbiError,
    "EMBEDDER": HostLibraryEmbedderError,
    "INTERNAL": HostLibraryInternalError,
}

__all__ = [
    "HostServiceError",
    "BadRequestError",
    "RateLimitedError",
    "UnavailableError",
    "NotBoundError",
    "VerbNotImplementedError",
    "ServiceError",
    "TransportError",
    "InvalidInputError",
    "RemoteError",
    "MvmTransportError",
    "MsgpackUnavailable",
    "PayloadTooLarge",
    "NoVmIntrospectionError",
    "SecretInArgError",
    "SecretInArgWarning",
    "EmittingContextError",
    "HostLibraryError",
    "MachineNotFoundError",
    "MachineSpecError",
    "MachineBackendError",
    "MachineUnauthorizedError",
    "MachineConflictError",
    "MachineRejectedError",
    "MachineUnavailableError",
    "HostLibraryInputError",
    "HostLibraryAbiError",
    "HostLibraryEmbedderError",
    "HostLibraryInternalError",
    "STATUS_OK",
    "STATUS_ERRORS",
    "CODE_ERRORS",
]
