[package]
name = "mvm-net"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Transparent vsock networking protocol and shared networking primitives for mvm."
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[[bin]]
name = "mvm-guest-netd"
path = "src/bin/mvm-guest-netd.rs"
required-features = ["guest-linux-runner"]

[[bin]]
name = "mvm-host-netd"
path = "src/bin/mvm-host-netd.rs"
required-features = ["host-netd"]

[features]
default = ["proto"]
guest = ["proto"]
guest-linux = ["guest", "dep:libc"]
guest-linux-runner = ["guest-linux", "wire-json"]
host = ["proto"]
host-mvm-core = ["host", "dep:mvm-core"]
host-netd = ["host-runner", "host-std", "host-mvm-core"]
host-runner = ["host", "wire-json"]
host-std = ["host"]
proto = []
serde = ["dep:serde"]
wire-json = ["proto", "serde", "dep:serde_json"]

[dependencies]
libc = { workspace = true, optional = true }
mvm-core = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
