//! Generate a compile target from the Rust examples in the documentation.
//!
//! A Rust snippet in the docs is an API claim, and the only thing that settles
//! an API claim is a compiler. Grep cannot: `mvm_client_local::LocalBackend`
//! reads perfectly and names a crate that does not exist.
//!
//! Every ```rust block in the documentation is emitted into `$OUT_DIR` and
//! included by `tests/doc_rust_examples.rs`, so `cargo check -p mvm-conformance
//! --tests` type-checks it against the real workspace crates. A block that
//! cannot compile as written — an IR shape sketch with `…` in it — opts out
//! with ```rust,ignore and must say why on its first line.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..");
    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR"));

    let mut files = Vec::new();
    for standalone in ["README.md", "AGENTS.md"] {
        let path = repo.join(standalone);
        if path.is_file() {
            files.push(path);
        }
    }
    for tree in ["public/src/content/docs", "crates/mvm-sdk/sdks", "examples"] {
        collect_markdown(&repo.join(tree), &mut files);
    }
    files.sort();

    let mut generated = String::from(
        "// @generated by crates/mvm-conformance/build.rs from the documentation.\n\
         // Each function is one ```rust block. Nothing calls them; compiling is\n\
         // the assertion.\n\n",
    );
    let mut emitted = 0usize;

    for file in &files {
        println!("cargo:rerun-if-changed={}", file.display());
        let Ok(body) = std::fs::read_to_string(file) else {
            continue;
        };
        let relative = file
            .strip_prefix(&repo)
            .unwrap_or(file)
            .display()
            .to_string();

        for block in rust_blocks(&body) {
            if block.ignored {
                continue;
            }
            emitted += 1;
            let name = format!("doc_example_{emitted}");
            let _ = writeln!(generated, "// {relative}:{}", block.line);
            if block.defines_main {
                // The snippet is a whole program; give it a module of its own
                // and rename `main` so it is not an entry point.
                let _ = writeln!(
                    generated,
                    "#[allow(dead_code, unused_imports, unused_variables, clippy::all)]\nmod {name} {{\n{}\n}}\n",
                    block.body.replace("fn main", "fn _main")
                );
            } else {
                // A statement snippet: wrap it so `?` and `.await` are legal.
                let _ = writeln!(
                    generated,
                    "#[allow(dead_code, unused_imports, unused_variables, clippy::all)]\nasync fn {name}() -> Result<(), Box<dyn std::error::Error>> {{\n{}\n    Ok(())\n}}\n",
                    block.body
                );
            }
        }
    }

    let _ = writeln!(
        generated,
        "// {emitted} documented Rust example(s) compiled."
    );
    std::fs::write(out.join("doc_rust_examples.rs"), generated).expect("write generated examples");
}

struct RustBlock {
    line: usize,
    body: String,
    ignored: bool,
    defines_main: bool,
}

/// Pull the ```rust blocks out of one Markdown file.
///
/// Deliberately a small standalone parser rather than a call into the crate's
/// own `doc_examples` module: a build script cannot depend on the crate it
/// builds.
fn rust_blocks(contents: &str) -> Vec<RustBlock> {
    let mut blocks = Vec::new();
    let mut open: Option<(usize, bool)> = None;
    let mut body = String::new();

    for (index, line) in contents.lines().enumerate() {
        let trimmed = line.trim();
        if let Some((start, ignored)) = open {
            if trimmed.starts_with("```") && trimmed.trim_end_matches('`').is_empty() {
                blocks.push(RustBlock {
                    line: start,
                    defines_main: body.contains("fn main"),
                    body: std::mem::take(&mut body),
                    ignored,
                });
                open = None;
            } else {
                body.push_str(line);
                body.push('\n');
            }
            continue;
        }
        if let Some(info) = trimmed.strip_prefix("```") {
            let token = info.split_whitespace().next().unwrap_or_default();
            let mut parts = token.split(',');
            if parts.next().map(str::to_ascii_lowercase).as_deref() == Some("rust") {
                let ignored = parts.any(|a| a == "ignore" || a == "no_compile");
                open = Some((index + 1, ignored));
                body.clear();
            }
        }
    }

    blocks
}

fn collect_markdown(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.filter_map(Result::ok) {
        let path = entry.path();
        if path.is_dir() {
            collect_markdown(&path, out);
        } else if path
            .extension()
            .and_then(|extension| extension.to_str())
            .is_some_and(|extension| matches!(extension, "md" | "mdx"))
        {
            out.push(path);
        }
    }
}
