/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/**
 * Which way `guest.cp` moves the file.
 */
export type CopyDirection = ("host_to_guest" | "guest_to_host")
/**
 * Type of a filesystem entry returned by `FsList` / `FsStat`.
 */
export type FsEntryKind = ("file" | "dir" | "symlink" | "other")
/**
 * Lifecycle state of a tracked process.
 */
export type ProcState = ("running" | {
exited: number
} | {
killed: number
} | "timed_out")
export type GuestProcListReply = ProcInfo[]
/**
 * Which output stream a chunk came from.
 */
export type StreamName = ("stdout" | "stderr")
/**
 * How a waited-on process ended.
 */
export type WaitOutcome = ({
code: number
kind: "exited"
} | {
kind: "killed"
signal: number
} | {
kind: "timed_out"
})
export type MachineId = string
/**
 * Finer-grained "is this VM usable?" state, composed alongside the coarse [`InstanceStatus`] lifecycle.
 * 
 * `InstanceStatus::Running` means the backend accepted the VM and it has not stopped. `InstanceReadiness` explains *whether* it is actually usable: did the agent answer? Are integration probes green? Is a streaming operation currently throttled?
 * 
 * Readiness transitions are independent of lifecycle transitions — they do not gate or require `InstanceStatus` to move.
 */
export type InstanceReadiness = ("launch_accepted" | "agent_connecting" | "agent_ready" | {
services_starting: {
/**
 * Services whose readiness scripts are still pending.
 */
pending: string[]
}
} | "services_ready" | {
degraded: {
/**
 * Services whose health probe has flipped to unhealthy.
 */
unhealthy: string[]
}
} | {
backpressured: {
/**
 * Typed reason for the throttle.
 */
reason: BackpressureReason
}
} | "stopping")
/**
 * Why a streaming or queued operation is currently throttled.
 * 
 * Closed enum: every reason is named, and drift between host and guest fails the serde `deny_unknown_fields`-equivalent path (variants must match). Detail strings carried alongside this enum are bounded and redacted — never argv / env / stdin / stdout / stderr / filesystem paths.
 */
export type BackpressureReason = ("guest_agent_unavailable" | {
service_health_pending: {
/**
 * Names of services whose readiness scripts have not yet reported success. Echoed verbatim — never user payload.
 */
pending: string[]
}
} | "output_consumer_slow" | "input_buffer_full" | "artifact_transfer_blocked" | "builder_busy")
export type MachineStatus = (("starting" | "running" | "stopped" | "failed") | "paused")
export type MachineInventoryReply = {

}[]
export type MachineListReply = MachineState2[]
/**
 * Whether the machine outlives the caller's session.
 */
export type RunMode = ("transient" | "persistent")

export interface HostAbi {
backend_capabilities: BackendCapabilities
guest_cp: GuestCp
guest_fs_list: GuestFsList
guest_fs_mkdir: GuestFsMkdir
guest_fs_read: GuestFsRead
guest_fs_remove: GuestFsRemove
guest_fs_rename: GuestFsRename
guest_fs_stat: GuestFsStat
guest_fs_write: GuestFsWrite
guest_proc_kill: GuestProcKill
guest_proc_list: GuestProcList
guest_proc_signal: GuestProcSignal
guest_proc_start: GuestProcStart
guest_proc_stdin: GuestProcStdin
guest_proc_stream_close: GuestProcStreamClose
guest_proc_stream_next: GuestProcStreamNext
guest_proc_stream_open: GuestProcStreamOpen
guest_proc_wait: GuestProcWait
machine_create: MachineCreate
machine_exec: MachineExec
machine_inspect: MachineInspect
machine_inventory: MachineInventory
machine_list: MachineList
machine_logs: MachineLogs
machine_rm: MachineRm
machine_run: MachineRun
machine_start: MachineStart
machine_stop: MachineStop
}
export interface BackendCapabilities {
reply: BackendCapabilitiesReply
request: Empty
}
/**
 * Opaque report; the shape is owned by the capability negotiation module.
 */
export interface BackendCapabilitiesReply {

}
/**
 * A request that carries nothing.
 */
export interface Empty {

}
export interface GuestCp {
reply: Empty1
request: CopyRequest
}
export interface Empty1 {

}
/**
 * A `guest.cp` request.
 */
export interface CopyRequest {
direction: CopyDirection
guest_path: string
host_path: string
id: string
}
export interface GuestFsList {
reply: ListReply
request: PathRequest
}
export interface ListReply {
entries: FsEntry[]
truncated: boolean
}
/**
 * One entry in an `FsList` response.
 */
export interface FsEntry {
/**
 * File type. `Other` covers sockets, FIFOs, devices.
 */
kind: FsEntryKind
/**
 * Bare entry name (no leading directory component).
 */
name: string
/**
 * Size in bytes, or `0` for non-files.
 */
size: number
}
export interface PathRequest {
id: string
path: string
}
export interface GuestFsMkdir {
reply: Empty2
request: MkdirRequest
}
export interface Empty2 {

}
export interface MkdirRequest {
id: string
mode?: (number | null)
parents?: boolean
path: string
}
export interface GuestFsRead {
reply: DataReply
request: ReadRequest
}
export interface DataReply {
data_b64: string
}
export interface ReadRequest {
follow_symlinks?: boolean
id: string
length: number
offset?: number
path: string
}
export interface GuestFsRemove {
reply: RemovedReply
request: RemoveRequest
}
export interface RemovedReply {
entries_removed: number
}
export interface RemoveRequest {
id: string
path: string
recursive?: boolean
}
export interface GuestFsRename {
reply: Empty3
request: RenameRequest
}
export interface Empty3 {

}
export interface RenameRequest {
from: string
id: string
to: string
}
export interface GuestFsStat {
reply: FsStat
request: StatRequest
}
/**
 * Stat metadata for a single filesystem entry.
 */
export interface FsStat {
/**
 * Canonical (post-`realpath`) path the agent operated on. Lets the host detect when a symlink resolution surprised it.
 */
canonical_path: string
kind: FsEntryKind
/**
 * Unix mode bits (e.g. `0o100644`). Always present; on backends without a unix mode the agent reports a best-effort equivalent.
 */
mode: number
/**
 * Modification timestamp as RFC 3339, or `None` if the underlying fs doesn't expose mtime.
 */
mtime?: (string | null)
size: number
}
export interface StatRequest {
follow_symlinks?: boolean
id: string
path: string
}
export interface GuestFsWrite {
reply: WrittenReply
request: WriteRequest
}
export interface WrittenReply {
bytes_written: number
}
export interface WriteRequest {
create_parents?: boolean
data_b64: string
follow_symlinks?: boolean
id: string
mode?: (number | null)
path: string
}
export interface GuestProcKill {
reply: Empty4
request: ProcessRequest
}
export interface Empty4 {

}
export interface ProcessRequest {
id: string
token: string
}
export interface GuestProcList {
reply: GuestProcListReply
request: MachineRequest
}
/**
 * Per-process metadata returned by `ProcList`.
 */
export interface ProcInfo {
/**
 * argv\[0\] for display only — the agent does not expose the full argv over the wire (it could echo secrets the caller passed in via env / stdin).
 */
argv0: string
pid_token: string
/**
 * RFC 3339 timestamp.
 */
started_at: string
state: ProcState
}
export interface MachineRequest {
id: string
}
export interface GuestProcSignal {
reply: Empty5
request: SignalRequest
}
export interface Empty5 {

}
export interface SignalRequest {
id: string
signum: number
token: string
}
export interface GuestProcStart {
reply: StartedReply
request: StartRequest
}
export interface StartedReply {
token: string
}
export interface StartRequest {
argv: string[]
cwd?: (string | null)
env?: {
[k: string]: string
}
id: string
}
export interface GuestProcStdin {
reply: AcceptedReply
request: StdinRequest
}
export interface AcceptedReply {
accepted: number
}
export interface StdinRequest {
data_b64: string
id: string
token: string
}
export interface GuestProcStreamClose {
reply: Empty6
request: CloseRequest
}
export interface Empty6 {

}
export interface CloseRequest {
stream: number
}
export interface GuestProcStreamNext {
reply: NextReply
request: NextRequest
}
export interface NextReply {
/**
 * The process has ended and the stream is closed.
 */
done: boolean
events: StreamEvent[]
/**
 * How it ended; present exactly when `done`.
 */
outcome?: (WaitOutcome | null)
}
/**
 * One chunk of output.
 */
export interface StreamEvent {
data_b64: string
stream: StreamName
}
export interface NextRequest {
stream: number
/**
 * How long to wait for a first chunk. At most [`MAX_WAIT_MS`].
 */
wait_ms?: (number | null)
}
export interface GuestProcStreamOpen {
reply: OpenReply
request: OpenRequest
}
export interface OpenReply {
stream: number
}
export interface OpenRequest {
id: string
/**
 * Bounds the wait on the guest; the stream ends `timed_out` past it.
 */
timeout_secs?: (number | null)
token: string
}
export interface GuestProcWait {
reply: WaitReply
request: WaitRequest
}
export interface WaitReply {
outcome: WaitOutcome
stderr_b64: string
stdout_b64: string
/**
 * Output past [`WAIT_OUTPUT_CAP`] on either stream was dropped.
 */
truncated: boolean
}
export interface WaitRequest {
id: string
timeout_secs?: (number | null)
token: string
}
export interface MachineCreate {
reply: MachineState
request: CreateRequest
}
/**
 * A machine's observed runtime state — the shared listing/inspect record. Every field is REST-satisfiable plain data (no host handles, no paths, no keys), so the same struct crosses the gateway wire. New fields carry `#[serde(default)]` so an older serialized record still deserializes.
 */
export interface MachineState {
/**
 * Whether connecting auto-resumes a sleeping machine.
 */
auto_resume?: boolean
/**
 * Backend that owns this machine (e.g. `"firecracker"`, `"hvf"`, `"libkrun"`). Empty when unknown.
 */
backend?: string
/**
 * vCPU count. `0` when unknown (e.g. a registered-but-stopped machine).
 */
cpus?: number
/**
 * RFC 3339 TTL expiry, when set. Whether it has elapsed is a caller (presentation) decision, not modeled here.
 */
expires_at?: (string | null)
/**
 * Original flake reference, when known.
 */
flake_ref?: (string | null)
/**
 * Guest IP, when networking is configured.
 */
guest_ip?: (string | null)
id: MachineId
/**
 * RFC 3339 timestamp of the last `readiness` change.
 */
last_readiness_change_at?: (string | null)
/**
 * Guest memory in MiB. `0` when unknown.
 */
memory_mib?: number
name: string
/**
 * Active host:guest port forwardings.
 */
ports?: PortMapping[]
/**
 * Flake profile name, when built from a profile.
 */
profile?: (string | null)
/**
 * Finer-grained host-observed readiness, when tracked.
 */
readiness?: (InstanceReadiness | null)
/**
 * Nix store revision hash, when known.
 */
revision?: (string | null)
status: MachineStatus
/**
 * Free-text detail for a non-happy `status` — e.g. the reason behind [`MachineStatus::Failed`]. `None` when the status needs no elaboration. Kept off `MachineStatus` so that enum stays `Copy` and cheap to compare.
 */
status_detail?: (string | null)
/**
 * Caller-supplied metadata tags.
 */
tags?: {
[k: string]: string
}
}
/**
 * A host:guest port forwarding on a machine — plain listing data that mirrors a backend's port mapping so a machine record can carry its forwards without exposing a runtime type.
 */
export interface PortMapping {
guest: number
host: number
}
/**
 * A `machine.create` request: a persistent definition, never booted here.
 */
export interface CreateRequest {
backend?: (string | null)
command?: string[]
cpus?: (number | null)
egress?: EgressTarget[]
env?: {
[k: string]: string
}
force?: boolean
image: string
memory_mib?: (number | null)
name: string
ports?: string[]
profile?: (string | null)
}
/**
 * One outbound destination the workload may reach. Each one lands in the signed plan's egress grant, which is what the host egress gate reads.
 */
export interface EgressTarget {
host: string
port: number
}
export interface MachineExec {
reply: ExecReply
request: ExecRequest
}
/**
 * A `machine.exec` reply. Stream bytes cross as base64, because JSON strings are not byte strings — the same convention as `machine.logs` and every `guest.*` payload.
 */
export interface ExecReply {
exit_code: number
stderr_b64: string
stdout_b64: string
}
/**
 * A `machine.exec` request.
 */
export interface ExecRequest {
command: string[]
id: string
}
export interface MachineInspect {
reply: MachineState1
request: MachineRef
}
/**
 * A machine's observed runtime state — the shared listing/inspect record. Every field is REST-satisfiable plain data (no host handles, no paths, no keys), so the same struct crosses the gateway wire. New fields carry `#[serde(default)]` so an older serialized record still deserializes.
 */
export interface MachineState1 {
/**
 * Whether connecting auto-resumes a sleeping machine.
 */
auto_resume?: boolean
/**
 * Backend that owns this machine (e.g. `"firecracker"`, `"hvf"`, `"libkrun"`). Empty when unknown.
 */
backend?: string
/**
 * vCPU count. `0` when unknown (e.g. a registered-but-stopped machine).
 */
cpus?: number
/**
 * RFC 3339 TTL expiry, when set. Whether it has elapsed is a caller (presentation) decision, not modeled here.
 */
expires_at?: (string | null)
/**
 * Original flake reference, when known.
 */
flake_ref?: (string | null)
/**
 * Guest IP, when networking is configured.
 */
guest_ip?: (string | null)
id: MachineId
/**
 * RFC 3339 timestamp of the last `readiness` change.
 */
last_readiness_change_at?: (string | null)
/**
 * Guest memory in MiB. `0` when unknown.
 */
memory_mib?: number
name: string
/**
 * Active host:guest port forwardings.
 */
ports?: PortMapping[]
/**
 * Flake profile name, when built from a profile.
 */
profile?: (string | null)
/**
 * Finer-grained host-observed readiness, when tracked.
 */
readiness?: (InstanceReadiness | null)
/**
 * Nix store revision hash, when known.
 */
revision?: (string | null)
status: MachineStatus
/**
 * Free-text detail for a non-happy `status` — e.g. the reason behind [`MachineStatus::Failed`]. `None` when the status needs no elaboration. Kept off `MachineStatus` so that enum stays `Copy` and cheap to compare.
 */
status_detail?: (string | null)
/**
 * Caller-supplied metadata tags.
 */
tags?: {
[k: string]: string
}
}
/**
 * A request naming one machine.
 */
export interface MachineRef {
id: string
}
export interface MachineInventory {
reply: MachineInventoryReply
request: Empty7
}
/**
 * A request that carries nothing.
 */
export interface Empty7 {

}
export interface MachineList {
reply: MachineListReply
request: MachineFilter
}
/**
 * A machine's observed runtime state — the shared listing/inspect record. Every field is REST-satisfiable plain data (no host handles, no paths, no keys), so the same struct crosses the gateway wire. New fields carry `#[serde(default)]` so an older serialized record still deserializes.
 */
export interface MachineState2 {
/**
 * Whether connecting auto-resumes a sleeping machine.
 */
auto_resume?: boolean
/**
 * Backend that owns this machine (e.g. `"firecracker"`, `"hvf"`, `"libkrun"`). Empty when unknown.
 */
backend?: string
/**
 * vCPU count. `0` when unknown (e.g. a registered-but-stopped machine).
 */
cpus?: number
/**
 * RFC 3339 TTL expiry, when set. Whether it has elapsed is a caller (presentation) decision, not modeled here.
 */
expires_at?: (string | null)
/**
 * Original flake reference, when known.
 */
flake_ref?: (string | null)
/**
 * Guest IP, when networking is configured.
 */
guest_ip?: (string | null)
id: MachineId
/**
 * RFC 3339 timestamp of the last `readiness` change.
 */
last_readiness_change_at?: (string | null)
/**
 * Guest memory in MiB. `0` when unknown.
 */
memory_mib?: number
name: string
/**
 * Active host:guest port forwardings.
 */
ports?: PortMapping[]
/**
 * Flake profile name, when built from a profile.
 */
profile?: (string | null)
/**
 * Finer-grained host-observed readiness, when tracked.
 */
readiness?: (InstanceReadiness | null)
/**
 * Nix store revision hash, when known.
 */
revision?: (string | null)
status: MachineStatus
/**
 * Free-text detail for a non-happy `status` — e.g. the reason behind [`MachineStatus::Failed`]. `None` when the status needs no elaboration. Kept off `MachineStatus` so that enum stays `Copy` and cheap to compare.
 */
status_detail?: (string | null)
/**
 * Caller-supplied metadata tags.
 */
tags?: {
[k: string]: string
}
}
export interface MachineFilter {
name?: (string | null)
status?: (MachineStatus | null)
}
export interface MachineLogs {
reply: LogsReply
request: LogsRequest
}
/**
 * Console bytes, which need not be UTF-8.
 */
export interface LogsReply {
data_b64: string
}
/**
 * A `machine.logs` request. There is no `follow`: following a log is a stream, and a single call returns once.
 */
export interface LogsRequest {
id: string
tail_lines?: (number | null)
}
export interface MachineRm {
reply: Empty8
request: RemoveRequest1
}
export interface Empty8 {

}
/**
 * A request naming one machine for removal.
 */
export interface RemoveRequest1 {
id: string
}
export interface MachineRun {
reply: RunReply
request: RunRequest
}
/**
 * A `machine.run` reply.
 */
export interface RunReply {
/**
 * `dev` or `prod`, resolved fail-closed the way the machine inventory resolves it. Only `dev` admits the DevOnly `guest.*` methods.
 */
build_mode: string
machine: MachineState3
/**
 * Content-addressed id of the admitted plan, for correlating with the chain-signed audit log.
 */
plan_id: string
}
/**
 * A machine's observed runtime state — the shared listing/inspect record. Every field is REST-satisfiable plain data (no host handles, no paths, no keys), so the same struct crosses the gateway wire. New fields carry `#[serde(default)]` so an older serialized record still deserializes.
 */
export interface MachineState3 {
/**
 * Whether connecting auto-resumes a sleeping machine.
 */
auto_resume?: boolean
/**
 * Backend that owns this machine (e.g. `"firecracker"`, `"hvf"`, `"libkrun"`). Empty when unknown.
 */
backend?: string
/**
 * vCPU count. `0` when unknown (e.g. a registered-but-stopped machine).
 */
cpus?: number
/**
 * RFC 3339 TTL expiry, when set. Whether it has elapsed is a caller (presentation) decision, not modeled here.
 */
expires_at?: (string | null)
/**
 * Original flake reference, when known.
 */
flake_ref?: (string | null)
/**
 * Guest IP, when networking is configured.
 */
guest_ip?: (string | null)
id: MachineId
/**
 * RFC 3339 timestamp of the last `readiness` change.
 */
last_readiness_change_at?: (string | null)
/**
 * Guest memory in MiB. `0` when unknown.
 */
memory_mib?: number
name: string
/**
 * Active host:guest port forwardings.
 */
ports?: PortMapping[]
/**
 * Flake profile name, when built from a profile.
 */
profile?: (string | null)
/**
 * Finer-grained host-observed readiness, when tracked.
 */
readiness?: (InstanceReadiness | null)
/**
 * Nix store revision hash, when known.
 */
revision?: (string | null)
status: MachineStatus
/**
 * Free-text detail for a non-happy `status` — e.g. the reason behind [`MachineStatus::Failed`]. `None` when the status needs no elaboration. Kept off `MachineStatus` so that enum stays `Copy` and cheap to compare.
 */
status_detail?: (string | null)
/**
 * Caller-supplied metadata tags.
 */
tags?: {
[k: string]: string
}
}
/**
 * A `machine.run` request.
 */
export interface RunRequest {
/**
 * Hypervisor override; the host's default when absent.
 */
backend?: (string | null)
/**
 * Command override. The in-process launcher refuses a non-empty one.
 */
command?: string[]
cpus?: (number | null)
egress?: EgressTarget[]
/**
 * Guest environment. The in-process launcher refuses a non-empty one.
 */
env?: {
[k: string]: string
}
/**
 * Persistent only: recreate a same-name definition whose config differs.
 */
force?: boolean
/**
 * What to boot: an OCI reference (optionally `oci:`-prefixed), an absolute or `./`-relative rootfs path, or `flake:<ref>#<attr>`.
 */
image: string
memory_mib?: (number | null)
mode?: RunMode
/**
 * Required for a persistent machine; generated for a transient one.
 */
name?: (string | null)
/**
 * Opaque TCP ingress, each written `host:guest`.
 */
ports?: string[]
/**
 * Security profile; `standard` when absent.
 */
profile?: (string | null)
ttl_seconds?: (number | null)
}
export interface MachineStart {
reply: MachineState4
request: MachineRef1
}
/**
 * A machine's observed runtime state — the shared listing/inspect record. Every field is REST-satisfiable plain data (no host handles, no paths, no keys), so the same struct crosses the gateway wire. New fields carry `#[serde(default)]` so an older serialized record still deserializes.
 */
export interface MachineState4 {
/**
 * Whether connecting auto-resumes a sleeping machine.
 */
auto_resume?: boolean
/**
 * Backend that owns this machine (e.g. `"firecracker"`, `"hvf"`, `"libkrun"`). Empty when unknown.
 */
backend?: string
/**
 * vCPU count. `0` when unknown (e.g. a registered-but-stopped machine).
 */
cpus?: number
/**
 * RFC 3339 TTL expiry, when set. Whether it has elapsed is a caller (presentation) decision, not modeled here.
 */
expires_at?: (string | null)
/**
 * Original flake reference, when known.
 */
flake_ref?: (string | null)
/**
 * Guest IP, when networking is configured.
 */
guest_ip?: (string | null)
id: MachineId
/**
 * RFC 3339 timestamp of the last `readiness` change.
 */
last_readiness_change_at?: (string | null)
/**
 * Guest memory in MiB. `0` when unknown.
 */
memory_mib?: number
name: string
/**
 * Active host:guest port forwardings.
 */
ports?: PortMapping[]
/**
 * Flake profile name, when built from a profile.
 */
profile?: (string | null)
/**
 * Finer-grained host-observed readiness, when tracked.
 */
readiness?: (InstanceReadiness | null)
/**
 * Nix store revision hash, when known.
 */
revision?: (string | null)
status: MachineStatus
/**
 * Free-text detail for a non-happy `status` — e.g. the reason behind [`MachineStatus::Failed`]. `None` when the status needs no elaboration. Kept off `MachineStatus` so that enum stays `Copy` and cheap to compare.
 */
status_detail?: (string | null)
/**
 * Caller-supplied metadata tags.
 */
tags?: {
[k: string]: string
}
}
/**
 * A request naming one machine.
 */
export interface MachineRef1 {
id: string
}
export interface MachineStop {
reply: Empty9
request: StopRequest
}
export interface Empty9 {

}
/**
 * A request naming one machine.
 */
export interface StopRequest {
id: string
}
