/* eslint-disable */
/**
 * Generated by `cargo xtask gen-stubs` from crates/mvm-hostlib/src/registry.rs.
 * DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
 *
 * The host-ABI method table: dotted names, schema keys, classifications.
 * Owned by the Rust registry; the C ABI answers exactly these methods.
 */
export const ABI_MAJOR = 1;
export const ABI_MINOR = 5;

export type Classification = "prod_safe" | "dev_only";

/** One dotted host-ABI method and its generated schema key. */
export interface HostAbiMethod {
  key: string;
  classification: Classification;
  summary: string;
}

/** Reports what the backend can do. */
export const BACKEND_CAPABILITIES = "backend.capabilities";

/**
 * Calls a workload's entrypoint in a transient microVM, admitted
 * under a signed plan.
 */
export const ENTRYPOINT_CALL = "entrypoint.call";

/** Persists a machine definition without booting it. */
export const MACHINE_CREATE = "machine.create";

/** Runs one non-interactive command in a machine. */
export const MACHINE_EXEC = "machine.exec";

/** Inspects one machine. */
export const MACHINE_INSPECT = "machine.inspect";

/** Lists every machine on this host with its dev/prod posture. */
export const MACHINE_INVENTORY = "machine.inventory";

/** Lists machines, optionally filtered. */
export const MACHINE_LIST = "machine.list";

/** Returns captured console output, base64-encoded. */
export const MACHINE_LOGS = "machine.logs";

/** Removes a machine, stopping it first when needed. */
export const MACHINE_RM = "machine.rm";

/** Closes a captured-output stream. Idempotent. */
export const MACHINE_LOGS_STREAM_CLOSE = "machine.logs.stream.close";

/** Returns the captured output that has arrived. */
export const MACHINE_LOGS_STREAM_NEXT = "machine.logs.stream.next";

/**
 * Opens a stream over a machine's captured output, replayed then
 * followed.
 */
export const MACHINE_LOGS_STREAM_OPEN = "machine.logs.stream.open";

/**
 * Pauses a running machine, sealing a snapshot where the backend
 * uses one.
 */
export const MACHINE_PAUSE = "machine.pause";

/**
 * Sends one prompt to a running machine's resident agent, granted by
 * its plan, journaled, recorded encrypted and chain-audited.
 */
export const MACHINE_PROMPT = "machine.prompt";

/** Patches a machine's resources and relaunches it when running. */
export const MACHINE_RECONFIGURE = "machine.reconfigure";

/** Resumes a paused machine, refusing a replayed snapshot. */
export const MACHINE_RESUME = "machine.resume";

/** Boots a machine through the admitted local launch. */
export const MACHINE_RUN = "machine.run";

/** Sets or clears the time the idle reaper removes a machine at. */
export const MACHINE_SET_TTL = "machine.set_ttl";

/** Boots a persisted machine definition. */
export const MACHINE_START = "machine.start";

/** Stops a machine. Idempotent. */
export const MACHINE_STOP = "machine.stop";

/** Calls the entrypoint in a running session's microVM. */
export const SESSION_CALL = "session.call";

/** Reports a session's record. */
export const SESSION_INFO = "session.info";

/** Boots a warm session for a workload, admitted under a signed plan. */
export const SESSION_START = "session.start";

/** Stops a session and tears down its microVM. */
export const SESSION_STOP = "session.stop";

/** Copies a file between the host and the guest. */
export const GUEST_CP = "guest.cp";

/** Lists a directory in the guest. */
export const GUEST_FS_LIST = "guest.fs.list";

/** Creates a directory in the guest. */
export const GUEST_FS_MKDIR = "guest.fs.mkdir";

/** Reads a file from the guest, base64-encoded. */
export const GUEST_FS_READ = "guest.fs.read";

/** Removes a path in the guest. */
export const GUEST_FS_REMOVE = "guest.fs.remove";

/** Moves a path in the guest. */
export const GUEST_FS_RENAME = "guest.fs.rename";

/** Stats a path in the guest. */
export const GUEST_FS_STAT = "guest.fs.stat";

/** Writes a file in the guest, base64-encoded. */
export const GUEST_FS_WRITE = "guest.fs.write";

/** Kills a tracked guest process. */
export const GUEST_PROC_KILL = "guest.proc.kill";

/** Lists tracked guest processes. */
export const GUEST_PROC_LIST = "guest.proc.list";

/** Signals a tracked guest process. */
export const GUEST_PROC_SIGNAL = "guest.proc.signal";

/** Starts a process in the guest. */
export const GUEST_PROC_START = "guest.proc.start";

/** Writes a tracked process's stdin, base64-encoded. */
export const GUEST_PROC_STDIN = "guest.proc.stdin";

/** Closes a process output stream. Idempotent. */
export const GUEST_PROC_STREAM_CLOSE = "guest.proc.stream.close";

/** Returns the process output that has arrived, and how it ended. */
export const GUEST_PROC_STREAM_NEXT = "guest.proc.stream.next";

/** Opens a stream over a guest process's output. */
export const GUEST_PROC_STREAM_OPEN = "guest.proc.stream.open";

/** Waits for a guest process to end, returning its output. */
export const GUEST_PROC_WAIT = "guest.proc.wait";

export const METHODS: Readonly<Record<string, HostAbiMethod>> = {
  "backend.capabilities": { key: "backend_capabilities", classification: "prod_safe", summary: "Reports what the backend can do." },
  "entrypoint.call": { key: "entrypoint_call", classification: "prod_safe", summary: "Calls a workload's entrypoint in a transient microVM, admitted under a signed plan." },
  "machine.create": { key: "machine_create", classification: "prod_safe", summary: "Persists a machine definition without booting it." },
  "machine.exec": { key: "machine_exec", classification: "prod_safe", summary: "Runs one non-interactive command in a machine." },
  "machine.inspect": { key: "machine_inspect", classification: "prod_safe", summary: "Inspects one machine." },
  "machine.inventory": { key: "machine_inventory", classification: "prod_safe", summary: "Lists every machine on this host with its dev/prod posture." },
  "machine.list": { key: "machine_list", classification: "prod_safe", summary: "Lists machines, optionally filtered." },
  "machine.logs": { key: "machine_logs", classification: "prod_safe", summary: "Returns captured console output, base64-encoded." },
  "machine.rm": { key: "machine_rm", classification: "prod_safe", summary: "Removes a machine, stopping it first when needed." },
  "machine.logs.stream.close": { key: "machine_logs_stream_close", classification: "prod_safe", summary: "Closes a captured-output stream. Idempotent." },
  "machine.logs.stream.next": { key: "machine_logs_stream_next", classification: "prod_safe", summary: "Returns the captured output that has arrived." },
  "machine.logs.stream.open": { key: "machine_logs_stream_open", classification: "prod_safe", summary: "Opens a stream over a machine's captured output, replayed then followed." },
  "machine.pause": { key: "machine_pause", classification: "prod_safe", summary: "Pauses a running machine, sealing a snapshot where the backend uses one." },
  "machine.prompt": { key: "machine_prompt", classification: "prod_safe", summary: "Sends one prompt to a running machine's resident agent, granted by its plan, journaled, recorded encrypted and chain-audited." },
  "machine.reconfigure": { key: "machine_reconfigure", classification: "prod_safe", summary: "Patches a machine's resources and relaunches it when running." },
  "machine.resume": { key: "machine_resume", classification: "prod_safe", summary: "Resumes a paused machine, refusing a replayed snapshot." },
  "machine.run": { key: "machine_run", classification: "prod_safe", summary: "Boots a machine through the admitted local launch." },
  "machine.set_ttl": { key: "machine_set_ttl", classification: "prod_safe", summary: "Sets or clears the time the idle reaper removes a machine at." },
  "machine.start": { key: "machine_start", classification: "prod_safe", summary: "Boots a persisted machine definition." },
  "machine.stop": { key: "machine_stop", classification: "prod_safe", summary: "Stops a machine. Idempotent." },
  "session.call": { key: "session_call", classification: "prod_safe", summary: "Calls the entrypoint in a running session's microVM." },
  "session.info": { key: "session_info", classification: "prod_safe", summary: "Reports a session's record." },
  "session.start": { key: "session_start", classification: "prod_safe", summary: "Boots a warm session for a workload, admitted under a signed plan." },
  "session.stop": { key: "session_stop", classification: "prod_safe", summary: "Stops a session and tears down its microVM." },
  "guest.cp": { key: "guest_cp", classification: "dev_only", summary: "Copies a file between the host and the guest." },
  "guest.fs.list": { key: "guest_fs_list", classification: "dev_only", summary: "Lists a directory in the guest." },
  "guest.fs.mkdir": { key: "guest_fs_mkdir", classification: "dev_only", summary: "Creates a directory in the guest." },
  "guest.fs.read": { key: "guest_fs_read", classification: "dev_only", summary: "Reads a file from the guest, base64-encoded." },
  "guest.fs.remove": { key: "guest_fs_remove", classification: "dev_only", summary: "Removes a path in the guest." },
  "guest.fs.rename": { key: "guest_fs_rename", classification: "dev_only", summary: "Moves a path in the guest." },
  "guest.fs.stat": { key: "guest_fs_stat", classification: "dev_only", summary: "Stats a path in the guest." },
  "guest.fs.write": { key: "guest_fs_write", classification: "dev_only", summary: "Writes a file in the guest, base64-encoded." },
  "guest.proc.kill": { key: "guest_proc_kill", classification: "dev_only", summary: "Kills a tracked guest process." },
  "guest.proc.list": { key: "guest_proc_list", classification: "dev_only", summary: "Lists tracked guest processes." },
  "guest.proc.signal": { key: "guest_proc_signal", classification: "dev_only", summary: "Signals a tracked guest process." },
  "guest.proc.start": { key: "guest_proc_start", classification: "dev_only", summary: "Starts a process in the guest." },
  "guest.proc.stdin": { key: "guest_proc_stdin", classification: "dev_only", summary: "Writes a tracked process's stdin, base64-encoded." },
  "guest.proc.stream.close": { key: "guest_proc_stream_close", classification: "dev_only", summary: "Closes a process output stream. Idempotent." },
  "guest.proc.stream.next": { key: "guest_proc_stream_next", classification: "dev_only", summary: "Returns the process output that has arrived, and how it ended." },
  "guest.proc.stream.open": { key: "guest_proc_stream_open", classification: "dev_only", summary: "Opens a stream over a guest process's output." },
  "guest.proc.wait": { key: "guest_proc_wait", classification: "dev_only", summary: "Waits for a guest process to end, returning its output." },
};
