/* eslint-disable */
/**
 * Generated by `cargo xtask gen-stubs` from crates/mvm-hostlib/src/registry.rs.
 * DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
 *
 * The host-ABI method table: dotted names, schema keys, classifications.
 * Owned by the Rust registry; the C ABI answers exactly these methods.
 */
export const ABI_MAJOR = 1;
export const ABI_MINOR = 1;

export type Classification = "prod_safe" | "dev_only";

/** One dotted host-ABI method and its generated schema key. */
export interface HostAbiMethod {
  key: string;
  classification: Classification;
  summary: string;
}

/** Reports what the backend can do. */
export const BACKEND_CAPABILITIES = "backend.capabilities";

/** Runs one non-interactive command in a machine. */
export const MACHINE_EXEC = "machine.exec";

/** Inspects one machine. */
export const MACHINE_INSPECT = "machine.inspect";

/** Lists machines, optionally filtered. */
export const MACHINE_LIST = "machine.list";

/** Returns captured console output, base64-encoded. */
export const MACHINE_LOGS = "machine.logs";

/** Removes a machine, stopping it first when needed. */
export const MACHINE_RM = "machine.rm";

/** Stops a machine. Idempotent. */
export const MACHINE_STOP = "machine.stop";

/** Copies a file between the host and the guest. */
export const GUEST_CP = "guest.cp";

/** Lists a directory in the guest. */
export const GUEST_FS_LIST = "guest.fs.list";

/** Creates a directory in the guest. */
export const GUEST_FS_MKDIR = "guest.fs.mkdir";

/** Reads a file from the guest, base64-encoded. */
export const GUEST_FS_READ = "guest.fs.read";

/** Removes a path in the guest. */
export const GUEST_FS_REMOVE = "guest.fs.remove";

/** Moves a path in the guest. */
export const GUEST_FS_RENAME = "guest.fs.rename";

/** Stats a path in the guest. */
export const GUEST_FS_STAT = "guest.fs.stat";

/** Writes a file in the guest, base64-encoded. */
export const GUEST_FS_WRITE = "guest.fs.write";

/** Kills a tracked guest process. */
export const GUEST_PROC_KILL = "guest.proc.kill";

/** Lists tracked guest processes. */
export const GUEST_PROC_LIST = "guest.proc.list";

/** Signals a tracked guest process. */
export const GUEST_PROC_SIGNAL = "guest.proc.signal";

/** Starts a process in the guest. */
export const GUEST_PROC_START = "guest.proc.start";

/** Writes a tracked process's stdin, base64-encoded. */
export const GUEST_PROC_STDIN = "guest.proc.stdin";

/** Waits for a guest process to end, returning its output. */
export const GUEST_PROC_WAIT = "guest.proc.wait";

export const METHODS: Readonly<Record<string, HostAbiMethod>> = {
  "backend.capabilities": { key: "backend_capabilities", classification: "prod_safe", summary: "Reports what the backend can do." },
  "machine.exec": { key: "machine_exec", classification: "prod_safe", summary: "Runs one non-interactive command in a machine." },
  "machine.inspect": { key: "machine_inspect", classification: "prod_safe", summary: "Inspects one machine." },
  "machine.list": { key: "machine_list", classification: "prod_safe", summary: "Lists machines, optionally filtered." },
  "machine.logs": { key: "machine_logs", classification: "prod_safe", summary: "Returns captured console output, base64-encoded." },
  "machine.rm": { key: "machine_rm", classification: "prod_safe", summary: "Removes a machine, stopping it first when needed." },
  "machine.stop": { key: "machine_stop", classification: "prod_safe", summary: "Stops a machine. Idempotent." },
  "guest.cp": { key: "guest_cp", classification: "dev_only", summary: "Copies a file between the host and the guest." },
  "guest.fs.list": { key: "guest_fs_list", classification: "dev_only", summary: "Lists a directory in the guest." },
  "guest.fs.mkdir": { key: "guest_fs_mkdir", classification: "dev_only", summary: "Creates a directory in the guest." },
  "guest.fs.read": { key: "guest_fs_read", classification: "dev_only", summary: "Reads a file from the guest, base64-encoded." },
  "guest.fs.remove": { key: "guest_fs_remove", classification: "dev_only", summary: "Removes a path in the guest." },
  "guest.fs.rename": { key: "guest_fs_rename", classification: "dev_only", summary: "Moves a path in the guest." },
  "guest.fs.stat": { key: "guest_fs_stat", classification: "dev_only", summary: "Stats a path in the guest." },
  "guest.fs.write": { key: "guest_fs_write", classification: "dev_only", summary: "Writes a file in the guest, base64-encoded." },
  "guest.proc.kill": { key: "guest_proc_kill", classification: "dev_only", summary: "Kills a tracked guest process." },
  "guest.proc.list": { key: "guest_proc_list", classification: "dev_only", summary: "Lists tracked guest processes." },
  "guest.proc.signal": { key: "guest_proc_signal", classification: "dev_only", summary: "Signals a tracked guest process." },
  "guest.proc.start": { key: "guest_proc_start", classification: "dev_only", summary: "Starts a process in the guest." },
  "guest.proc.stdin": { key: "guest_proc_stdin", classification: "dev_only", summary: "Writes a tracked process's stdin, base64-encoded." },
  "guest.proc.wait": { key: "guest_proc_wait", classification: "dev_only", summary: "Waits for a guest process to end, returning its output." },
};
