//! Renderer for the generated `flake.nix`.
//!
//! The flake declares an `mvm` guest-lib input (pinned, override-able), follows
//! mvm's `nixpkgs`, and exposes `packages.<system>.default = mvm.lib.<system>.mkGuest { ... }`
//! for both `x86_64-linux` and `aarch64-linux`. `mvm.workload` and
//! `mvm.metadata` remain at their stable attribute paths.
//!
//! For `entrypoint.kind == "function"` workloads the flake dispatches through
//! `mvm.lib.<system>.mk<Lang>FunctionService`.
//! The factory returns
//! `{ extraFiles, servicePackages, service }`, which we merge into
//! `mkGuest`. mvm does not ship local copies of the factories;
//! the substrate (mvm) is the sole source of truth.
//!
//! Determinism: the output depends only on workload ID, IR hash, the resolved
//! `mvm` flake URL, the IR schema version, and toolchain version. No HashMap,
//! no time, no environment beyond the explicit `MVM_FLAKE_URL` lookup.

use crate::compile::launch::{ARTIFACT_FORMAT_VERSION, TOOLCHAIN_VERSION};
use crate::compile::mvm_pin::resolved_mvm_flake_url;
use crate::ir::{Workload, ir_hash};

pub fn build_flake_nix(workload: &Workload) -> Result<String, serde_json::Error> {
    let hash = ir_hash(workload)?;
    Ok(format!(
        r##"# Generated by mvm {toolchain}. Do not edit by hand — re-run `mvmctl compile`.
# IR-derived workload data lives in ./launch.json.
# User source tree is bundled in ./src and built into a Nix derivation per ADR-0008.
# Function-call workloads dispatch through mvm.lib.<system>.mk<Lang>FunctionService (ADR-0010 §3).
{{
  description = "{id} — generated by mvm {toolchain}";
  inputs.mvm.url = "{mvm_url}";
  inputs.nixpkgs.follows = "mvm/nixpkgs";
  outputs = {{ self, mvm, nixpkgs, ... }}:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      eachSystem = f: builtins.listToAttrs
        (map (s: {{ name = s; value = f s; }}) systems);
      launch = builtins.fromJSON (builtins.readFile ./launch.json);
      shellQuote = arg:
        "'" + builtins.replaceStrings [ "'" ] [ "'\\''" ] arg + "'";
      # When the bundled Node source ships an npm lockfile, build
      # node_modules reproducibly at BUILD time (in the builder VM) via
      # nixpkgs' importNpmLock — hash-free, reads package-lock.json directly
      # using its integrity hashes. node_modules is baked into the app
      # derivation, which is symlinked at the working dir, so the runtime
      # resolves `<working_dir>/node_modules` natively: no boot-time install,
      # no runtime network, no separate volume mount. A bare package.json
      # with no lockfile falls through to the plain copy (nothing to pin).
      nodeHasLock =
        (launch.entrypoint.language or "") == "node"
        && builtins.pathExists ./src/package.json
        && builtins.pathExists ./src/package-lock.json;
      mkAppPkg = pkgs:
        if nodeHasLock
        then pkgs.buildNpmPackage {{
          pname = "${{launch.workload_id}}-app";
          version = "0";
          src = ./src;
          nodejs = pkgs.nodejs_22;
          npmDeps = pkgs.importNpmLock {{ npmRoot = ./src; }};
          npmConfigHook = pkgs.importNpmLock.npmConfigHook;
          # No transpile step — Node strips TS types at import (>=22.18). The
          # default install assumes a `bin`/`files` package; we instead keep
          # the whole tree + the npm-populated node_modules.
          dontNpmBuild = true;
          installPhase = ''
            runHook preInstall
            mkdir -p $out
            cp -R . $out/
            runHook postInstall
          '';
        }}
        else pkgs.stdenv.mkDerivation {{
          pname = "${{launch.workload_id}}-app";
          version = "0";
          src = ./src;
          installPhase = ''
            mkdir -p $out
            cp -R . $out/
          '';
        }};
      buildEntrypoint = pkgs:
        pkgs.writeShellScript "${{launch.workload_id}}-entrypoint" ''
          set -eu
          cd ${{launch.entrypoint.working_dir}}
          exec ${{builtins.concatStringsSep " "
            (map shellQuote launch.entrypoint.command)}}
        '';
      buildPreStart = pkgs: appPkg:
        pkgs.writeShellScript "${{launch.workload_id}}-prestart" ''
          set -eu
          mkdir -p "$(dirname ${{launch.entrypoint.working_dir}})"
          ln -sfn ${{appPkg}} ${{launch.entrypoint.working_dir}}
        '';
      isFunction = launch.entrypoint.kind == "function";
      # Per ADR-0010 §3 (Option A, amended 2026-05-06): factories live
      # in mvm; mvm dispatches through `mvm.lib.${{system}}.mk<Lang>
      # FunctionService` and never bundles a local fallback. If an mvm
      # revision is pinned that doesn't expose the symbol, the rendered
      # flake fails at evaluation with a helpful error pointing at the
      # missing symbol — fix the pin upstream rather than papering over
      # it on the mvm side.
      # The substrate exposes a single generic `mkFunctionService` that
      # dispatches on `language` via its registry (nix/lib/factories/
      # languages/) — not the per-language `mk<Lang>FunctionService` names
      # ADR-0010 originally sketched. Pass `language` straight through;
      # `mkFunctionService` validates it against the registry and throws
      # for unknown languages.
      buildFactoryService = system: pkgs: appPkg:
        if !isFunction then null
        else
          let
            mvmLib = mvm.lib.${{system}};
          in
          if mvmLib ? mkFunctionService
          then mvmLib.mkFunctionService {{
            inherit pkgs appPkg;
            language = launch.entrypoint.language;
            workloadId = launch.workload_id;
            module = launch.entrypoint.module;
            function = launch.entrypoint.function;
            format = launch.entrypoint.format;
            sourcePath = launch.entrypoint.working_dir;
            # ADR-0011 warm-process tier. Skip-serialized in IR when
            # absent, so `or null` falls through to cold tier.
            concurrency = launch.entrypoint.concurrency or null;
            # SDK port Phase 10b — pre-merged per-phase hook lists.
            hooks = launch.hooks or {{ before_build = [ ]; before_start = [ ]; after_start = [ ]; before_stop = [ ]; }};
          }}
          else throw "mvmforge: pinned mvm revision does not expose `mvm.lib.${{system}}.mkFunctionService` (per ADR-0010 §3 / specs/contracts/mvm-mkfunctionservice.md). Bump `MVM_REV` in crates/mvm-sdk/src/compile/mvm_pin.rs to a revision that ships the upstream factory, or override via MVM_FLAKE_URL.";
    in {{
      packages = eachSystem (system:
        let
          pkgs = nixpkgs.legacyPackages.${{system}};
          appPkg = mkAppPkg pkgs;
          imagePackages =
            if launch.image.kind == "nix_packages"
            then map (name: pkgs.${{name}}) launch.image.packages
            else throw "mvmforge: unsupported image.kind '${{launch.image.kind}}'";
          factoryService = buildFactoryService system pkgs appPkg;
          # Function workloads: PID 1 is the factory's idle `bootCommand`
          # (stage source → before_start hook → idle), routed to
          # /etc/mvm/boot via mkGuest's `bootCommand`. /etc/mvm/entrypoint
          # stays the agent's per-call marker (the wrapper), baked by the
          # factory's extraFiles — overloading one file made extraFiles
          # clobber PID 1, so it exec'd the single-shot wrapper and the
          # kernel panicked at boot. The boot script is owned by the
          # factory (single source of truth shared with mkFunctionWorkload).
          #
          # Command workloads keep the single-file path: cmdBootScript
          # stages the source then execs the long-running command, and
          # mkGuest writes it straight to /etc/mvm/entrypoint.
          cmdBootScript = pkgs.writeShellScript "${{launch.workload_id}}-boot" ''
            set -eu
            ${{buildPreStart pkgs appPkg}}
            exec ${{buildEntrypoint pkgs}}
          '';
          mkGuestArgs =
            if isFunction
            then {{
              name = launch.workload_id;
              packages = [ appPkg ] ++ imagePackages ++ factoryService.servicePackages;
              # uid 0: the bootScript symlinks into working_dir (root-owned);
              # the per-call wrapper drops privs internally (ADR-002 W2.3).
              uids.entrypoint = 0;
              # entrypoint drives classification only; not written to disk
              # when bootCommand is set (extraFiles owns /etc/mvm/entrypoint).
              entrypoint.command = factoryService.bootCommand;
              bootCommand = factoryService.bootCommand;
              extraFiles = factoryService.extraFiles;
            }}
            else {{
              name = launch.workload_id;
              packages = [ appPkg ] ++ imagePackages;
              uids.entrypoint = 0;
              entrypoint.command = [ "${{cmdBootScript}}" ];
            }};
        in {{
          default = mvm.lib.${{system}}.mkGuest mkGuestArgs;
        }});

      mvm = {{
        workload = launch;
        metadata = {{
          ir_hash = "{hash}";
          ir_schema_version = "{schema}";
          artifact_format_version = "{format}";
          toolchain_version = "{toolchain}";
        }};
      }};
    }};
}}
"##,
        toolchain = TOOLCHAIN_VERSION,
        id = workload.id,
        mvm_url = resolved_mvm_flake_url(),
        hash = hash,
        schema = workload.schema_version,
        format = ARTIFACT_FORMAT_VERSION,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{App, Entrypoint, Image, Resources, Source};

    fn sample() -> Workload {
        Workload {
            schema_version: "0.1".into(),
            id: "hello".into(),
            apps: vec![App {
                name: "hello".into(),
                source: Source::LocalPath {
                    path: ".".into(),
                    include: vec!["**".into()],
                    exclude: vec![],
                },
                image: Image::NixPackages {
                    packages: vec!["python312".into()],
                },
                entrypoints: vec![Entrypoint::Command {
                    command: vec!["python".into()],
                    working_dir: "/app".into(),
                    env: Default::default(),
                }],
                env: Default::default(),
                mounts: vec![],
                network: None,
                resources: Resources {
                    cpu_cores: 1,
                    memory_mb: 64,
                    rootfs_size_mb: 128,
                },
                dependencies: None,
                threat_tier: Default::default(),
                addons: vec![],
                hooks: Default::default(),
            }],
            volumes: vec![],
            extensions: Default::default(),
        }
    }

    #[test]
    fn flake_is_deterministic_under_default_pin() {
        // Defensive: clear any test-set override.
        unsafe { std::env::remove_var("MVM_FLAKE_URL") };
        let a = build_flake_nix(&sample()).unwrap();
        let b = build_flake_nix(&sample()).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn flake_uses_mkguest_attribute() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("mvm.lib.${system}.mkGuest"));
        // Single canonical lowering: `entrypoint.command = [ bootScript ]`.
        // mk-guest.nix's multi-service entrypoint form is a recovery-shell
        // stub, so we never emit it; and never a top-level
        // `services`/`hostname` arg, which mkGuest rejects.
        assert!(s.contains("entrypoint.command = [ "));
        assert!(!s.contains("entrypoint.services"));
        assert!(!s.contains("hostname = launch.workload_id"));
    }

    #[test]
    fn flake_declares_mvm_and_nixpkgs_inputs() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("inputs.mvm.url"));
        assert!(s.contains("inputs.nixpkgs.follows = \"mvm/nixpkgs\""));
    }

    #[test]
    fn flake_emits_both_systems() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("\"x86_64-linux\""));
        assert!(s.contains("\"aarch64-linux\""));
    }

    #[test]
    fn flake_carries_stable_metadata_attributes() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("mvm = {"));
        assert!(s.contains("workload = launch;"));
        assert!(s.contains("ir_schema_version = \"0.1\""));
    }

    fn sample_function() -> Workload {
        let mut w = sample();
        w.apps[0].entrypoints = vec![Entrypoint::Function {
            language: "python".into(),
            module: "app".into(),
            function: "greet".into(),
            format: crate::ir::Format::Json,
            working_dir: "/app".into(),
            env: Default::default(),
            args_schema: None,
            return_schema: None,
            extra_imports: vec![],
            primary: true,
            concurrency: None,
        }];
        w
    }

    // Regression guard for the boot→ping panic: a function workload's
    // PID 1 must be the factory's idle bootCommand
    // (→ /etc/mvm/boot), with /etc/mvm/entrypoint left as the agent's
    // per-call marker via the factory's extraFiles. The old lowering
    // baked the idle script onto entrypoint.command, which extraFiles
    // then clobbered with the single-shot wrapper → kernel panic.
    #[test]
    fn flake_function_entrypoint_splits_pid1_boot_from_agent_marker() {
        let s = build_flake_nix(&sample_function()).unwrap();
        assert!(
            s.contains("bootCommand = factoryService.bootCommand;"),
            "function PID 1 must come from the factory bootCommand"
        );
        assert!(
            s.contains("entrypoint.command = factoryService.bootCommand;"),
            "entrypoint (classification) tracks the factory bootCommand"
        );
        // The old inlined idle script (the clobber path) is gone.
        assert!(!s.contains("funcBootScript"));
    }

    #[test]
    fn flake_has_lf_line_endings() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(!s.contains('\r'));
    }

    #[test]
    fn flake_bakes_node_modules_when_lockfile_present() {
        // The app-package builder branches on a Node lockfile in ./src and,
        // when present, builds node_modules reproducibly via importNpmLock at
        // build time (baked into the RO app derivation → resolves at
        // /app/node_modules natively, no runtime mount). The branch is in the
        // emitted nix, so it shows up for any workload; the runtime predicate
        // (`nodeHasLock`) gates it per build.
        let s = build_flake_nix(&sample_function()).unwrap();
        assert!(s.contains("nodeHasLock"), "lockfile predicate emitted");
        assert!(s.contains("pkgs.buildNpmPackage"), "npm build path emitted");
        assert!(
            s.contains("pkgs.importNpmLock { npmRoot = ./src; }"),
            "hash-free importNpmLock path emitted"
        );
        assert!(
            s.contains("builtins.pathExists ./src/package-lock.json"),
            "keys off the bundled lockfile"
        );
    }

    #[test]
    fn flake_dispatches_to_factory_for_function_workloads() {
        // The factory dispatch is keyed off `launch.entrypoint.kind`.
        // The substrate exposes a single generic
        // `mvm.lib.<system>.mkFunctionService` that dispatches on the
        // `language` arg via its own registry — no local fallback, no
        // per-language symbol. The artifact never bundles
        // internal-toolchain Nix files.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(
            !s.contains("/nix/factories/"),
            "rendered flake must not reference any local factory copy"
        );
        assert!(s.contains("mvm.lib."));
        assert!(s.contains("mkFunctionService"));
        // Language flows through as an arg, not a symbol-name switch.
        assert!(s.contains("language = launch.entrypoint.language"));
        // Missing-symbol path produces a helpful Nix `throw` rather
        // than silently falling through.
        assert!(s.contains("does not expose"));
        assert!(s.contains("launch.entrypoint.kind == \"function\""));
    }

    #[test]
    fn flake_dispatch_uses_factory_extra_files_and_packages() {
        // The factory returns `{ extraFiles, servicePackages,
        // bootCommand, service }`; the function path consumes all of
        // the first three. The idle bootScript (before_start hook →
        // sleep infinity) now lives inside the factory, not inlined in
        // the emitted flake — so PID 1 is `factoryService.bootCommand`.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("factoryService.servicePackages"));
        assert!(s.contains("factoryService.extraFiles"));
        assert!(s.contains("factoryService.bootCommand"));
    }

    #[test]
    fn flake_threads_concurrency_through_factory_args() {
        // The warm-process concurrency block must reach the
        // per-language factory via factoryArgs so the factory can
        // emit it into /etc/mvm/runtime.json. The IR
        // skip-serializes `concurrency` when None, so the `or null`
        // fallback covers cold-tier workloads without breaking
        // determinism.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(
            s.contains("concurrency = launch.entrypoint.concurrency or null"),
            "rendered flake must thread concurrency from launch.entrypoint into factoryArgs;\nrendered:\n{s}"
        );
    }
}
