//! Renderer for the generated `flake.nix` per ADR-0007.
//!
//! The flake declares an `mvm` guest-lib input (pinned, override-able), follows
//! mvm's `nixpkgs`, and exposes `packages.<system>.default = mvm.lib.<system>.mkGuest { ... }`
//! for both `x86_64-linux` and `aarch64-linux`. `mvm.workload` and
//! `mvm.metadata` remain at their stable attribute paths from ADR-0006 §3.
//!
//! For `entrypoint.kind == "function"` workloads (plan 0003 phase 4 /
//! ADR-0009) the flake dispatches through
//! `mvm.lib.<system>.mk<Lang>FunctionService` per ADR-0010 §3 (Option A,
//! amended 2026-05-06). The factory returns
//! `{ extraFiles, servicePackages, service }`, which we merge into
//! `mkGuest`. mvm does not ship local copies of the factories;
//! the substrate (mvm) is the sole source of truth.
//!
//! Determinism: the output depends only on workload ID, IR hash, the resolved
//! `mvm` flake URL, the IR schema version, and toolchain version. No HashMap,
//! no time, no environment beyond the explicit `MVM_FLAKE_URL` lookup.

use crate::compile::launch::{ARTIFACT_FORMAT_VERSION, TOOLCHAIN_VERSION};
use crate::compile::mvm_pin::resolved_mvm_flake_url;
use mvm_ir::{Workload, ir_hash};

pub fn build_flake_nix(workload: &Workload) -> Result<String, serde_json::Error> {
    let hash = ir_hash(workload)?;
    Ok(format!(
        r##"# Generated by mvm {toolchain}. Do not edit by hand — re-run `mvmctl compile`.
# IR-derived workload data lives in ./launch.json.
# User source tree is bundled in ./src and built into a Nix derivation per ADR-0008.
# Function-call workloads dispatch through mvm.lib.<system>.mk<Lang>FunctionService (ADR-0010 §3).
{{
  description = "{id} — generated by mvm {toolchain}";
  inputs.mvm.url = "{mvm_url}";
  inputs.nixpkgs.follows = "mvm/nixpkgs";
  outputs = {{ self, mvm, nixpkgs, ... }}:
    let
      systems = [ "x86_64-linux" "aarch64-linux" ];
      eachSystem = f: builtins.listToAttrs
        (map (s: {{ name = s; value = f s; }}) systems);
      launch = builtins.fromJSON (builtins.readFile ./launch.json);
      shellQuote = arg:
        "'" + builtins.replaceStrings [ "'" ] [ "'\\''" ] arg + "'";
      mkAppPkg = pkgs: pkgs.stdenv.mkDerivation {{
        pname = "${{launch.workload_id}}-app";
        version = "0";
        src = ./src;
        installPhase = ''
          mkdir -p $out
          cp -R . $out/
        '';
      }};
      buildEntrypoint = pkgs:
        pkgs.writeShellScript "${{launch.workload_id}}-entrypoint" ''
          set -eu
          cd ${{launch.entrypoint.working_dir}}
          exec ${{builtins.concatStringsSep " "
            (map shellQuote launch.entrypoint.command)}}
        '';
      buildPreStart = pkgs: appPkg:
        pkgs.writeShellScript "${{launch.workload_id}}-prestart" ''
          set -eu
          mkdir -p "$(dirname ${{launch.entrypoint.working_dir}})"
          ln -sfn ${{appPkg}} ${{launch.entrypoint.working_dir}}
        '';
      isFunction = launch.entrypoint.kind == "function";
      # Per ADR-0010 §3 (Option A, amended 2026-05-06): factories live
      # in mvm; mvm dispatches through `mvm.lib.${{system}}.mk<Lang>
      # FunctionService` and never bundles a local fallback. If an mvm
      # revision is pinned that doesn't expose the symbol, the rendered
      # flake fails at evaluation with a helpful error pointing at the
      # missing symbol — fix the pin upstream rather than papering over
      # it on the mvm side.
      buildFactoryService = system: pkgs: appPkg:
        if !isFunction then null
        else
          let
            factoryArgs = {{
              inherit pkgs appPkg;
              workloadId = launch.workload_id;
              module = launch.entrypoint.module;
              function = launch.entrypoint.function;
              format = launch.entrypoint.format;
              sourcePath = launch.entrypoint.working_dir;
              # ADR-0011 warm-process tier. Skip-serialized in IR when
              # absent, so `or null` falls through to cold tier.
              concurrency = launch.entrypoint.concurrency or null;
            }};
            langCap =
              if launch.entrypoint.language == "python" then "Python"
              else if launch.entrypoint.language == "node" then "Node"
              else if launch.entrypoint.language == "wasm" then "Wasm"
              else throw "mvmforge: unsupported language '${{launch.entrypoint.language}}' — update mvm_ir::SUPPORTED_LANGUAGES and ship the matching factory in mvm (ADR-0010 §3, §4)";
            symbolName = "mk${{langCap}}FunctionService";
            mvmLib = mvm.lib.${{system}};
            factory =
              if mvmLib ? ${{symbolName}}
              then mvmLib.${{symbolName}}
              else throw "mvmforge: pinned mvm revision does not expose `mvm.lib.${{system}}.${{symbolName}}` (per ADR-0010 §3 / specs/contracts/mvm-mkfunctionservice.md). Bump `MVM_REV` in crates/mvmforge/src/mvm_pin.rs to a revision that ships the upstream factories, or override via MVM_FLAKE_URL.";
          in factory factoryArgs;
    in {{
      packages = eachSystem (system:
        let
          pkgs = nixpkgs.legacyPackages.${{system}};
          appPkg = mkAppPkg pkgs;
          imagePackages =
            if launch.image.kind == "nix_packages"
            then map (name: pkgs.${{name}}) launch.image.packages
            else throw "mvmforge: unsupported image.kind '${{launch.image.kind}}'";
          mergedEnv = launch.env // launch.entrypoint.env;
          factoryService = buildFactoryService system pkgs appPkg;
          mkGuestArgs =
            if isFunction
            then {{
              name = launch.workload_id;
              hostname = launch.workload_id;
              packages = [ appPkg ] ++ imagePackages ++ factoryService.servicePackages;
              services.${{launch.workload_id}} = factoryService.service // {{ env = mergedEnv; }};
              extraFiles = factoryService.extraFiles;
            }}
            else {{
              name = launch.workload_id;
              hostname = launch.workload_id;
              packages = [ appPkg ] ++ imagePackages;
              services.${{launch.workload_id}} = {{
                command = buildEntrypoint pkgs;
                preStart = buildPreStart pkgs appPkg;
                env = mergedEnv;
              }};
            }};
        in {{
          default = mvm.lib.${{system}}.mkGuest mkGuestArgs;
        }});

      mvm = {{
        workload = launch;
        metadata = {{
          ir_hash = "{hash}";
          ir_schema_version = "{schema}";
          artifact_format_version = "{format}";
          toolchain_version = "{toolchain}";
        }};
      }};
    }};
}}
"##,
        toolchain = TOOLCHAIN_VERSION,
        id = workload.id,
        mvm_url = resolved_mvm_flake_url(),
        hash = hash,
        schema = workload.schema_version,
        format = ARTIFACT_FORMAT_VERSION,
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use mvm_ir::{App, Entrypoint, Image, Resources, Source};

    fn sample() -> Workload {
        Workload {
            schema_version: "0.1".into(),
            id: "hello".into(),
            apps: vec![App {
                name: "hello".into(),
                source: Source::LocalPath {
                    path: ".".into(),
                    include: vec!["**".into()],
                    exclude: vec![],
                },
                image: Image::NixPackages {
                    packages: vec!["python312".into()],
                },
                entrypoints: vec![Entrypoint::Command {
                    command: vec!["python".into()],
                    working_dir: "/app".into(),
                    env: Default::default(),
                }],
                env: Default::default(),
                mounts: vec![],
                network: None,
                resources: Resources {
                    cpu_cores: 1,
                    memory_mb: 64,
                    rootfs_size_mb: 128,
                },
                dependencies: None,
                threat_tier: Default::default(),
                addons: vec![],
                hooks: Default::default(),
            }],
            volumes: vec![],
            extensions: Default::default(),
        }
    }

    #[test]
    fn flake_is_deterministic_under_default_pin() {
        // Defensive: clear any test-set override.
        unsafe { std::env::remove_var("MVM_FLAKE_URL") };
        let a = build_flake_nix(&sample()).unwrap();
        let b = build_flake_nix(&sample()).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn flake_uses_mkguest_attribute() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("mvm.lib.${system}.mkGuest"));
        assert!(s.contains("services.${launch.workload_id}"));
    }

    #[test]
    fn flake_declares_mvm_and_nixpkgs_inputs() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("inputs.mvm.url"));
        assert!(s.contains("inputs.nixpkgs.follows = \"mvm/nixpkgs\""));
    }

    #[test]
    fn flake_emits_both_systems() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("\"x86_64-linux\""));
        assert!(s.contains("\"aarch64-linux\""));
    }

    #[test]
    fn flake_carries_stable_metadata_attributes() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("mvm = {"));
        assert!(s.contains("workload = launch;"));
        assert!(s.contains("ir_schema_version = \"0.1\""));
    }

    #[test]
    fn flake_has_lf_line_endings() {
        let s = build_flake_nix(&sample()).unwrap();
        assert!(!s.contains('\r'));
    }

    #[test]
    fn flake_dispatches_to_factory_for_function_workloads() {
        // The factory dispatch is keyed off `launch.entrypoint.kind`
        // and `launch.entrypoint.language`. Per ADR-0010 §3 (Option A,
        // amended 2026-05-06), the rendered flake dispatches through
        // `mvm.lib.<system>.mk<Lang>FunctionService` directly — no
        // local fallback. The artifact never bundles internal-toolchain
        // Nix files.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(
            !s.contains("/nix/factories/"),
            "rendered flake must not reference any local factory copy"
        );
        assert!(s.contains("mvm.lib."));
        assert!(s.contains("mkPythonFunctionService") || s.contains("mk${langCap}FunctionService"));
        // Missing-symbol path produces a helpful Nix `throw` rather
        // than silently falling through.
        assert!(s.contains("does not expose"));
        assert!(s.contains("launch.entrypoint.kind == \"function\""));
        assert!(s.contains("launch.entrypoint.language == \"python\""));
        assert!(s.contains("launch.entrypoint.language == \"node\""));
        assert!(s.contains("launch.entrypoint.language == \"wasm\""));
    }

    #[test]
    fn flake_dispatch_uses_factory_extra_files_and_packages() {
        // The factories return `{ extraFiles, servicePackages,
        // service }`; mkGuest must consume all three.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(s.contains("factoryService.servicePackages"));
        assert!(s.contains("factoryService.extraFiles"));
        assert!(s.contains("factoryService.service"));
    }

    #[test]
    fn flake_threads_concurrency_through_factory_args() {
        // ADR-0011 W-FACTORY: the warm-process concurrency block must
        // reach the per-language factory via factoryArgs so the
        // factory can emit it into /etc/mvm/runtime.json. The IR
        // skip-serializes `concurrency` when None, so the `or null`
        // fallback covers cold-tier workloads without breaking
        // determinism.
        let s = build_flake_nix(&sample()).unwrap();
        assert!(
            s.contains("concurrency = launch.entrypoint.concurrency or null"),
            "rendered flake must thread concurrency from launch.entrypoint into factoryArgs;\nrendered:\n{s}"
        );
    }
}
