"""Generate the offline fixture from predownloaded, digest-pinned public assets.

Usage: python3 generate_published_root.py DIRECTORY
DIRECTORY must contain image-set.json and image-set.json.bundle from:
https://github.com/tinylabscom/mvm-images/releases/tag/image-set/v0.2.4

This maintenance tool performs no downloads. Tests never run this generator.
"""

import hashlib
from pathlib import Path
import sys


ASSETS = (
    ("MANIFEST", "image-set.json", 17784,
     "5033520a59514f5d206d76d13db8c9b7e5841f068c83dd8585ef141879a1bb24"),
    ("BUNDLE", "image-set.json.bundle", 10455,
     "15962832c1e665f7e9cfa3fca9179f01db908201805fd773cfd8eca66d542ac8"),
)
BASE_URL = (
    "https://github.com/tinylabscom/mvm-images/releases/download/image-set/v0.2.4"
)


def generate(directory):
    lines = [
        "//! Generated by generate_published_root.py; do not transcribe signed bytes.",
        "//! Proves root authentication only, not member bytes, packs, or boot.",
    ]
    literals = []
    for name, filename, size, digest in ASSETS:
        with (directory / filename).open("rb") as source:
            data = source.read(size + 1)
        if len(data) != size or hashlib.sha256(data).hexdigest() != digest:
            raise ValueError(f"{filename}: not the pinned public release bytes")
        text = data.decode("utf-8")
        if '"###' in text:
            raise ValueError(f"{filename}: raw-literal delimiter collision")
        lines.extend([
            f"//! {name}: {BASE_URL}/{filename}",
            f"//! {size} bytes; SHA256 {digest}.",
        ])
        literals.append(f'pub const {name}: &[u8] = r###"{text}"###.as_bytes();')
    lines.extend(["", *literals])
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    output = generate(Path(sys.argv[1]))
    Path(__file__).with_name("published_root.rs").write_text(output, encoding="utf-8")
