//! Step definitions, one module per scenario surface.

mod admission_audit;
mod agent_capability;
mod agent_session;
mod apple_container;
mod claim;
pub(crate) mod cli;
mod cold_launch;
mod doc_examples;
mod hvf_save_restore;
mod initramfs;
mod kernel_pin;
mod network_surface;
mod oci_unpack;
mod one_transport;
mod policy_approval;
mod readme_contract;
mod runtime_overlay;
mod sdk;
mod sdk_sidecar;
mod secrets_pii;
mod service_plane;
mod snapshot;
mod transcript;
mod verified_boot;
mod volume;
mod warm_claim;
mod warm_restore;
mod workload_identity;
