[meta]
version = 1

[profiles.gateway]
module = "roles/gateway.nix"

[profiles.worker]
module = "roles/worker.nix"

[roles.gateway]
module = "roles/gateway.nix"
requires_config_drive = true
requires_secrets_drive = true

[roles.worker]
module = "roles/worker.nix"
requires_config_drive = true
requires_secrets_drive = true
