/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/**
 * Request sent from host to guest vsock agent.
 * 
 * `#[serde(deny_unknown_fields)]` is load-bearing: the guest agent must refuse frames whose JSON contains fields the deserializer doesn't recognise, on the principle that silent acceptance of unknown fields is a deserialization-bug gadget waiting to happen. Today every variant is a struct or unit, so the attribute applies cleanly.
 */
export type GuestRequest = ({
ProtocolHello: {
host_protocol_version: number
host_version: string
min_supported_version: number
requested_capabilities: GuestCapability[]
}
} | "WorkerStatus" | {
SleepPrep: {
drain_timeout_secs: number
}
} | "Wake" | "Ping" | "IntegrationStatus" | {
CheckpointIntegrations: {
integrations: string[]
}
} | "ProbeStatus" | "PrimedStatus" | {
Exec: {
command: string
stdin?: (string | null)
timeout_secs?: (number | null)
}
} | {
ExecBatch: {
commands: string[][]
stages: StageFile[]
timeout_secs?: (number | null)
}
} | {
RunEntrypoint: {
/**
 * Env vars injected into the workload after `env_clear()` (`HTTP_PROXY` + secret placeholder vars). Empty for a plain call; omitted on the wire defaults to empty.
 */
env?: [string, string][]
/**
 * Bytes piped to the wrapper's stdin.
 */
stdin: number[]
/**
 * Wall-clock timeout for the call, in seconds. The agent kills the wrapper on overrun and emits `EntrypointEvent::Error { kind: Timeout }`.
 */
timeout_secs: number
}
} | {
PostRestore: {
/**
 * @minItems 16
 * @maxItems 16
 */
token?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
}
} | "FsDiff" | {
StartPortForward: {
guest_port: number
}
} | {
StartUnixSocketForward: {
guest_path: string
host_vsock_port: number
socket_mode: number
}
} | {
ConsoleOpen: {
argv?: string[]
cols: number
env?: [string, string][]
rows: number
}
} | {
ConsoleClose: {
session_id: number
}
} | {
ConsoleResize: {
cols: number
rows: number
session_id: number
}
} | "EntrypointStatus" | "ReadinessStatus" | {
FsRead: {
/**
 * `true` to follow symlinks during canonicalization. Default `true` for read; the host CLI may toggle to `false` for TOCTOU-resistant audits.
 */
follow_symlinks?: boolean
length: number
offset?: (number | null)
path: string
}
} | {
FsWrite: {
content: number[]
/**
 * Create parent directories if missing.
 */
create_parents?: boolean
/**
 * Defaults to `false` for write — TOCTOU-safe default since a malicious symlink could redirect the write.
 */
follow_symlinks?: boolean
/**
 * File mode for newly-created files (e.g. `0o644`). Ignored when overwriting an existing file (existing perms kept).
 */
mode: number
path: string
}
} | {
FsList: {
follow_symlinks?: boolean
path: string
}
} | {
FsStat: {
follow_symlinks?: boolean
path: string
}
} | {
FsMkdir: {
mode: number
parents?: boolean
path: string
}
} | {
FsRemove: {
/**
 * Defaults to `false` for remove; symlink-following on remove is a known footgun.
 */
follow_symlinks?: boolean
path: string
recursive?: boolean
}
} | {
FsMove: {
follow_symlinks?: boolean
from: string
to: string
}
} | {
ProcStart: {
/**
 * Argument vector. `argv[0]` is the executable to spawn.
 */
argv: string[]
/**
 * Working directory inside the guest. `None` = process inherits the agent's cwd.
 */
cwd?: (string | null)
/**
 * Environment variables. Replaces (does not extend) the agent's environment.
 */
env?: {
[k: string]: string
}
/**
 * Initial stdin bytes. Further input goes via `ProcSendInput`.
 */
stdin?: number[]
/**
 * Optional wall-clock kill on overrun. `None` = no agent- imposed timeout; the caller can still send SIGTERM via `ProcSignal` or `ProcKill`.
 */
timeout_secs?: (number | null)
}
} | "ProcList" | {
ProcSignal: {
pid_token: string
signum: number
}
} | {
ProcSendInput: {
bytes: number[]
pid_token: string
}
} | {
ProcWait: {
pid_token: string
timeout_secs?: (number | null)
}
} | {
ProcKill: {
pid_token: string
}
} | {
MountVolume: {
guest_path: string
read_only: boolean
volume_name: string
}
} | {
UnmountVolume: {
force: boolean
guest_path: string
}
} | {
UpdateIdleTimeout: {
secs: number
}
} | {
RunCode: {
code: string
timeout_secs?: (number | null)
}
})
/**
 * Guest-agent control protocol capability. Closed enum so host and guest fail loudly on drift instead of accepting arbitrary strings.
 */
export type GuestCapability = (("ping" | "integration_status" | "entrypoint_status" | "run_entrypoint" | "filesystem_rpc" | "process_rpc" | "console" | "volume_mount" | "update_idle_timeout") | "unix_socket_forward" | "readiness")
/**
 * Response from guest vsock agent to host.
 * 
 * Same `deny_unknown_fields` discipline as `GuestRequest` — a compromised guest must not be able to slip extra fields past the host's deserializer.
 */
export type GuestResponse = ({
ProtocolHelloAck: {
agent_protocol_version: number
agent_version: string
capabilities: GuestCapability[]
min_supported_version: number
}
} | {
ProtocolMismatch: {
agent_protocol_version: number
host_protocol_version: number
message: string
required_action: ProtocolUpgradeAction
}
} | {
WorkerStatus: {
last_busy_at?: (string | null)
status: string
}
} | {
SleepPrepAck: {
detail?: (string | null)
success: boolean
}
} | {
WakeAck: {
success: boolean
}
} | "Pong" | {
Error: {
message: string
}
} | {
UnsupportedInProfile: {
/**
 * Active profile on the agent that rejected the call.
 */
profile: AgentProfile
/**
 * `verb_name()` of the rejected request. Wire-stable.
 */
verb: string
}
} | {
<<<<<<< HEAD
VerbNotAuthorized: {
verb: string
}
} | {
=======
>>>>>>> c34986d0 (fix(xtask): disable formatter in stub codegen for true determinism)
IntegrationStatusReport: {
integrations: IntegrationStateReport[]
}
} | {
CheckpointResult: {
detail?: (string | null)
/**
 * Names of integrations that failed to checkpoint.
 */
failed: string[]
success: boolean
}
} | {
ProbeStatusReport: {
probes: ProbeResult[]
}
} | {
PrimedStatusReport: {
primed: boolean
}
} | {
EntrypointEvent: EntrypointEvent
} | {
ExecEvent: ExecEvent
} | {
ExecBatchResult: {
outcomes: ExecOutcomeWire[]
}
} | {
PostRestoreAck: {
detail?: (string | null)
/**
 * `true` iff the delivered generation token changed and the guest reseeded its CSPRNG (a fresh clone). `false` for an unchanged/zero token (a plain wake or no-rotation restore). Defaults to `false` on the wire for forward-compat with a pre-rotation ack.
 */
reseeded?: boolean
success: boolean
}
} | {
FsDiffResult: {
changes: FsChange[]
}
} | {
PortForwardStarted: {
guest_port: number
vsock_port: number
}
} | {
UnixSocketForwardStarted: {
guest_path: string
host_vsock_port: number
}
} | {
ConsoleOpened: {
data_port: number
session_id: number
}
} | {
ConsoleExited: {
exit_code: number
session_id: number
}
} | {
ConsoleResized: {
session_id: number
}
} | {
EntrypointStatusReport: {
detail?: (string | null)
ok: boolean
path?: (string | null)
}
} | {
ReadinessStatusReport: ReadinessReport
} | {
FsResult: FsResult
} | {
ProcResult: ProcResult
} | {
ProcWaitEvent: ProcWaitEvent
} | {
VolumeMountResult: VolumeMountResult
} | {
UpdateIdleTimeoutAck: {
applied_secs: number
previous_secs: number
}
})
/**
 * Required remediation for a host/guest protocol mismatch.
 */
<<<<<<< HEAD
<<<<<<< HEAD
export type ProtocolUpgradeAction = ("upgrade_host" | "rebuild_guest" | "downgrade_host")
=======
export type ProtocolUpgradeAction =
  | "upgrade_host"
  | "rebuild_guest"
  | "downgrade_host";
>>>>>>> 423f7dfc (fix(xtask): make protocol stub codegen deterministic via explicit print width)
=======
export type ProtocolUpgradeAction = ("upgrade_host" | "rebuild_guest" | "downgrade_host")
>>>>>>> c34986d0 (fix(xtask): disable formatter in stub codegen for true determinism)
/**
 * Profile baked into an mvm guest image. Determines the set of vsock verbs the guest agent's dispatcher will accept; dev-only verbs (`Exec`, `ConsoleOpen`, `ProcStart`, `RunCode`, filesystem RPC, port forwarding) are rejected pre-handler when the image declares `SealedProd`.
 * 
 * **Source of truth.** The profile is declared by the image config — `/etc/mvm/security.json` on a sealed-prod image lives on a dm-verity rootfs, so the value cannot be widened at runtime: any modification breaks the verity hash and the kernel panics in `mvm-verity-init` before userspace. The loader treats absence of the policy file as an unprovisioned dev image (`SecurityPolicy::dev_defaults`).
 * 
 * **Builder uses a different protocol.** `mvm-builder-agent`'s wire type is `HostVmRequest`, not `GuestRequest`; the `Builder` profile is reserved for any future `GuestRequest` variant that only makes sense during a build. No current variant is `BuilderOnly`, so the value is wire-stable but unused for the tenant agent today.
 */
export type AgentProfile = ("sealed-prod" | "dev" | "builder")
/**
 * Runtime status of a single integration on a guest.
 */
export type IntegrationStatus = ("active" | "paused" | {
error: string
} | "pending" | "starting")
/**
 * One event in the streaming response of a `RunEntrypoint` call.
 * 
 * `Stdout` / `Stderr` carry bytes from the wrapper's respective streams. `Exit` and `Error` are terminal — they end the response stream for one call. The agent emits exactly one terminal event per call.
 * 
 * v1 buffers each stream fully before sending one `Stdout` and one `Stderr` event (sizes bounded by agent caps). v2 may chunk progressively without changing the type or the protocol shape: the host already reads frames in a loop until terminal.
 */
export type EntrypointEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Control: {
/**
 * JSON-encoded record header (deserialized by the host into a kind-specific struct). Agent does not parse beyond UTF-8 validation.
 */
header_json: string
/**
 * Opaque per-record payload. Empty for envelope-style records; used for raw bytes on log-style records.
 */
payload: number[]
}
} | {
Exit: {
code: number
}
} | {
Error: {
kind: RunEntrypointError
message: string
}
})
/**
 * Kind of agent-side error reported via `EntrypointEvent::Error`.
 * 
 * The variants are deliberately coarse — the host correlates by `kind` and surfaces the human-readable `message` to the operator. Adding a variant is a wire change; renaming or removing is a breaking change.
 */
export type RunEntrypointError = ("PayloadCap" | "Timeout" | "Busy" | "WrapperCrashed" | "NotReady" | "EntrypointInvalid" | "SessionKilled" | "InternalError")
/**
 * One event in the response stream of an `Exec` call (dev-shell only). The agent emits a sequence of these for a single `Exec` request, terminated by `Exit`. The host reads frames in a loop until terminal.
 */
export type ExecEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Exit: {
code: number
}
} | "TimedOut")
/**
 * Kind of filesystem change.
 */
export type FsChangeKind = ("created" | "modified" | "deleted")
/**
 * State of a single guest subsystem during boot.
 * 
 * `Disabled` is distinct from `Ready` — a missing optional subsystem (no integrations declared, no warm pool configured, no probes registered) reports `Disabled`, while a present-and-warmed subsystem reports `Ready`. This lets the host UX distinguish "the workload doesn't use X" from "X is still warming".
 * 
 * `Default` is `Disabled` — the most-conservative semantically correct value (= "this subsystem isn't configured"). Lets constructors of `ReadinessReport` use `..Default::default()` to elide subsystems they don't care about in tests / fixtures.
 */
export type ComponentState = ("disabled" | "starting" | "ready" | {
failed: {
/**
 * Short human-readable failure reason. Stable enough for an operator to recognise, not a structured cause — pair with stderr logs for diagnosis.
 */
message: string
}
})
/**
 * Result of a filesystem RPC call. Closed enum with `deny_unknown_fields` so a compromised agent can't smuggle extra data past the host's deserializer.
 */
export type FsResult = ({
Read: {
content: number[]
total_size: number
}
} | {
Write: {
bytes_written: number
}
} | {
List: {
entries: FsEntry[]
truncated: boolean
}
} | {
Stat: FsStat
} | "Mkdir" | {
Remove: {
entries_removed: number
}
} | "Move" | {
Error: {
kind: FsErrorKind
message: string
}
})
/**
 * Type of a filesystem entry returned by `FsList` / `FsStat`.
 */
export type FsEntryKind = ("file" | "dir" | "symlink" | "other")
/**
 * Class of error returned in `FsResult::Error`. Closed enum so the host can branch on `kind` without parsing message text.
 */
export type FsErrorKind = ("PolicyDenied" | "NotFound" | "PermissionDenied" | "AlreadyExists" | "CapExceeded" | "CrossDevice" | "DirectoryNotEmpty" | "IoError" | "BadPath" | "Other")
/**
 * Result of a non-streaming process-control verb. Closed enum with `deny_unknown_fields` so a compromised agent can't smuggle extra fields past the host's deserializer.
 */
export type ProcResult = ({
Started: {
pid_token: string
}
} | {
List: {
processes: ProcInfo[]
}
} | "Signaled" | {
InputAccepted: {
bytes_accepted: number
}
} | "Killed" | {
Error: {
kind: ProcErrorKind
message: string
}
})
/**
 * Lifecycle state of a tracked process.
 */
export type ProcState = ("running" | {
exited: number
} | {
killed: number
} | "timed_out")
/**
 * Class of error returned in `ProcResult::Error` and `ProcWaitEvent::Error`.
 */
export type ProcErrorKind = ("UnknownToken" | "SpawnFailed" | "SecurityEnvelopeFailed" | "InvalidArgv" | "InvalidEnv" | "BadCwd" | "CapExceeded" | "UnsupportedInProduction" | "Other")
/**
 * One event in the streaming response of a `ProcWait` call. Terminal events end the stream — the host loops on `is_terminal()` just like for `EntrypointEvent`.
 */
export type ProcWaitEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Exit: {
code: number
}
} | {
Killed: {
signal: number
}
} | "TimedOut" | {
Error: {
kind: ProcErrorKind
message: string
}
} | {
Backpressure: {
detail: string
reason: BackpressureReason
}
})
/**
 * Why a streaming or queued operation is currently throttled.
 * 
 * Closed enum: every reason is named, and drift between host and guest fails the serde `deny_unknown_fields`-equivalent path (variants must match). Detail strings carried alongside this enum are bounded and redacted — never argv / env / stdin / stdout / stderr / filesystem paths.
 */
export type BackpressureReason = ("guest_agent_unavailable" | {
service_health_pending: {
/**
 * Names of services whose readiness scripts have not yet reported success. Echoed verbatim — never user payload.
 */
pending: string[]
}
} | "output_consumer_slow" | "input_buffer_full" | "artifact_transfer_blocked" | "builder_busy")
/**
 * Result of a virtio-fs volume mount operation. (Renamed from `ShareResult`.)
 */
export type VolumeMountResult = ({
Mounted: {
canonical_path: string
}
} | "Unmounted" | {
Error: {
kind: VolumeMountErrorKind
message: string
}
})
/**
 * Class of error returned in `VolumeMountResult::Error`. Closed enum so the host can branch on `kind` without parsing message text. (Renamed from `ShareErrorKind`.)
 */
export type VolumeMountErrorKind = ("BadPath" | "PolicyDenied" | "BadVolumeName" | "MountFailed" | "Busy" | "IoError" | "Other")

/**
 * Schema root: both wire directions under one document so the shared `$defs` (`FsResult`, `ProcResult`, `EntrypointEvent`, …) are emitted once and the generated clients reference a single definition set.
 */
export interface Protocol {
request: GuestRequest
response: GuestResponse
}
/**
 * A file to stage into the guest before an [`GuestRequest::ExecBatch`] runs.
 */
export interface StageFile {
content: number[]
mode: number
path: string
}
/**
 * Full state report for a single integration (returned by guest agent).
 */
export interface IntegrationStateReport {
/**
 * Latest health check result, if a health_cmd is configured.
 */
health?: (IntegrationHealthResult | null)
/**
 * ISO timestamp of last successful checkpoint.
 */
last_checkpoint_at?: (string | null)
name: string
/**
 * Bytes of state data on disk.
 */
state_size_bytes?: number
status: IntegrationStatus
}
/**
 * Result of a single health check execution.
 */
export interface IntegrationHealthResult {
/**
 * ISO 8601 timestamp of when this check ran.
 */
checked_at: string
/**
 * Human-readable detail ("ok" on success, stderr or exit code on failure).
 */
detail: string
/**
 * Whether the health check passed (exit code 0).
 */
healthy: boolean
}
/**
 * Result of running a single probe.
 */
export interface ProbeResult {
/**
 * ISO 8601 timestamp of when this probe ran.
 */
checked_at: string
/**
 * Human-readable detail (stderr for exit_code mode, error message on failure).
 */
detail: string
/**
 * Whether the probe passed (exit code 0).
 */
healthy: boolean
/**
 * Probe name.
 */
name: string
/**
 * Parsed stdout JSON (only for json output_format, None otherwise).
 */
output?: {
[k: string]: unknown
}
}
/**
 * One command's buffered outcome from an [`GuestRequest::ExecBatch`]. Agent- measured: `duration_ms` is the in-guest wall-clock and `peak_rss_kib` the `getrusage` high-water mark when the guest can report it.
 */
export interface ExecOutcomeWire {
duration_ms: number
peak_rss_kib?: (number | null)
status: number
stderr: number[]
stdout: number[]
}
/**
 * A single filesystem change detected since boot.
 */
export interface FsChange {
/**
 * Type of change.
 */
kind: FsChangeKind
/**
 * Path relative to the filesystem root.
 */
path: string
/**
 * File size in bytes (0 for deleted files).
 */
size: number
}
/**
 * Snapshot of agent readiness at the moment of a `ReadinessStatus` call.
 * 
 * Used by host callers (`mvmctl wait`, `mvmctl up --timings`, `mvmctl doctor`) to distinguish:
 * 
 * - "control plane is up, workload not yet warm" → invoke would block; the host can stream progress to the user - "entrypoint validation failed" → invoke would fail fast with a typed error; the host can surface the validation message - "optional subsystem failed" → invoke is still safe; the host surfaces a warning
 * 
 * `Default` composes the `Default` impls of each field — every component is `Disabled`, the profile is `SealedProd`, all timings are `None`. Tests and fixtures can construct partial reports with `..Default::default()`.
 */
export interface ReadinessReport {
/**
 * Per-phase monotonic timings.
 */
boot_millis: BootTimingReport
/**
 * Vsock listener bound and accepting. Always `Ready` if the agent could respond at all.
 */
control_plane: ComponentState
/**
 * `/etc/mvm/entrypoint` validation result. Gates `RunEntrypoint` — a request submitted while `Starting` returns `RunEntrypointError::NotReady`.
 */
entrypoint: ComponentState
/**
 * Drop-in integration scan + health loop. `Disabled` if no `/etc/mvm/integrations.d/*.json` files present.
 */
integrations: ComponentState
/**
 * Drop-in probe scan + probe loop. `Disabled` if no `/etc/mvm/probes.d/*.json` files present.
 */
probes: ComponentState
/**
 * Active agent profile. Same value the dispatcher uses for the `allowed_in` gate.
 */
profile: AgentProfile
/**
 * Volume-mount state — wire-stable placeholder. `Disabled` in v1 (mount/unmount are on-demand verbs, not boot state).
 */
volumes: ComponentState
/**
 * Warm-process pool readiness. `Disabled` for cold-tier images; `Ready` once the `after_start.sh` probe passes.
 */
warm_pool: ComponentState
}
/**
 * Per-phase monotonic boot timings in milliseconds since the agent process started.
 * 
 * `agent_started_ms`, `vsock_bound_ms`, `first_accept_ms`, and `entrypoint_ready_ms` are wired so callers can already display the cold-path timing breakdown. The remaining fields (`warm_pool_ready_ms`, `integrations_ready_ms`, `probes_ready_ms`) are reserved and stay `None` for now.
 */
export interface BootTimingReport {
/**
 * Milliseconds from agent process start to vsock bind/listen. Always present once the agent has bound — this number is the dominant signal for early-readiness regressions.
 */
agent_started_ms?: (number | null)
/**
 * Milliseconds from agent start to `entrypoint = Ready` (or `Failed`). `None` while still `Starting`.
 */
entrypoint_ready_ms?: (number | null)
/**
 * Milliseconds from agent start to the first accepted host connection. `None` until the first `accept()` returns.
 */
first_accept_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
integrations_ready_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
probes_ready_ms?: (number | null)
/**
 * Milliseconds from agent start to a successful `bind+listen` pair on the control port. Same anchor as `agent_started_ms` today; reserved for diverging if a future refactor splits "process started" from "socket created".
 */
vsock_bound_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
warm_pool_ready_ms?: (number | null)
}
/**
 * One entry in an `FsList` response.
 */
export interface FsEntry {
/**
 * File type. `Other` covers sockets, FIFOs, devices.
 */
kind: FsEntryKind
/**
 * Bare entry name (no leading directory component).
 */
name: string
/**
 * Size in bytes, or `0` for non-files.
 */
size: number
}
/**
 * Stat metadata for a single filesystem entry.
 */
export interface FsStat {
/**
 * Canonical (post-`realpath`) path the agent operated on. Lets the host detect when a symlink resolution surprised it.
 */
canonical_path: string
kind: FsEntryKind
/**
 * Unix mode bits (e.g. `0o100644`). Always present; on backends without a unix mode the agent reports a best-effort equivalent.
 */
mode: number
/**
 * Modification timestamp as RFC 3339, or `None` if the underlying fs doesn't expose mtime.
 */
mtime?: (string | null)
size: number
}
/**
 * Per-process metadata returned by `ProcList`.
 */
export interface ProcInfo {
/**
 * argv\[0\] for display only — the agent does not expose the full argv over the wire (it could echo secrets the caller passed in via env / stdin).
 */
argv0: string
pid_token: string
/**
 * RFC 3339 timestamp.
 */
started_at: string
state: ProcState
}
