# Minimal PID 1 init script generator for mvm guests.
#
# Produces a shell script (using busyboxStatic) that replaces systemd
# as PID 1 inside Firecracker microVMs.  No NixOS, no systemd — just
# mount, network, service respawn loops, and the guest agent.
#
# Usage:
#   initScript = import ./minimal-init.nix {
#     inherit pkgs;
#     hostname = "my-vm";
#     services.my-app = {
#       command = "${pkgs.python3}/bin/python3 -m http.server 8080";
#       preStart = "mkdir -p /tmp/www";  # optional
#       env = { FOO = "bar"; };          # optional
#     };
#     healthChecks.my-app = {
#       healthCmd = "${pkgs.curl}/bin/curl -sf http://localhost:8080/";
#       healthIntervalSecs = 5;
#       healthTimeoutSecs = 3;
#     };
#     guestAgentPkg = mvm-guest-agent;
#   };

{ pkgs
, lib ? pkgs.lib
, busybox ? pkgs.pkgsStatic.busybox
, hostname ? "mvm"
, services ? {}
, healthChecks ? {}
, guestAgentPkg ? null
}:

let
  bb = busybox;

  # Generate a respawn loop for one service.
  mkServiceBlock = name: svc:
    let
      preStart = svc.preStart or "";
      preBlock = lib.optionalString (preStart != "") ''
        echo "[init] preStart for ${name}..." > /dev/console
        ${preStart}
      '';
      envLines = lib.concatStringsSep "\n" (
        lib.mapAttrsToList (k: v: "export ${k}='${v}'") (svc.env or {})
      );
    in ''
      # --- Service: ${name} ---
      (
        ${envLines}
        ${preBlock}
        while true; do
          echo "[init] starting ${name}..." > /dev/console
          ${svc.command} > /dev/console 2>&1
          RC=$?
          echo "[init] ${name} exited ($RC), restarting in 2s..." > /dev/console
          sleep 2
        done
      ) &
    '';

  # Generate health check JSON for the guest agent.
  mkHealthCheckFile = name: check:
    let
      obj = {
        inherit name;
        health_cmd = check.healthCmd;
        health_interval_secs = check.healthIntervalSecs or 30;
        health_timeout_secs = check.healthTimeoutSecs or 10;
      } // lib.optionalAttrs (check ? checkpointCmd) {
        checkpoint_cmd = check.checkpointCmd;
      } // lib.optionalAttrs (check ? restoreCmd) {
        restore_cmd = check.restoreCmd;
      } // lib.optionalAttrs (check ? critical) {
        critical = check.critical;
      };
      json = builtins.toJSON obj;
    in ''
      cat > /etc/mvm/integrations.d/${name}.json <<'HEALTHEOF'
      ${json}
      HEALTHEOF
    '';

  serviceBlocks = lib.concatStringsSep "\n" (
    lib.mapAttrsToList mkServiceBlock services
  );

  healthCheckBlocks = lib.concatStringsSep "\n" (
    lib.mapAttrsToList mkHealthCheckFile healthChecks
  );

  guestAgentBlock = lib.optionalString (guestAgentPkg != null) ''
    # --- mvm-guest-agent ---
    (
      while true; do
        echo "[init] starting mvm-guest-agent..." > /dev/console
        ${guestAgentPkg}/bin/mvm-guest-agent > /dev/console 2>&1
        RC=$?
        echo "[init] mvm-guest-agent exited ($RC), restarting in 2s..." > /dev/console
        sleep 2
      done
    ) &
  '';

in
pkgs.writeScript "mvm-minimal-init" ''
  #!${bb}/bin/sh
  # mvm minimal init — PID 1, no systemd.
  # Generated by nix/lib/minimal-init.nix

  export PATH="${bb}/bin"

  echo "[init] mvm minimal init starting..." > /dev/console

  # ── 1. Mount virtual filesystems ─────────────────────────────────
  # /dev is auto-mounted by the kernel (CONFIG_DEVTMPFS_MOUNT=y).
  mount -t proc proc /proc
  mount -t sysfs sys /sys
  mkdir -p /dev/pts /tmp /run /var/run /var/log /root
  mount -t devpts devpts /dev/pts 2>/dev/null || true
  mount -t tmpfs tmpfs /tmp
  mount -t tmpfs tmpfs /run

  # ── 2. Minimal /etc ──────────────────────────────────────────────
  mkdir -p /etc/mvm/integrations.d
  echo 'root:x:0:0:root:/root:${bb}/bin/sh' > /etc/passwd
  echo 'root:x:0:' > /etc/group
  echo '${hostname}' > /etc/hostname
  hostname '${hostname}'

  # ── 3. Parse kernel cmdline for network config ───────────────────
  MVM_IP="" MVM_GW=""
  for arg in $(cat /proc/cmdline); do
    case "$arg" in
      mvm.ip=*) MVM_IP="''${arg#mvm.ip=}" ;;
      mvm.gw=*) MVM_GW="''${arg#mvm.gw=}" ;;
    esac
  done

  # ── 4. Configure networking ─────────────────────────────────────
  if [ -n "$MVM_IP" ] && [ -n "$MVM_GW" ]; then
    echo "[init] network: eth0 $MVM_IP gw $MVM_GW" > /dev/console
    ip link set lo up
    ip link set eth0 up
    ip addr add "$MVM_IP" dev eth0
    ip route add default via "$MVM_GW"
    echo "nameserver $MVM_GW" > /etc/resolv.conf
  else
    echo "[init] WARNING: no mvm.ip/mvm.gw on cmdline, skipping network" > /dev/console
  fi

  # ── 5. Mount optional drives (best-effort) ──────────────────────
  mkdir -p /mnt/config /mnt/secrets /mnt/data

  mount -t ext4 -o ro,noexec,nosuid,nodev /dev/vdb /mnt/config 2>/dev/null && \
    echo "[init] mounted config drive (vdb)" > /dev/console || true

  mount -t ext4 -o ro,noexec,nosuid,nodev /dev/vdc /mnt/secrets 2>/dev/null && \
    echo "[init] mounted secrets drive (vdc)" > /dev/console || true

  mount -t ext4 -o noexec,nosuid,nodev /dev/vdd /mnt/data 2>/dev/null && \
    echo "[init] mounted data drive (vdd)" > /dev/console || true

  # ── 6. Write health check integration configs ───────────────────
  ${healthCheckBlocks}

  # ── 7. Start services (respawn loops) ───────────────────────────
  ${serviceBlocks}

  # ── 8. Start guest agent ────────────────────────────────────────
  ${guestAgentBlock}

  echo "[init] all services started" > /dev/console

  # ── 9. PID 1 reaper: wait for children, loop forever ────────────
  while true; do
    wait
  done
''
