# generated by datamodel-codegen:
#   filename:  protocol-v0.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Union


class AgentProfile1(Enum):
    sealed_prod = 'sealed-prod'


class AgentProfile2(Enum):
    dev = 'dev'


class AgentProfile3(Enum):
    builder = 'builder'


AgentProfile = Union[AgentProfile1, AgentProfile2, AgentProfile3]


class BackpressureReason1(Enum):
    guest_agent_unavailable = 'guest_agent_unavailable'


@dataclass
class ServiceHealthPending:
    pending: List[str]


@dataclass
class BackpressureReason2:
    service_health_pending: ServiceHealthPending


class BackpressureReason3(Enum):
    output_consumer_slow = 'output_consumer_slow'


class BackpressureReason4(Enum):
    input_buffer_full = 'input_buffer_full'


class BackpressureReason5(Enum):
    artifact_transfer_blocked = 'artifact_transfer_blocked'


class BackpressureReason6(Enum):
    builder_busy = 'builder_busy'


BackpressureReason = Union[
    BackpressureReason1,
    BackpressureReason2,
    BackpressureReason3,
    BackpressureReason4,
    BackpressureReason5,
    BackpressureReason6,
]


@dataclass
class BootTimingReport:
    agent_started_ms: Optional[int] = None
    entrypoint_ready_ms: Optional[int] = None
    first_accept_ms: Optional[int] = None
    integrations_ready_ms: Optional[int] = None
    probes_ready_ms: Optional[int] = None
    vsock_bound_ms: Optional[int] = None
    warm_pool_ready_ms: Optional[int] = None


class ComponentState1(Enum):
    disabled = 'disabled'


class ComponentState2(Enum):
    starting = 'starting'


class ComponentState3(Enum):
    ready = 'ready'


@dataclass
class Failed:
    message: str


@dataclass
class ComponentState4:
    failed: Failed


ComponentState = Union[
    ComponentState1, ComponentState2, ComponentState3, ComponentState4
]


@dataclass
class Stdout:
    chunk: List[int]


@dataclass
class EntrypointEvent1:
    Stdout: Stdout


@dataclass
class Stderr:
    chunk: List[int]


@dataclass
class EntrypointEvent2:
    Stderr: Stderr


@dataclass
class Control:
    header_json: str
    payload: List[int]


@dataclass
class EntrypointEvent3:
    Control: Control


@dataclass
class Exit:
    code: int


@dataclass
class EntrypointEvent4:
    Exit: Exit


@dataclass
class ExecEvent1:
    Stdout: Stdout


@dataclass
class ExecEvent2:
    Stderr: Stderr


@dataclass
class ExecEvent3:
    Exit: Exit


class ExecEvent4(Enum):
    TimedOut = 'TimedOut'


ExecEvent = Union[ExecEvent1, ExecEvent2, ExecEvent3, ExecEvent4]


class FsChangeKind(Enum):
    created = 'created'
    modified = 'modified'
    deleted = 'deleted'


class FsEntryKind(Enum):
    file = 'file'
    dir = 'dir'
    symlink = 'symlink'
    other = 'other'


class FsErrorKind1(Enum):
    PolicyDenied = 'PolicyDenied'


class FsErrorKind2(Enum):
    NotFound = 'NotFound'


class FsErrorKind3(Enum):
    PermissionDenied = 'PermissionDenied'


class FsErrorKind4(Enum):
    AlreadyExists = 'AlreadyExists'


class FsErrorKind5(Enum):
    CapExceeded = 'CapExceeded'


class FsErrorKind6(Enum):
    CrossDevice = 'CrossDevice'


class FsErrorKind7(Enum):
    DirectoryNotEmpty = 'DirectoryNotEmpty'


class FsErrorKind8(Enum):
    IoError = 'IoError'


class FsErrorKind9(Enum):
    BadPath = 'BadPath'


class FsErrorKind10(Enum):
    Other = 'Other'


FsErrorKind = Union[
    FsErrorKind1,
    FsErrorKind2,
    FsErrorKind3,
    FsErrorKind4,
    FsErrorKind5,
    FsErrorKind6,
    FsErrorKind7,
    FsErrorKind8,
    FsErrorKind9,
    FsErrorKind10,
]


@dataclass
class Read:
    content: List[int]
    total_size: int


@dataclass
class FsResult1:
    Read: Read


@dataclass
class Write:
    bytes_written: int


@dataclass
class FsResult2:
    Write: Write


class FsResult5(Enum):
    Mkdir = 'Mkdir'


@dataclass
class Remove:
    entries_removed: int


@dataclass
class FsResult6:
    Remove: Remove


class FsResult7(Enum):
    Move = 'Move'


@dataclass
class Error1:
    kind: FsErrorKind
    message: str


@dataclass
class FsResult8:
    Error: Error1


@dataclass
class FsStat:
    canonical_path: str
    kind: FsEntryKind
    mode: int
    size: int
    mtime: Optional[str] = None


class GuestCapability1(Enum):
    ping = 'ping'
    integration_status = 'integration_status'
    entrypoint_status = 'entrypoint_status'
    run_entrypoint = 'run_entrypoint'
    filesystem_rpc = 'filesystem_rpc'
    process_rpc = 'process_rpc'
    console = 'console'
    volume_mount = 'volume_mount'
    update_idle_timeout = 'update_idle_timeout'


class GuestCapability2(Enum):
    readiness = 'readiness'


GuestCapability = Union[GuestCapability1, GuestCapability2]


@dataclass
class ProtocolHello:
    host_protocol_version: int
    host_version: str
    min_supported_version: int
    requested_capabilities: List[GuestCapability]


@dataclass
class GuestRequest1:
    ProtocolHello: ProtocolHello


class GuestRequest2(Enum):
    WorkerStatus = 'WorkerStatus'


@dataclass
class SleepPrep:
    drain_timeout_secs: int


@dataclass
class GuestRequest3:
    SleepPrep: SleepPrep


class GuestRequest4(Enum):
    Wake = 'Wake'


class GuestRequest5(Enum):
    Ping = 'Ping'


class GuestRequest6(Enum):
    IntegrationStatus = 'IntegrationStatus'


@dataclass
class CheckpointIntegrations:
    integrations: List[str]


@dataclass
class GuestRequest7:
    CheckpointIntegrations: CheckpointIntegrations


class GuestRequest8(Enum):
    ProbeStatus = 'ProbeStatus'


@dataclass
class Exec:
    command: str
    stdin: Optional[str] = None
    timeout_secs: Optional[int] = None


@dataclass
class GuestRequest9:
    Exec: Exec


@dataclass
class RunEntrypoint:
    stdin: List[int]
    timeout_secs: int
    env: Optional[List[List[str]]] = field(default_factory=lambda: [])


@dataclass
class GuestRequest10:
    RunEntrypoint: RunEntrypoint


class GuestRequest11(Enum):
    PostRestore = 'PostRestore'


class GuestRequest12(Enum):
    FsDiff = 'FsDiff'


@dataclass
class StartPortForward:
    guest_port: int


@dataclass
class GuestRequest13:
    StartPortForward: StartPortForward


@dataclass
class StartUnixSocketForward:
    guest_path: str
    host_vsock_port: int
    socket_mode: int


@dataclass
class GuestRequest14:
    StartUnixSocketForward: StartUnixSocketForward


@dataclass
class ConsoleOpen:
    cols: int
    rows: int
    env: Optional[List[List[str]]] = field(default_factory=lambda: [])


@dataclass
class GuestRequest15:
    ConsoleOpen: ConsoleOpen


@dataclass
class ConsoleClose:
    session_id: int


@dataclass
class GuestRequest16:
    ConsoleClose: ConsoleClose


@dataclass
class ConsoleResize:
    cols: int
    rows: int
    session_id: int


@dataclass
class GuestRequest17:
    ConsoleResize: ConsoleResize


class GuestRequest18(Enum):
    EntrypointStatus = 'EntrypointStatus'


class GuestRequest19(Enum):
    ReadinessStatus = 'ReadinessStatus'


@dataclass
class FsRead:
    length: int
    path: str
    follow_symlinks: Optional[bool] = True
    offset: Optional[int] = None


@dataclass
class GuestRequest20:
    FsRead: FsRead


@dataclass
class FsWrite:
    content: List[int]
    mode: int
    path: str
    create_parents: Optional[bool] = False
    follow_symlinks: Optional[bool] = False


@dataclass
class GuestRequest21:
    FsWrite: FsWrite


@dataclass
class FsList:
    path: str
    follow_symlinks: Optional[bool] = True


@dataclass
class GuestRequest22:
    FsList: FsList


@dataclass
class FsStat1:
    path: str
    follow_symlinks: Optional[bool] = True


@dataclass
class GuestRequest23:
    FsStat: FsStat1


@dataclass
class FsMkdir:
    mode: int
    path: str
    parents: Optional[bool] = False


@dataclass
class GuestRequest24:
    FsMkdir: FsMkdir


@dataclass
class FsRemove:
    path: str
    follow_symlinks: Optional[bool] = False
    recursive: Optional[bool] = False


@dataclass
class GuestRequest25:
    FsRemove: FsRemove


@dataclass
class FsMove:
    from_: str
    to: str
    follow_symlinks: Optional[bool] = False


@dataclass
class GuestRequest26:
    FsMove: FsMove


@dataclass
class ProcStart:
    argv: List[str]
    cwd: Optional[str] = None
    env: Optional[Dict[str, str]] = field(default_factory=lambda: {})
    stdin: Optional[List[int]] = field(default_factory=lambda: [])
    timeout_secs: Optional[int] = None


@dataclass
class GuestRequest27:
    ProcStart: ProcStart


class GuestRequest28(Enum):
    ProcList = 'ProcList'


@dataclass
class ProcSignal:
    pid_token: str
    signum: int


@dataclass
class GuestRequest29:
    ProcSignal: ProcSignal


@dataclass
class ProcSendInput:
    bytes: List[int]
    pid_token: str


@dataclass
class GuestRequest30:
    ProcSendInput: ProcSendInput


@dataclass
class ProcWait:
    pid_token: str
    timeout_secs: Optional[int] = None


@dataclass
class GuestRequest31:
    ProcWait: ProcWait


@dataclass
class ProcKill:
    pid_token: str


@dataclass
class GuestRequest32:
    ProcKill: ProcKill


@dataclass
class MountVolume:
    guest_path: str
    read_only: bool
    volume_name: str


@dataclass
class GuestRequest33:
    MountVolume: MountVolume


@dataclass
class UnmountVolume:
    force: bool
    guest_path: str


@dataclass
class GuestRequest34:
    UnmountVolume: UnmountVolume


@dataclass
class UpdateIdleTimeout:
    secs: int


@dataclass
class GuestRequest35:
    UpdateIdleTimeout: UpdateIdleTimeout


@dataclass
class RunCode:
    code: str
    timeout_secs: Optional[int] = None


@dataclass
class GuestRequest36:
    RunCode: RunCode


GuestRequest = Union[
    GuestRequest1,
    GuestRequest2,
    GuestRequest3,
    GuestRequest4,
    GuestRequest5,
    GuestRequest6,
    GuestRequest7,
    GuestRequest8,
    GuestRequest9,
    GuestRequest10,
    GuestRequest11,
    GuestRequest12,
    GuestRequest13,
    GuestRequest14,
    GuestRequest15,
    GuestRequest16,
    GuestRequest17,
    GuestRequest18,
    GuestRequest19,
    GuestRequest20,
    GuestRequest21,
    GuestRequest22,
    GuestRequest23,
    GuestRequest24,
    GuestRequest25,
    GuestRequest26,
    GuestRequest27,
    GuestRequest28,
    GuestRequest29,
    GuestRequest30,
    GuestRequest31,
    GuestRequest32,
    GuestRequest33,
    GuestRequest34,
    GuestRequest35,
    GuestRequest36,
]


@dataclass
class ProtocolHelloAck:
    agent_protocol_version: int
    agent_version: str
    capabilities: List[GuestCapability]
    min_supported_version: int


@dataclass
class GuestResponse1:
    ProtocolHelloAck: ProtocolHelloAck


@dataclass
class WorkerStatus:
    status: str
    last_busy_at: Optional[str] = None


@dataclass
class GuestResponse3:
    WorkerStatus: WorkerStatus


@dataclass
class SleepPrepAck:
    success: bool
    detail: Optional[str] = None


@dataclass
class GuestResponse4:
    SleepPrepAck: SleepPrepAck


@dataclass
class WakeAck:
    success: bool


@dataclass
class GuestResponse5:
    WakeAck: WakeAck


class GuestResponse6(Enum):
    Pong = 'Pong'


@dataclass
class Error2:
    message: str


@dataclass
class GuestResponse7:
    Error: Error2


@dataclass
class UnsupportedInProfile:
    profile: AgentProfile
    verb: str


@dataclass
class GuestResponse8:
    UnsupportedInProfile: UnsupportedInProfile


@dataclass
class CheckpointResult:
    failed: List[str]
    success: bool
    detail: Optional[str] = None


@dataclass
class GuestResponse10:
    CheckpointResult: CheckpointResult


@dataclass
class GuestResponse13:
    ExecEvent: ExecEvent


@dataclass
class PostRestoreAck:
    success: bool
    detail: Optional[str] = None


@dataclass
class GuestResponse14:
    PostRestoreAck: PostRestoreAck


@dataclass
class PortForwardStarted:
    guest_port: int
    vsock_port: int


@dataclass
class GuestResponse16:
    PortForwardStarted: PortForwardStarted


@dataclass
class UnixSocketForwardStarted:
    guest_path: str
    host_vsock_port: int


@dataclass
class GuestResponse17:
    UnixSocketForwardStarted: UnixSocketForwardStarted


@dataclass
class ConsoleOpened:
    data_port: int
    session_id: int


@dataclass
class GuestResponse18:
    ConsoleOpened: ConsoleOpened


@dataclass
class ConsoleExited:
    exit_code: int
    session_id: int


@dataclass
class GuestResponse19:
    ConsoleExited: ConsoleExited


@dataclass
class ConsoleResized:
    session_id: int


@dataclass
class GuestResponse20:
    ConsoleResized: ConsoleResized


@dataclass
class EntrypointStatusReport:
    ok: bool
    detail: Optional[str] = None
    path: Optional[str] = None


@dataclass
class GuestResponse21:
    EntrypointStatusReport: EntrypointStatusReport


@dataclass
class UpdateIdleTimeoutAck:
    applied_secs: int
    previous_secs: int


@dataclass
class GuestResponse27:
    UpdateIdleTimeoutAck: UpdateIdleTimeoutAck


@dataclass
class IntegrationHealthResult:
    checked_at: str
    detail: str
    healthy: bool


class IntegrationStatus1(Enum):
    active = 'active'


class IntegrationStatus2(Enum):
    paused = 'paused'


@dataclass
class IntegrationStatus3:
    error: str


class IntegrationStatus4(Enum):
    pending = 'pending'


class IntegrationStatus5(Enum):
    starting = 'starting'


IntegrationStatus = Union[
    IntegrationStatus1,
    IntegrationStatus2,
    IntegrationStatus3,
    IntegrationStatus4,
    IntegrationStatus5,
]


@dataclass
class ProbeResult:
    checked_at: str
    detail: str
    healthy: bool
    name: str
    output: Optional[Any] = None


class ProcErrorKind1(Enum):
    UnknownToken = 'UnknownToken'


class ProcErrorKind2(Enum):
    SpawnFailed = 'SpawnFailed'


class ProcErrorKind3(Enum):
    SecurityEnvelopeFailed = 'SecurityEnvelopeFailed'


class ProcErrorKind4(Enum):
    InvalidArgv = 'InvalidArgv'


class ProcErrorKind5(Enum):
    InvalidEnv = 'InvalidEnv'


class ProcErrorKind6(Enum):
    BadCwd = 'BadCwd'


class ProcErrorKind7(Enum):
    CapExceeded = 'CapExceeded'


class ProcErrorKind8(Enum):
    UnsupportedInProduction = 'UnsupportedInProduction'


class ProcErrorKind9(Enum):
    Other = 'Other'


ProcErrorKind = Union[
    ProcErrorKind1,
    ProcErrorKind2,
    ProcErrorKind3,
    ProcErrorKind4,
    ProcErrorKind5,
    ProcErrorKind6,
    ProcErrorKind7,
    ProcErrorKind8,
    ProcErrorKind9,
]


@dataclass
class Started:
    pid_token: str


@dataclass
class ProcResult1:
    Started: Started


class ProcResult3(Enum):
    Signaled = 'Signaled'


@dataclass
class InputAccepted:
    bytes_accepted: int


@dataclass
class ProcResult4:
    InputAccepted: InputAccepted


class ProcResult5(Enum):
    Killed = 'Killed'


@dataclass
class Error3:
    kind: ProcErrorKind
    message: str


@dataclass
class ProcResult6:
    Error: Error3


class ProcState1(Enum):
    running = 'running'


@dataclass
class ProcState2:
    exited: int


@dataclass
class ProcState3:
    killed: int


class ProcState4(Enum):
    timed_out = 'timed_out'


ProcState = Union[ProcState1, ProcState2, ProcState3, ProcState4]


@dataclass
class ProcWaitEvent1:
    Stdout: Stdout


@dataclass
class ProcWaitEvent2:
    Stderr: Stderr


@dataclass
class ProcWaitEvent3:
    Exit: Exit


@dataclass
class Killed:
    signal: int


@dataclass
class ProcWaitEvent4:
    Killed: Killed


class ProcWaitEvent5(Enum):
    TimedOut = 'TimedOut'


@dataclass
class ProcWaitEvent6:
    Error: Error3


@dataclass
class Backpressure:
    detail: str
    reason: BackpressureReason


@dataclass
class ProcWaitEvent7:
    Backpressure: Backpressure


ProcWaitEvent = Union[
    ProcWaitEvent1,
    ProcWaitEvent2,
    ProcWaitEvent3,
    ProcWaitEvent4,
    ProcWaitEvent5,
    ProcWaitEvent6,
    ProcWaitEvent7,
]


class ProtocolUpgradeAction(Enum):
    upgrade_host = 'upgrade_host'
    rebuild_guest = 'rebuild_guest'
    downgrade_host = 'downgrade_host'


@dataclass
class ReadinessReport:
    boot_millis: BootTimingReport
    control_plane: ComponentState
    entrypoint: ComponentState
    integrations: ComponentState
    probes: ComponentState
    profile: AgentProfile
    volumes: ComponentState
    warm_pool: ComponentState


class RunEntrypointError1(Enum):
    PayloadCap = 'PayloadCap'


class RunEntrypointError2(Enum):
    Timeout = 'Timeout'


class RunEntrypointError3(Enum):
    Busy = 'Busy'


class RunEntrypointError4(Enum):
    WrapperCrashed = 'WrapperCrashed'


class RunEntrypointError5(Enum):
    NotReady = 'NotReady'


class RunEntrypointError6(Enum):
    EntrypointInvalid = 'EntrypointInvalid'


class RunEntrypointError7(Enum):
    SessionKilled = 'SessionKilled'


class RunEntrypointError8(Enum):
    InternalError = 'InternalError'


RunEntrypointError = Union[
    RunEntrypointError1,
    RunEntrypointError2,
    RunEntrypointError3,
    RunEntrypointError4,
    RunEntrypointError5,
    RunEntrypointError6,
    RunEntrypointError7,
    RunEntrypointError8,
]


class VolumeMountErrorKind1(Enum):
    BadPath = 'BadPath'


class VolumeMountErrorKind2(Enum):
    PolicyDenied = 'PolicyDenied'


class VolumeMountErrorKind3(Enum):
    BadVolumeName = 'BadVolumeName'


class VolumeMountErrorKind4(Enum):
    MountFailed = 'MountFailed'


class VolumeMountErrorKind5(Enum):
    Busy = 'Busy'


class VolumeMountErrorKind6(Enum):
    IoError = 'IoError'


class VolumeMountErrorKind7(Enum):
    Other = 'Other'


VolumeMountErrorKind = Union[
    VolumeMountErrorKind1,
    VolumeMountErrorKind2,
    VolumeMountErrorKind3,
    VolumeMountErrorKind4,
    VolumeMountErrorKind5,
    VolumeMountErrorKind6,
    VolumeMountErrorKind7,
]


@dataclass
class Mounted:
    canonical_path: str


@dataclass
class VolumeMountResult1:
    Mounted: Mounted


class VolumeMountResult2(Enum):
    Unmounted = 'Unmounted'


@dataclass
class Error5:
    kind: VolumeMountErrorKind
    message: str


@dataclass
class VolumeMountResult3:
    Error: Error5


VolumeMountResult = Union[VolumeMountResult1, VolumeMountResult2, VolumeMountResult3]


@dataclass
class Error:
    kind: RunEntrypointError
    message: str


@dataclass
class EntrypointEvent5:
    Error: Error


EntrypointEvent = Union[
    EntrypointEvent1,
    EntrypointEvent2,
    EntrypointEvent3,
    EntrypointEvent4,
    EntrypointEvent5,
]


@dataclass
class FsChange:
    kind: FsChangeKind
    path: str
    size: int


@dataclass
class FsEntry:
    kind: FsEntryKind
    name: str
    size: int


@dataclass
class ListModel:
    entries: List[FsEntry]
    truncated: bool


@dataclass
class FsResult3:
    List: ListModel


@dataclass
class FsResult4:
    Stat: FsStat


FsResult = Union[
    FsResult1,
    FsResult2,
    FsResult3,
    FsResult4,
    FsResult5,
    FsResult6,
    FsResult7,
    FsResult8,
]


@dataclass
class ProtocolMismatch:
    agent_protocol_version: int
    host_protocol_version: int
    message: str
    required_action: ProtocolUpgradeAction


@dataclass
class GuestResponse2:
    ProtocolMismatch: ProtocolMismatch


@dataclass
class ProbeStatusReport:
    probes: List[ProbeResult]


@dataclass
class GuestResponse11:
    ProbeStatusReport: ProbeStatusReport


@dataclass
class GuestResponse12:
    EntrypointEvent: EntrypointEvent


@dataclass
class FsDiffResult:
    changes: List[FsChange]


@dataclass
class GuestResponse15:
    FsDiffResult: FsDiffResult


@dataclass
class GuestResponse22:
    ReadinessStatusReport: ReadinessReport


@dataclass
class GuestResponse23:
    FsResult: FsResult


@dataclass
class GuestResponse25:
    ProcWaitEvent: ProcWaitEvent


@dataclass
class GuestResponse26:
    VolumeMountResult: VolumeMountResult


@dataclass
class IntegrationStateReport:
    name: str
    status: IntegrationStatus
    health: Optional[IntegrationHealthResult] = None
    last_checkpoint_at: Optional[str] = None
    state_size_bytes: Optional[int] = 0


@dataclass
class ProcInfo:
    argv0: str
    pid_token: str
    started_at: str
    state: ProcState


@dataclass
class List1:
    processes: List[ProcInfo]


@dataclass
class ProcResult2:
    List: List1


ProcResult = Union[
    ProcResult1, ProcResult2, ProcResult3, ProcResult4, ProcResult5, ProcResult6
]


@dataclass
class IntegrationStatusReport:
    integrations: List[IntegrationStateReport]


@dataclass
class GuestResponse9:
    IntegrationStatusReport: IntegrationStatusReport


@dataclass
class GuestResponse24:
    ProcResult: ProcResult


GuestResponse = Union[
    GuestResponse1,
    GuestResponse2,
    GuestResponse3,
    GuestResponse4,
    GuestResponse5,
    GuestResponse6,
    GuestResponse7,
    GuestResponse8,
    GuestResponse9,
    GuestResponse10,
    GuestResponse11,
    GuestResponse12,
    GuestResponse13,
    GuestResponse14,
    GuestResponse15,
    GuestResponse16,
    GuestResponse17,
    GuestResponse18,
    GuestResponse19,
    GuestResponse20,
    GuestResponse21,
    GuestResponse22,
    GuestResponse23,
    GuestResponse24,
    GuestResponse25,
    GuestResponse26,
    GuestResponse27,
]


@dataclass
class Protocol:
    request: GuestRequest
    response: GuestResponse
