//! Renders the Rust-owned SDK env-var registry into Python and
//! TypeScript source.
//!
//! This sits beside [`crate::gen_stubs`] rather than inside it because
//! the two pipelines differ in kind. `gen_stubs` turns a JSON *Schema*
//! into type declarations via two pinned third-party generators;
//! this turns a JSON *instance* into value bindings, which neither of
//! those generators can produce:
//!
//! * `json-schema-to-typescript` only ever emits `export type`, and a
//!   type is erased by `tsc` — so the constant would be absent at
//!   runtime and invisible to the s27 surface check, which reads
//!   `Object.keys(mvm)`.
//! * `datamodel-code-generator` emits models; a `const`-shaped schema
//!   becomes an `Enum` class, not a module-level binding.
//!
//! Rendering here is therefore not a shortcut around the pinned
//! generators — it is the only way to emit a value. It also costs
//! nothing in determinism, which is the property the pins exist to
//! protect: the output depends on this function alone, so there is no
//! `--no-format`-style hazard (see `gen_stubs`' note on prettier).

use anyhow::{Context, Result};
use serde::Deserialize;

/// One row of `schema/sdk-env-v0.json`.
#[derive(Debug, Clone, Deserialize, PartialEq, Eq)]
pub struct EnvVar {
    /// Constant identifier, identical in every language.
    pub ident: String,
    /// The environment variable's actual name.
    pub name: String,
    /// One-line description rendered as a doc comment.
    pub doc: String,
    /// Surfaces that export this name (`rust` / `python` / `typescript`).
    pub surfaces: Vec<String>,
}

/// The manifest document as a whole.
#[derive(Debug, Clone, Deserialize)]
pub struct EnvManifest {
    /// Registry rows, in declaration order.
    pub vars: Vec<EnvVar>,
}

impl EnvManifest {
    /// Parse a manifest emitted by `mvm-sdk`'s `emit_sdk_env` bin.
    pub fn parse(bytes: &[u8]) -> Result<Self> {
        serde_json::from_slice(bytes).context("parsing sdk-env manifest")
    }

    /// Rows exported by `surface`, in declaration order.
    pub fn exported_to(&self, surface: &str) -> Vec<&EnvVar> {
        self.vars
            .iter()
            .filter(|v| v.surfaces.iter().any(|s| s == surface))
            .collect()
    }
}

/// Wrap `text` as a comment body at `width`, one line per element.
fn wrap(text: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut cur = String::new();
    for word in text.split_whitespace() {
        if !cur.is_empty() && cur.chars().count() + 1 + word.chars().count() > width {
            lines.push(std::mem::take(&mut cur));
        }
        if !cur.is_empty() {
            cur.push(' ');
        }
        cur.push_str(word);
    }
    if !cur.is_empty() {
        lines.push(cur);
    }
    if lines.is_empty() {
        lines.push(String::new());
    }
    lines
}

/// Render the Python binding module.
pub fn render_python(manifest: &EnvManifest) -> String {
    let vars = manifest.exported_to("python");
    let mut out = String::new();
    out.push_str("# Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/env.rs.\n");
    out.push_str("# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.\n");
    out.push_str("\"\"\"SDK environment-variable names, owned by the Rust registry.\"\"\"\n");
    for v in &vars {
        out.push('\n');
        for line in wrap(&v.doc, 66) {
            if line.is_empty() {
                out.push_str("#:\n");
            } else {
                out.push_str(&format!("#: {line}\n"));
            }
        }
        out.push_str(&format!("{} = {:?}\n", v.ident, v.name));
    }
    out.push_str("\n__all__ = [\n");
    for v in &vars {
        out.push_str(&format!("    {:?},\n", v.ident));
    }
    out.push_str("]\n");
    out
}

/// Render the TypeScript binding module.
pub fn render_typescript(manifest: &EnvManifest) -> String {
    let vars = manifest.exported_to("typescript");
    let mut out = String::new();
    out.push_str("/* eslint-disable */\n");
    out.push_str("/**\n");
    out.push_str(" * Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/env.rs.\n");
    out.push_str(" * DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.\n");
    out.push_str(" */\n");
    for v in &vars {
        out.push('\n');
        let doc = wrap(&v.doc, 66);
        if doc.len() == 1 {
            out.push_str(&format!("/** {} */\n", doc[0]));
        } else {
            out.push_str("/**\n");
            for line in &doc {
                out.push_str(&format!(" * {line}\n"));
            }
            out.push_str(" */\n");
        }
        out.push_str(&format!("export const {} = {:?};\n", v.ident, v.name));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest() -> EnvManifest {
        EnvManifest::parse(
            br#"{"vars":[
                {"ident":"A_ENV","name":"A","doc":"First one.",
                 "surfaces":["rust","python","typescript"]},
                {"ident":"B_ENV","name":"B","doc":"Second one, python only.",
                 "surfaces":["rust","python"]}
            ]}"#,
        )
        .unwrap()
    }

    #[test]
    fn python_render_includes_every_python_row() {
        let py = render_python(&manifest());
        assert!(py.contains(r#"A_ENV = "A""#));
        assert!(py.contains(r#"B_ENV = "B""#));
        assert!(py.contains("__all__"));
        assert!(py.contains(r#"    "A_ENV","#));
        assert!(py.contains(r#"    "B_ENV","#));
    }

    #[test]
    fn typescript_render_omits_rows_that_do_not_export_to_it() {
        // The honesty property: a name TypeScript does not read must not
        // appear as a TypeScript export, or the divergence gate would
        // certify a parity that does not exist.
        let ts = render_typescript(&manifest());
        assert!(ts.contains(r#"export const A_ENV = "A";"#));
        assert!(
            !ts.contains("B_ENV"),
            "python-only row leaked into the TypeScript binding"
        );
    }

    #[test]
    fn both_renders_carry_a_do_not_edit_header() {
        let m = manifest();
        assert!(render_python(&m).contains("DO NOT EDIT BY HAND"));
        assert!(render_typescript(&m).contains("DO NOT EDIT BY HAND"));
    }

    #[test]
    fn render_is_deterministic() {
        let m = manifest();
        assert_eq!(render_python(&m), render_python(&m));
        assert_eq!(render_typescript(&m), render_typescript(&m));
    }

    #[test]
    fn declaration_order_is_preserved() {
        let py = render_python(&manifest());
        assert!(py.find("A_ENV").unwrap() < py.find("B_ENV").unwrap());
    }

    #[test]
    fn wrap_splits_on_width_without_losing_words() {
        let text = "one two three four five six";
        let lines = wrap(text, 9);
        assert!(lines.len() > 1);
        assert_eq!(lines.join(" "), text);
        assert!(lines.iter().all(|l| l.chars().count() <= 9));
    }

    #[test]
    fn wrap_never_yields_zero_lines() {
        assert_eq!(wrap("", 10), vec![String::new()]);
    }

    #[test]
    fn parse_rejects_a_malformed_manifest() {
        assert!(EnvManifest::parse(b"{\"vars\": 3}").is_err());
    }

    #[test]
    fn exported_to_is_empty_for_an_unknown_surface() {
        assert!(manifest().exported_to("elixir").is_empty());
    }
}
