//! `xtask gen-stubs` and `xtask check-stubs`
//!
//! Codegen pipeline for the Python and TypeScript SDKs' generated
//! types. Two Rust-owned JSON Schemas are the single source of truth,
//! each emitted by a `schemars`-backed bin and fed through the same
//! per-language generators (see [`artifacts`]):
//!
//! * The **workload IR** — `mvm-sdk`'s `ir::Workload` →
//!   `schema/workload-ir-v0.json` → `sdks/.../_ir`.
//! * The **host↔guest protocol** — `mvm-guest`'s `GuestRequest` /
//!   `GuestResponse` → `schema/protocol-v0.json` → `sdks/.../_protocol`.
//!
//! The xtask packages every step into one command so a dev who edits
//! either the IR or the protocol types runs `cargo xtask gen-stubs`
//! and gets everything refreshed; CI runs `cargo xtask check-stubs`
//! and fails on drift.
//!
//! Toolchain:
//!
//! * Rust schema emit: a `cargo run` per artifact (the protocol bin
//!   needs `--features schema`; the IR bin does not).
//! * Python: `uvx --from datamodel-code-generator==<PIN>
//!   datamodel-codegen ...` — zero-install via `uv`. Devs don't need
//!   to `uv sync` a Python env first.
//! * TypeScript: `npx --yes json-schema-to-typescript@<PIN> json2ts
//!   ...` — zero-install via `npx`. Devs don't need to
//!   `pnpm install` first.
//!
//! Pinning the generator versions in the xtask (not in
//! `pyproject.toml` / `package.json`) means CI and local always run
//! the same generator. If a SDK's own `pyproject.toml` /
//! `package.json` later pins the same versions for IDE / test
//! tooling, that's a redundancy — but two redundant pins is a
//! cheaper failure mode than a drift between them.

use anyhow::{Context, Result, bail};
use std::path::Path;
use std::process::Command;

/// Pinned generator versions. Bumping a pin is a deliberate one-line
/// change in this file; bump, re-run `cargo xtask gen-stubs`, commit
/// the regenerated files and the pin in the same patch.
const DATAMODEL_CODEGEN_VERSION: &str = "0.25.9";
const JSON_SCHEMA_TO_TS_VERSION: &str = "15.0.3";

/// One language-stub set: a Rust schema-emitter feeding the Python +
/// TypeScript generators, with the committed paths `check-stubs` diffs
/// against. The pipeline is identical per artifact — only the emit
/// command, output paths, and root class name vary — so the two
/// schemas (workload IR + host↔guest protocol) are data, not branches.
struct StubArtifact {
    /// Human label for progress output.
    label: &'static str,
    /// `cargo` args that emit the JSON schema to stdout. The protocol
    /// emitter is gated behind `--features schema`; the IR emitter is
    /// not — hence per-artifact args rather than a shared constant.
    emit_args: &'static [&'static str],
    /// Workspace-relative committed schema path.
    schema_path: &'static str,
    /// Workspace-relative committed Python dataclass module.
    python_path: &'static str,
    /// Workspace-relative committed TypeScript interface module.
    ts_path: &'static str,
    /// Root class name handed to datamodel-codegen.
    class_name: &'static str,
    /// Basename for the fresh tempdir copies in `check`.
    stem: &'static str,
}

/// The full set of stub artifacts regenerated by `gen-stubs` and
/// drift-checked by `check-stubs`.
fn artifacts() -> &'static [StubArtifact] {
    &[
        StubArtifact {
            label: "workload IR",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-sdk",
                "--bin",
                "emit_workload_schema",
            ],
            schema_path: "schema/workload-ir-v0.json",
            python_path: "sdks/python/mvm/_ir/workload.py",
            ts_path: "sdks/typescript/src/ir/workload.ts",
            class_name: "Workload",
            stem: "workload-ir-v0",
        },
        StubArtifact {
            label: "host↔guest protocol",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-guest",
                "--features",
                "schema",
                "--bin",
                "emit_protocol_schema",
            ],
            schema_path: "schema/protocol-v0.json",
            python_path: "sdks/python/mvm/_protocol/protocol.py",
            ts_path: "sdks/typescript/src/protocol/protocol.ts",
            class_name: "Protocol",
            stem: "protocol-v0",
        },
    ]
}

/// Generate every artifact's schema + Python + TypeScript types in place.
pub fn generate(workspace: &Path) -> Result<()> {
    for art in artifacts() {
        println!("==> {} stubs", art.label);
        let schema_path = workspace.join(art.schema_path);
        let py_path = workspace.join(art.python_path);
        let ts_path = workspace.join(art.ts_path);

        ensure_parent_dir(&schema_path)?;
        ensure_parent_dir(&py_path)?;
        ensure_parent_dir(&ts_path)?;

        let schema = emit_schema(workspace, art)?;
        std::fs::write(&schema_path, &schema)
            .with_context(|| format!("writing {}", schema_path.display()))?;
        println!("    wrote {}", schema_path.display());

        run_python_codegen(workspace, &schema_path, &py_path, art.class_name)?;
        println!("    wrote {}", py_path.display());

        run_ts_codegen(workspace, &schema_path, &ts_path)?;
        println!("    wrote {}", ts_path.display());
    }

    println!("\ngen-stubs complete. Commit the regenerated files.");
    Ok(())
}

/// CI guard: regenerate every artifact to a tempdir, diff against the
/// committed paths, fail if any has drifted. Exit 0 = no drift.
pub fn check(workspace: &Path) -> Result<()> {
    let tmp = tempfile::tempdir().context("creating tempdir")?;
    let mut drift = false;

    for art in artifacts() {
        let fresh_schema = tmp.path().join(format!("{}.json", art.stem));
        let fresh_py = tmp.path().join(format!("{}.py", art.stem));
        let fresh_ts = tmp.path().join(format!("{}.ts", art.stem));

        let schema = emit_schema(workspace, art)?;
        std::fs::write(&fresh_schema, &schema)
            .with_context(|| format!("writing {}", fresh_schema.display()))?;
        run_python_codegen(workspace, &fresh_schema, &fresh_py, art.class_name)?;
        run_ts_codegen(workspace, &fresh_schema, &fresh_ts)?;

        drift |= diff_or_report(&fresh_schema, &workspace.join(art.schema_path))?;
        drift |= diff_or_report(&fresh_py, &workspace.join(art.python_path))?;
        drift |= diff_or_report(&fresh_ts, &workspace.join(art.ts_path))?;
    }

    if drift {
        bail!("generated stubs are stale — run `cargo xtask gen-stubs` and commit the result");
    }
    println!("check-stubs: no drift");
    Ok(())
}

fn emit_schema(workspace: &Path, art: &StubArtifact) -> Result<Vec<u8>> {
    let output = Command::new("cargo")
        .args(art.emit_args)
        .current_dir(workspace)
        .output()
        .with_context(|| format!("spawning cargo {}", art.emit_args.join(" ")))?;
    if !output.status.success() {
        bail!(
            "schema emit for {} exited {}: {}",
            art.label,
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(output.stdout)
}

fn run_python_codegen(workspace: &Path, schema: &Path, out: &Path, class_name: &str) -> Result<()> {
    let from = format!("datamodel-code-generator=={DATAMODEL_CODEGEN_VERSION}");
    let status = Command::new("uvx")
        .args(["--from", &from, "datamodel-codegen", "--input"])
        .arg(schema)
        .args([
            "--input-file-type",
            "jsonschema",
            "--output-model-type",
            "dataclasses.dataclass",
            "--class-name",
            class_name,
            "--target-python-version",
            "3.10",
            "--disable-timestamp",
            "--output",
        ])
        .arg(out)
        .current_dir(workspace)
        .status()
        .context(
            "spawning uvx datamodel-codegen — install uv (https://docs.astral.sh/uv/) to run codegen",
        )?;
    if !status.success() {
        bail!("datamodel-codegen exited {status}");
    }
    Ok(())
}

fn run_ts_codegen(workspace: &Path, schema: &Path, out: &Path) -> Result<()> {
    let pkg = format!("json-schema-to-typescript@{JSON_SCHEMA_TO_TS_VERSION}");
    let status = Command::new("npx")
        .args(["--yes", &pkg, "--input"])
        .arg(schema)
        .arg("--output")
        .arg(out)
        .arg("--no-additionalProperties")
        .current_dir(workspace)
        .status()
        .context("spawning npx json-schema-to-typescript — install node + npx to run codegen")?;
    if !status.success() {
        bail!("json-schema-to-typescript exited {status}");
    }
    Ok(())
}

fn ensure_parent_dir(path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    Ok(())
}

fn diff_or_report(fresh: &Path, committed: &Path) -> Result<bool> {
    if !committed.exists() {
        eprintln!(
            "drift: {} is missing — run `cargo xtask gen-stubs` to create it",
            committed.display()
        );
        return Ok(true);
    }
    let fresh_bytes =
        std::fs::read(fresh).with_context(|| format!("reading {}", fresh.display()))?;
    let committed_bytes =
        std::fs::read(committed).with_context(|| format!("reading {}", committed.display()))?;
    if fresh_bytes == committed_bytes {
        return Ok(false);
    }

    eprintln!("drift: {} differs from fresh output", committed.display());
    // Best-effort unified diff via the `diff` binary; we don't fail
    // the check if `diff` itself is unavailable, since the equality
    // check above is the source of truth.
    let _ = Command::new("diff")
        .args(["-u", "--label", "committed", "--label", "fresh"])
        .arg(committed)
        .arg(fresh)
        .status();
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn diff_or_report_returns_false_when_identical() {
        let tmp = tempdir().unwrap();
        let a = tmp.path().join("a");
        let b = tmp.path().join("b");
        std::fs::write(&a, b"same").unwrap();
        std::fs::write(&b, b"same").unwrap();
        assert!(!diff_or_report(&a, &b).unwrap());
    }

    #[test]
    fn diff_or_report_returns_true_when_committed_missing() {
        let tmp = tempdir().unwrap();
        let fresh = tmp.path().join("fresh");
        let missing = tmp.path().join("never-existed");
        std::fs::write(&fresh, b"x").unwrap();
        assert!(diff_or_report(&fresh, &missing).unwrap());
    }

    #[test]
    fn diff_or_report_returns_true_on_drift() {
        let tmp = tempdir().unwrap();
        let a = tmp.path().join("a");
        let b = tmp.path().join("b");
        std::fs::write(&a, b"hello").unwrap();
        std::fs::write(&b, b"world").unwrap();
        assert!(diff_or_report(&a, &b).unwrap());
    }

    #[test]
    fn ensure_parent_dir_creates_missing_path() {
        let tmp = tempdir().unwrap();
        let nested = tmp.path().join("a/b/c/file.txt");
        ensure_parent_dir(&nested).unwrap();
        assert!(nested.parent().unwrap().is_dir());
    }

    #[test]
    fn artifacts_cover_workload_ir_and_protocol() {
        let schemas: Vec<&str> = artifacts().iter().map(|a| a.schema_path).collect();
        assert!(
            schemas.contains(&"schema/workload-ir-v0.json"),
            "workload IR artifact missing"
        );
        assert!(
            schemas.contains(&"schema/protocol-v0.json"),
            "protocol artifact missing"
        );
    }

    #[test]
    fn protocol_artifact_emits_under_schema_feature() {
        let proto = artifacts()
            .iter()
            .find(|a| a.schema_path == "schema/protocol-v0.json")
            .expect("protocol artifact present");
        // The emit_protocol_schema bin carries `required-features =
        // ["schema"]`; dropping the flag silently builds nothing and the
        // emit fails closed — so the descriptor must keep it.
        assert!(proto.emit_args.contains(&"--features"));
        assert!(proto.emit_args.contains(&"schema"));
        assert!(proto.emit_args.contains(&"emit_protocol_schema"));
        assert_eq!(proto.python_path, "sdks/python/mvm/_protocol/protocol.py");
        assert_eq!(proto.ts_path, "sdks/typescript/src/protocol/protocol.ts");
        assert_eq!(proto.class_name, "Protocol");
    }

    #[test]
    fn artifact_output_paths_are_unique() {
        // Guards against a copy-pasted descriptor that would have one
        // artifact overwrite a sibling's committed output.
        let mut paths: Vec<&str> = Vec::new();
        for a in artifacts() {
            paths.push(a.schema_path);
            paths.push(a.python_path);
            paths.push(a.ts_path);
        }
        let mut deduped = paths.clone();
        deduped.sort_unstable();
        deduped.dedup();
        assert_eq!(
            paths.len(),
            deduped.len(),
            "duplicate output path among artifacts"
        );
    }
}
