//! `xtask gen-stubs` and `xtask check-stubs`
//!
//! Codegen pipeline for the Python and TypeScript SDKs' generated
//! types. Rust-owned JSON Schemas are the single source of truth,
//! each emitted by a `schemars`-backed bin and fed through the same
//! per-language generators (see [`artifacts`]):
//!
//! * The **workload IR** — `mvm-sdk`'s `ir::Workload` →
//!   `schema/workload-ir-v0.json` → `crates/mvm-sdk/.../_ir`.
//! * The **host↔guest protocol** — `mvm-agentd`'s `GuestRequest` /
//!   `GuestResponse` → `schema/protocol-v0.json` → `crates/mvm-sdk/.../_protocol`.
//! * The **live runtime contract** — `mvm-sdk`'s runtime result and
//!   filesystem types → `schema/runtime-v0.json` → `crates/mvm-sdk/.../_runtime`.
//!
//! The xtask packages every step into one command so a dev who edits
//! either the IR or the protocol types runs `cargo xtask gen-stubs`
//! and gets everything refreshed; CI runs `cargo xtask check-stubs`
//! and fails on drift.
//!
//! Toolchain:
//!
//! * Rust schema emit: a `cargo run` per artifact (the protocol bin
//!   needs `--features schema`; the IR bin does not).
//! * Python: `uvx --from datamodel-code-generator==<PIN>
//!   datamodel-codegen ...` — zero-install via `uv`. Devs don't need
//!   to `uv sync` a Python env first.
//! * TypeScript: `npx --yes json-schema-to-typescript@<PIN> json2ts
//!   ...` — zero-install via `npx`. Devs don't need to
//!   `pnpm install` first.
//!
//! Pinning the generator versions in the xtask (not in
//! `pyproject.toml` / `package.json`) means CI and local always run
//! the same generator. If a SDK's own `pyproject.toml` /
//! `package.json` later pins the same versions for IDE / test
//! tooling, that's a redundancy — but two redundant pins is a
//! cheaper failure mode than a drift between them.

use anyhow::{Context, Result, bail};
use std::path::Path;
use std::process::Command;

/// Pinned generator versions. Bumping a pin is a deliberate one-line
/// change in this file; bump, re-run `cargo xtask gen-stubs`, commit
/// the regenerated files and the pin in the same patch.
const DATAMODEL_CODEGEN_VERSION: &str = "0.25.9";
const JSON_SCHEMA_TO_TS_VERSION: &str = "15.0.3";

/// One language-stub set: a Rust schema-emitter feeding the Python +
/// TypeScript generators, with the committed paths `check-stubs` diffs
/// against. The pipeline is identical per artifact — only the emit
/// command, output paths, and root class name vary — so the two
/// schemas (workload IR + host↔guest protocol) are data, not branches.
struct StubArtifact {
    /// Human label for progress output.
    label: &'static str,
    /// `cargo` args that emit the JSON schema to stdout. The protocol
    /// emitter is gated behind `--features schema`; the IR emitter is
    /// not — hence per-artifact args rather than a shared constant.
    emit_args: &'static [&'static str],
    /// Workspace-relative committed schema path.
    schema_path: &'static str,
    /// Workspace-relative committed Python dataclass module.
    python_path: &'static str,
    /// Workspace-relative committed TypeScript interface module.
    ts_path: &'static str,
    /// Root class name handed to datamodel-codegen.
    class_name: &'static str,
    /// Basename for the fresh tempdir copies in `check`.
    stem: &'static str,
}

/// The full set of stub artifacts regenerated by `gen-stubs` and
/// drift-checked by `check-stubs`.
fn artifacts() -> &'static [StubArtifact] {
    &[
        StubArtifact {
            label: "workload IR",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-sdk",
                "--features",
                "schema",
                "--bin",
                "emit_workload_schema",
            ],
            schema_path: "schema/workload-ir-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_ir/workload.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/ir/workload.ts",
            class_name: "Workload",
            stem: "workload-ir-v0",
        },
        StubArtifact {
            label: "host↔guest protocol",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-agentd",
                "--features",
                "schema",
                "--bin",
                "emit_protocol_schema",
            ],
            schema_path: "schema/protocol-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_protocol/protocol.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/protocol/protocol.ts",
            class_name: "Protocol",
            stem: "protocol-v0",
        },
        StubArtifact {
            label: "host-services broker",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-core",
                "--features",
                "schema",
                "--bin",
                "emit_broker_schema",
            ],
            schema_path: "schema/broker-services-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_broker/services.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/broker/services.ts",
            class_name: "BrokerServices",
            stem: "broker-services-v0",
        },
        StubArtifact {
            label: "live runtime contract",
            emit_args: &[
                "run",
                "-q",
                "-p",
                "mvm-sdk",
                "--features",
                "schema",
                "--bin",
                "emit_runtime_schema",
            ],
            schema_path: "schema/runtime-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_runtime/runtime.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/runtime/runtime.ts",
            class_name: "Runtime",
            stem: "runtime-v0",
        },
    ]
}

/// One constant-bearing artifact: a Rust-owned JSON **instance** rendered
/// into Python and TypeScript value bindings by [`crate::gen_sdk_surface`].
///
/// Deliberately a separate descriptor from [`StubArtifact`] rather than an
/// extra variant on it: `StubArtifact`'s pipeline is hardcoded around the two
/// pinned schema generators, and neither of them can emit a value. Bending one
/// descriptor to cover both would put an `Option<Generator>` in the middle of
/// the loop every future artifact then has to reason about.
struct ConstArtifact {
    /// Which renderer pair this artifact uses.
    kind: ConstKind,
    /// Human label for progress output.
    label: &'static str,
    /// `cargo` args emitting the JSON manifest to stdout.
    emit_args: &'static [&'static str],
    /// Workspace-relative committed manifest path.
    manifest_path: &'static str,
    /// Workspace-relative committed Python binding module.
    python_path: &'static str,
    /// Workspace-relative committed TypeScript binding module.
    ts_path: &'static str,
    /// Basename for the fresh tempdir copies in `check`.
    stem: &'static str,
}

/// Which renderer pair a [`ConstArtifact`] uses. The manifests differ in
/// shape — a flat list of name/value pairs versus a class hierarchy with a
/// status mapping — so the descriptor names its renderer rather than
/// pretending one function can read both.
#[derive(Clone, Copy)]
enum ConstKind {
    /// `schema/sdk-env-v0.json` — environment-variable names.
    EnvVars,
    /// `schema/sdk-errors-v0.json` — the error taxonomy.
    Errors,
    /// `schema/sdk-ctors-v0.json` — the constructor surface.
    Ctors,
}

/// Constant-bearing artifacts, regenerated and drift-checked alongside
/// the schema-backed ones.
fn const_artifacts() -> &'static [ConstArtifact] {
    &[
        ConstArtifact {
            kind: ConstKind::EnvVars,
            label: "SDK env-var registry",
            emit_args: &["run", "-q", "-p", "mvm-sdk", "--bin", "emit_sdk_env"],
            manifest_path: "schema/sdk-env-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_env/vars.py",
            // `_env`, not `env`: a bare `env/` is a virtualenv pattern that
            // commonly appears in a global gitignore, which would silently
            // drop this generated file and surface as a phantom drift
            // failure. The underscore also matches the sibling
            // `_sandbox.ts` / `_cli.ts` convention and Python's `_env/`.
            ts_path: "crates/mvm-sdk/sdks/typescript/src/_env/vars.ts",
            stem: "sdk-env-v0",
        },
        ConstArtifact {
            kind: ConstKind::Errors,
            label: "SDK error taxonomy",
            emit_args: &["run", "-q", "-p", "mvm-sdk", "--bin", "emit_sdk_errors"],
            manifest_path: "schema/sdk-errors-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_errors/types.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/_errors/types.ts",
            stem: "sdk-errors-v0",
        },
        ConstArtifact {
            kind: ConstKind::Ctors,
            label: "SDK constructor surface",
            emit_args: &["run", "-q", "-p", "mvm-sdk", "--bin", "emit_sdk_ctors"],
            manifest_path: "schema/sdk-ctors-v0.json",
            python_path: "crates/mvm-sdk/sdks/python/mvm/_ctors/generated.py",
            ts_path: "crates/mvm-sdk/sdks/typescript/src/_ctors/generated.ts",
            stem: "sdk-ctors-v0",
        },
    ]
}

/// Render one const artifact's manifest into its two language bindings.
fn render_const(kind: ConstKind, manifest: &[u8]) -> Result<(String, String)> {
    Ok(match kind {
        ConstKind::EnvVars => {
            let m = crate::gen_sdk_surface::EnvManifest::parse(manifest)?;
            (
                crate::gen_sdk_surface::render_python(&m),
                crate::gen_sdk_surface::render_typescript(&m),
            )
        }
        ConstKind::Errors => {
            let m = crate::gen_sdk_surface::ErrorManifest::parse(manifest)?;
            (
                crate::gen_sdk_surface::render_python_errors(&m),
                crate::gen_sdk_surface::render_typescript_errors(&m),
            )
        }
        ConstKind::Ctors => {
            let m = crate::gen_sdk_surface::CtorManifest::parse(manifest)?;
            (
                crate::gen_sdk_surface::render_python_ctors(&m),
                crate::gen_sdk_surface::render_typescript_ctors(&m),
            )
        }
    })
}

/// Generate every artifact's schema + Python + TypeScript types in place.
pub fn generate(workspace: &Path) -> Result<()> {
    for art in artifacts() {
        println!("==> {} stubs", art.label);
        let schema_path = workspace.join(art.schema_path);
        let py_path = workspace.join(art.python_path);
        let ts_path = workspace.join(art.ts_path);

        ensure_parent_dir(&schema_path)?;
        ensure_parent_dir(&py_path)?;
        ensure_parent_dir(&ts_path)?;

        let schema = emit_schema(workspace, art)?;
        std::fs::write(&schema_path, &schema)
            .with_context(|| format!("writing {}", schema_path.display()))?;
        println!("    wrote {}", schema_path.display());

        run_python_codegen(workspace, &schema_path, &py_path, art.class_name)?;
        println!("    wrote {}", py_path.display());

        run_ts_codegen(workspace, &schema_path, &ts_path)?;
        println!("    wrote {}", ts_path.display());
    }

    for art in const_artifacts() {
        println!("==> {} bindings", art.label);
        let manifest_path = workspace.join(art.manifest_path);
        let py_path = workspace.join(art.python_path);
        let ts_path = workspace.join(art.ts_path);

        ensure_parent_dir(&manifest_path)?;
        ensure_parent_dir(&py_path)?;
        ensure_parent_dir(&ts_path)?;

        let manifest = run_emit(workspace, art.label, art.emit_args)?;
        std::fs::write(&manifest_path, &manifest)
            .with_context(|| format!("writing {}", manifest_path.display()))?;
        println!("    wrote {}", manifest_path.display());

        let (py, ts) = render_const(art.kind, &manifest)?;
        std::fs::write(&py_path, py).with_context(|| format!("writing {}", py_path.display()))?;
        println!("    wrote {}", py_path.display());
        std::fs::write(&ts_path, ts).with_context(|| format!("writing {}", ts_path.display()))?;
        println!("    wrote {}", ts_path.display());
    }

    println!("\ngen-stubs complete. Commit the regenerated files.");
    Ok(())
}

/// CI guard: regenerate every artifact to a tempdir, diff against the
/// committed paths, fail if any has drifted. Exit 0 = no drift.
pub fn check(workspace: &Path) -> Result<()> {
    let tmp = tempfile::tempdir().context("creating tempdir")?;
    let mut drift = false;

    for art in artifacts() {
        let fresh_schema = tmp.path().join(format!("{}.json", art.stem));
        let fresh_py = tmp.path().join(format!("{}.py", art.stem));
        let fresh_ts = tmp.path().join(format!("{}.ts", art.stem));

        let schema = emit_schema(workspace, art)?;
        std::fs::write(&fresh_schema, &schema)
            .with_context(|| format!("writing {}", fresh_schema.display()))?;
        run_python_codegen(workspace, &fresh_schema, &fresh_py, art.class_name)?;
        run_ts_codegen(workspace, &fresh_schema, &fresh_ts)?;

        drift |= diff_or_report(&fresh_schema, &workspace.join(art.schema_path))?;
        drift |= diff_or_report(&fresh_py, &workspace.join(art.python_path))?;
        drift |= diff_or_report(&fresh_ts, &workspace.join(art.ts_path))?;
    }

    for art in const_artifacts() {
        let fresh_manifest = tmp.path().join(format!("{}.json", art.stem));
        let fresh_py = tmp.path().join(format!("{}.py", art.stem));
        let fresh_ts = tmp.path().join(format!("{}.ts", art.stem));

        let manifest = run_emit(workspace, art.label, art.emit_args)?;
        std::fs::write(&fresh_manifest, &manifest)
            .with_context(|| format!("writing {}", fresh_manifest.display()))?;
        let (py, ts) = render_const(art.kind, &manifest)?;
        std::fs::write(&fresh_py, py).with_context(|| format!("writing {}", fresh_py.display()))?;
        std::fs::write(&fresh_ts, ts).with_context(|| format!("writing {}", fresh_ts.display()))?;

        drift |= diff_or_report(&fresh_manifest, &workspace.join(art.manifest_path))?;
        drift |= diff_or_report(&fresh_py, &workspace.join(art.python_path))?;
        drift |= diff_or_report(&fresh_ts, &workspace.join(art.ts_path))?;
    }

    if drift {
        bail!("generated stubs are stale — run `cargo xtask gen-stubs` and commit the result");
    }
    println!("check-stubs: no drift");
    Ok(())
}

fn emit_schema(workspace: &Path, art: &StubArtifact) -> Result<Vec<u8>> {
    run_emit(workspace, art.label, art.emit_args)
}

/// The `--bin` name in a `cargo run` argument list, if it names one.
fn emitter_bin_name<'a>(args: &[&'a str]) -> Option<&'a str> {
    let idx = args.iter().position(|a| *a == "--bin")?;
    args.get(idx + 1).copied()
}

/// An already-built emitter binary, when one exists for this target dir.
///
/// `cargo run` takes cargo's package lock, which is global to the machine.
/// This runs from inside a BDD scenario, so a suite that shells out here
/// serialises against every other cargo process on the host — including ones in
/// unrelated worktrees. Three concurrent suites once sat behind that lock long
/// enough to read as a hang: the blocked process showed 4m30s elapsed against
/// 0.01s of CPU.
///
/// Executing a prebuilt binary takes no lock at all. `just bdd` builds these
/// alongside `mvmctl` and `xtask` for exactly that reason; the `cargo run`
/// fallback below keeps a direct `cargo run -p xtask -- gen-stubs` working for
/// anyone who has not.
fn prebuilt_emitter(workspace: &Path, bin: &str) -> Option<std::path::PathBuf> {
    let target = std::env::var_os("CARGO_TARGET_DIR")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|| workspace.join("target"));
    let path = target.join("debug").join(bin);
    path.is_file().then_some(path)
}

/// Run an emitter and capture its stdout, failing loudly on a nonzero exit.
/// Shared by both descriptor kinds.
fn run_emit(workspace: &Path, label: &str, args: &[&str]) -> Result<Vec<u8>> {
    if let Some(bin) = emitter_bin_name(args)
        && let Some(path) = prebuilt_emitter(workspace, bin)
    {
        let output = Command::new(&path)
            .current_dir(workspace)
            .output()
            .with_context(|| format!("spawning {}", path.display()))?;
        if !output.status.success() {
            bail!(
                "schema emit for {} exited {}: {}",
                label,
                output.status,
                String::from_utf8_lossy(&output.stderr)
            );
        }
        return Ok(output.stdout);
    }

    let output = Command::new("cargo")
        .args(args)
        .current_dir(workspace)
        .output()
        .with_context(|| format!("spawning cargo {}", args.join(" ")))?;
    if !output.status.success() {
        bail!(
            "schema emit for {} exited {}: {}",
            label,
            output.status,
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(output.stdout)
}

fn run_python_codegen(workspace: &Path, schema: &Path, out: &Path, class_name: &str) -> Result<()> {
    let from = format!("datamodel-code-generator=={DATAMODEL_CODEGEN_VERSION}");
    let status = Command::new("uvx")
        .args(["--from", &from, "datamodel-codegen", "--input"])
        .arg(schema)
        .args([
            "--input-file-type",
            "jsonschema",
            "--output-model-type",
            "dataclasses.dataclass",
            "--class-name",
            class_name,
            "--target-python-version",
            "3.10",
            "--disable-timestamp",
            "--output",
        ])
        .arg(out)
        .current_dir(workspace)
        .status()
        .context(
            "spawning uvx datamodel-codegen — install uv (https://docs.astral.sh/uv/) to run codegen",
        )?;
    if !status.success() {
        bail!("datamodel-codegen exited {status}");
    }
    Ok(())
}

fn run_ts_codegen(workspace: &Path, schema: &Path, out: &Path) -> Result<()> {
    let pkg = format!("json-schema-to-typescript@{JSON_SCHEMA_TO_TS_VERSION}");
    // Disable the generator's prettier pass. prettier is an unpinned transitive
    // dep whose union-wrapping heuristic differs by version, so formatting drifts
    // between machines (green locally, red in CI) no matter the print width.
    // `--no-format` emits the generator's own deterministic output, which depends
    // only on the pinned json-schema-to-typescript version — making `check-stubs`
    // reproducible everywhere.
    let status = Command::new("npx")
        .args(["--yes", &pkg, "--input"])
        .arg(schema)
        .arg("--output")
        .arg(out)
        .arg("--no-additionalProperties")
        .arg("--no-format")
        .current_dir(workspace)
        .status()
        .context("spawning npx json-schema-to-typescript — install node + npx to run codegen")?;
    if !status.success() {
        bail!("json-schema-to-typescript exited {status}");
    }
    Ok(())
}

fn ensure_parent_dir(path: &Path) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    Ok(())
}

fn diff_or_report(fresh: &Path, committed: &Path) -> Result<bool> {
    if !committed.exists() {
        eprintln!(
            "drift: {} is missing — run `cargo xtask gen-stubs` to create it",
            committed.display()
        );
        return Ok(true);
    }
    let fresh_bytes =
        std::fs::read(fresh).with_context(|| format!("reading {}", fresh.display()))?;
    let committed_bytes =
        std::fs::read(committed).with_context(|| format!("reading {}", committed.display()))?;
    if fresh_bytes == committed_bytes {
        return Ok(false);
    }

    eprintln!("drift: {} differs from fresh output", committed.display());
    // Best-effort unified diff via the `diff` binary; we don't fail
    // the check if `diff` itself is unavailable, since the equality
    // check above is the source of truth.
    let _ = Command::new("diff")
        .args(["-u", "--label", "committed", "--label", "fresh"])
        .arg(committed)
        .arg(fresh)
        .status();
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn diff_or_report_returns_false_when_identical() {
        let tmp = tempdir().unwrap();
        let a = tmp.path().join("a");
        let b = tmp.path().join("b");
        std::fs::write(&a, b"same").unwrap();
        std::fs::write(&b, b"same").unwrap();
        assert!(!diff_or_report(&a, &b).unwrap());
    }

    #[test]
    fn diff_or_report_returns_true_when_committed_missing() {
        let tmp = tempdir().unwrap();
        let fresh = tmp.path().join("fresh");
        let missing = tmp.path().join("never-existed");
        std::fs::write(&fresh, b"x").unwrap();
        assert!(diff_or_report(&fresh, &missing).unwrap());
    }

    #[test]
    fn diff_or_report_returns_true_on_drift() {
        let tmp = tempdir().unwrap();
        let a = tmp.path().join("a");
        let b = tmp.path().join("b");
        std::fs::write(&a, b"hello").unwrap();
        std::fs::write(&b, b"world").unwrap();
        assert!(diff_or_report(&a, &b).unwrap());
    }

    #[test]
    fn ensure_parent_dir_creates_missing_path() {
        let tmp = tempdir().unwrap();
        let nested = tmp.path().join("a/b/c/file.txt");
        ensure_parent_dir(&nested).unwrap();
        assert!(nested.parent().unwrap().is_dir());
    }

    #[test]
    fn artifacts_cover_workload_ir_protocol_and_runtime() {
        let schemas: Vec<&str> = artifacts().iter().map(|a| a.schema_path).collect();
        assert!(
            schemas.contains(&"schema/workload-ir-v0.json"),
            "workload IR artifact missing"
        );
        assert!(
            schemas.contains(&"schema/protocol-v0.json"),
            "protocol artifact missing"
        );
        assert!(
            schemas.contains(&"schema/runtime-v0.json"),
            "runtime artifact missing"
        );
    }

    #[test]
    fn protocol_artifact_emits_under_schema_feature() {
        let proto = artifacts()
            .iter()
            .find(|a| a.schema_path == "schema/protocol-v0.json")
            .expect("protocol artifact present");
        // The emit_protocol_schema bin carries `required-features =
        // ["schema"]`; dropping the flag silently builds nothing and the
        // emit fails closed — so the descriptor must keep it.
        assert!(proto.emit_args.contains(&"--features"));
        assert!(proto.emit_args.contains(&"schema"));
        assert!(proto.emit_args.contains(&"emit_protocol_schema"));
        assert_eq!(
            proto.python_path,
            "crates/mvm-sdk/sdks/python/mvm/_protocol/protocol.py"
        );
        assert_eq!(
            proto.ts_path,
            "crates/mvm-sdk/sdks/typescript/src/protocol/protocol.ts"
        );
        assert_eq!(proto.class_name, "Protocol");
    }

    #[test]
    fn artifact_output_paths_are_unique() {
        // Guards against a copy-pasted descriptor that would have one
        // artifact overwrite a sibling's committed output.
        let mut paths: Vec<&str> = Vec::new();
        for a in artifacts() {
            paths.push(a.schema_path);
            paths.push(a.python_path);
            paths.push(a.ts_path);
        }
        let mut deduped = paths.clone();
        deduped.sort_unstable();
        deduped.dedup();
        assert_eq!(
            paths.len(),
            deduped.len(),
            "duplicate output path among artifacts"
        );
    }
}
