/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * One command in a hook phase.
 *
 * Two variants, internally tagged on `kind` — matches the rest of the IR's enum conventions (`Source`, `Image`, `MountSource`, …) so the JSON Schema and SDK generators handle the discriminant uniformly.
 */
export type HookCmd =
  | {
      kind: "shell";
      line: string;
    }
  | {
      argv: string[];
      kind: "argv";
    };
/**
 * Resolution kind for an addon — registry-published or local-path.
 */
export type AddonRef =
  | {
      kind: "registry";
      url: string;
      version: string;
    }
  | {
      kind: "local";
      path: string;
    };
/**
 * Addon composition tier.
 *
 * `Separate` is the v1 shape — the addon runs as its own microVM and the consumer reaches it over the mesh. `InVm` is reserved for the future in-VM addon tier where small Nix fragments compose directly into the consumer's `mkGuest` flake (see `specs/plans/0012-in-vm-addon-tier.md`); it is rejected by the validator with `E_ADDON_TIER_NOT_IMPLEMENTED` until that plan lands.
 */
export type AddonTier = "separate" | "in_vm";
/**
 * Per-app dependency declaration. ADR-0009 / plan-0008.
 *
 * The host validates the lockfile exists in the bundled source tree and that it's pinned (every entry carries hashes the install step can verify). The actual install runs at image build time inside the upstream-mvm Nix factory; this IR field is the *declaration* shape, not the install machinery.
 */
export type Dependencies =
  | {
      kind: "python";
      /**
       * Path to the lockfile, relative to `app.source.path`.
       */
      lockfile: string;
      tool: PythonTool;
    }
  | {
      kind: "node";
      /**
       * Path to the lockfile, relative to `app.source.path`.
       */
      lockfile: string;
      tool: NodeTool;
    }
  | {
      kind: "none";
    };
export type PythonTool = "uv" | "pip_tools";
export type NodeTool = "pnpm" | "npm" | "yarn";
/**
 * How the wrapper inside the microVM is dispatched. ADR-0009.
 *
 * `Command` is the legacy shape: an explicit argv that runs once at boot. `Function` is the function-call shape introduced by plan 0003: a long-running language wrapper baked into the image dispatches a named function whose return value is encoded back to the caller per the declared serialization format.
 */
export type Entrypoint =
  | {
      command: string[];
      env?: {
        [k: string]: EnvValue;
      };
      kind: "command";
      working_dir?: string;
    }
  | {
      /**
       * JSON Schema for the inbound args payload. Validated at build time for secret-shaped field names; will gate per-call payloads at the wrapper once the upstream-mvm factory wires it. Shape: a strict subset of JSON Schema (object/array/string/integer/number/boolean/null/enum/oneOf). Plan-0009 / ADR-0009 §Decision §Cross-cutting.
       */
      args_schema?: JsonSchemaShape | null;
      /**
       * Opt-in concurrency model for this entrypoint (ADR-0011).
       *
       * When `None`, the function runs under the cold model: a fresh wrapper process per invocation. When `Some(WarmProcess(...))`, mvm bakes a long-running wrapper that handles many sequential calls without respawning, dispatched via mvm's warm-process worker pool. Warm-process is opt-in because state can leak across calls; ADR-0011 §Decision documents the safety/perf tradeoff.
       */
      concurrency?: Concurrency | null;
      env?: {
        [k: string]: EnvValue;
      };
      /**
       * Extra modules to bundle beyond what the host's reachability walker discovers from the entry module. Use for dynamic imports, plugin loaders, and other paths the static AST walk can't follow (plan-0007 §Phase 2). Each entry is a module identifier resolved relative to `working_dir` per the language's import rules.
       */
      extra_imports?: string[];
      /**
       * Serialization format for stdin args + stdout return. Closed enum: `Json` or `Msgpack` (plan 0003 invariant — code-executing serializer formats are forbidden).
       */
      format: Format;
      /**
       * Function identifier within the module.
       */
      function: string;
      kind: "function";
      /**
       * Language whose shim renderer / Nix factory mvm dispatches to when compiling this entrypoint. Open string validated mvm-side; current allowlist is in `validate.rs::SUPPORTED_LANGUAGES`. Adding a language is a one-PR change in mvm — no IR schema bump. Per ADR-0010 §4. SDKs set this from their own language at registration time (`"python"` for the Python SDK, `"node"` for the TypeScript SDK); users can override for cross-language manifest authoring (e.g. authoring a Python workload from the TypeScript SDK).
       *
       * Replaces the closed-enum `runtime: Runtime` field shipped in PR #7. Pre-1.0 schema bump.
       */
      language: string;
      /**
       * Module identifier (e.g. Python dotted path `pkg.subpkg.mod`, TypeScript module path `./src/mod`).
       */
      module: string;
      /**
       * Marks this entry as the workload's default function — the one `mvmctl invoke <id>` (no `--fn` selector) dispatches to. Multi-function apps (ADR-0014 Phase 2) require exactly one entrypoint to be primary; single-function apps mark their sole entrypoint primary by convention.
       */
      primary?: boolean;
      /**
       * JSON Schema for the return value. Same shape constraints as `args_schema`.
       */
      return_schema?: JsonSchemaShape | null;
      working_dir?: string;
    };
export type EnvValue =
  | {
      kind: "literal";
      value: string;
    }
  | {
      kind: "secret_ref";
      ref: SecretRef;
    };
export type SecretMount =
  | {
      kind: "env";
      var: string;
    }
  | {
      kind: "file";
      path: string;
    };
/**
 * Concurrency model for a function-entrypoint (ADR-0011).
 *
 * Open enum tagged on `kind` so future tiers (`InProcessConcurrent`, `Pool`, …) can be added without breaking existing IR. Today the only variant is `WarmProcess` — a long-running wrapper handling many sequential calls per worker, with bounded recycling.
 */
export type Concurrency = {
  /**
   * In-process dispatch mode. Only `Serial` is supported in v0.2; `Concurrent` is reserved for a follow-up ADR.
   */
  in_process: InProcessMode;
  kind: "warm_process";
  /**
   * Recycle a worker after this many dispatches. Bounds memory growth from per-call interpreter state. Lower bound 100 per ADR-0011 — anything smaller cancels the warm-tier benefit.
   */
  max_calls_per_worker: number;
  /**
   * Optional cap on the number of pending calls queued in front of the pool. When unset, mvm picks a default. When set, callers receive backpressure once the queue is full.
   */
  max_queue_depth?: number | null;
  /**
   * Recycle a worker if its RSS exceeds this (MiB). Must not exceed `app.resources.memory_mb`.
   */
  max_rss_mb: number;
  /**
   * Number of worker processes per microVM. v0.2 ships with `1` being the typical value; up to 64 is allowed.
   */
  pool_size: number;
};
/**
 * In-worker dispatch model. Per ADR-0011, only `Serial` is implemented in v0.2; `Concurrent` (multiple in-flight calls per worker via async) is rejected at parse time.
 */
export type InProcessMode = "serial" | "concurrent";
/**
 * Serialization format for function-entrypoint stdin / stdout. ADR-0009 invariant: closed enum — adding a variant is a wire change reviewed against the no-code-execution rule.
 */
export type Format = "json" | "msgpack";
export type Image =
  | {
      kind: "nix_packages";
      packages: string[];
    }
  | {
      digest: string;
      kind: "oci_base";
      reference: string;
    };
export type MountMode = "ro" | "rw";
export type MountSource =
  | {
      kind: "volume";
      name: string;
    }
  | {
      kind: "host_path";
      path: string;
    }
  | {
      kind: "tmpfs";
      size_mb: number;
    };
export type NetworkDns =
  | {
      kind: "none";
    }
  | {
      kind: "system";
    }
  | {
      host: string;
      kind: "resolver";
      port: number;
    };
export type NetworkMode = "none" | "bridge" | "host";
export type PortProto = "tcp" | "udp";
export type Source =
  | {
      exclude?: string[];
      include?: string[];
      kind: "local_path";
      path: string;
    }
  | {
      expr: string;
      kind: "nix_derivation";
    }
  | {
      digest: string;
      kind: "oci_image";
      reference: string;
    };
/**
 * Threat-tier label on the *consumer* (App). Combines with the addon's `[security].trust_tier` to drive mvmd's SMT-affinity scheduler matrix per ADR-0018 §"Trust-tier labeling and SMT-affinity policy".
 *
 * Defaults to `Untrusted` (most protective). Workloads that run only first-party reviewed code can opt into `Trusted` for finer packing.
 */
export type ThreatTier = "untrusted" | "trusted";

export interface Workload {
  apps: App[];
  extensions?: {
    [k: string]: unknown;
  };
  id: string;
  schema_version: string;
  volumes?: Volume[];
}
export interface App {
  /**
   * Composable addon-uses (ADR-0018). Each entry pulls a sha-attested addon from the registry (or a local-path during development); mvmd instantiates each addon-use as a separate microVM and bridges it to this app over the workload mesh (ADR-0020).
   *
   * Empty list (or absent field) = no addons; preserves the v0 behavior. Each entry is validated against the lockfile by `addon::resolve_and_validate` (sibling to `compile::compile`, hermetic boundary preserved).
   */
  addons?: AddonUse[];
  /**
   * Dependency declaration (plan-0008 / ADR-0009).
   *
   * Function-entrypoint workloads must declare this explicitly — either point at a hash-pinned lockfile or assert `kind = "none"` if the workload only needs stdlib. The host's `mvm validate` enforces existence + per-format hash-pin heuristic and rejects unpinned entries with `E_UNPINNED_DEPS`.
   *
   * Optional for command-style entrypoints (preserved v0 behavior) until a future ADR flips that default.
   */
  dependencies?: Dependencies | null;
  /**
   * One or more entrypoints. v0 single-function workloads have a one-element list; multi-function apps (ADR-0014 Phase 2) have multiple `Entrypoint::Function` entries with exactly one marked `primary = true`. Command-style entrypoints are always a single-element list.
   */
  entrypoints: Entrypoint[];
  env?: {
    [k: string]: EnvValue;
  };
  /**
   * Lifecycle hooks (SDK port Phase 1a — IR field reserved; consumers in Phase 10). Each phase is a `Vec<HookCmd>`; the compiler unions addon hooks (in attachment order) before the app's hooks. `Hooks::is_empty()` skip-serializes the field so v0 IR documents that don't carry `hooks` remain byte-identical.
   */
  hooks?: Hooks;
  image: Image;
  mounts?: Mount[];
  name: string;
  network?: Network | null;
  resources: Resources;
  source: Source;
  /**
   * Threat tier of the consumer (this app). Combined with the `[security].trust_tier` of each addon to drive mvmd's SMT-affinity scheduler matrix per ADR-0018. Defaults to `Untrusted` (most protective). Workloads that run only first-party reviewed code can opt into `Trusted` for finer packing in mvmd's scheduler. **Skip-serialized when default (`Untrusted`)** so legacy corpus fixtures stay byte-identical; the default is the maximally-protective value.
   */
  threat_tier?: ThreatTier;
}
/**
 * One use of an addon by the consuming app.
 *
 * The triple `(name, ref, sha256)` uniquely identifies the addon artifact; `alias` disambiguates env-var prefixes when the same addon is used multiple times. `params` are validated against the manifest's `[[addon.params]]` table at compile time.
 */
export interface AddonUse {
  /**
   * Optional alias. When present, every env var the addon exports is prefixed `<ALIAS_UPPER>_` verbatim (per ADR-0018). When absent, exports use their bare names. Two `AddonUse`s with the same `name` must use distinct aliases (validated mvm-side).
   */
  alias?: string | null;
  /**
   * Hooks bundled by this addon (SDK port Phase 1a — IR field reserved; consumers in Phase 10). The compiler concatenates each addon's hook vecs in attachment order, then appends the consuming app's own hooks. Empty `Hooks` is the default and is skip-serialized so v0 addon-use entries stay byte-identical.
   */
  hooks?: Hooks;
  /**
   * Bare addon name (matches the manifest's `[addon].name`). Pattern `^[a-z][a-z0-9-]{1,63}$`. Reserved names (`core`, `mvm`, `mvm`, `mvmd`) blocked at the registry side.
   */
  name: string;
  /**
   * Param values the consumer passes to the addon. Keys must match a `[[addon.params]]` entry in the manifest at the resolved version; values must match the declared `type` (validated at `addon::resolve_and_validate` time).
   */
  params?: {
    [k: string]: unknown;
  };
  /**
   * Pointer to the addon's published artifact. Either a registry reference (`Registry { url, version }`) or a local-path reference (`Local { path }`) for development. Local-path uses are gated: `mvm addon publish` rejects a workload that contains any.
   */
  ref: AddonRef;
  /**
   * sha256 of the canonical-form addon artifact. Matches the `sha256` in `mvm.lock` for the resolved version. Verified at compile time against the cached artifact bytes (no network).
   */
  sha256: string;
  /**
   * Composition tier — currently only `Separate` (a separate addon-microVM bridged via the mesh). `InVm` is reserved by `specs/plans/0012-in-vm-addon-tier.md` and rejected by `validate.rs` until that plan lands.
   */
  tier: AddonTier;
}
/**
 * Per-phase lifecycle command lists for an `App` or an `AddonUse`.
 *
 * Each phase is a `Vec<HookCmd>` — always. The "empty vec means no hook" rule plus the `skip_serializing_if = "Vec::is_empty"` field attribute on every phase keeps IR documents that don't use hooks byte-identical to v0 fixtures: the JSON object simply omits the `hooks` key when every phase is empty.
 */
export interface Hooks {
  after_start?: HookCmd[];
  before_build?: HookCmd[];
  before_start?: HookCmd[];
  before_stop?: HookCmd[];
}
export interface SecretRef {
  mount: SecretMount;
  name: string;
}
export interface JsonSchemaShape {}
export interface Mount {
  mode: MountMode;
  source: MountSource;
  target: string;
}
export interface Network {
  /**
   * DNS posture (plan-0004 §Phase 5). `Some(None_)` = no resolver; `Some(System)` = inherit substrate default; `Some(Resolver)` = pin a single host:port resolver. Default (None) means "unspecified — substrate picks based on `mode`".
   */
  dns?: NetworkDns | null;
  /**
   * Granular egress allowlist (plan-0004 §Phase 5). Each entry names a `host:port` pair the guest may dial. Wildcard hosts (`*`, `0.0.0.0`, `::`, `0.0.0.0/0`, `::/0`) are rejected with `E_NETWORK_WILDCARD`.
   */
  egress?: NetworkEgress | null;
  mode: NetworkMode;
  /**
   * Cross-workload reachability allowlist. Each entry is a workload id this app is allowed to talk to via the substrate's internal mesh. Validated against the `^[a-z][a-z0-9-]{0,62}$` id pattern.
   */
  peers?: string[];
  ports?: PortForward[];
}
export interface NetworkEgress {
  /**
   * Allowed `host:port` destinations. Hosts may be IP literals or hostnames; CIDRs are rejected. Empty list means "no egress" — distinct from `mode = "none"` which removes the TAP entirely.
   */
  allowlist: HostPort[];
}
export interface HostPort {
  host: string;
  port: number;
}
export interface PortForward {
  guest: number;
  host: number;
  proto: PortProto;
}
export interface Resources {
  cpu_cores: number;
  memory_mb: number;
  rootfs_size_mb: number;
}
export interface Volume {
  name: string;
  persist: boolean;
  size_mb: number;
}
