# generated by datamodel-codegen:
#   filename:  host-abi-v0.json

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional, Union


@dataclass
class BackendCapabilitiesReply:
    pass


@dataclass
class BackendCapabilitiesRequest:
    pass


class BackpressureReason1(Enum):
    guest_agent_unavailable = 'guest_agent_unavailable'


@dataclass
class ServiceHealthPending:
    pending: List[str]


@dataclass
class BackpressureReason2:
    service_health_pending: ServiceHealthPending


class BackpressureReason3(Enum):
    output_consumer_slow = 'output_consumer_slow'


class BackpressureReason4(Enum):
    input_buffer_full = 'input_buffer_full'


class BackpressureReason5(Enum):
    artifact_transfer_blocked = 'artifact_transfer_blocked'


class BackpressureReason6(Enum):
    builder_busy = 'builder_busy'


BackpressureReason = Union[
    BackpressureReason1,
    BackpressureReason2,
    BackpressureReason3,
    BackpressureReason4,
    BackpressureReason5,
    BackpressureReason6,
]


class FsEntryKind(Enum):
    file = 'file'
    dir = 'dir'
    symlink = 'symlink'
    other = 'other'


@dataclass
class GuestFsListRequest:
    id: str
    path: str


@dataclass
class GuestFsMkdirReply:
    pass


@dataclass
class GuestFsMkdirRequest:
    id: str
    path: str
    mode: Optional[int] = None
    parents: Optional[bool] = False


@dataclass
class GuestFsReadReply:
    data_b64: str


@dataclass
class GuestFsReadRequest:
    id: str
    length: int
    path: str
    follow_symlinks: Optional[bool] = True
    offset: Optional[int] = 0


@dataclass
class GuestFsRemoveReply:
    entries_removed: int


@dataclass
class GuestFsRemoveRequest:
    id: str
    path: str
    recursive: Optional[bool] = False


@dataclass
class GuestFsRenameReply:
    pass


@dataclass
class GuestFsRenameRequest:
    from_: str
    id: str
    to: str


@dataclass
class GuestFsStatReply:
    canonical_path: str
    kind: FsEntryKind
    mode: int
    size: int
    mtime: Optional[str] = None


@dataclass
class GuestFsStatRequest:
    id: str
    path: str
    follow_symlinks: Optional[bool] = True


@dataclass
class GuestFsWriteReply:
    bytes_written: int


@dataclass
class GuestFsWriteRequest:
    data_b64: str
    id: str
    path: str
    create_parents: Optional[bool] = False
    follow_symlinks: Optional[bool] = False
    mode: Optional[int] = None


@dataclass
class GuestProcKillReply:
    pass


@dataclass
class GuestProcKillRequest:
    id: str
    token: str


@dataclass
class GuestProcListRequest:
    id: str


@dataclass
class GuestProcSignalReply:
    pass


@dataclass
class GuestProcSignalRequest:
    id: str
    signum: int
    token: str


@dataclass
class GuestProcStartReply:
    token: str


@dataclass
class GuestProcStartRequest:
    argv: List[str]
    id: str
    cwd: Optional[str] = None
    env: Optional[Dict[str, str]] = field(default_factory=lambda: {})


@dataclass
class GuestProcStdinReply:
    accepted: int


@dataclass
class GuestProcStdinRequest:
    data_b64: str
    id: str
    token: str


@dataclass
class GuestProcWaitRequest:
    id: str
    token: str
    timeout_secs: Optional[int] = None


class InstanceReadiness1(Enum):
    launch_accepted = 'launch_accepted'


class InstanceReadiness2(Enum):
    agent_connecting = 'agent_connecting'


class InstanceReadiness3(Enum):
    agent_ready = 'agent_ready'


@dataclass
class ServicesStarting:
    pending: List[str]


@dataclass
class InstanceReadiness4:
    services_starting: ServicesStarting


class InstanceReadiness5(Enum):
    services_ready = 'services_ready'


@dataclass
class Degraded:
    unhealthy: List[str]


@dataclass
class InstanceReadiness6:
    degraded: Degraded


@dataclass
class Backpressured:
    reason: BackpressureReason


@dataclass
class InstanceReadiness7:
    backpressured: Backpressured


class InstanceReadiness8(Enum):
    stopping = 'stopping'


InstanceReadiness = Union[
    InstanceReadiness1,
    InstanceReadiness2,
    InstanceReadiness3,
    InstanceReadiness4,
    InstanceReadiness5,
    InstanceReadiness6,
    InstanceReadiness7,
    InstanceReadiness8,
]


MachineId = str


@dataclass
class MachineInspectRequest:
    id: str


@dataclass
class MachineLogsReply:
    data_b64: str


@dataclass
class MachineLogsRequest:
    id: str
    tail_lines: Optional[int] = None


class MachineStatus1(Enum):
    starting = 'starting'
    running = 'running'
    stopped = 'stopped'
    failed = 'failed'


class MachineStatus2(Enum):
    paused = 'paused'


MachineStatus = Union[MachineStatus1, MachineStatus2]


@dataclass
class PortMapping:
    guest: int
    host: int


class ProcState1(Enum):
    running = 'running'


@dataclass
class ProcState2:
    exited: int


@dataclass
class ProcState3:
    killed: int


class ProcState4(Enum):
    timed_out = 'timed_out'


ProcState = Union[ProcState1, ProcState2, ProcState3, ProcState4]


class Kind(Enum):
    exited = 'exited'


@dataclass
class WaitOutcome1:
    code: int
    kind: Kind


class Kind2(Enum):
    killed = 'killed'


@dataclass
class WaitOutcome2:
    kind: Kind2
    signal: int


class Kind3(Enum):
    timed_out = 'timed_out'


@dataclass
class WaitOutcome3:
    kind: Kind3


WaitOutcome = Union[WaitOutcome1, WaitOutcome2, WaitOutcome3]


@dataclass
class BackendCapabilities:
    reply: BackendCapabilitiesReply
    request: BackendCapabilitiesRequest


@dataclass
class GuestFsMkdir:
    reply: GuestFsMkdirReply
    request: GuestFsMkdirRequest


@dataclass
class GuestFsRead:
    reply: GuestFsReadReply
    request: GuestFsReadRequest


@dataclass
class GuestFsRemove:
    reply: GuestFsRemoveReply
    request: GuestFsRemoveRequest


@dataclass
class GuestFsRename:
    reply: GuestFsRenameReply
    request: GuestFsRenameRequest


@dataclass
class GuestFsStat:
    reply: GuestFsStatReply
    request: GuestFsStatRequest


@dataclass
class GuestFsWrite:
    reply: GuestFsWriteReply
    request: GuestFsWriteRequest


@dataclass
class GuestProcKill:
    reply: GuestProcKillReply
    request: GuestProcKillRequest


@dataclass
class GuestProcSignal:
    reply: GuestProcSignalReply
    request: GuestProcSignalRequest


@dataclass
class GuestProcStart:
    reply: GuestProcStartReply
    request: GuestProcStartRequest


@dataclass
class GuestProcStdin:
    reply: GuestProcStdinReply
    request: GuestProcStdinRequest


@dataclass
class MachineLogs:
    reply: MachineLogsReply
    request: MachineLogsRequest


@dataclass
class FsEntry:
    kind: FsEntryKind
    name: str
    size: int


@dataclass
class GuestFsListReply:
    entries: List[FsEntry]
    truncated: bool


@dataclass
class GuestProcListReplyItem:
    argv0: str
    pid_token: str
    started_at: str
    state: ProcState


GuestProcListReply = List[GuestProcListReplyItem]


@dataclass
class GuestProcWaitReply:
    outcome: WaitOutcome
    stderr_b64: str
    stdout_b64: str
    truncated: bool


@dataclass
class MachineInspectReply:
    id: MachineId
    name: str
    status: MachineStatus
    auto_resume: Optional[bool] = True
    backend: Optional[str] = ''
    cpus: Optional[int] = 0
    expires_at: Optional[str] = None
    flake_ref: Optional[str] = None
    guest_ip: Optional[str] = None
    last_readiness_change_at: Optional[str] = None
    memory_mib: Optional[int] = 0
    ports: Optional[List[PortMapping]] = field(default_factory=lambda: [])
    profile: Optional[str] = None
    readiness: Optional[InstanceReadiness] = None
    revision: Optional[str] = None
    status_detail: Optional[str] = None
    tags: Optional[Dict[str, str]] = field(default_factory=lambda: {})


@dataclass
class MachineListReplyItem:
    id: MachineId
    name: str
    status: MachineStatus
    auto_resume: Optional[bool] = True
    backend: Optional[str] = ''
    cpus: Optional[int] = 0
    expires_at: Optional[str] = None
    flake_ref: Optional[str] = None
    guest_ip: Optional[str] = None
    last_readiness_change_at: Optional[str] = None
    memory_mib: Optional[int] = 0
    ports: Optional[List[PortMapping]] = field(default_factory=lambda: [])
    profile: Optional[str] = None
    readiness: Optional[InstanceReadiness] = None
    revision: Optional[str] = None
    status_detail: Optional[str] = None
    tags: Optional[Dict[str, str]] = field(default_factory=lambda: {})


MachineListReply = List[MachineListReplyItem]


@dataclass
class MachineListRequest:
    name: Optional[str] = None
    status: Optional[MachineStatus] = None


@dataclass
class GuestFsList:
    reply: GuestFsListReply
    request: GuestFsListRequest


@dataclass
class GuestProcList:
    reply: GuestProcListReply
    request: GuestProcListRequest


@dataclass
class GuestProcWait:
    reply: GuestProcWaitReply
    request: GuestProcWaitRequest


@dataclass
class MachineInspect:
    reply: MachineInspectReply
    request: MachineInspectRequest


@dataclass
class MachineList:
    reply: MachineListReply
    request: MachineListRequest


@dataclass
class HostAbi:
    backend_capabilities: BackendCapabilities
    guest_fs_list: GuestFsList
    guest_fs_mkdir: GuestFsMkdir
    guest_fs_read: GuestFsRead
    guest_fs_remove: GuestFsRemove
    guest_fs_rename: GuestFsRename
    guest_fs_stat: GuestFsStat
    guest_fs_write: GuestFsWrite
    guest_proc_kill: GuestProcKill
    guest_proc_list: GuestProcList
    guest_proc_signal: GuestProcSignal
    guest_proc_start: GuestProcStart
    guest_proc_stdin: GuestProcStdin
    guest_proc_wait: GuestProcWait
    machine_inspect: MachineInspect
    machine_list: MachineList
    machine_logs: MachineLogs
