# Generated by `cargo xtask gen-stubs` from crates/mvm-hostlib/src/registry.rs.
# DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
"""The host-ABI method table: dotted names, schema keys, classifications.

Owned by the Rust registry; the C ABI answers exactly these methods.
"""
from __future__ import annotations

import dataclasses
from enum import Enum
from typing import Final

ABI_MAJOR: Final = 1
ABI_MINOR: Final = 2


class Classification(str, Enum):
    """Admission classification of a host-ABI method."""

    PROD_SAFE = "prod_safe"
    DEV_ONLY = "dev_only"


@dataclasses.dataclass(frozen=True)
class Method:
    """One dotted host-ABI method and its generated schema key."""

    key: str
    classification: Classification
    summary: str


#: Reports what the backend can do.
BACKEND_CAPABILITIES: Final = "backend.capabilities"


#: Persists a machine definition without booting it.
MACHINE_CREATE: Final = "machine.create"


#: Runs one non-interactive command in a machine.
MACHINE_EXEC: Final = "machine.exec"


#: Inspects one machine.
MACHINE_INSPECT: Final = "machine.inspect"


#: Lists every machine on this host with its dev/prod posture.
MACHINE_INVENTORY: Final = "machine.inventory"


#: Lists machines, optionally filtered.
MACHINE_LIST: Final = "machine.list"


#: Returns captured console output, base64-encoded.
MACHINE_LOGS: Final = "machine.logs"


#: Removes a machine, stopping it first when needed.
MACHINE_RM: Final = "machine.rm"


#: Boots a machine through the admitted local launch.
MACHINE_RUN: Final = "machine.run"


#: Boots a persisted machine definition.
MACHINE_START: Final = "machine.start"


#: Stops a machine. Idempotent.
MACHINE_STOP: Final = "machine.stop"


#: Copies a file between the host and the guest.
GUEST_CP: Final = "guest.cp"


#: Lists a directory in the guest.
GUEST_FS_LIST: Final = "guest.fs.list"


#: Creates a directory in the guest.
GUEST_FS_MKDIR: Final = "guest.fs.mkdir"


#: Reads a file from the guest, base64-encoded.
GUEST_FS_READ: Final = "guest.fs.read"


#: Removes a path in the guest.
GUEST_FS_REMOVE: Final = "guest.fs.remove"


#: Moves a path in the guest.
GUEST_FS_RENAME: Final = "guest.fs.rename"


#: Stats a path in the guest.
GUEST_FS_STAT: Final = "guest.fs.stat"


#: Writes a file in the guest, base64-encoded.
GUEST_FS_WRITE: Final = "guest.fs.write"


#: Kills a tracked guest process.
GUEST_PROC_KILL: Final = "guest.proc.kill"


#: Lists tracked guest processes.
GUEST_PROC_LIST: Final = "guest.proc.list"


#: Signals a tracked guest process.
GUEST_PROC_SIGNAL: Final = "guest.proc.signal"


#: Starts a process in the guest.
GUEST_PROC_START: Final = "guest.proc.start"


#: Writes a tracked process's stdin, base64-encoded.
GUEST_PROC_STDIN: Final = "guest.proc.stdin"


#: Closes a process output stream. Idempotent.
GUEST_PROC_STREAM_CLOSE: Final = "guest.proc.stream.close"


#: Returns the process output that has arrived, and how it ended.
GUEST_PROC_STREAM_NEXT: Final = "guest.proc.stream.next"


#: Opens a stream over a guest process's output.
GUEST_PROC_STREAM_OPEN: Final = "guest.proc.stream.open"


#: Waits for a guest process to end, returning its output.
GUEST_PROC_WAIT: Final = "guest.proc.wait"


METHODS: dict[str, Method] = {
    "backend.capabilities": Method(key="backend_capabilities", classification=Classification.PROD_SAFE, summary="Reports what the backend can do."),
    "machine.create": Method(key="machine_create", classification=Classification.PROD_SAFE, summary="Persists a machine definition without booting it."),
    "machine.exec": Method(key="machine_exec", classification=Classification.PROD_SAFE, summary="Runs one non-interactive command in a machine."),
    "machine.inspect": Method(key="machine_inspect", classification=Classification.PROD_SAFE, summary="Inspects one machine."),
    "machine.inventory": Method(key="machine_inventory", classification=Classification.PROD_SAFE, summary="Lists every machine on this host with its dev/prod posture."),
    "machine.list": Method(key="machine_list", classification=Classification.PROD_SAFE, summary="Lists machines, optionally filtered."),
    "machine.logs": Method(key="machine_logs", classification=Classification.PROD_SAFE, summary="Returns captured console output, base64-encoded."),
    "machine.rm": Method(key="machine_rm", classification=Classification.PROD_SAFE, summary="Removes a machine, stopping it first when needed."),
    "machine.run": Method(key="machine_run", classification=Classification.PROD_SAFE, summary="Boots a machine through the admitted local launch."),
    "machine.start": Method(key="machine_start", classification=Classification.PROD_SAFE, summary="Boots a persisted machine definition."),
    "machine.stop": Method(key="machine_stop", classification=Classification.PROD_SAFE, summary="Stops a machine. Idempotent."),
    "guest.cp": Method(key="guest_cp", classification=Classification.DEV_ONLY, summary="Copies a file between the host and the guest."),
    "guest.fs.list": Method(key="guest_fs_list", classification=Classification.DEV_ONLY, summary="Lists a directory in the guest."),
    "guest.fs.mkdir": Method(key="guest_fs_mkdir", classification=Classification.DEV_ONLY, summary="Creates a directory in the guest."),
    "guest.fs.read": Method(key="guest_fs_read", classification=Classification.DEV_ONLY, summary="Reads a file from the guest, base64-encoded."),
    "guest.fs.remove": Method(key="guest_fs_remove", classification=Classification.DEV_ONLY, summary="Removes a path in the guest."),
    "guest.fs.rename": Method(key="guest_fs_rename", classification=Classification.DEV_ONLY, summary="Moves a path in the guest."),
    "guest.fs.stat": Method(key="guest_fs_stat", classification=Classification.DEV_ONLY, summary="Stats a path in the guest."),
    "guest.fs.write": Method(key="guest_fs_write", classification=Classification.DEV_ONLY, summary="Writes a file in the guest, base64-encoded."),
    "guest.proc.kill": Method(key="guest_proc_kill", classification=Classification.DEV_ONLY, summary="Kills a tracked guest process."),
    "guest.proc.list": Method(key="guest_proc_list", classification=Classification.DEV_ONLY, summary="Lists tracked guest processes."),
    "guest.proc.signal": Method(key="guest_proc_signal", classification=Classification.DEV_ONLY, summary="Signals a tracked guest process."),
    "guest.proc.start": Method(key="guest_proc_start", classification=Classification.DEV_ONLY, summary="Starts a process in the guest."),
    "guest.proc.stdin": Method(key="guest_proc_stdin", classification=Classification.DEV_ONLY, summary="Writes a tracked process's stdin, base64-encoded."),
    "guest.proc.stream.close": Method(key="guest_proc_stream_close", classification=Classification.DEV_ONLY, summary="Closes a process output stream. Idempotent."),
    "guest.proc.stream.next": Method(key="guest_proc_stream_next", classification=Classification.DEV_ONLY, summary="Returns the process output that has arrived, and how it ended."),
    "guest.proc.stream.open": Method(key="guest_proc_stream_open", classification=Classification.DEV_ONLY, summary="Opens a stream over a guest process's output."),
    "guest.proc.wait": Method(key="guest_proc_wait", classification=Classification.DEV_ONLY, summary="Waits for a guest process to end, returning its output."),
}

__all__ = [
    "BACKEND_CAPABILITIES",
    "MACHINE_CREATE",
    "MACHINE_EXEC",
    "MACHINE_INSPECT",
    "MACHINE_INVENTORY",
    "MACHINE_LIST",
    "MACHINE_LOGS",
    "MACHINE_RM",
    "MACHINE_RUN",
    "MACHINE_START",
    "MACHINE_STOP",
    "GUEST_CP",
    "GUEST_FS_LIST",
    "GUEST_FS_MKDIR",
    "GUEST_FS_READ",
    "GUEST_FS_REMOVE",
    "GUEST_FS_RENAME",
    "GUEST_FS_STAT",
    "GUEST_FS_WRITE",
    "GUEST_PROC_KILL",
    "GUEST_PROC_LIST",
    "GUEST_PROC_SIGNAL",
    "GUEST_PROC_START",
    "GUEST_PROC_STDIN",
    "GUEST_PROC_STREAM_CLOSE",
    "GUEST_PROC_STREAM_NEXT",
    "GUEST_PROC_STREAM_OPEN",
    "GUEST_PROC_WAIT",
    "ABI_MAJOR",
    "ABI_MINOR",
    "Classification",
    "Method",
    "METHODS",
]
