/* eslint-disable */
/**
 * Generated by `cargo xtask gen-stubs` from crates/mvm-sdk/src/error_taxonomy.rs.
 * DO NOT EDIT BY HAND — `cargo xtask check-stubs` fails on drift.
 */

/** Base of every typed host-services failure. */
export class HostServiceError extends Error {}

/** The host rejected the record shape or size (audit cap). */
export class BadRequestError extends HostServiceError {}

/** The per-workload audit emit rate limit is exhausted. */
export class RateLimitedError extends HostServiceError {}

/** The host could not answer (handler down, broker not ready). */
export class UnavailableError extends HostServiceError {}

/**
 * The workload's `ExecutionPlan.services` did not bind the
 * service.
 */
export class NotBoundError extends HostServiceError {}

/** The verb is not implemented in this build. */
export class VerbNotImplementedError extends HostServiceError {}

/** Any other typed broker error code. */
export class ServiceError extends HostServiceError {}

/**
 * Connect, framing, or (de)serialization failure on the vsock
 * path.
 */
export class TransportError extends HostServiceError {}

/**
 * The request was malformed: unknown method or a body the verb
 * rejects.
 */
export class InvalidInputError extends HostServiceError {}

/**
 * User code inside the VM raised; a structured envelope was
 * parsed.
 */
export class RemoteError extends Error {
  /** Error class the guest reported. */
  readonly kind: string;
  /** Correlation id for the failing call. */
  readonly error_id: string;
  constructor(opts: { kind: string; error_id: string; message: string }) {
    super(`${opts.kind}: ${opts.message} (error_id=${opts.error_id})`);
    this.name = "RemoteError";
    this.kind = opts.kind;
    this.error_id = opts.error_id;
  }
}

/** Could not reach the substrate, or got an unparseable response. */
export class MvmTransportError extends Error {}

/**
 * The workload declared msgpack but the SDK has no msgpack
 * support.
 */
export class MsgpackUnavailable extends Error {}

/**
 * The encoded request exceeded the payload cap, refused before any
 * subprocess spawned.
 */
export class PayloadTooLarge extends MvmTransportError {}

/**
 * No-VM dispatch was requested without a local function to
 * introspect. Python-only in practice: the mode itself has no
 * TypeScript form.
 */
export class NoVmIntrospectionError extends MvmTransportError {}

/**
 * A secret-shaped value was passed as a call argument under strict
 * mode.
 */
export class SecretInArgError extends Error {}

/**
 * A transport call fired inside an emit subprocess, where no live
 * microVM exists.
 */
export class EmittingContextError extends Error {}

/** The success status; any other value is a failure. */
export const STATUS_OK = 0;

/**
 * Broker status code -> error type. Mirrors the `MVM_HSVC_*`
 * constants; `MVM_HSVC_OK` is absent because it is not a failure.
 */
export const STATUS_ERRORS: Record<number, new (msg: string) => Error> = {
  1: BadRequestError,
  2: RateLimitedError,
  3: UnavailableError,
  4: NotBoundError,
  5: VerbNotImplementedError,
  6: ServiceError,
  7: TransportError,
  8: InvalidInputError,
};
