# generated by datamodel-codegen:
#   filename:  broker-services-v0.json

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any, List, Union


@dataclass
class CostReport:
    spent_micros_usd: int


class Kind(Enum):
    ok = 'ok'


@dataclass
class EmitBatchEntryStatus1:
    chain_head: str
    kind: Kind


class Kind1(Enum):
    err = 'err'


class Kind2(Enum):
    skipped = 'skipped'


@dataclass
class EmitBatchEntryStatus3:
    kind: Kind2


class EmitErrorCode1(Enum):
    record_too_large = 'record_too_large'


class EmitErrorCode2(Enum):
    invalid_entry = 'invalid_entry'


class EmitErrorCode3(Enum):
    audit_signer_error = 'audit_signer_error'


EmitErrorCode = Union[EmitErrorCode1, EmitErrorCode2, EmitErrorCode3]


@dataclass
class EmitRequest:
    fields: Any
    ts: str


@dataclass
class EmitResponse:
    chain_head: str


class ServiceErrorCode1(Enum):
    not_bound = 'not_bound'


class ServiceErrorCode2(Enum):
    not_implemented = 'not_implemented'


class ServiceErrorCode3(Enum):
    bad_request = 'bad_request'


class ServiceErrorCode4(Enum):
    rate_limit_exceeded = 'rate_limit_exceeded'


class ServiceErrorCode5(Enum):
    lifetime_quota_exhausted = 'lifetime_quota_exhausted'


class ServiceErrorCode6(Enum):
    queue_full = 'queue_full'


class ServiceErrorCode7(Enum):
    response_too_large = 'response_too_large'


class ServiceErrorCode8(Enum):
    timeout = 'timeout'


class ServiceErrorCode9(Enum):
    unavailable = 'unavailable'


class ServiceErrorCode10(Enum):
    not_ready = 'not_ready'


class ServiceErrorCode11(Enum):
    composition_depth = 'composition_depth'


class ServiceErrorCode12(Enum):
    composition_width = 'composition_width'


class ServiceErrorCode13(Enum):
    service_call_abuse = 'service_call_abuse'


class ServiceErrorCode14(Enum):
    session_revoked = 'session_revoked'


class ServiceErrorCode15(Enum):
    internal_error = 'internal_error'


ServiceErrorCode = Union[
    ServiceErrorCode1,
    ServiceErrorCode2,
    ServiceErrorCode3,
    ServiceErrorCode4,
    ServiceErrorCode5,
    ServiceErrorCode6,
    ServiceErrorCode7,
    ServiceErrorCode8,
    ServiceErrorCode9,
    ServiceErrorCode10,
    ServiceErrorCode11,
    ServiceErrorCode12,
    ServiceErrorCode13,
    ServiceErrorCode14,
    ServiceErrorCode15,
]


ServiceId = str


class Kind3(Enum):
    ok = 'ok'


@dataclass
class ServiceResponse1:
    correlation_id: str
    kind: Kind3
    payload: Any


class Kind4(Enum):
    err = 'err'


@dataclass
class ServiceResponse2:
    code: ServiceErrorCode
    correlation_id: str
    kind: Kind4
    message: str


ServiceResponse = Union[ServiceResponse1, ServiceResponse2]


@dataclass
class TimeNowResponse:
    wall_ms: int


@dataclass
class EmitBatchEntryStatus2:
    code: EmitErrorCode
    kind: Kind1
    message: str


EmitBatchEntryStatus = Union[
    EmitBatchEntryStatus1, EmitBatchEntryStatus2, EmitBatchEntryStatus3
]


@dataclass
class EmitBatchRequest:
    entries: List[EmitRequest]


@dataclass
class EmitBatchResponse:
    chain_head: str
    statuses: List[EmitBatchEntryStatus]


@dataclass
class ServiceCall:
    correlation_id: str
    payload: Any
    service: ServiceId
    verb: str


@dataclass
class BrokerServices:
    cost_report: CostReport
    emit_batch_request: EmitBatchRequest
    emit_batch_response: EmitBatchResponse
    emit_request: EmitRequest
    emit_response: EmitResponse
    service_call: ServiceCall
    service_response: ServiceResponse
    time_now_response: TimeNowResponse
