/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

/**
 * Request sent from host to guest vsock agent.
 * 
 * `#[serde(deny_unknown_fields)]` is load-bearing: the guest agent must refuse frames whose JSON contains fields the deserializer doesn't recognise, on the principle that silent acceptance of unknown fields is a deserialization-bug gadget waiting to happen. Today every variant is a struct or unit, so the attribute applies cleanly.
 */
export type GuestRequest = ({
ActivateEnvironment: ActivateEnvironment
} | {
ProtocolHello: {
host_protocol_version: number
host_version: string
min_supported_version: number
requested_capabilities: GuestCapability[]
}
} | "WorkerStatus" | {
SleepPrep: {
drain_timeout_secs: number
}
} | "Wake" | "Ping" | "ResourceUsage" | "IntegrationStatus" | {
CheckpointIntegrations: {
integrations: string[]
}
} | "ProbeStatus" | "PrimedStatus" | {
Exec: {
command: string
stdin?: (string | null)
timeout_secs?: (number | null)
}
} | {
ExecBatch: {
commands: string[][]
stages: StageFile[]
timeout_secs?: (number | null)
}
} | {
RunEntrypoint: {
/**
 * Env vars injected into the workload after `env_clear()` (`HTTP_PROXY` + secret placeholder vars). Empty for a plain call; omitted on the wire defaults to empty.
 */
env?: [string, string][]
/**
 * Bytes piped to the wrapper's stdin.
 */
stdin: number[]
/**
 * Keep the workload's stdin open after `stdin` is written, so `StreamInput` frames can keep feeding it until `CloseStreamInput`.
 * 
 * Off by default, and the host only turns it on for a plan that carries the input grant. It has to be a per-call decision rather than the agent's default: an entrypoint whose stdin stays open never sees EOF, so a `cat`-shaped workload under a host that forgot to close would run to its timeout instead of exiting.
 */
stream_input?: boolean
/**
 * Wall-clock timeout for the call, in seconds. The agent kills the wrapper on overrun and emits `EntrypointEvent::Error { kind: Timeout }`.
 */
timeout_secs: number
}
} | {
RunExtension: {
dispatch: ExtensionDispatch
}
} | {
CancelExtension: {
cancellation: ExtensionCancellation
}
} | {
RunDetached: {
/**
 * The program and its arguments. `argv[0]` is the program; resolved via PATH when not absolute.
 */
argv: string[]
/**
 * Env vars injected after `env_clear()` (plus a minimal safe base). Empty when omitted on the wire.
 */
env?: [string, string][]
}
} | {
PostRestore: {
/**
 * Host-minted verb-grant envelope to re-pin after restore. When the plan changes across a snapshot boundary the host delivers a fresh envelope here so the guest updates its pinned grant without a reboot. Absent on callers that do not rotate grants.
 */
grant_envelope?: (VerbGrantEnvelope | null)
/**
 * Host wall-clock epoch seconds to apply before the init restart hook. Omitted by legacy callers that do not request clock sync.
 */
host_epoch_secs?: (number | null)
/**
 * Workload identity to install as the kernel hostname after a warm parent is restored into a named child. Legacy resume callers omit it and leave the current hostname unchanged.
 */
hostname?: (string | null)
/**
 * @minItems 16
 * @maxItems 16
 */
token?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
}
} | "FsDiff" | {
StartUnixSocketForward: {
guest_path: string
host_vsock_port: number
socket_mode: number
}
} | {
ConsoleOpen: {
argv?: string[]
cols: number
env?: [string, string][]
rows: number
}
} | {
ConsoleClose: {
session_id: number
}
} | {
ConsoleResize: {
cols: number
rows: number
session_id: number
}
} | "EntrypointStatus" | "ReadinessStatus" | {
FsRead: {
/**
 * `true` to follow symlinks during canonicalization. Default `true` for read; the host CLI may toggle to `false` for TOCTOU-resistant audits.
 */
follow_symlinks?: boolean
length: number
offset?: (number | null)
path: string
}
} | {
FsWrite: {
content: number[]
/**
 * Create parent directories if missing.
 */
create_parents?: boolean
/**
 * Defaults to `false` for write — TOCTOU-safe default since a malicious symlink could redirect the write.
 */
follow_symlinks?: boolean
/**
 * File mode for newly-created files (e.g. `0o644`). Ignored when overwriting an existing file (existing perms kept).
 */
mode: number
/**
 * Byte offset at which this chunk is written. Defaults to the start.
 */
offset?: (number | null)
path: string
/**
 * Truncate before writing. Defaults to the original one-shot behavior.
 */
truncate?: boolean
}
} | {
FsList: {
follow_symlinks?: boolean
path: string
}
} | {
FsStat: {
follow_symlinks?: boolean
path: string
}
} | {
FsMkdir: {
mode: number
parents?: boolean
path: string
}
} | {
FsRemove: {
/**
 * Defaults to `false` for remove; symlink-following on remove is a known footgun.
 */
follow_symlinks?: boolean
path: string
recursive?: boolean
}
} | {
FsMove: {
follow_symlinks?: boolean
from: string
to: string
}
} | {
ProcStart: {
/**
 * Argument vector. `argv[0]` is the executable to spawn.
 */
argv: string[]
/**
 * Working directory inside the guest. `None` = process inherits the agent's cwd.
 */
cwd?: (string | null)
/**
 * Environment variables. Replaces (does not extend) the agent's environment.
 */
env?: {
[k: string]: string
}
/**
 * Initial stdin bytes. Further input goes via `ProcSendInput`.
 */
stdin?: number[]
/**
 * Optional wall-clock kill on overrun. `None` = no agent- imposed timeout; the caller can still send SIGTERM via `ProcSignal` or `ProcKill`.
 */
timeout_secs?: (number | null)
}
} | "ProcList" | {
ProcSignal: {
pid_token: string
signum: number
}
} | {
ProcSendInput: {
bytes: number[]
pid_token: string
}
} | {
ProcWait: {
pid_token: string
timeout_secs?: (number | null)
}
} | {
ProcKill: {
pid_token: string
}
} | {
MountVolume: {
guest_path: string
read_only: boolean
volume_name: string
}
} | {
UnmountVolume: {
force: boolean
guest_path: string
}
} | {
UpdateIdleTimeout: {
secs: number
}
} | {
RunCode: {
code: string
timeout_secs?: (number | null)
}
} | {
StreamInput: InputFrame
} | {
CloseStreamInput: CloseInput
})
/**
 * Reverse-DNS-like service identifier with a mandatory version segment.
 * 
 * Examples: `host.secrets.v1`, `host.time.v1`, `host.cost.v1`, `broker.v1`.
 * 
 * Strings are validated at construction so the gate code can rely on the shape (in particular, the version segment is the rate-limiting parser for the binding gate).
 */
export type ServiceId = string
/**
 * Where MVM places and launches the verified executable.
 */
export type ExtensionPlacement = ("guest_workload" | "isolated_controller")
/**
 * A bounded, audit-safe identifier.
 * 
 * Unlike the agent-session identifiers this contract sits beside, uppercase is legal: the finding and rule identifiers minted upstream look like `SCOUT-RCE-001`, and lowercasing them here would silently break the join back to the source finding.
 */
export type AssuranceId = string
/**
 * Per-plan replay-protection nonce. 16 random bytes, generated by the plan signer. The supervisor's `NonceStore` (see `crate::plan::validity`) refuses a second admission with the same nonce for the same signer until the plan's `valid_until` passes.
 * 
 * Wire format: 32-character lowercase hex string. Stored as a string rather than `[u8; 16]` so JSON readers can eyeball it; the type guarantees length and case via `from_hex` / `from_bytes`.
 */
export type Nonce = string
/**
 * A guest-agent control-verb identifier: the stable `kind_name()` token (non-empty kebab-case). Validated at construction so an `agent_verbs` grant can never carry an unparseable verb.
 */
export type VerbId = string
/**
 * Device kind for a boot-time user volume.
 */
export type VolumeConfigKind = ("virtio_fs" | "block")
/**
 * Guest-agent control protocol capability. Closed enum so host and guest fail loudly on drift instead of accepting arbitrary strings.
 */
export type GuestCapability = (("ping" | "resource_usage" | "integration_status" | "entrypoint_status" | "run_entrypoint" | "run_extension" | "filesystem_rpc" | "process_rpc" | "console" | "volume_mount" | "update_idle_timeout") | "unix_socket_forward" | "readiness")
/**
 * A `sha256:<64 hex>` digest.
 * 
 * Stored in its wire form rather than as `[u8; 32]` so that a digest which round-trips through this contract is byte-identical to the one the counterparty computed, including its hex case. Equality is over those exact bytes, which is what the identity checks downstream depend on.
 */
export type Sha256Digest = string
/**
 * Response from guest vsock agent to host.
 * 
 * Same `deny_unknown_fields` discipline as `GuestRequest` — a compromised guest must not be able to slip extra fields past the host's deserializer.
 */
export type GuestResponse = ({
ProtocolHelloAck: {
agent_protocol_version: number
agent_version: string
capabilities: GuestCapability[]
min_supported_version: number
}
} | {
ProtocolMismatch: {
agent_protocol_version: number
host_protocol_version: number
message: string
required_action: ProtocolUpgradeAction
}
} | "ActivateEnvironmentAck" | {
ActivateEnvironmentError: {
message: string
}
} | "NotActivated" | {
WorkerStatus: {
last_busy_at?: (string | null)
status: string
}
} | {
SleepPrepAck: {
detail?: (string | null)
success: boolean
}
} | {
WakeAck: {
success: boolean
}
} | "Pong" | {
ResourceUsageReport: {
rss_bytes: number
}
} | {
Error: {
message: string
}
} | {
UnsupportedInProfile: {
/**
 * Active profile on the agent that rejected the call.
 */
profile: AgentProfile
/**
 * `verb_name()` of the rejected request. Wire-stable.
 */
verb: string
}
} | {
VerbNotAuthorized: {
verb: string
}
} | {
WorkloadPrivilegeRefused: {
uid: number
verb: string
}
} | {
IntegrationStatusReport: {
integrations: IntegrationStateReport[]
}
} | {
CheckpointResult: {
detail?: (string | null)
/**
 * Names of integrations that failed to checkpoint.
 */
failed: string[]
success: boolean
}
} | {
ProbeStatusReport: {
probes: ProbeResult[]
}
} | {
PrimedStatusReport: {
primed: boolean
}
} | {
EntrypointEvent: EntrypointEvent
} | "ExtensionCancellationAck" | {
ExecEvent: ExecEvent
} | {
ExecBatchResult: {
outcomes: ExecOutcomeWire[]
}
} | {
DetachedStarted: {
pid: number
}
} | {
PostRestoreAck: {
/**
 * `true` iff the guest applied the host-provided restore epoch before signaling init. Defaults to `false` for older agents.
 */
clock_resynced?: boolean
detail?: (string | null)
/**
 * `true` iff the delivered generation token changed and the guest reseeded its CSPRNG (a fresh clone). `false` for an unchanged/zero token (a plain wake or no-rotation restore). Defaults to `false` on the wire for forward-compat with a pre-rotation ack.
 */
reseeded?: boolean
success: boolean
}
} | {
FsDiffResult: {
changes: FsChange[]
}
} | {
UnixSocketForwardStarted: {
guest_path: string
host_vsock_port: number
}
} | {
ConsoleOpened: {
data_port: number
session_id: number
}
} | {
ConsoleExited: {
exit_code: number
session_id: number
}
} | {
ConsoleResized: {
session_id: number
}
} | {
EntrypointStatusReport: {
detail?: (string | null)
ok: boolean
path?: (string | null)
}
} | {
ReadinessStatusReport: ReadinessReport
} | {
FsResult: FsResult
} | {
ProcResult: ProcResult
} | {
ProcWaitEvent: ProcWaitEvent
} | {
VolumeMountResult: VolumeMountResult
} | {
UpdateIdleTimeoutAck: {
applied_secs: number
previous_secs: number
}
} | {
StreamInputResult: StreamInputResult
})
/**
 * Required remediation for a host/guest protocol mismatch.
 */
export type ProtocolUpgradeAction = ("upgrade_host" | "rebuild_guest" | "downgrade_host")
/**
 * Profile baked into an mvm guest image. Determines the set of vsock verbs the guest agent's dispatcher will accept; dev-only verbs (`Exec`, `ConsoleOpen`, `ProcStart`, `RunCode`, filesystem RPC, port forwarding) are rejected pre-handler when the image declares `SealedProd`.
 * 
 * **Source of truth.** The profile is declared by the image config — `/etc/mvm/security.json` on a sealed-prod image lives on a dm-verity rootfs, so the value cannot be widened at runtime: any modification breaks the verity hash and the kernel panics in `mvm-verity-init` before userspace. The loader treats absence of the policy file as an unprovisioned dev image (`SecurityPolicy::dev_defaults`).
 * 
 * **Builder uses a different protocol.** `mvm-builder-agent`'s wire type is `HostVmRequest`, not `GuestRequest`; the `Builder` profile is reserved for any future `GuestRequest` variant that only makes sense during a build. No current variant is `BuilderOnly`, so the value is wire-stable but unused for the tenant agent today.
 */
export type AgentProfile = ("sealed-prod" | "dev" | "builder")
/**
 * Runtime status of a single integration on a guest.
 */
export type IntegrationStatus = ("active" | "paused" | {
error: string
} | "pending" | "starting")
/**
 * One event in the streaming response of a `RunEntrypoint` call.
 * 
 * `Stdout` / `Stderr` carry bytes from the wrapper's respective streams. `Exit` and `Error` are terminal — they end the response stream for one call. The agent emits exactly one terminal event per call.
 * 
 * Buffered output is split into bounded `Stdout` and `Stderr` events without changing the protocol shape: the host reads frames until terminal.
 */
export type EntrypointEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Control: {
/**
 * JSON-encoded record header (deserialized by the host into a kind-specific struct). Agent does not parse beyond UTF-8 validation.
 */
header_json: string
/**
 * Opaque per-record payload. Empty for envelope-style records; used for raw bytes on log-style records.
 */
payload: number[]
}
} | {
Exit: {
code: number
}
} | {
Error: {
kind: RunEntrypointError
message: string
}
})
/**
 * Kind of agent-side error reported via `EntrypointEvent::Error`.
 * 
 * The variants are deliberately coarse — the host correlates by `kind` and surfaces the human-readable `message` to the operator. Adding a variant is a wire change; renaming or removing is a breaking change.
 */
export type RunEntrypointError = ("PayloadCap" | "Timeout" | "Canceled" | "Busy" | "WrapperCrashed" | "NotReady" | "EntrypointInvalid" | "SessionKilled" | "InternalError")
/**
 * One event in the response stream of a DevOnly `Exec` call. The agent emits a sequence of these for a single `Exec` request, terminated by `Exit`. The host reads frames in a loop until terminal.
 */
export type ExecEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Exit: {
code: number
}
} | "TimedOut")
/**
 * Kind of filesystem change.
 */
export type FsChangeKind = ("created" | "modified" | "deleted")
/**
 * State of a single guest subsystem during boot.
 * 
 * `Disabled` is distinct from `Ready` — a missing optional subsystem (no integrations declared, no warm pool configured, no probes registered) reports `Disabled`, while a present-and-warmed subsystem reports `Ready`. This lets the host UX distinguish "the workload doesn't use X" from "X is still warming".
 * 
 * `Default` is `Disabled` — the most-conservative semantically correct value (= "this subsystem isn't configured"). Lets constructors of `ReadinessReport` use `..Default::default()` to elide subsystems they don't care about in tests / fixtures.
 */
export type ComponentState = ("disabled" | "starting" | "ready" | {
failed: {
/**
 * Short human-readable failure reason. Stable enough for an operator to recognise, not a structured cause — pair with stderr logs for diagnosis.
 */
message: string
}
})
/**
 * Result of a filesystem RPC call. Closed enum with `deny_unknown_fields` so a compromised agent can't smuggle extra data past the host's deserializer.
 */
export type FsResult = ({
Read: {
content: number[]
total_size: number
}
} | {
Write: {
bytes_written: number
}
} | {
List: {
entries: FsEntry[]
truncated: boolean
}
} | {
Stat: FsStat
} | "Mkdir" | {
Remove: {
entries_removed: number
}
} | "Move" | {
Error: {
kind: FsErrorKind
message: string
}
})
/**
 * Type of a filesystem entry returned by `FsList` / `FsStat`.
 */
export type FsEntryKind = ("file" | "dir" | "symlink" | "other")
/**
 * Class of error returned in `FsResult::Error`. Closed enum so the host can branch on `kind` without parsing message text.
 */
export type FsErrorKind = ("PolicyDenied" | "NotFound" | "PermissionDenied" | "AlreadyExists" | "CapExceeded" | "CrossDevice" | "DirectoryNotEmpty" | "IoError" | "BadPath" | "Other")
/**
 * Result of a non-streaming process-control verb. Closed enum with `deny_unknown_fields` so a compromised agent can't smuggle extra fields past the host's deserializer.
 */
export type ProcResult = ({
Started: {
pid_token: string
}
} | {
List: {
processes: ProcInfo[]
}
} | "Signaled" | {
InputAccepted: {
bytes_accepted: number
}
} | "Killed" | {
Error: {
kind: ProcErrorKind
message: string
}
})
/**
 * Lifecycle state of a tracked process.
 */
export type ProcState = ("running" | {
exited: number
} | {
killed: number
} | "timed_out")
/**
 * Class of error returned in `ProcResult::Error` and `ProcWaitEvent::Error`.
 */
export type ProcErrorKind = ("UnknownToken" | "SpawnFailed" | "SecurityEnvelopeFailed" | "InvalidArgv" | "InvalidEnv" | "BadCwd" | "CapExceeded" | "UnsupportedInProduction" | "Other")
/**
 * One event in the streaming response of a `ProcWait` call. Terminal events end the stream — the host loops on `is_terminal()` just like for `EntrypointEvent`.
 */
export type ProcWaitEvent = ({
Stdout: {
chunk: number[]
}
} | {
Stderr: {
chunk: number[]
}
} | {
Exit: {
code: number
}
} | {
Killed: {
signal: number
}
} | "TimedOut" | {
Error: {
kind: ProcErrorKind
message: string
}
} | {
Backpressure: {
detail: string
reason: BackpressureReason
}
})
/**
 * Why a streaming or queued operation is currently throttled.
 * 
 * Closed enum: every reason is named, and drift between host and guest fails the serde `deny_unknown_fields`-equivalent path (variants must match). Detail strings carried alongside this enum are bounded and redacted — never argv / env / stdin / stdout / stderr / filesystem paths.
 */
export type BackpressureReason = ("guest_agent_unavailable" | {
service_health_pending: {
/**
 * Names of services whose readiness scripts have not yet reported success. Echoed verbatim — never user payload.
 */
pending: string[]
}
} | "output_consumer_slow" | "input_buffer_full" | "artifact_transfer_blocked" | "builder_busy")
/**
 * Result of a virtio-fs volume mount operation. (Renamed from `ShareResult`.)
 */
export type VolumeMountResult = ({
Mounted: {
canonical_path: string
}
} | "Unmounted" | {
Error: {
kind: VolumeMountErrorKind
message: string
}
})
/**
 * Class of error returned in `VolumeMountResult::Error`. Closed enum so the host can branch on `kind` without parsing message text. (Renamed from `ShareErrorKind`.)
 */
export type VolumeMountErrorKind = ("BadPath" | "PolicyDenied" | "BadVolumeName" | "MountFailed" | "Busy" | "IoError" | "Other")
/**
 * Outcome of one `StreamInput` frame or one `CloseStreamInput`.
 * 
 * Every arm is a fact about *queuing*, never about the workload having read the bytes: the agent hands input to a writer thread and answers straight away, because waiting on a child that stopped reading its stdin would hold the control connection open for as long as the workload runs.
 */
export type StreamInputResult = ({
Accepted: {
queued_bytes: number
}
} | "Closed" | {
Refused: {
kind: StreamInputRefusal
message: string
}
})
/**
 * Why the agent would not deliver an input frame.
 */
export type StreamInputRefusal = ("no_workload" | "out_of_order" | "queue_full" | "workload_gone")

/**
 * Schema root: both wire directions under one document so the shared `$defs` (`FsResult`, `ProcResult`, `EntrypointEvent`, …) are emitted once and the generated clients reference a single definition set.
 */
export interface Protocol {
request: GuestRequest
response: GuestResponse
}
/**
 * Host-to-guest activation message.  This is the only control verb accepted before privilege drop in PID-1 initramfs mode.
 */
export interface ActivateEnvironment {
/**
 * Exact optional extension identities admitted by the signed plan.
 */
extensions?: ExtensionConfig[]
/**
 * Rootfs configuration.  The data device (or virtio-fs tag) becomes the guest's `/` after activation.
 */
rootfs: RootfsConfig
/**
 * Runtime-overlay dm-verity configuration, when the boot carries an overlay.  Mounted read-only at `/mvm/runtime` inside the rootfs before pivot.  `None` for a rootfs-only boot.
 */
runtime?: (RuntimeOverlayConfig | null)
/**
 * Optional verb-grant envelope to pin before serving operational RPCs.  When present, the activation message itself must be signed by the host-signer trust anchor.
 */
verb_grant_envelope?: (VerbGrantEnvelope | null)
/**
 * Optional virtio-fs volumes mounted after the rootfs and runtime overlay are in place.
 */
volumes?: VolumeConfig[]
}
/**
 * One read-only extension artifact mounted for identity-only dispatch.
 */
export interface ExtensionConfig {
binding: ExtensionPlanBinding
device: string
mountpoint: string
plan_id: AssuranceId
}
/**
 * Exact extension identity and authority embedded in the signed execution plan after pack verification and policy/grant intersection.
 */
export interface ExtensionPlanBinding {
artifact: string
budgets: ExtensionBudgets
/**
 * Already-intersected exact typed capabilities. The broker receives these from the host-signed admission; the extension cannot widen them.
 */
capabilities: CapabilityBinding[]
/**
 * SHA-256 of [`ExtensionPackContract`].
 * 
 * @minItems 32
 * @maxItems 32
 */
contract_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
entrypoint: string
extension_id: string
/**
 * SHA-256 of the enclosing verified pack's canonical manifest.
 * 
 * @minItems 32
 * @maxItems 32
 */
pack_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
placement: ExtensionPlacement
version: string
}
/**
 * Maximum resources the extension publisher permits one admitted instance to receive. Host policy and the short-lived grant may only narrow these.
 */
export interface ExtensionBudgets {
cpu_millis: number
duration_ms: number
max_artifact_bytes: number
max_concurrency: number
max_output_bytes: number
max_payload_bytes: number
max_steps: number
memory_bytes: number
}
/**
 * Exact descriptor identity admitted for one workload.
 */
export interface CapabilityBinding {
/**
 * Capability identity approved by admission.
 */
capability: CapabilityId
/**
 * Digest of the complete descriptor approved by admission.
 * 
 * @minItems 32
 * @maxItems 32
 */
descriptor_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
}
/**
 * A versioned service verb that can be admitted independently.
 */
export interface CapabilityId {
/**
 * Versioned host service identity.
 */
service: ServiceId
/**
 * Verb within the versioned service.
 */
verb: string
}
/**
 * Root device the guest mounts as `/`.  Three mount shapes, selected by which optional fields are set, plus one mount-free shape:
 * 
 * - **dm-verity block** (`roothash` + `hash_dev`): create the `root` dm-verity target and mount it read-only. - **plain block** (neither): mount `data_dev` read-only without verification (unverified dev-tier boot). - **virtio-fs root** (`virtiofs_tag`): mount the virtio-fs tag read-only as the root — the block-less dev-tier boot. - **in place** (`in_place`): the runtime already owns `/` — a shared-kernel container whose root is the image itself. Nothing is mounted and no pivot happens; activation is the privilege drop and the gate flip only.
 */
export interface RootfsConfig {
/**
 * Data device path, e.g. `/dev/vda`.  Empty for a virtio-fs root.
 */
data_dev: string
/**
 * Hash-tree device path, e.g. `/dev/vdb`.  Present only for a dm-verity rootfs.
 */
hash_dev?: (string | null)
/**
 * The root is already in place (shared-kernel container tier): skip the rootfs mount and the pivot entirely. Mutually exclusive with every other field — a host that sets this alongside a device, hash, or tag gets a validation error from the agent, not a silent choice.
 */
in_place?: boolean
/**
 * 64-character lowercase hex dm-verity root hash.  Absent for an unverified plain-block root.
 */
roothash?: (string | null)
/**
 * virtio-fs tag to mount as the root instead of a block device.
 */
virtiofs_tag?: (string | null)
}
/**
 * dm-verity runtime-overlay target.  The runtime overlay is always verity-sealed, so its fields stay required when it is present.
 */
export interface RuntimeOverlayConfig {
/**
 * Data device path, e.g. `/dev/vdc`.
 */
data_dev: string
/**
 * Hash-tree device path, e.g. `/dev/vdd`.
 */
hash_dev: string
/**
 * 64-character lowercase hex dm-verity root hash.
 */
roothash: string
}
/**
 * Envelope carried in the `mvm.verb_grant=<base64(JSON)>` kernel-cmdline token.
 * 
 * The host base64-encodes the JSON so the value is a single space/newline-free token that `/proc/cmdline` round-trips without quoting. base64 rather than hex because this is the largest token on the cmdline and the kernel silently drops anything past `COMMAND_LINE_SIZE`. The guest decodes it, parses the JSON with `deny_unknown_fields`, then passes the inner `VerbGrant` to `pin_verb_grant` for signature verification before use.
 * 
 * `pubkey_hex` is the 32-byte Ed25519 verifying key in lowercase hex. `plan_nonce_hex` is the `Nonce::as_hex()` of the plan nonce the grant was issued under — the guest uses it as the `plan_nonce` argument to `VerbGrant::verify`. Fixed-field-order struct: `serde_json::to_vec` output is byte-deterministic with no external canonicalizer.
 */
export interface VerbGrantEnvelope {
grant: VerbGrant
plan_nonce_hex: string
predecessor_plan_nonce_hex?: (string | null)
/**
 * When present on a restore-time re-pin envelope, proves which pinned grant lineage the new grant is replacing. Boot-time cmdline envelopes leave both predecessor fields absent.
 */
predecessor_session_id?: (string | null)
pubkey_hex: string
}
/**
 * Host-signer-signed, session- and time-bound capability granting a workload a subset of agent control verbs. Signed by the admission authority, verified by the guest — deliberately a different key from the per-session frame-signing key.
 */
export interface VerbGrant {
not_after: string
plan_nonce: Nonce
session_id: string
/**
 * Raw Ed25519 signature bytes (64) over signing_bytes(), serialized as base64. A `Vec<u8>` would otherwise render as a JSON array of 64 decimal numbers — roughly 230 characters against base64's 88 — and this grant rides the guest kernel cmdline, where the budget is finite and silently enforced. `sig` is excluded from `signing_bytes`, so how it is encoded cannot affect signature validity.
 */
sig: string
verbs: VerbId[]
}
/**
 * User volume to mount after rootfs activation.
 */
export interface VolumeConfig {
/**
 * Guest block device for [`VolumeConfigKind::Block`]. Must be absent for virtio-fs and is validated against the bounded `/dev/vd[a-z]` range.
 */
device?: (string | null)
/**
 * Attachment kind. Missing on older messages means virtio-fs.
 */
kind?: (VolumeConfigKind & string)
/**
 * ext4 volume label on the attached image, when the host wrote one.
 * 
 * Preferred over [`Self::device`] for a block volume: a device node names whichever image landed in that slot, so a slot-order change mounts the wrong one and succeeds. Matching the label proves the guest mounted the image the host meant. `None` falls back to the node.
 */
label?: (string | null)
/**
 * Absolute guest mountpoint.  Must pass `MountPathPolicy`.
 */
mountpoint: string
/**
 * Mount read-only when `true`.
 */
read_only?: boolean
/**
 * Stable attachment identifier. For virtio-fs this is the advertised tag; for block devices it preserves the host's `uvol{index}` identity.
 */
tag: string
}
/**
 * A file to stage into the guest before an [`GuestRequest::ExecBatch`] runs.
 */
export interface StageFile {
content: number[]
mode: number
path: string
}
/**
 * Identity-bound input for one optional extension invocation. There is no program, argv, environment, mount, destination, or host path on this wire.
 */
export interface ExtensionDispatch {
campaign_id: AssuranceId
/**
 * @minItems 32
 * @maxItems 32
 */
contract_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
extension_id: string
grant_digest: Sha256Digest
idempotency_key: AssuranceId
input: number[]
nonce: AssuranceId
/**
 * @minItems 32
 * @maxItems 32
 */
pack_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
plan_id: AssuranceId
request_id: AssuranceId
session_id: AssuranceId
trial_id: AssuranceId
}
/**
 * Identity-only cancellation for one active optional-extension invocation. It deliberately carries no process selector, signal, path, or cleanup scope; the guest resolves the already-admitted process from this identity.
 */
export interface ExtensionCancellation {
campaign_id: AssuranceId
/**
 * @minItems 32
 * @maxItems 32
 */
contract_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
extension_id: string
grant_digest: Sha256Digest
idempotency_key: AssuranceId
nonce: AssuranceId
/**
 * @minItems 32
 * @maxItems 32
 */
pack_digest: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number]
plan_id: AssuranceId
request_id: AssuranceId
session_id: AssuranceId
trial_id: AssuranceId
}
/**
 * One host→guest byte chunk on the input plane.
 * 
 * `seq` numbers frames within one writer's session so the receiving gate can detect a gap or a reorder; unlike [`crate::stream::StreamRecord`] there is no `prev_hash` here — a single leased writer needs ordering, not a tamper-evident chain, and the gate that admits these frames (a later piece) owns replay/lease bookkeeping.
 */
export interface InputFrame {
/**
 * Raw bytes to deliver to the entrypoint's stdin, verbatim.
 */
payload: number[]
/**
 * 0-based position of this frame in the writer's session.
 */
seq: number
}
/**
 * Explicit end-of-input marker, and the last bytes that go with it.
 * 
 * Continuous input has no natural end the way one-shot `stdin_data` does (`entrypoint.rs` writes it once and closes the pipe immediately). Without this frame, a read-to-EOF program — `cat`-shaped workloads chief among them — hangs forever waiting on a stdin that never closes.
 * 
 * It is not a pure signal, because the admitting gate withholds the tail of the stream that is still a live prefix of a known secret rather than shipping it and refusing afterwards. Closing is what proves that tail was only ever a prefix, so the tail rides on the close: [`trailing`] is delivered *before* EOF, and dropping it would silently swallow the writer's last bytes. [`after_seq`] fixes where EOF sits in the sequence, so a receiver can refuse a close that overtook a frame still in flight.
 * 
 * One type, not two: this is both what the gate returns when a session ends and what travels the wire, so the host's idea of "where the stream ended" cannot drift from the guest's.
 * 
 * [`trailing`]: Self::trailing [`after_seq`]: Self::after_seq
 */
export interface CloseInput {
/**
 * Highest [`InputFrame::seq`] the writer's session admitted, or `None` when it admitted nothing. EOF is ordered immediately after it.
 */
after_seq?: (number | null)
/**
 * Bytes the gate cleared but held back, released here because closing proves they were a proper prefix of a secret and not a secret.
 */
trailing: number[]
}
/**
 * Full state report for a single integration (returned by guest agent).
 */
export interface IntegrationStateReport {
/**
 * Latest health check result, if a health_cmd is configured.
 */
health?: (IntegrationHealthResult | null)
/**
 * ISO timestamp of last successful checkpoint.
 */
last_checkpoint_at?: (string | null)
name: string
/**
 * Bytes of state data on disk.
 */
state_size_bytes?: number
status: IntegrationStatus
}
/**
 * Result of a single health check execution.
 */
export interface IntegrationHealthResult {
/**
 * ISO 8601 timestamp of when this check ran.
 */
checked_at: string
/**
 * Human-readable detail ("ok" on success, stderr or exit code on failure).
 */
detail: string
/**
 * Whether the health check passed (exit code 0).
 */
healthy: boolean
}
/**
 * Result of running a single probe.
 */
export interface ProbeResult {
/**
 * ISO 8601 timestamp of when this probe ran.
 */
checked_at: string
/**
 * Human-readable detail (stderr for exit_code mode, error message on failure).
 */
detail: string
/**
 * Whether the probe passed (exit code 0).
 */
healthy: boolean
/**
 * Probe name.
 */
name: string
/**
 * Parsed stdout JSON (only for json output_format, None otherwise).
 */
output?: {
[k: string]: unknown
}
}
/**
 * One command's buffered outcome from an [`GuestRequest::ExecBatch`]. Agent- measured: `duration_ms` is the in-guest wall-clock and `peak_rss_kib` the `getrusage` high-water mark when the guest can report it.
 */
export interface ExecOutcomeWire {
duration_ms: number
peak_rss_kib?: (number | null)
status: number
stderr: number[]
stdout: number[]
}
/**
 * A single filesystem change detected since boot.
 */
export interface FsChange {
/**
 * Type of change.
 */
kind: FsChangeKind
/**
 * Path relative to the filesystem root.
 */
path: string
/**
 * File size in bytes (0 for deleted files).
 */
size: number
}
/**
 * Snapshot of agent readiness at the moment of a `ReadinessStatus` call.
 * 
 * Used by host callers (`mvmctl wait`, `mvmctl up --timings`, `mvmctl doctor`) to distinguish:
 * 
 * - "control plane is up, workload not yet warm" → invoke would block; the host can stream progress to the user - "entrypoint validation failed" → invoke would fail fast with a typed error; the host can surface the validation message - "optional subsystem failed" → invoke is still safe; the host surfaces a warning
 * 
 * `Default` composes the `Default` impls of each field — every component is `Disabled`, the profile is `SealedProd`, all timings are `None`. Tests and fixtures can construct partial reports with `..Default::default()`.
 */
export interface ReadinessReport {
/**
 * Per-phase monotonic timings.
 */
boot_millis: BootTimingReport
/**
 * Vsock listener bound and accepting. Always `Ready` if the agent could respond at all.
 */
control_plane: ComponentState
/**
 * `/etc/mvm/entrypoint` validation result. Gates `RunEntrypoint` — a request submitted while `Starting` returns `RunEntrypointError::NotReady`.
 */
entrypoint: ComponentState
/**
 * Drop-in integration scan + health loop. `Disabled` if no `/etc/mvm/integrations.d/*.json` files present.
 */
integrations: ComponentState
/**
 * Drop-in probe scan + probe loop. `Disabled` if no `/etc/mvm/probes.d/*.json` files present.
 */
probes: ComponentState
/**
 * Active agent profile. Same value the dispatcher uses for the `allowed_in` gate.
 */
profile: AgentProfile
/**
 * Volume-mount state — wire-stable placeholder. `Disabled` because mount/unmount are on-demand verbs, not boot state.
 */
volumes: ComponentState
/**
 * Warm-process pool readiness. `Disabled` for cold-tier images; `Ready` once the `after_start.sh` probe passes.
 */
warm_pool: ComponentState
}
/**
 * Per-phase monotonic boot timings in milliseconds since the agent process started.
 * 
 * `agent_started_ms`, `vsock_bound_ms`, `first_accept_ms`, and `entrypoint_ready_ms` are wired so callers can already display the cold-path timing breakdown. The remaining fields (`warm_pool_ready_ms`, `integrations_ready_ms`, `probes_ready_ms`) are reserved and stay `None` for now.
 */
export interface BootTimingReport {
/**
 * Milliseconds from agent process start to vsock bind/listen. Always present once the agent has bound — this number is the dominant signal for early-readiness regressions.
 */
agent_started_ms?: (number | null)
/**
 * Milliseconds from agent start to `entrypoint = Ready` (or `Failed`). `None` while still `Starting`.
 */
entrypoint_ready_ms?: (number | null)
/**
 * Milliseconds from agent start to the first accepted host connection. `None` until the first `accept()` returns.
 */
first_accept_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
integrations_ready_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
probes_ready_ms?: (number | null)
/**
 * Milliseconds from agent start to a successful `bind+listen` pair on the control port. Same anchor as `agent_started_ms` today; reserved for diverging if a future refactor splits "process started" from "socket created".
 */
vsock_bound_ms?: (number | null)
/**
 * Reserved; not yet populated, so `None` for now.
 */
warm_pool_ready_ms?: (number | null)
}
/**
 * One entry in an `FsList` response.
 */
export interface FsEntry {
/**
 * File type. `Other` covers sockets, FIFOs, devices.
 */
kind: FsEntryKind
/**
 * Bare entry name (no leading directory component).
 */
name: string
/**
 * Size in bytes, or `0` for non-files.
 */
size: number
}
/**
 * Stat metadata for a single filesystem entry.
 */
export interface FsStat {
/**
 * Canonical (post-`realpath`) path the agent operated on. Lets the host detect when a symlink resolution surprised it.
 */
canonical_path: string
kind: FsEntryKind
/**
 * Unix mode bits (e.g. `0o100644`). Always present; on backends without a unix mode the agent reports a best-effort equivalent.
 */
mode: number
/**
 * Modification timestamp as RFC 3339, or `None` if the underlying fs doesn't expose mtime.
 */
mtime?: (string | null)
size: number
}
/**
 * Per-process metadata returned by `ProcList`.
 */
export interface ProcInfo {
/**
 * argv\[0\] for display only — the agent does not expose the full argv over the wire (it could echo secrets the caller passed in via env / stdin).
 */
argv0: string
pid_token: string
/**
 * RFC 3339 timestamp.
 */
started_at: string
state: ProcState
}
