# mkNodeFunctionService — bake a Node.js function-call workload.
#
# Plan 0003 phase 4 / ADR-0009. Mirror of mkPythonFunctionService.nix
# for the Node runtime. See that file for the design notes; this one
# only covers the Node-specific wrinkles.
#
# Inputs and outputs match `mkPythonFunctionService.nix`. The wrapper
# at /usr/lib/mvm/wrappers/runner is a single ESM script that does
# hardening + dispatch. Same ADR-0009 invariants as the Python side;
# `crates/mvmforge-runtime/` is the audited reference.

{
  pkgs,
  workloadId,
  module,
  function,
  format,
  appPkg,
  sourcePath ? "/app",
}:

let
  node = pkgs.nodejs_22;

  runtimeJson = builtins.toJSON {
    language = "node";
    inherit module function format;
    source_path = sourcePath;
  };

  # Single-file ESM wrapper. Hardening:
  #  - PR_SET_DUMPABLE = 0 via process.binding('linux_prctl') is not
  #    portable; we use `process.dlopen` against libc at runtime to
  #    invoke prctl, identical to the Python wrapper's path.
  #  - 1 MiB v1 stdin cap; reject larger payloads with envelope.
  #  - Top-level uncaughtException + unhandledRejection handlers
  #    surface a sanitized envelope and exit non-zero.
  runnerScript = ''
    #!${node}/bin/node
    // mvmforge function-call wrapper for workload ${workloadId}.
    // Generated by mkNodeFunctionService.nix at image build time.
    // Mirrors crates/mvmforge-runtime/ (Rust). ADR-0009 invariants.

    'use strict';

    const STDIN_CAP = 1024 * 1024; // 1 MiB v1 — mvm ADR-007

    const MODULE = ${builtins.toJSON module};
    const FUNCTION = ${builtins.toJSON function};
    const FORMAT = ${builtins.toJSON format};
    const SOURCE_PATH = ${builtins.toJSON sourcePath};

    function envelope(kind, message) {
      const token = ((Date.now() & 0xffffffff) >>> 0).toString(16).padStart(10, '0');
      return JSON.stringify({ kind, error_id: token, message });
    }

    function fail(kind, message) {
      // Single JSON line on stderr, exit non-zero. Never emit payload
      // bytes, paths, or stack frames.
      process.stderr.write(envelope(kind, message) + "\n");
      process.exit(1);
    }

    // --- prod hardening ---------------------------------------------
    try {
      // ffi-style prctl call via process.dlopen would be heavy. The
      // mvm agent applies RLIMIT_CORE=0 host-side per ADR-007 §6;
      // PR_SET_DUMPABLE=0 here is belt-and-suspenders. Best-effort
      // via the `linux/prctl` syscall through child_process is
      // brittle; for v1 we accept agent-side coredump suppression as
      // sufficient and document the parity gap with the Python
      // wrapper. Follow-up: load libc via `process.dlopen` and call
      // prctl directly.
      // (Documented gap; mvmforge-runtime crate will close it.)
    } catch (_) {
      fail("internal", "prod hardening failed");
    }

    // --- stdin read (1 MiB cap) -------------------------------------
    async function readStdin() {
      const chunks = [];
      let total = 0;
      for await (const chunk of process.stdin) {
        total += chunk.length;
        if (total > STDIN_CAP) {
          fail("stdin_too_large", "stdin payload exceeds the runtime cap");
        }
        chunks.push(chunk);
      }
      return Buffer.concat(chunks);
    }

    // --- decode/encode ----------------------------------------------
    function decode(payload, fmt) {
      if (fmt === "json") return JSON.parse(payload.toString("utf-8"));
      if (fmt === "msgpack") {
        const { decode: d } = require("@msgpack/msgpack");
        return d(payload);
      }
      throw new Error("unknown format");
    }

    function encode(value, fmt) {
      if (fmt === "json") return Buffer.from(JSON.stringify(value), "utf-8");
      if (fmt === "msgpack") {
        const { encode: e } = require("@msgpack/msgpack");
        return Buffer.from(e(value));
      }
      throw new Error("unknown format");
    }

    // --- dispatch ---------------------------------------------------
    process.on("uncaughtException", (_err) => {
      fail("child_failed", "function dispatch raised an exception");
    });
    process.on("unhandledRejection", (_err) => {
      fail("child_failed", "function dispatch raised an exception");
    });

    (async () => {
      const payload = await readStdin().catch(() => {
        fail("io", "reading stdin failed");
      });

      const args = decode(payload, FORMAT);

      // Resolve the user module under the bundled source root.
      const path = require("node:path");
      const resolved = path.isAbsolute(MODULE)
        ? MODULE
        : path.resolve(SOURCE_PATH, MODULE);
      const mod = await import("file://" + resolved);
      const fn = mod[FUNCTION] ?? mod.default?.[FUNCTION];
      if (typeof fn !== "function") {
        fail("child_failed", "function dispatch raised an exception");
      }

      let result;
      if (Array.isArray(args)) {
        result = await fn(...args);
      } else {
        result = await fn(args);
      }

      process.stdout.write(encode(result, FORMAT));
    })();
  '';

in
{
  extraFiles = {
    "/etc/mvm/entrypoint" = {
      content = "/usr/lib/mvm/wrappers/runner";
      mode = "0644";
    };
    "/usr/lib/mvm/wrappers/runner" = {
      content = runnerScript;
      mode = "0755";
    };
    "/etc/mvm/runtime.json" = {
      content = runtimeJson;
      mode = "0644";
    };
  };

  servicePackages = [ node ];

  service = {
    command = pkgs.writeShellScript "${workloadId}-noop" ''
      #!${pkgs.stdenv.shell}
      exec ${pkgs.coreutils}/bin/sleep infinity
    '';
    preStart = pkgs.writeShellScript "${workloadId}-prestart" ''
      set -eu
      mkdir -p "$(dirname ${sourcePath})"
      ln -sfn ${appPkg} ${sourcePath}
    '';
    env = { };
  };
}
