# mkPythonFunctionService — bake a Python function-call workload.
#
# Plan 0003 phase 4 / ADR-0009. Returns the `extraFiles`,
# `servicePackages`, and `service` triple the generated mvmforge flake
# composes into mvm's `mkGuest`.
#
# v1 wrapper hardening lives in this single Python script (mirroring
# the audited Rust `mvmforge-runtime` crate's semantics — see
# `crates/mvmforge-runtime/`). A follow-up PR replaces this with the
# compiled Rust binary baked at `/usr/lib/mvm/wrappers/runner`. Until
# then, **changes to the runtime crate's hardening must be mirrored
# here.**
#
# Inputs:
#   pkgs        — nixpkgs.legacyPackages.<system>
#   workloadId  — workload id from the IR
#   module      — IR entrypoint.module
#   function    — IR entrypoint.function
#   format      — IR entrypoint.format ("json" | "msgpack")
#   appPkg      — derivation built from the bundled user source
#                 (per ADR-0008)
#   sourcePath  — absolute path inside the rootfs where the user
#                 source tree lives (e.g. "/app")
#
# Outputs (record):
#   extraFiles      — passed straight to mvm's `mkGuest extraFiles`
#   servicePackages — extra packages required in the rootfs
#   service         — `services.<workloadId>` entry for mkGuest

{
  pkgs,
  workloadId,
  module,
  function,
  format,
  appPkg,
  sourcePath ? "/app",
}:

let
  python = pkgs.python3;

  # Per-workload runtime config. Mirrors the IR field set on
  # `Entrypoint::Function` (see `crates/mvmforge-ir/src/workload.rs`)
  # plus the resolved source path. Baked into the rootfs at build
  # time — nothing here is decided at call time.
  runtimeJson = builtins.toJSON {
    language = "python";
    inherit module function format;
    source_path = sourcePath;
  };

  # Wrapper at /usr/lib/mvm/wrappers/runner. Mode 0755, owned root
  # (mvm `RunEntrypoint` agent path policy). Hardening:
  #
  #  - PR_SET_DUMPABLE = 0 via ctypes(prctl) at startup.
  #  - 1 MiB v1 stdin cap; reject larger payloads with a sanitized
  #    envelope on stderr.
  #  - Top-level catch + sanitized envelope on stderr. NEVER logs
  #    payload bytes, paths, or traceback frames.
  #
  # The Rust `mvmforge-runtime` crate has the corresponding semantics
  # in audited form; this single-file Python version reproduces them
  # per ADR-0009 §"Wrapper template".
  runnerScript = ''
    #!${python}/bin/python3
    """mvmforge function-call wrapper for workload ${workloadId}.

    Generated by mkPythonFunctionService.nix at image build time. Mirrors
    crates/mvmforge-runtime/ (Rust) line-for-line; ADR-0009 invariants.
    """
    from __future__ import annotations

    import ctypes
    import ctypes.util
    import importlib
    import io
    import json
    import os
    import sys
    from time import time

    STDIN_CAP = 1024 * 1024  # 1 MiB v1 — mvm ADR-007

    MODULE = ${builtins.toJSON module}
    FUNCTION = ${builtins.toJSON function}
    FORMAT = ${builtins.toJSON format}
    SOURCE_PATH = ${builtins.toJSON sourcePath}


    def _envelope(kind: str, message: str) -> str:
        # Short opaque correlation token. ms-resolution clock + addr
        # entropy. Operators correlate on the operator-log channel.
        token = format(int(time() * 1000) & 0xffffffff, "010x")
        return json.dumps({"kind": kind, "error_id": token, "message": message})


    def _fail(kind: str, message: str) -> None:
        # Single JSON line on stderr, exit non-zero. Never emit payload
        # bytes, path strings, or local var values.
        sys.stderr.write(_envelope(kind, message) + "\n")
        sys.stderr.flush()
        raise SystemExit(1)


    # --- prod hardening -----------------------------------------------
    try:
        libc_name = ctypes.util.find_library("c")
        if libc_name is not None:
            libc = ctypes.CDLL(libc_name, use_errno=True)
            # PR_SET_DUMPABLE = 4. Disables coredumps and
            # /proc/<pid>/mem access from non-root processes.
            if libc.prctl(4, 0, 0, 0, 0) < 0:
                _fail("internal", "prod hardening failed")
    except OSError:
        _fail("internal", "prod hardening failed")


    # --- stdin read (1 MiB cap) ---------------------------------------
    try:
        chunks = []
        remaining = STDIN_CAP + 1
        while remaining > 0:
            buf = sys.stdin.buffer.read(min(remaining, 65536))
            if not buf:
                break
            chunks.append(buf)
            remaining -= len(buf)
        payload = b"".join(chunks)
        if len(payload) > STDIN_CAP:
            _fail("stdin_too_large", "stdin payload exceeds the runtime cap")
    except OSError:
        _fail("io", "reading stdin failed")


    # --- decode -------------------------------------------------------
    def _decode(data: bytes, fmt: str):
        if fmt == "json":
            return json.loads(data.decode("utf-8"))
        if fmt == "msgpack":
            import msgpack  # noqa: WPS433  (opt-in; image carries the dep)

            return msgpack.unpackb(data, raw=False)
        raise ValueError(f"unknown format: {fmt}")


    def _encode(value, fmt: str) -> bytes:
        if fmt == "json":
            return json.dumps(value, ensure_ascii=False).encode("utf-8")
        if fmt == "msgpack":
            import msgpack  # noqa: WPS433

            return msgpack.packb(value, use_bin_type=True)
        raise ValueError(f"unknown format: {fmt}")


    # --- dispatch -----------------------------------------------------
    try:
        if SOURCE_PATH and SOURCE_PATH not in sys.path:
            sys.path.insert(0, SOURCE_PATH)

        args = _decode(payload, FORMAT)
        mod = importlib.import_module(MODULE)
        fn = getattr(mod, FUNCTION)

        if isinstance(args, list):
            result = fn(*args)
        elif isinstance(args, dict):
            result = fn(**args)
        else:
            result = fn(args)

        sys.stdout.buffer.write(_encode(result, FORMAT))
        sys.stdout.flush()
    except SystemExit:
        raise
    except BaseException:
        # NEVER surface the traceback to the SDK caller. That's what
        # the operator-log channel is for (mvm-side, ADR-007).
        _fail("child_failed", "function dispatch raised an exception")
  '';

in
{
  extraFiles = {
    "/etc/mvm/entrypoint" = {
      content = "/usr/lib/mvm/wrappers/runner";
      mode = "0644";
    };
    "/usr/lib/mvm/wrappers/runner" = {
      content = runnerScript;
      mode = "0755";
    };
    "/etc/mvm/runtime.json" = {
      content = runtimeJson;
      mode = "0644";
    };
  };

  servicePackages = [ python ];

  # The agent (mvm `RunEntrypoint`) execs the wrapper directly per
  # call; no long-running service is needed. The `service` slot stays
  # populated for `mkGuest`'s shape — it requires every workload-id
  # key to declare a service block — but the command is a no-op
  # idle loop. preStart wires the appPkg symlink as today.
  service = {
    command = pkgs.writeShellScript "${workloadId}-noop" ''
      #!${pkgs.stdenv.shell}
      exec ${pkgs.coreutils}/bin/sleep infinity
    '';
    preStart = pkgs.writeShellScript "${workloadId}-prestart" ''
      set -eu
      mkdir -p "$(dirname ${sourcePath})"
      ln -sfn ${appPkg} ${sourcePath}
    '';
    env = { };
  };
}
