# generated by datamodel-codegen:
#   filename:  runtime-v0.json

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional


@dataclass
class RuntimeFsEntry:
    kind: str
    name: str
    size: int


@dataclass
class RuntimeFsStat:
    canonical_path: str
    kind: str
    mode: int
    size: int
    mtime: Optional[str] = None


@dataclass
class RuntimeProcessEvent:
    data: List[int]
    stream: str


@dataclass
class RuntimeProcessResult:
    exit_code: int
    stderr: List[int]
    stdout: List[int]


@dataclass
class Runtime:
    fs_entry: RuntimeFsEntry
    fs_stat: RuntimeFsStat
    process_event: RuntimeProcessEvent
    process_result: RuntimeProcessResult
